Repository kubernetes-sigs/cluster-api, pull requests merged in 2018-10, with the labels that each got.

#517 Fix json tags for API types
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/common_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#515 Update the error message to be object neutral
  pkg/controller/error/requeue_error.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#498 Change requeue after to requeue-after
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#521 readme: remove upgrader and repair tools from readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#524 Fix fmt strings
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#525 Add Kubermatic machine-controller to API Adoption section
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#537 Updated broken link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#538 Remove folks that are no longer project owners.
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#540 Fix machineDeployment controller tests
  Makefile
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  pkg/controller/machinedeployment/machinedeployment_controller_suite_test.go
  pkg/controller/machinedeployment/machinedeployment_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#539 cmd/clusterctl: fix broken links to "provider implementations"
  cmd/clusterctl/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#544 Set MachineDeployment status
  pkg/controller/machinedeployment/machinedeployment_controller_test.go
  pkg/controller/machinedeployment/rolling.go
  pkg/controller/machinedeployment/sync.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#550 clusterdeployer: Apply addons before pivot
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#546 add call to return if machine exists and consider requeue-after error…
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#549 Fix machineDeployment CRD for kube 1.12
  Makefile
  config/crds/cluster_v1alpha1_machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#488 Add apis for machine-class
  config/crds/cluster_v1alpha1_cluster.yaml
  config/crds/cluster_v1alpha1_machine.yaml
  config/crds/cluster_v1alpha1_machineclass.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
  pkg/apis/cluster/v1alpha1/common_types.go
  pkg/apis/cluster/v1alpha1/machineclass_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  sample/machineclass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#551 Make MachineDeployment.Spec.Strategy a pointer
  pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/machinedeployment/machinedeployment_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#564 docs: Update link for DigitalOcean Cluster-API provider
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#562 Remove ginkgo code
  Gopkg.lock
  Gopkg.toml
  cmd/clusterctl/validation/validate_cluster_api_objects_suite_test.go
  cmd/clusterctl/validation/validate_cluster_api_objects_test.go
  pkg/apis/cluster/v1alpha1/cluster_types_test.go
  pkg/apis/cluster/v1alpha1/machine_types_test.go
  pkg/apis/cluster/v1alpha1/machinedeployment_types_test.go
  pkg/apis/cluster/v1alpha1/machineset_types_test.go
  pkg/controller/cluster/cluster_controller_suite_test.go
  pkg/controller/cluster/cluster_controller_test.go
  pkg/controller/machine/machine_controller_suite_test.go
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machinedeployment/machinedeployment_controller_suite_test.go
  pkg/controller/machinedeployment/machinedeployment_controller_test.go
  pkg/controller/machineset/machineset_controller_suite_test.go
  pkg/controller/machineset/machineset_controller_test.go
  pkg/controller/node/node_controller_suite_test.go
  pkg/controller/node/node_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
