Repository kubernetes-sigs/cluster-api, pull requests merged in 2018-09, with the labels that each got.

#487 Add support for actuators requeuing machines after duration.
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#491 Fix bug in machine controller enqueueAfter.
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#489 Add requeueing support to cluster actuator
  pkg/controller/cluster/controller.go
  pkg/controller/error/requeue_error.go
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#481 Support cluster API objects in multiple namespaces
  clusterctl/clusterdeployer/BUILD.bazel
  clusterctl/clusterdeployer/clusterclient.go
  clusterctl/clusterdeployer/clusterdeployer.go
  clusterctl/clusterdeployer/clusterdeployer_test.go
  clusterctl/cmd/delete_cluster.go
  clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
  vendor/k8s.io/kube-openapi/example/openapi-gen/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/aggregator/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/builder/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/common/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/generators/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/handler/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/util/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/util/proto/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/util/proto/testing/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#496 Add vm-driver to the delete command
  clusterctl/cmd/delete_cluster.go
  clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
Labels: approved, cncf-cla: yes, lgtm, size/XS

#500 clusterctl: match kubeconfig by path instead of content
  clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#499 Fix machine deployment controller revision annotation update
  pkg/controller/machinedeployment/sync.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#507 Run `make depend`
  Gopkg.lock
  pkg/controller/cluster/BUILD.bazel
  pkg/controller/error/BUILD.bazel
  pkg/controller/machine/BUILD.bazel
  vendor/github.com/spf13/cobra/cobra/cmd/BUILD.bazel
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#504 Check if machineDeployment queue exists before using it
  pkg/controller/machinedeployment/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#511 Update README to include API adoption
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#509 Cluster-API apiserver should be namespace-ed
  clusterctl/clusterdeployer/clusterdeployer.go
  pkg/deployer/clusterapiserver.go
  pkg/deployer/clusterapiservertemplate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#514 clusterctl/clusterclient: use correct namespace in helpers
  clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/M
