Repository kubernetes-sigs/cluster-api, pull requests merged in 2018-04, with the labels that each got.

#76 Add .gitignore for gcp-deployer files.
  gcp-deployer/.gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#78 Fix dockfile to new repository location.
  cloud/google/cmd/gce-machine-controller/Dockerfile
  cmd/apiserver/Dockerfile
  cmd/controller-manager/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#102 Change references from the 'kubernetes/kube-deploy' to 'kubernetes-si…
  README.md
  gcp-deployer/CONTRIBUTING.md
  gcp-deployer/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#104 Handling configurable machine setup/installation
  cloud/google/cmd/gce-machine-controller/main.go
  cloud/google/cmd/generate-image/main.go
  cloud/google/config/configtemplate.go
  cloud/google/gceproviderconfig/types.go
  cloud/google/gceproviderconfig/v1alpha1/types.go
  cloud/google/machineactuator.go
  cloud/google/machinesetup/config_types.go
  cloud/google/machinesetup/config_types_test.go
  cloud/google/metadata.go
  cloud/google/templates.go
  gcp-deployer/cmd/add.go
  gcp-deployer/cmd/create.go
  gcp-deployer/cmd/delete.go
  gcp-deployer/deploy/deploy.go
  gcp-deployer/deploy/deploy_helper.go
  gcp-deployer/deploy/machinedeployer.go
  gcp-deployer/machine_setup_configs.yaml
  gcp-deployer/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#74 Implement parallel worker in machine controller.
  cloud/google/cmd/gce-machine-controller/main.go
  pkg/controller/config/configuration.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/machine_suite_test.go
  pkg/controller/machine/queue.go
  pkg/controller/machine/reconcile_test.go
  pkg/controller/machine/testactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#110 Prototype of named machines for vsphere
  cloud/terraform/cmd/terraform-machine-controller/Dockerfile
  cloud/terraform/cmd/terraform-machine-controller/main.go
  cloud/terraform/config/configtemplate.go
  cloud/terraform/machineactuator.go
  cloud/terraform/namedmachines/namedmachines.go
  cloud/terraform/pods.go
  cloud/terraform/terraformproviderconfig/types.go
  cloud/terraform/terraformproviderconfig/v1alpha1/types.go
  tf-deployer/cluster.yaml
  tf-deployer/cmd/add.go
  tf-deployer/cmd/create.go
  tf-deployer/cmd/delete.go
  tf-deployer/deploy/deploy.go
  tf-deployer/deploy/deploy_helper.go
  tf-deployer/deploy/machinedeployer.go
  tf-deployer/machines.yaml.template
  tf-deployer/vsphere_named_machines.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#108 Add owner reference for machines created via machineset controller
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/reconcile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#113 Bump GCE machine controller image
  cloud/google/cmd/gce-machine-controller/Makefile
  cloud/google/pods.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#73 Refactor GCEClient: wrap compute.Service in an interface for mocking …
  cloud/google/clients/computeservice.go
  cloud/google/clients/computeservice_test.go
  cloud/google/machineactuator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#107 Use kubenet instead of weavenet for GCP provider
  cloud/google/machineactuator.go
  gcp-deployer/machine_setup_configs.yaml
  gcp-deployer/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#116 Bump machine controller image
  cloud/google/cmd/gce-machine-controller/Makefile
  cloud/google/pods.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
