Repository kubernetes-sigs/cluster-api, pull requests merged in 2018-08, with the labels that each got.

#472 Reference the official git repo for vsphere provider
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#469 fixed errors from running: make verify
  clusterctl/clusterdeployer/externalclusterprovisioner/externalbootstrapcluster.go
  clusterctl/clusterdeployer/externalclusterprovisioner/externalbootstrapcluster_test.go
  clusterctl/validation/validate_cluster_api_objects_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#474 README: Add implementer office hours
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#478 clusterctl/cmd: improve error message for not implemented interface
  clusterctl/cmd/create_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#482 Expose the "--kubeconfig" option in the kubeadm wrapper
  pkg/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#484 [clusterctl] Rename external to bootstrap and internal to target
  clusterctl/clusterdeployer/bootstrap/existing/BUILD.bazel
  clusterctl/clusterdeployer/bootstrap/existing/exisingcluster.go
  clusterctl/clusterdeployer/bootstrap/existing/existingcluster_test.go
  clusterctl/clusterdeployer/bootstrap/minikube/BUILD.bazel
  clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
  clusterctl/clusterdeployer/bootstrap/minikube/minikube_test.go
  clusterctl/clusterdeployer/clusterdeployer.go
  clusterctl/clusterdeployer/clusterdeployer_test.go
  clusterctl/cmd/BUILD.bazel
  clusterctl/cmd/create_cluster.go
  clusterctl/cmd/delete_cluster.go
  clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  clusterctl/testdata/create-cluster-no-args.golden
Labels: approved, cncf-cla: yes, lgtm, size/L

#477 export getApiServerYaml
  clusterctl/clusterdeployer/BUILD.bazel
  clusterctl/clusterdeployer/clusterdeployer.go
  pkg/deployer/BUILD.bazel
  pkg/deployer/clusterapiserver.go
  pkg/deployer/clusterapiservertemplate.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#486 Remove priority field from the APIService manifest to make it compatible with 1.11+ bootstrap clusters
  pkg/deployer/clusterapiservertemplate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
