Repository kubernetes-sigs/cluster-api, pull requests merged in 2018-11, with the labels that each got.

#553 [clusterctl] add phases create-bootstrap-cluster subcommand
  .gitignore
  cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
  cmd/clusterctl/clusterdeployer/bootstrap/provisioner.go
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/cmd/alpha.go
  cmd/clusterctl/cmd/alpha_phase_create_bootstrap_cluster.go
  cmd/clusterctl/cmd/alpha_phases.go
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/cmd/delete_cluster.go
  cmd/clusterctl/phases/createbootstrapcluster.go
  cmd/clusterctl/testdata/no-args-invalid-flag.golden
  cmd/clusterctl/testdata/no-args.golden
Labels: approved, cncf-cla: yes, lgtm, size/L

#573 Create a phase for applying the Cluster API components
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/cmd/alpha_phase_apply_cluster_api_components.go
  cmd/clusterctl/phases/applyclusterapicomponents.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#563 Create machines in parallel in clusterctl create
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#566 Initial draft GitBook.
  .gitignore
  docs/book/Dockerfile
  docs/book/GLOSSARY.md
  docs/book/README.md
  docs/book/RELEASE
  docs/book/SUMMARY.md
  docs/book/appendices/keps/0003-cluster-api.md
  docs/book/book.json
  docs/book/common_code/architecture.md
  docs/book/common_code/architecture.png
  docs/book/common_code/cluster_controller.md
  docs/book/common_code/machine_controller.md
  docs/book/common_code/machinedeployment_controller.md
  docs/book/common_code/machineset_controller.md
  docs/book/common_code/repository_layout.md
  docs/book/getting_started/existing_providers.md
  docs/book/package-lock.json
  docs/book/provider_implementations/building_running_and_testing.md
  docs/book/provider_implementations/create_actuators.md
  docs/book/provider_implementations/generate_crds.md
  docs/book/provider_implementations/naming.md
  docs/book/provider_implementations/overview.md
  docs/book/provider_implementations/register_controllers.md
  docs/book/provider_implementations/register_schemes.md
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/machine_types.go
  pkg/apis/cluster/v1alpha1/machineclass_types.go
  pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  pkg/apis/cluster/v1alpha1/machineset_types.go
  pkg/controller/cluster/actuator.go
  pkg/controller/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#575 Invalid directory path in clusterctl README.md (#574)
  cmd/clusterctl/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#578 Update lodash to 4.17.11 to fix CVE-2018-3721 (fixes #576).
  docs/book/package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#584 add ref to tencent cloud provider
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#572 Switch yaml package from ghodss repo to sigs.k8s.io fork
  Gopkg.lock
  cmd/clusterctl/cmd/create_cluster.go
  vendor/sigs.k8s.io/yaml/.gitignore
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/CONTRIBUTING.md
  vendor/sigs.k8s.io/yaml/LICENSE
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/RELEASE.md
  vendor/sigs.k8s.io/yaml/SECURITY_CONTACTS
  vendor/sigs.k8s.io/yaml/code-of-conduct.md
  vendor/sigs.k8s.io/yaml/fields.go
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_go110.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#583 Default kubebuilder test controlplane timeouts to 60s
  Gopkg.lock
  Makefile
  vendor/sigs.k8s.io/controller-runtime/Gopkg.lock
  vendor/sigs.k8s.io/controller-runtime/example/main.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/bootstrap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/certgenerator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/fake/certgenerator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/selfsigned.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/util.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/provisioner.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/certwriter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/fs.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/secret.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#579 Add Context to Actuator
  pkg/controller/machine/actuator.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/testactuator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#586 Add MachineClassList type to fix client-gen
  pkg/apis/cluster/v1alpha1/machineclass_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#582 Implement Scale Subresource for MachineSet and MachineDeployment (#580)
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
  config/samples/cluster_v1alpha1_machinedeployment.yaml
  config/samples/cluster_v1alpha1_machineset.yaml
  pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  pkg/apis/cluster/v1alpha1/machineset_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#577 Create a phase for applying the Addon components
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/cmd/alpha_phase_apply_addons.go
  cmd/clusterctl/cmd/alpha_phase_apply_cluster_api_components.go
  cmd/clusterctl/phases/applyaddons.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#591 Fix the build comment for clusterctl
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#581 [clusterctl] add phases for apply-machines and apply-cluster
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/cmd/alpha_phase_apply_cluster.go
  cmd/clusterctl/cmd/alpha_phase_apply_machines.go
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/cmd/create_cluster_test.go
  cmd/clusterctl/phases/applycluster.go
  cmd/clusterctl/phases/applymachines.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#593 ensure machine annotation api uniqueness
  pkg/controller/node/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#590 Migrate from glog to klog
  Gopkg.lock
  cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
  cmd/clusterctl/clusterdeployer/clusterclient/BUILD.bazel
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/cmd/alpha_phase_apply_addons.go
  cmd/clusterctl/cmd/alpha_phase_apply_cluster.go
  cmd/clusterctl/cmd/alpha_phase_apply_cluster_api_components.go
  cmd/clusterctl/cmd/alpha_phase_apply_machines.go
  cmd/clusterctl/cmd/alpha_phase_create_bootstrap_cluster.go
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/cmd/delete_cluster.go
  cmd/clusterctl/cmd/logutil.go
  cmd/clusterctl/cmd/root.go
  cmd/clusterctl/phases/applyaddons.go
  cmd/clusterctl/phases/applycluster.go
  cmd/clusterctl/phases/applyclusterapicomponents.go
  cmd/clusterctl/phases/applymachines.go
  cmd/clusterctl/phases/createbootstrapcluster.go
  cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-cluster-no-args.golden
  cmd/clusterctl/testdata/create-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-no-args.golden
  cmd/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-cluster-no-args.golden
  cmd/clusterctl/testdata/delete-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-no-args.golden
  cmd/clusterctl/testdata/no-args-invalid-flag.golden
  cmd/clusterctl/testdata/no-args.golden
  cmd/clusterctl/testdata/validate-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args.golden
  pkg/apis/cluster/common/plugins.go
  pkg/cert/cert_authority.go
  pkg/controller/cluster/controller.go
  pkg/controller/machine/controller.go
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machinedeployment/rolling.go
  pkg/controller/machinedeployment/sync.go
  pkg/controller/machinedeployment/util/util.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/machine.go
  pkg/controller/machineset/status.go
  pkg/controller/node/node.go
  pkg/controller/node/node_controller.go
  pkg/util/util.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/glog/README.md
  vendor/k8s.io/klog/glog/glog.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#531 Add APIs for machine phases
  config/crds/cluster_v1alpha1_machine.yaml
  pkg/apis/cluster/v1alpha1/machine_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#600 .gitignore: ignore emacs temp files
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#604 Add cluster api implementation reference for Baidu Cloud.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#608 Add -f (--fail) arg to all curl commands
  docs/book/provider_implementations/overview.md
  scripts/fetch_ext_bins.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#609 docker image: move manager binary to root
  Dockerfile
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
