Repository kubernetes-sigs/cluster-api, pull requests merged in 2018-12, with the labels that each got.

#610 Initialize klog in clusterctl
  cmd/clusterctl/cmd/root.go
  cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-cluster-no-args.golden
  cmd/clusterctl/testdata/create-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-no-args.golden
  cmd/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-cluster-no-args.golden
  cmd/clusterctl/testdata/delete-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-no-args.golden
  cmd/clusterctl/testdata/no-args-invalid-flag.golden
  cmd/clusterctl/testdata/no-args.golden
  cmd/clusterctl/testdata/validate-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args.golden
Labels: approved, cncf-cla: yes, lgtm, size/M

#616 Fix typo in filename: should be existingcluster.go
  cmd/clusterctl/clusterdeployer/bootstrap/existing/existingcluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#617 kubectl apply: warn on unknown errors, not just known errors
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#597 Included context into docs of Machine Actuator
  docs/book/provider_implementations/create_actuators.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#619 Add {update-verify}-bazel.sh scripts for CI
  hack/update-bazel.sh
  hack/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#618 Don't swallow errors from ExecCommand
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#620 Add template for GitHub issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#599 Local defaulting
  pkg/apis/cluster/v1alpha1/BUILD.bazel
  pkg/apis/cluster/v1alpha1/defaults.go
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machinedeployment/sync.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#626 Report only non-nil errors
  pkg/controller/machineset/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#628 Add a Bazel rule to generate yaml
  WORKSPACE
  config/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/S

#629 Kustomization needs to work with relative directories
  config/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#606 Add machineClasses to default kustomization config list
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#631 Refactor Makefile with help
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#635 Set the image version for the 0.0.0-alpha.4 release.
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#636 Set the image version back to latest for development on master.
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#648 Typo fixes
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  pkg/apis/cluster/common/consts.go
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/machine_types.go
  pkg/apis/cluster/v1alpha1/machineset_types.go
  pkg/controller/machinedeployment/sync.go
  pkg/controller/machinedeployment/util/util.go
  pkg/controller/machineset/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#643 Increase machineSet unit test coverage
  Gopkg.lock
  pkg/controller/machineset/controller_test.go
  pkg/controller/machineset/machine.go
  pkg/controller/machineset/machine_test.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#653 Correct KEP link so that Gitbook will render and Jekyll will build.
  docs/book/appendices/keps/0003-cluster-api.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#642 Update Bazel to Go 1.11.4
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#654 Update Gitbook with corrected contents.
  GLOSSARY.html
  appendices/keps/0003-cluster-api.html
  common_code/architecture.html
  common_code/cluster_controller.html
  common_code/machine_controller.html
  common_code/machinedeployment_controller.html
  common_code/machineset_controller.html
  common_code/repository_layout.html
  getting_started/existing_providers.html
  index.html
  provider_implementations/building_running_and_testing.html
  provider_implementations/create_actuators.html
  provider_implementations/generate_crds.html
  provider_implementations/naming.html
  provider_implementations/overview.html
  provider_implementations/register_controllers.html
  provider_implementations/register_schemes.html
  search_index.json
Labels: cncf-cla: yes, size/L

#598 Re-queue delete machine on re-queue error
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#633 Fix clientset verification
  Makefile
  hack/verify-bazel.sh
  hack/verify_clientset.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#646 Deployment unit tests
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machinedeployment/controller_test.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/controller_test.go
  pkg/controller/machineset/machineset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#657 Polishing machine controller
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#649 Fixed nil pointer crash in machine deployment controller
  pkg/controller/machinedeployment/rolling.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#627 Short circuit return when adding finalizers
  pkg/controller/cluster/controller.go
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
