Repository kubernetes-sigs/cluster-api, pull requests merged in 2019-08, with the labels that each got.

#1217 Fix jsonpatch go module
  go.sum
  hack/update-vendor.sh
  vendor/gomodules.xyz/jsonpatch/v2/.gitignore
  vendor/gomodules.xyz/jsonpatch/v2/.travis.yml
  vendor/gomodules.xyz/jsonpatch/v2/CHANGELOG.md
  vendor/gomodules.xyz/jsonpatch/v2/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1215 Document procedure for creating per release books.
  docs/book/RELEASE
Labels: approved, cncf-cla: yes, lgtm, size/M

#1216 Add openstack acronym to gitbook
  docs/book/ABBREVIATIONS.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1214 Adopt conditionally based on owner
  pkg/controller/machine/machine_controller.go
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machineset/machineset_controller.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1204 Fix Netlify redirects
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1211 Adds a v1a1 to v1a2 comparison document
  docs/developer/v1alpha1-compared-to-v1alpha2.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1223 Return early if InfrastructureRef is nil
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1224 Update controller-tools to v0.2.0-beta.5
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/known_types.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/traverse.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/help/pretty/help.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1225 Cluster: delete children first.
  pkg/controller/cluster/BUILD.bazel
  pkg/controller/cluster/cluster_controller.go
  pkg/util/BUILD.bazel
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1222 Allow optional addresses
  pkg/controller/machine/machine_controller_phases.go
  pkg/controller/machine/machine_controller_phases_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1231 Release v0.1.9
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1233 return nil when Bootstrap.ConfigRef doesn't exist
  pkg/controller/machine/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1232 Fix cluster not found error
  pkg/controller/cluster/cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1230 Fixes a bug in GetClusterByName
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1235 Return correct Machine Name in util.GetOwnerMachine
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1236 Controller runtime v0.2.0-beta.5
  go.mod
  go.sum
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/machinedeployment/machinedeployment_reconciler_test.go
  pkg/util/BUILD.bazel
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection/leader_election.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/decode.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/certwatcher/certwatcher.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1238 Remove unnecessary get for MachineSet in MachineSetToDeployments
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machinedeployment/machinedeployment_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1239 Update CRDs
  config/crds/cluster.k8s.io_clusters.yaml
  config/crds/cluster.k8s.io_machineclasses.yaml
  config/crds/cluster.k8s.io_machinedeployments.yaml
  config/crds/cluster.k8s.io_machines.yaml
  config/crds/cluster.k8s.io_machinesets.yaml
  config/crds/cluster.x-k8s.io_clusters.yaml
  config/crds/cluster.x-k8s.io_machinedeployments.yaml
  config/crds/cluster.x-k8s.io_machines.yaml
  config/crds/cluster.x-k8s.io_machinesets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#822 Avoid get machine when doing MachineToMachineSets
  pkg/controller/machineset/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1246 Improve hack files
  hack/build-gitbook.sh
  hack/pin-dependency.sh
  hack/update-vendor.sh
  hack/verify-bazel.sh
  hack/verify-clientset.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1251 Remove sample folder
  sample/cluster.yaml
  sample/machine.yaml
  sample/machineclass.yaml
  sample/machinedeployment.yaml
  sample/machineset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1247 Make cluster.status.phase and machine.status.phase non-pointers
  pkg/apis/cluster/v1alpha2/cluster_phase_types.go
  pkg/apis/cluster/v1alpha2/cluster_types.go
  pkg/apis/cluster/v1alpha2/machine_phase_types.go
  pkg/apis/cluster/v1alpha2/machine_types.go
  pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/cluster/cluster_controller_phases.go
  pkg/controller/machine/machine_controller_phases.go
  test/integration/cluster/cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1209 [clusterctl] Fix ensure namespace function in clusterclient
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1150 issue-934: Add doctoc for docs updating
  CONTRIBUTING.md
  Makefile
  README.md
  cmd/clusterctl/README.md
  docs/developer/releasing.md
  docs/how-to-use-clusterctl.md
  docs/proposals/20181121-machine-api.md
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
  docs/proposals/YYYYMMDD-template.md
  docs/proposals/images/machine-states-preboot/README.md
  docs/scope-and-objectives.md
  docs/staging-use-cases.md
  hack/verify-doctoc.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1252 Migrate Cluster Controller to Kubebuilder v2
  cmd/example-provider/BUILD.bazel
  cmd/example-provider/main.go
  controllers/BUILD.bazel
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
  controllers/cluster_controller_test.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machineset_controller.go
  controllers/suite_test.go
  pkg/controller/BUILD.bazel
  pkg/controller/add_cluster.go
  pkg/controller/cluster/BUILD.bazel
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/cluster_reconciler_suite_test.go
  pkg/controller/cluster/cluster_reconciler_test.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1255 Update controller-tools / fix CI verify step
  Makefile
  api/v1alpha2/zz_generated.deepcopy.go
  go.mod
  go.sum
  hack/verify-clientset.sh
  hack/verify-doctoc.sh
  pkg/apis/deprecated/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/pkg/crd/BUILD.bazel
  vendor/sigs.k8s.io/controller-tools/pkg/crd/desc_visitor.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1253 Fix: update cluster annotations when control plane is ready
  pkg/controller/machine/machine_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1257 chore: verify-generated-files
  Makefile
  hack/verify-generated-files.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1262 :warning: Migrate Machine Controller to Kubebuilder v2
  controllers/BUILD.bazel
  controllers/machine_controller.go
  controllers/machine_controller_noderef.go
  controllers/machine_controller_noderef_test.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/suite_test.go
  pkg/controller/BUILD.bazel
  pkg/controller/add_machine.go
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_reconciler_suite_test.go
  pkg/controller/machine/machine_reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1261 🐛 Ensure status updates succeed
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1254 Require PR title to include typed emoji
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1263 :warning: Migrate MachineSet controller to Kubebuilder v2
  controllers/BUILD.bazel
  controllers/cluster_controller_phases.go
  controllers/cluster_controller_test.go
  controllers/machine_controller.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controllers/machineset_controller.go
  controllers/machineset_controller_test.go
  controllers/machineset_delete_policy.go
  controllers/machineset_delete_policy_test.go
  controllers/machineset_status.go
  controllers/suite_test.go
  pkg/controller/BUILD.bazel
  pkg/controller/add_machineset.go
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/machine.go
  pkg/controller/machineset/machine_test.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/machineset/machineset_controller_test.go
  pkg/controller/machineset/machineset_reconciler_suite_test.go
  pkg/controller/machineset/machineset_reconciler_test.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1265 :sparkles: Add optional pprof http server
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1248 Adds sequence diagram for v1alpha2
  docs/proposals/images/developer/diagram.plantuml
  docs/proposals/images/developer/diagram.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#1268 :running: Update controller-{runtime, tools} to v0.2.0-rc.0
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/log/log.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1270 🐛 Update and fix kustomize files
  Makefile
  cmd/example-provider/BUILD.bazel
  cmd/example-provider/Dockerfile
  cmd/example-provider/main.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/ci/kustomization.yaml
  config/ci/manager_image_patch.yaml
  config/ci/manager_label_patch.yaml
  config/ci/rbac/kustomization.yaml
  config/ci/rbac/leader_election_role.yaml
  config/ci/rbac/leader_election_role_binding.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_label_patch.yaml
  config/manager/manager.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  scripts/ci-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1273 🏃Update Go 1.12.9 / Bazel deps
  Dockerfile
  WORKSPACE
  cmd/example-provider/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#1277 🐛 chore: set up recorder for machineset controller
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1275 :sparkles: Add PatchHelper to utils
  .gitignore
  controllers/BUILD.bazel
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/machine_controller.go
  controllers/machineset_controller_test.go
  controllers/suite_util_test.go
  util/patch/BUILD.bazel
  util/patch/patch.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1278 🏃Use const instead of var for string constants
  api/v1alpha2/cluster_phase_types.go
  api/v1alpha2/machine_phase_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1283 🏃Raise golangci-lint deadline to 2m
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1284 add cluster-api categories
  api/v1alpha2/cluster_types.go
  api/v1alpha2/machine_types.go
  api/v1alpha2/machinedeployment_types.go
  api/v1alpha2/machineset_types.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1281 🐛 Fix wrong selectorpath for scale subresources
  api/v1alpha2/machinedeployment_types.go
  api/v1alpha2/machineset_types.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controllers/machinedeployment_controller.go
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1286 🐛Remove provider from get-kubeconfig alpha phase
  cmd/clusterctl/cmd/alpha_phase_get_kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1287 ✨ Add Phase printcolumn to Cluster
  api/v1alpha2/cluster_types.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1288 :sparkles: Remove unnecessary requeues
  controllers/cluster_controller_phases.go
  controllers/machine_controller_noderef.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1289 🏃Improve RequeueAfterError log lines
  controllers/machine_controller_noderef.go
  errors/controllers.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1291 🐛Call reconcileExternal earlier for bootstrap resources
  controllers/machine_controller.go
  controllers/machine_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1264 Bump klog v0.3.1 to v0.4.0
  cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-cluster-no-args.golden
  cmd/clusterctl/testdata/create-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-no-args.golden
  cmd/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-cluster-no-args.golden
  cmd/clusterctl/testdata/delete-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-no-args.golden
  cmd/clusterctl/testdata/no-args-invalid-flag.golden
  cmd/clusterctl/testdata/no-args.golden
  cmd/clusterctl/testdata/validate-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args.golden
  go.mod
  go.sum
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1282 ✨ util/yaml: generic Cluster API yaml parser for clusterctl
  cmd/clusterctl/cmd/BUILD.bazel
  cmd/clusterctl/cmd/alpha_phase_apply_cluster.go
  cmd/clusterctl/cmd/alpha_phase_apply_machines.go
  cmd/clusterctl/cmd/create_cluster.go
  util/BUILD.bazel
  util/util.go
  util/util_test.go
  util/yaml/BUILD.bazel
  util/yaml/yaml.go
  util/yaml/yaml_test.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1292 ✨Add retry poll when acquiring a new clusterctl client
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1293 🏃Update KIND in CI to 0.5.0
  scripts/ci-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1285 Moved RBAC kubebuilder rule generators relevant controllers
  config/rbac/role.yaml
  controllers/cluster_controller.go
  controllers/doc.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1300 🏃Remove release note section from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1296 ✨ support kustomize v3.1.0
  config/certmanager/kustomization.yaml
  config/ci/kustomization.yaml
  config/ci/manager/kustomization.yaml
  config/ci/rbac/kustomization.yaml
  config/crd/kustomization.yaml
  config/crds/kustomization.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/rbac/kustomization.yaml
  scripts/ci-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1302 :warning: [0.1] Cluster, machine controller: support concurrency
  cmd/example-provider/main.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/cluster_reconciler_test.go
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-longterm, size/M

#1305 🏃‍♂️ Remove unused test functions
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  controllers/mdutil/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1308 :sparkles: Make all ClusterNetwork fields optional
  api/v1alpha2/cluster_types.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1311 🏃Update controller runtime and tools to v0.2.0
  go.mod
  go.sum
  vendor/gomodules.xyz/jsonpatch/v2/.gitignore
  vendor/gomodules.xyz/jsonpatch/v2/.travis.yml
  vendor/gomodules.xyz/jsonpatch/v2/CHANGELOG.md
  vendor/gomodules.xyz/jsonpatch/v2/README.md
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/crd.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1298 🐛fix: clean up isDeleteReady logic
  controllers/machine_controller.go
  controllers/machine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1310 ⚠️ Allow nil for ClusterNetwork's Services and Pods
  api/v1alpha2/cluster_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  test/integration/cluster/cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1312 ✨ Support concurrency in all controllers
  BUILD.bazel
  cmd/example-provider/BUILD.bazel
  cmd/example-provider/main.go
  controllers/BUILD.bazel
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machineset_controller.go
  controllers/suite_test.go
  main.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/feature, lgtm, size/M

#1314 🏃Fixup nits from #1312
  cmd/example-provider/main.go
  controllers/suite_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1313 ⚠️ Add APIServerPort field to Cluster networking
  api/v1alpha2/cluster_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  test/integration/cluster/cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1335 🏃 Adds release notes generator tool
  hack/tools/release/notes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1334 :running: Remove hack/sed.sh
  Makefile
  hack/sed.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1337 :running: Allow to provide custom GOPROXY
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1338 Configure manage with sync-period flag
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1339 :sparkles: Feature/move kubeconfig functionality to util
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  util/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1340 :bug: Fix release-notes bug to correctly match on :running:
  hack/tools/release/notes.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1323 ✨ Allow for easier UX when using MS/MD template refs
  controllers/external/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1343 :sparkles: Add tag to action, update Makefile
  .github/workflows/main.yml
  .gitignore
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1342 ⚠️ Add certificate and secret utils
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  cmd/clusterctl/phases/getkubeconfig.go
  controllers/remote/cluster.go
  controllers/remote/cluster_test.go
  util/certs/certs.go
  util/certs/consts.go
  util/certs/types.go
  util/kubeconfig/kubeconfig.go
  util/kubeconfig/kubeconfig_test.go
  util/secret/consts.go
  util/secret/secret.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1345 :warning: Set InfrastructureReady before APIEndpoint
  controllers/cluster_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1344 🏃‍♂️ Name v1alpha2 imports
  cmd/clusterctl/cmd/validate_cluster.go
  cmd/clusterctl/main.go
  cmd/clusterctl/validation/validate_cluster_api_objects.go
  cmd/clusterctl/validation/validate_cluster_api_objects_suite_test.go
  cmd/clusterctl/validation/validate_cluster_api_objects_test.go
  cmd/example-provider/main.go
  controllers/cluster_controller_phases.go
  controllers/machine_controller_noderef.go
  controllers/machine_controller_noderef_test.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/machineset_controller_test.go
  controllers/machineset_delete_policy.go
  controllers/machineset_delete_policy_test.go
  controllers/machineset_status.go
  controllers/mdutil/util.go
  controllers/mdutil/util_test.go
  controllers/remote/cluster.go
  controllers/remote/cluster_test.go
  controllers/suite_test.go
  main.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1346 :bug: Fix output of event when scaling a MachineDeployment
  controllers/machinedeployment_sync.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1347 🏃Release notes tool improvements
  hack/tools/release/notes.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1350 ✨ Create Kubeconfig when APIEndpoints is populated
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
  controllers/remote/cluster.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  util/kubeconfig/kubeconfig.go
  util/kubeconfig/kubeconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1348 🏃 Add release targets
  .github/workflows/main.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#1354 🐛 Retrieve only non-deleted Machines
  controllers/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1353 🐛Delete control plane Machines at the end
  controllers/cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1355 :bug: Fix RBAC for kubeconfig secret generation
  config/rbac/role.yaml
  controllers/cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
