Repository kubernetes-sigs/cluster-api, pull requests merged in 2019-06, with the labels that each got.

#973 updates Google Cloud branding to mach other usages
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#960 Cannot retrieve machine name
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
Labels: approved, cncf-cla: yes, kind/clusterctl, lgtm, ok-to-test, size/XS

#953 Allow to use foregroundDeletion for MachineDeployments and MachineSets
  Gopkg.lock
  pkg/controller/machinedeployment/BUILD.bazel
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machinedeployment/sync.go
  pkg/controller/machineset/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#968 Rename controllers test files
  config/rbac/rbac_role.yaml
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machinedeployment/BUILD.bazel
  pkg/controller/machinedeployment/machinedeployment_controller_test.go
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/machineset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#955 make cluster-api-manager container run with a non-root user
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#659 Update Gitbook release process
  docs/book/RELEASE
  docs/book/SUMMARY.md
  docs/book/book.json
  docs/book/npm-shrinkwrap.json
  docs/book/package.json
  hack/build-gitbook.sh
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#967 Add versioning and releases to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#978 Add more log for cluster deletion failure
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#982 Update vendored dependencies
  Gopkg.lock
  Gopkg.toml
  cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-cluster-no-args.golden
  cmd/clusterctl/testdata/create-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-no-args.golden
  cmd/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-cluster-no-args.golden
  cmd/clusterctl/testdata/delete-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-no-args.golden
  cmd/clusterctl/testdata/no-args-invalid-flag.golden
  cmd/clusterctl/testdata/no-args.golden
  cmd/clusterctl/testdata/validate-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args.golden
  vendor/github.com/google/uuid/node.go
  vendor/github.com/onsi/ginkgo/.travis.yml
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/internal/spec/specs.go
  vendor/github.com/onsi/gomega/.travis.yml
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/Makefile
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/have_occurred_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_xml_matcher.go
  vendor/k8s.io/klog/klog.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#988 Add foregroundDeletion finalizer to Cluster object
  pkg/controller/cluster/cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#987 Remove duplicate checks for deletionTimestamp
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machineset/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#989 Backport foreground deletion
  pkg/controller/cluster/cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#990 Release 0.1.2
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#998 Rename pkg/controller/controller.go
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1000 Always pull distroless/static:latest before building
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1002 Always pull distroless/static:latest before building (Backport to release-0.1)
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1003 Release 0.1.3
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1004 Add remote/util.go helpers to work with KubeConfig Secrets
  pkg/controller/BUILD.bazel
  pkg/controller/cluster/BUILD.bazel
  pkg/controller/remote/BUILD.bazel
  pkg/controller/remote/util.go
  pkg/controller/remote/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1001 add glossary to documentation
  docs/book/SUMMARY.md
  docs/glossary.md
  docs/scope-and-objectives.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#1006 Add remote.ClusterClient to access remote workload clusters
  pkg/controller/remote/BUILD.bazel
  pkg/controller/remote/cluster.go
  pkg/controller/remote/cluster_test.go
  pkg/controller/remote/util.go
  pkg/controller/remote/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#984 support random generate cluster name
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go
  cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1008 Fix links in Architecture documentation.
  docs/book/common_code/architecture.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1013 Update GitBook URL to point to netlify served pages instead of
  README.md
  docs/book/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1012 Add events to MachineSet operations
  pkg/controller/machineset/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1021 Add patch to events rbac
  config/rbac/rbac_role.yaml
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1019 Update some bazel dependencies
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#1026 Add CLUSTER_API_KUBECONFIG_READY_TIMEOUT to clusterctl
  cmd/clusterctl/README.md
  cmd/clusterctl/phases/getkubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1028 docs: fix cluster API glossary page
  docs/book/GLOSSARY.md
  docs/book/SUMMARY.md
  docs/glossary.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1029 Fixup glossary to match GitBook conventions.
  docs/book/GLOSSARY.md
  docs/book/npm-shrinkwrap.json
  docs/scope-and-objectives.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1030 note about membership requirement for /assign
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1032 Update controller-runtime and controller-tools
  Gopkg.lock
  Gopkg.toml
  pkg/controller/machinedeployment/BUILD.bazel
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/api/errors/errors.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/codec.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
  vendor/k8s.io/client-go/transport/token_source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/bootstrap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/certgenerator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/selfsigned.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/util.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/provisioner.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/atomic/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/atomic/atomic_writer.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/certwriter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/error.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/fs.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/secret.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/util.go
  vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/generator.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/crd.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/index.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/util.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/manifests.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/BUILD.bazel
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/admission.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/generator.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/internal/BUILD.bazel
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/internal/client.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/internal/manager.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/manifests.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/types.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/writer.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1020 Support for wrapped RequeueAfterError/interface
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/error/requeue_error.go
  pkg/controller/machine/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#933 Added use case for Cluster Health Checking.
  docs/staging-use-cases.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1043 Bazel updates
  WORKSPACE
  build/run_in_workspace_with_goroot.bzl
Labels: approved, cncf-cla: yes, lgtm, size/M

#1045 clean up shell scripts in cluster-api
  scripts/ci-build.sh
  scripts/ci-integration.sh
  scripts/ci-is-vendor-in-sync.sh
  scripts/ci-make.sh
  scripts/ci-test.sh
  scripts/fetch_ext_bins.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1047 move hpa to the correct spot in the glossary
  docs/book/GLOSSARY.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1048 Update k8s/code-generator to latest release-1.13
  Gopkg.lock
  Gopkg.toml
  pkg/controller/cluster/BUILD.bazel
  pkg/controller/machine/BUILD.bazel
  vendor/k8s.io/code-generator/cmd/client-gen/generators/BUILD.bazel
  vendor/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/tags.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/BUILD.bazel
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/generic.go
  vendor/k8s.io/code-generator/pkg/namer/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/M

#975 downgrade log of util.ExecuteCommand
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#919 Make ClusterNetwork ClusterNetworkingConfig field optional within
  pkg/apis/cluster/v1alpha1/cluster_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1050 Update generated files, add workaround for controller-tools
  .gitignore
  Makefile
  config/ci/rbac/kustomization.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/rbac/kustomization.yaml
  config/rbac/manager_role.yaml
  config/rbac/manager_role_binding.yaml
  pkg/controller/noderef/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/S

#1053 Update controller-tools to 0.1.11
  Gopkg.lock
  Gopkg.toml
  Makefile
  vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/manifests.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1056 Update dep check
  scripts/ci-is-vendor-in-sync.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#997 Machine States & Preboot Bootstrapping
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
  docs/proposals/images/machine-states-preboot/Figure1.png
  docs/proposals/images/machine-states-preboot/Figure2.png
  docs/proposals/images/machine-states-preboot/Figure3.png
  docs/proposals/images/machine-states-preboot/Figure4.png
  docs/proposals/images/machine-states-preboot/Figure5.png
  docs/proposals/images/machine-states-preboot/Figure6.png
  docs/proposals/images/machine-states-preboot/Figure7.png
  docs/proposals/images/machine-states-preboot/Figure8.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#1060 Use development gcr.io project as default registry
  Makefile
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1062 Embed only a subset of metav1.ObjectMeta fields
  config/crds/cluster_v1alpha1_machine.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
  pkg/apis/cluster/v1alpha1/common_types.go
  pkg/apis/cluster/v1alpha1/machine_types.go
  pkg/apis/cluster/v1alpha1/machineset_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/machinedeployment/machinedeployment_reconciler_test.go
  pkg/controller/machinedeployment/util/util_test.go
  pkg/controller/machineset/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1061 Improve generate-* targets in Makefile
  Makefile
  hack/verify_clientset.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1064 Fix register bootstrap options in alpha phases
  cmd/clusterctl/cmd/alpha_phase_create_bootstrap_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1052 Use remote NodeRef in Machine and MachineSet controllers
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/machine_controller.go
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/status.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1068 Add boilerplate.go.txt for kubebuilder
  hack/boilerplate.go.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#1077 correct word
  cmd/clusterctl/phases/getkubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1066 Add noderef controller documentation to gitbook
  docs/book/SUMMARY.md
  docs/book/common_code/node_controller.md
  docs/book/common_code/noderef_controller.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1058 Bootstrap proposal: convert Figures 3-8 to PlantUML, add make target to generate
  .gitignore
  docs/proposals/images/machine-states-preboot/Figure3.plantuml
  docs/proposals/images/machine-states-preboot/Figure3.png
  docs/proposals/images/machine-states-preboot/Figure4.plantuml
  docs/proposals/images/machine-states-preboot/Figure4.png
  docs/proposals/images/machine-states-preboot/Figure5.plantuml
  docs/proposals/images/machine-states-preboot/Figure5.png
  docs/proposals/images/machine-states-preboot/Figure6.plantuml
  docs/proposals/images/machine-states-preboot/Figure6.png
  docs/proposals/images/machine-states-preboot/Figure7.plantuml
  docs/proposals/images/machine-states-preboot/Figure7.png
  docs/proposals/images/machine-states-preboot/Figure8.plantuml
  docs/proposals/images/machine-states-preboot/Figure8.png
  docs/proposals/images/machine-states-preboot/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#1082 Update releasing doc for better go module support
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1080 Add MachinePhase type and helper functions
  config/crds/cluster.sigs.k8s.io_machines.yaml
  pkg/apis/cluster/v1alpha2/BUILD.bazel
  pkg/apis/cluster/v1alpha2/machine_phase_types.go
  pkg/apis/cluster/v1alpha2/machine_types.go
  pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1084 Release v0.1.4
  Makefile
  config/default/manager_image_patch.yaml
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1083 v1alpha2 Machine Controller logic
  cmd/clusterctl/validation/BUILD.bazel
  cmd/clusterctl/validation/validate_cluster_api_objects_test.go
  config/crds/cluster.sigs.k8s.io_machinedeployments.yaml
  config/crds/cluster.sigs.k8s.io_machines.yaml
  config/crds/cluster.sigs.k8s.io_machinesets.yaml
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
  pkg/apis/cluster/v1alpha2/BUILD.bazel
  pkg/apis/cluster/v1alpha2/machine_types.go
  pkg/apis/cluster/v1alpha2/machine_types_test.go
  pkg/apis/cluster/v1alpha2/machinedeployment_types_test.go
  pkg/apis/cluster/v1alpha2/machineset_types_test.go
  pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/error/BUILD.bazel
  pkg/controller/error/requeue_error.go
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_controller_phases.go
  pkg/controller/machine/machine_controller_phases_test.go
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machine/machine_reconciler_test.go
  pkg/controller/machinedeployment/BUILD.bazel
  pkg/controller/machinedeployment/machinedeployment_reconciler_test.go
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/machineset_reconciler_test.go
  pkg/controller/noderef/BUILD.bazel
  pkg/controller/noderef/noderef_controller_test.go
  pkg/util/BUILD.bazel
  pkg/util/util.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1088 Update controller-runtime to v0.2.0-beta.3
  go.mod
  go.sum
  vendor/github.com/appscode/jsonpatch/.gitignore
  vendor/github.com/appscode/jsonpatch/.travis.yml
  vendor/github.com/appscode/jsonpatch/README.md
  vendor/github.com/appscode/jsonpatch/go.mod
  vendor/github.com/appscode/jsonpatch/go.sum
  vendor/github.com/evanphx/json-patch/BUILD.bazel
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/gomodules.xyz/jsonpatch/v2/BUILD.bazel
  vendor/gomodules.xyz/jsonpatch/v2/LICENSE
  vendor/gomodules.xyz/jsonpatch/v2/go.mod
  vendor/gomodules.xyz/jsonpatch/v2/go.sum
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/conversion/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/workqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/multi.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/response.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/alias.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/decoder.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
