Repository kubernetes-sigs/cluster-api, pull requests merged in 2019-07, with the labels that each got.

#1091 Switch kubebuilder domain to sigs.k8s.io
  PROJECT
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1089 Add dynamic watchers to Machine controller
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_controller_phases.go
  pkg/controller/machine/machine_controller_phases_test.go
  pkg/controller/machine/machine_reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1092 Update Go to 1.12.6 and update build flags in Dockerfile
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1093 Use EnsureOwnerRef in MachineDeployment and MachineSet controllers
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machineset/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1095 Add RBAC rules for infrastructure and bootstrap resources
  config/rbac/role.yaml
  pkg/controller/controller.go
  pkg/controller/machinedeployment/BUILD.bazel
  pkg/controller/machineset/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/M

#1094 Add external package to work with unstructured objects
  pkg/controller/external/util.go
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_controller_phases.go
  pkg/controller/machineset/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1101 Change controllerError to lowercase
  pkg/controller/cluster/cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1098 Add templating support to MachineSet (bootstrap & infrastructure)
  go.mod
  pkg/controller/external/BUILD.bazel
  pkg/controller/external/testing.go
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/machineset/machineset_reconciler_suite_test.go
  pkg/controller/machineset/machineset_reconciler_test.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#1107 Update controller-runtime to v0.2.0-beta.4
  cmd/clusterctl/validation/validate_cluster_api_objects_test.go
  go.mod
  go.sum
  pkg/controller/cluster/cluster_reconciler_test.go
  pkg/controller/machine/machine_reconciler_test.go
  pkg/controller/machinedeployment/machinedeployment_reconciler_test.go
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/machineset_reconciler_test.go
  pkg/controller/noderef/noderef_controller_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/listener.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1106 MachineSet reconcile test hardening
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/machineset_reconciler_suite_test.go
  pkg/controller/machineset/machineset_reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1111 Scope MachineSet controller Machine listing with labels
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/machineset/machineset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1121 Fix ProviderID handling of scheme://oneSegment
  pkg/controller/noderefutil/BUILD.bazel
  pkg/controller/noderefutil/providerid.go
  pkg/controller/noderefutil/providerid_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1123 [0.1] Fix ProviderID handling of scheme://oneSegment (#1121)
  pkg/controller/noderefutil/BUILD.bazel
  pkg/controller/noderefutil/providerid.go
  pkg/controller/noderefutil/providerid_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1116 MachineDeployment controller and test hardening
  pkg/controller/machinedeployment/BUILD.bazel
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machinedeployment/machinedeployment_reconciler_suite_test.go
  pkg/controller/machinedeployment/machinedeployment_reconciler_test.go
  pkg/controller/machinedeployment/rolling.go
  pkg/controller/machinedeployment/sync.go
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/machineset_reconciler_suite_test.go
  pkg/controller/machineset/machineset_reconciler_test.go
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1087 Match ncdc owner aliases with k/org
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1117 Don't swallow errors when reconciling noderef
  pkg/controller/noderef/noderef_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1124 Document Netlify based OS agnostic testing (fixes #1005).
  docs/book/RELEASE
Labels: approved, cncf-cla: yes, lgtm, size/S

#1126 Cleanup Machine controller tests
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/machine_reconciler_suite_test.go
  pkg/controller/machine/machine_reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1130 Remove pkg/kubeadm and pkg/cmdrunner
  pkg/cmdrunner/BUILD.bazel
  pkg/cmdrunner/cmd_runner.go
  pkg/cmdrunner/cmd_runner_test.go
  pkg/kubeadm/BUILD.bazel
  pkg/kubeadm/kubeadm.go
  pkg/kubeadm/kubeadm_test.go
  pkg/testcmdrunner/BUILD.bazel
  pkg/testcmdrunner/test_cmd_runner.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1108 Add Dockerfile for plantuml image used to generate proposal diagrams
  docs/proposals/images/machine-states-preboot/Dockerfile
  docs/proposals/images/machine-states-preboot/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1129 Consolidate error packages
  pkg/controller/cluster/BUILD.bazel
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/error/BUILD.bazel
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_controller_phases.go
  pkg/controller/machine/machine_controller_phases_test.go
  pkg/errors/BUILD.bazel
  pkg/errors/controllers.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1110 Do not delete NodeRef for last control plane node
  pkg/controller/machine/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1133 Rereconcile machineset if not all replicas are ready
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/machineset/status.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1136 [0.1] Rereconcile machineset if not all replicas are ready (#1133)
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/machineset/status.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1135 Do not delete NodeRef for last control plane node
  pkg/controller/machine/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1128 Embed NodeRef logic into Machine controller
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
  pkg/controller/BUILD.bazel
  pkg/controller/add_noderef.go
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_controller_noderef.go
  pkg/controller/machine/machine_controller_noderef_test.go
  pkg/controller/machine/machine_controller_phases.go
  pkg/controller/machine/machine_controller_phases_test.go
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machinedeployment/util/BUILD.bazel
  pkg/controller/noderef/BUILD.bazel
  pkg/controller/noderef/noderef_controller.go
  pkg/controller/noderef/noderef_controller_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1139 Add section around backporting patches
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1140 [0.1] Reduce Reconcile() complexity with needUpdateFinalizers
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1081 Remove NodeConditions from Machine.Status
  config/crds/cluster.sigs.k8s.io_machines.yaml
  pkg/apis/cluster/v1alpha2/machine_types.go
  pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1134 Add full vendor utilities for gomod
  go.vendor
  hack/update-vendor.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1144 Release v0.1.5
  Makefile
  config/default/manager_image_patch.yaml
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1146 Release v0.1.6
  Makefile
  config/default/manager_image_patch.yaml
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1147 Add gazelle rule for grpc-ecosystem
  BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1149 Rename controller name with - instead of _
  config/rbac/role.yaml
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/machine/machine_controller.go
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machineset/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1131 Doc on clusterctl. How to use and how it works.
  README.md
  docs/how-to-use-clusterctl.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1154 [0.1] Don't swallow errors when reconciling noderef
  pkg/controller/noderef/noderef_controller.go
Labels: cncf-cla: yes, lgtm, size/S

#1155 Add GetControlPlaneMachinesFromList and remove deprecated function
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1152 Add util.GetClusterFromMetadata
  pkg/controller/machine/machine_controller.go
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machineset/machineset_controller.go
  pkg/util/BUILD.bazel
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1153 Add util.MachineToInfrastructureMapFunc for infrastructure providers
  config/rbac/role.yaml
  pkg/util/BUILD.bazel
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1159 Add util.GetMachineOwner
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1163 Convert bootstrap Figure1 to plantuml
  docs/proposals/images/machine-states-preboot/Figure1.plantuml
  docs/proposals/images/machine-states-preboot/Figure1.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#1151 add log to indicate cluster/machine mismatch
  pkg/controller/machine/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1148 Update Releasing Docs
  config/default/manager_image_patch.yaml
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1164 Release v0.1.7
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1162 Add MachineAddress type for infrastructure providers
  pkg/apis/cluster/v1alpha2/common_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1165 Adds a trailing newline
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1157 Update lodash to address CVE
  docs/book/npm-shrinkwrap.json
  docs/book/package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#1167 Use an inline decoder so we don't constantly have to (un)marshal
  pkg/util/BUILD.bazel
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1160 Convert {Bootstrap,Infrastructure}Ready fields to plain bools
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
  pkg/apis/cluster/v1alpha2/machine_types.go
  pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/machine/machine_controller_phases.go
  pkg/controller/machine/machine_controller_phases_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1100 Update glossary doc with terminology
  docs/book/GLOSSARY.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1169 Set control-plane-ready annotation on Cluster
  pkg/apis/cluster/v1alpha2/BUILD.bazel
  pkg/apis/cluster/v1alpha2/cluster_types.go
  pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/machine/machine_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1156 [0.1] Update lodash gitbook dependency to address CVE
  docs/book/npm-shrinkwrap.json
  docs/book/package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#1175 Always Patch machines on defer, requeue if finalizer cannot be removed
  pkg/controller/machine/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1137 Externalize provider specific specs and status in separated CRDs
  docs/proposals/20190709-cluster-spec-crds.md
  docs/proposals/images/cluster-spec-crds/figure1.plantuml
  docs/proposals/images/cluster-spec-crds/figure1.png
  docs/proposals/images/cluster-spec-crds/figure2.platuml
  docs/proposals/images/cluster-spec-crds/figure2.png
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1176 Update Netlify config for v1alpha1 subdomain
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1161 Update bootstrap proposal: document Status.Ready
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
  docs/proposals/images/machine-states-preboot/Figure3.plantuml
  docs/proposals/images/machine-states-preboot/Figure3.png
  docs/proposals/images/machine-states-preboot/Figure4.plantuml
  docs/proposals/images/machine-states-preboot/Figure4.png
  docs/proposals/images/machine-states-preboot/Figure5.plantuml
  docs/proposals/images/machine-states-preboot/Figure5.png
  docs/proposals/images/machine-states-preboot/Figure6.plantuml
  docs/proposals/images/machine-states-preboot/Figure6.png
  docs/proposals/images/machine-states-preboot/Figure7.png
  docs/proposals/images/machine-states-preboot/Figure8.plantuml
  docs/proposals/images/machine-states-preboot/Figure8.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#1179 Make clusterctl provider agnostic / remove deployer
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  cmd/clusterctl/clusterdeployer/provider/BUILD.bazel
  cmd/clusterctl/clusterdeployer/provider/provider.go
  cmd/clusterctl/cmd/BUILD.bazel
  cmd/clusterctl/cmd/alpha_phase_get_kubeconfig.go
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/cmd/create_cluster_test.go
  cmd/clusterctl/phases/BUILD.bazel
  cmd/clusterctl/phases/getkubeconfig.go
  cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-cluster-no-args.golden
  cmd/example-provider/BUILD.bazel
  cmd/example-provider/main.go
  pkg/apis/cluster/common/BUILD.bazel
  pkg/apis/cluster/common/plugins.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1181 Improve diagram generation / fixup cluster proposal
  Makefile
  docs/proposals/images/Dockerfile
  docs/proposals/images/Makefile
  docs/proposals/images/cluster-spec-crds/figure1.plantuml
  docs/proposals/images/cluster-spec-crds/figure1.png
  docs/proposals/images/cluster-spec-crds/figure2.plantuml
  docs/proposals/images/cluster-spec-crds/figure2.png
  docs/proposals/images/machine-states-preboot/Figure5.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#1170 Build manager binary inside a container
  Makefile
Labels: approved, area/release, cncf-cla: yes, lgtm, size/S

#1182 Switch apiGroup to x-k8s.io
  PROJECT
  cmd/clusterctl/validation/validate_cluster_api_objects_test.go
  config/crds/cluster.x-k8s.io_clusters.yaml
  config/crds/cluster.x-k8s.io_machinedeployments.yaml
  config/crds/cluster.x-k8s.io_machines.yaml
  config/crds/cluster.x-k8s.io_machinesets.yaml
  config/crds/kustomization.yaml
  config/rbac/role.yaml
  pkg/apis/cluster/v1alpha2/cluster_types.go
  pkg/apis/cluster/v1alpha2/doc.go
  pkg/apis/cluster/v1alpha2/machine_types.go
  pkg/apis/cluster/v1alpha2/machine_types_test.go
  pkg/apis/cluster/v1alpha2/machinedeployment_types_test.go
  pkg/apis/cluster/v1alpha2/machineset_types.go
  pkg/apis/cluster/v1alpha2/machineset_types_test.go
  pkg/apis/cluster/v1alpha2/register.go
  pkg/client/clientset_generated/clientset/typed/cluster/v1alpha2/cluster_client.go
  pkg/client/clientset_generated/clientset/typed/cluster/v1alpha2/fake/fake_cluster.go
  pkg/client/clientset_generated/clientset/typed/cluster/v1alpha2/fake/fake_machine.go
  pkg/client/clientset_generated/clientset/typed/cluster/v1alpha2/fake/fake_machinedeployment.go
  pkg/client/clientset_generated/clientset/typed/cluster/v1alpha2/fake/fake_machineset.go
  pkg/client/informers_generated/externalversions/generic.go
  pkg/controller/controller.go
  pkg/controller/external/testing.go
  pkg/controller/machine/machine_controller_phases_test.go
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machinedeployment/machinedeployment_reconciler_test.go
  pkg/controller/machineset/machineset_reconciler_test.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1183 Release v0.1.8
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1174 Add logic to copy Machine Addresses from InfraRef
  config/crds/cluster.x-k8s.io_machines.yaml
  pkg/apis/cluster/v1alpha2/machine_types.go
  pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/machine/machine_controller_phases.go
  pkg/controller/machine/machine_controller_phases_test.go
  pkg/controller/machine/machine_controller_test.go
  pkg/util/BUILD.bazel
  pkg/util/util.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#1184 kustomization.yaml: Use patchesStrategicMerge
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1185 release-0.1: kustomization.yaml: Use patchesStrategicMerge (#1184)
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1186 Use v1alpha2 as version in tests
  cmd/clusterctl/validation/validate_cluster_api_objects_test.go
  pkg/apis/cluster/v1alpha2/machine_types_test.go
  pkg/apis/cluster/v1alpha2/machinedeployment_types_test.go
  pkg/apis/cluster/v1alpha2/machineset_types_test.go
  pkg/controller/external/testing.go
  pkg/controller/machine/machine_controller_phases_test.go
  pkg/controller/machine/machine_controller_test.go
  pkg/controller/machine/machine_reconciler_test.go
  pkg/controller/machinedeployment/machinedeployment_reconciler_test.go
  pkg/controller/machineset/machineset_reconciler_test.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#1189 Add Packet to cluster-api provider list
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1180 [0.1] Delete machines
  pkg/controller/cluster/BUILD.bazel
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/cluster_reconciler_test.go
  pkg/util/BUILD.bazel
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1192 [0.1] Match ncdc owner aliases with k/org (#1087)
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1194 Update plantuml generation to use CAPI-managed image
  docs/proposals/images/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1193 Revert proposal change of ClusterStatus.APIEndpoints to APIEndpoint
  docs/proposals/20190709-cluster-spec-crds.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1200 Fix GVK in Machine Controller
  pkg/controller/machine/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/S

#1212 Add Cluster helper funcs for infra providers to use
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/L

#1171 Update sample config files
  .gitignore
  config/samples/cluster_v1alpha1_cluster.yaml
  config/samples/cluster_v1alpha1_machine.yaml
  config/samples/cluster_v1alpha1_machinedeployment.yaml
  config/samples/cluster_v1alpha1_machineset.yaml
  config/samples/cluster_v1alpha2_cluster.yaml
  config/samples/cluster_v1alpha2_machine.yaml
  config/samples/cluster_v1alpha2_machinedeployment.yaml
  config/samples/cluster_v1alpha2_machineset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1213 Add section on acronyms to the GitBook
  .gitignore
  Makefile
  docs/book/ABBREVIATIONS.md
  docs/book/RELEASE
  docs/book/SUMMARY.md
  hack/build-gitbook.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1207 [0.1] set OwnerRef in more cases
  pkg/controller/machine/machine_controller.go
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machineset/machineset_controller.go
  pkg/util/BUILD.bazel
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
