Repository kubernetes-sigs/cluster-api, pull requests merged in 2019-01, with the labels that each got.

#665 Fix broken link
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#664 Fix typo in gitbook include
  docs/book/common_code/machineset_controller.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#637 Mark required flags of clusterctl as required explicitly
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-cluster-no-args.golden
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#650 Add unit test for machine controller reconcile
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/testactuator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#668 Update link to azure cluster-api cloud provider
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#673 Replace remaining uses of Poll with PollImmediate.
  pkg/controller/machineset/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#672 Switch from debian:latest to gcr.io/distroless/static:latest
  Dockerfile
  config/crds/cluster_v1alpha1_cluster.yaml
  config/crds/cluster_v1alpha1_machine.yaml
  config/crds/cluster_v1alpha1_machineclass.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
  config/default/manager_image_patch.yaml-e
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machinedeployment/BUILD.bazel
  pkg/controller/machineset/BUILD.bazel
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/L

#675 Pretty diffs in clusterctl testing
  Gopkg.lock
  cmd/clusterctl/main_integration_test.go
  vendor/github.com/sergi/go-diff/AUTHORS
  vendor/github.com/sergi/go-diff/CONTRIBUTORS
  vendor/github.com/sergi/go-diff/LICENSE
  vendor/github.com/sergi/go-diff/diffmatchpatch/BUILD.bazel
  vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#680 Fix format of Resources section in book README
  docs/book/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#681 Add JoinClusterTimeoutMachineError
  pkg/apis/cluster/common/consts.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#685 Update meeting notes and zoom links
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#691 Fix pull-cluster-api-vendor-in-sync presubmit
  scripts/ci-is-vendor-in-sync.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#692 Add Make dep-ensure
  Makefile
  cmd/manager/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#696 use the new link of the cluster-api KEPs in the documentation
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#694 Updated godoc for machine_types.go to align with best practices
  config/crds/cluster_v1alpha1_machine.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
  pkg/apis/cluster/v1alpha1/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#674 Add KIND as cluster bootstrapper
  cmd/clusterctl/clusterdeployer/bootstrap/BUILD.bazel
  cmd/clusterctl/clusterdeployer/bootstrap/kind/BUILD.bazel
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind_test.go
  cmd/clusterctl/clusterdeployer/bootstrap/provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#690 Use pkg/errors instead of fmt.Errorf
  Makefile
  cmd/clusterctl/clusterdeployer/BUILD.bazel
  cmd/clusterctl/clusterdeployer/bootstrap/existing/BUILD.bazel
  cmd/clusterctl/clusterdeployer/bootstrap/existing/existingcluster.go
  cmd/clusterctl/clusterdeployer/bootstrap/minikube/BUILD.bazel
  cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
  cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube_test.go
  cmd/clusterctl/clusterdeployer/clusterclient/BUILD.bazel
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  cmd/clusterctl/cmd/BUILD.bazel
  cmd/clusterctl/cmd/alpha_phase_apply_cluster.go
  cmd/clusterctl/cmd/alpha_phase_apply_cluster_api_components.go
  cmd/clusterctl/cmd/alpha_phase_apply_machines.go
  cmd/clusterctl/cmd/alpha_phase_create_bootstrap_cluster.go
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/cmd/delete_cluster.go
  cmd/clusterctl/cmd/validate_cluster.go
  cmd/clusterctl/main_integration_test.go
  cmd/clusterctl/phases/BUILD.bazel
  cmd/clusterctl/phases/applycluster.go
  cmd/clusterctl/phases/applyclusterapicomponents.go
  cmd/clusterctl/phases/applymachines.go
  cmd/clusterctl/phases/createbootstrapcluster.go
  cmd/clusterctl/providercomponents/BUILD.bazel
  cmd/clusterctl/providercomponents/providercomponents.go
  cmd/clusterctl/providercomponents/providercomponents_test.go
  cmd/clusterctl/validation/BUILD.bazel
  cmd/clusterctl/validation/testdata/fail-to-validate-machine-objects-with-noderef-errors.golden
  cmd/clusterctl/validation/validate_cluster_api_objects.go
  pkg/apis/cluster/common/BUILD.bazel
  pkg/apis/cluster/common/plugins.go
  pkg/cert/BUILD.bazel
  pkg/cert/cert_authority.go
  pkg/controller/machinedeployment/BUILD.bazel
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machinedeployment/rolling.go
  pkg/controller/machinedeployment/sync.go
  pkg/controller/machinedeployment/util/BUILD.bazel
  pkg/controller/machinedeployment/util/util.go
  pkg/controller/machinedeployment/util/util_test.go
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/status.go
  pkg/errors/BUILD.bazel
  pkg/errors/deployer.go
  pkg/test-cmd-runner/BUILD.bazel
  pkg/test-cmd-runner/test_cmd_runner.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#698 [clusterctl] Fix create cluster workflow
  cmd/clusterctl/cmd/create_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#703 Fix for KIND kubeconfig returning with newline
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#704 Fix the GitBook link in the docs
  docs/book/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#705 Fix some typos and dead links in the documentation
  docs/book/README.md
  docs/book/common_code/architecture.md
  docs/book/common_code/machine_controller.md
  docs/book/provider_implementations/building_running_and_testing.md
  docs/book/provider_implementations/create_actuators.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#702 Attempt to fix TestReconcile races
  pkg/controller/machinedeployment/machinedeployment_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#670 Update project maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#708 use latest security patch release of golang
  Dockerfile
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#684 Require providerSpec.Value[From] to be always set
  config/crds/cluster_v1alpha1_machine.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#714 Update bazel rules-go
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#715 Correctly initialize klog in clusterctl
  cmd/clusterctl/cmd/root.go
  cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-cluster-no-args.golden
  cmd/clusterctl/testdata/create-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-no-args.golden
  cmd/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-cluster-no-args.golden
  cmd/clusterctl/testdata/delete-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-no-args.golden
  cmd/clusterctl/testdata/no-args-invalid-flag.golden
  cmd/clusterctl/testdata/no-args.golden
  cmd/clusterctl/testdata/validate-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/validate-no-args.golden
  cmd/manager/main.go
  config/crds/cluster_v1alpha1_machine.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#699 Add CI linter
  .golangci.yml
  BUILD.bazel
  Makefile
  WORKSPACE
  build/BUILD
  build/run_in_workspace_with_goroot.bzl
  cmd/clusterctl/clientcmd/configutil.go
  cmd/clusterctl/clusterdeployer/bootstrap/existing/cluster_test.go
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind_test.go
  cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube_test.go
  cmd/clusterctl/clusterdeployer/bootstrap/provisioner.go
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  cmd/clusterctl/cmd/alpha_phase_create_bootstrap_cluster.go
  cmd/clusterctl/validation/validate_cluster_api_objects.go
  cmd/clusterctl/validation/validate_cluster_api_objects_test.go
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/machine_types.go
  pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  pkg/apis/cluster/v1alpha1/machineset_types.go
  pkg/cert/cert_authority_test.go
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machinedeployment/controller_test.go
  pkg/controller/machinedeployment/rolling.go
  pkg/controller/machinedeployment/sync.go
  pkg/controller/machinedeployment/util/util.go
  pkg/controller/machinedeployment/util/util_test.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/machine.go
  pkg/controller/node/node.go
  pkg/controller/noderefutil/util_test.go
  pkg/errors/deployer.go
  pkg/kubeadm/kubeadm.go
  pkg/kubeadm/kubeadm_test.go
  pkg/util/util.go
  scripts/ci-make.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#716 Improve YAML processing in clusterctl
  Gopkg.lock
  pkg/util/BUILD.bazel
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#565 Extend MachineStatus to add ProviderID
  pkg/apis/cluster/v1alpha1/machine_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#710 clusterctl: kind should ignore some extra flags
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#724 Make CRDs public in Bazel
  config/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS
