Repository kubernetes-sigs/cluster-api, pull requests merged in 2019-09, with the labels that each got.

#1360 :bug: Update API endpoints if missing
  controllers/cluster_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1361 :running: Release target fixes
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1367 🐛 Set the correct OwnerRef Kind in MD controller
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_controller_test.go
  controllers/machinedeployment_sync.go
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1357 [0.1] Pivot secrets
  cmd/clusterctl/clusterdeployer/BUILD.bazel
  cmd/clusterctl/clusterdeployer/clusterclient/BUILD.bazel
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  cmd/clusterctl/phases/BUILD.bazel
  cmd/clusterctl/phases/pivot.go
  cmd/clusterctl/phases/pivot_test.go
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1363 🏃Add release binaries target to Makefile
  .gitignore
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#1364 🏃 Update the release docs to reflect the new process
  Makefile
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1376 Add .DS_Store to .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1378 :bug: Fix MachineDeployment test flake
  controllers/machinedeployment_controller_test.go
  controllers/suite_util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1325 :sparkles: Improve ErrorMessage from referenced resources
  controllers/cluster_controller_phases.go
  controllers/machine_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1385 🏃 ClusterReconciler: make Client a proper field
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1387 🏃 MachineDeploymentReconciler: make Client a proper field
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_sync.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1386 🏃 MachineSetReconciler: make Client a proper field
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1388 🏃 MachineReconciler: make Client a proper field
  controllers/machine_controller.go
  controllers/machine_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1392 :running: Use prow/GCB for automated image builds rather than GitHub Actions
  .github/workflows/main.yml
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1393 🐛 Updates release notes generator
  hack/tools/release/notes.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1394 📖 Mark proposals as implemented
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
  docs/proposals/20190709-cluster-spec-crds.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1395 :running: Prepare for v0.1.10
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1396 📖 Improve quickstart for AWS components installation
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1401 :book: Add WIP for various docs
  docs/book/src/abbreviations.md
  docs/book/src/architecture/controllers.md
  docs/book/src/architecture/controllers/machine-deployment.md
  docs/book/src/architecture/controllers/machine-set.md
  docs/book/src/architecture/developer-guide.md
  docs/book/src/architecture/repository-layout.md
  docs/book/src/tooling/tooling.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#1403 ⚠️ Add OwnerReference to Kubeconfig secret
  util/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1405 :bug: manager: use our RESTMapper
  cmd/clusterctl/clientcmd/configutil.go
  main.go
  util/restmapper/cached.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#1406 :running: Update cloudbuild.yaml for PULL_BASE_REF substitution
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1380 :bug: Improve handling of patching and updates in MachineSet and MachineDeployment controllers
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_sync.go
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1397 📖 Move clusterctl to book
  docs/book/src/tooling/clusterctl.md
  docs/how-to-use-clusterctl.md
  hack/verify-doctoc.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1413 ✨ Add util/record package from CAPA
  util/record/recorder.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#1358 🐛 track MS with old labels after updating MD labels
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_controller_test.go
  controllers/mdutil/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1420 📖 Automate the release links in mdbook
  docs/book/Makefile
  docs/book/book.toml
  docs/book/src/user/quick-start.md
  docs/book/util-releaselink.sh
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/mdbook/releaselink/releaselink.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1417 🏃 Make getMachinesInCluster a helper function
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machine_helpers.go
  controllers/machine_helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1426 Better check to wait for the control-plane to become available
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1430 🐛Fix patch in MachineSet adoption
  controllers/machinedeployment_sync.go
  controllers/machineset_controller.go
  controllers/machineset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1424 📖 Updated release docs
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1432 📖 Add CABPK abbreviation and v1alpha2-ize other abbreviations
  docs/book/src/reference/abbreviations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1390 📖 Adds a cluster controller document
  docs/book/src/architecture/controllers/cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1434 Update issue templates prior to v1alpha3 mass submission.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1436 🏃 Update controller-runtime@v0.2.2 and controller-tools@v0.2.1
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#1435 re-apply secret OwnerRef on pivot with correct UID
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  cmd/clusterctl/phases/pivot.go
  cmd/clusterctl/phases/pivot_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1437 🐛 Fix the issue feature template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1439 🐛Add deprecation message to clusterctl commands
  cmd/clusterctl/cmd/alpha_phase_apply_addons.go
  cmd/clusterctl/cmd/alpha_phase_apply_boostrap_components.go
  cmd/clusterctl/cmd/alpha_phase_apply_cluster.go
  cmd/clusterctl/cmd/alpha_phase_apply_cluster_api_components.go
  cmd/clusterctl/cmd/alpha_phase_apply_machines.go
  cmd/clusterctl/cmd/alpha_phase_create_bootstrap_cluster.go
  cmd/clusterctl/cmd/alpha_phase_get_kubeconfig.go
  cmd/clusterctl/cmd/alpha_phase_pivot.go
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/cmd/delete_cluster.go
  cmd/clusterctl/cmd/root.go
  cmd/clusterctl/cmd/validate_cluster.go
  cmd/clusterctl/testdata/create-no-args.golden
  cmd/clusterctl/testdata/delete-cluster-no-args.golden
  cmd/clusterctl/testdata/delete-no-args.golden
  cmd/clusterctl/testdata/no-args.golden
  cmd/clusterctl/testdata/validate-no-args.golden
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1443 🏃 Add go mod verification in CI
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1409 🏃 Adds chuckha to maintainers list
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1448 📖 Changes confusing language in the CAEP template
  docs/proposals/YYYYMMDD-template.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1449 :running: Fix table CSS
  docs/book/theme/css/general.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1447 ✨Tag branches or latest when building images
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1453 :running: Remove for machineset concurrent delete calls
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1454 ⚠️ Clarify Machine.Spec.ObjectMeta use in godoc
  api/v1alpha2/machine_types.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controllers/mdutil/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1452 🐛 Machine deletion: try up to 10s to delete the Node, then move on
  controllers/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1425 ✨ Removed redundant OwnerReference check
  controllers/cluster_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1457 🐛Fix reference to PULL_BASE_REF for image building
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1463 🏃Remove unused function `isScalingEvent`
  controllers/machinedeployment_sync.go
  controllers/mdutil/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1464 🐛 DeepCopy unstructured objects in helper before patching
  util/patch/patch.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1467 🐛 DeepCopy unstructured object in patch helper Patch method
  util/patch/patch.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1462 📖Fix broken links to api-conventions doc
  OWNERS_ALIASES
  api/v1alpha2/common_types.go
  api/v1alpha2/machineset_types.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crds/cluster.k8s.io_clusters.yaml
  config/crds/cluster.k8s.io_machineclasses.yaml
  config/crds/cluster.k8s.io_machinedeployments.yaml
  config/crds/cluster.k8s.io_machines.yaml
  config/crds/cluster.k8s.io_machinesets.yaml
  pkg/apis/deprecated/v1alpha1/common_types.go
  pkg/apis/deprecated/v1alpha1/machineset_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1458 :bug: Update Machine Status with Error Reason and Error Message if infra object is deleted
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
