Repository kubernetes-sigs/cluster-api, pull requests merged in 2019-02, with the labels that each got.

#725 Add golint to CI linters
  .golangci.yml
  cmd/clusterctl/clusterdeployer/clusterclient/clientfactory.go
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  pkg/apis/cluster/v1alpha1/machineset_types.go
  pkg/apis/cluster/v1alpha1/register.go
  pkg/cmdrunner/cmd_runner.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#722 Use RevisionVersion field instead of CreationTimestamp to decide which MS is new/old
  pkg/controller/machinedeployment/machinedeployment_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#624 clusterctl - Add phase for get-kubeconfig
  cmd/clusterctl/clusterdeployer/BUILD.bazel
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  cmd/clusterctl/clusterdeployer/provider/BUILD.bazel
  cmd/clusterctl/clusterdeployer/provider/provider.go
  cmd/clusterctl/clusterdeployer/providercomponentsstorefactory.go
  cmd/clusterctl/cmd/BUILD.bazel
  cmd/clusterctl/cmd/alpha_phase_get_kubeconfig.go
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/phases/BUILD.bazel
  cmd/clusterctl/phases/getkubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#729 Updated link to OWNERS docs
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#727 Remove client.ListOptions.Raw hack
  config/crds/cluster_v1alpha1_machine.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/controller.go
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machineset/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#734 Avoid hardcoding port in clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#737 Fix passing context from the start in run validate cluster cmd
  cmd/clusterctl/cmd/validate_cluster.go
  cmd/clusterctl/validation/validate_cluster_api_objects.go
  cmd/clusterctl/validation/validate_cluster_api_objects_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#736 Fixed creating clusters in different namespaces when pivoting
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#728 Stronger link between Machine* <-> Cluster
  Gopkg.lock
  docs/book/common_code/machine_controller.md
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machinedeployment/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#739 Validate MachineSet and MachineDeployment labels
  cmd/clusterctl/clusterdeployer/BUILD.bazel
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machineset/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#740 Index metadata.name for cluster-name label
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#744 Simplify cluster-name query using Get
  Gopkg.lock
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#751 gazelle: specify proto disable_global
  BUILD.bazel
  vendor/github.com/golang/protobuf/ptypes/BUILD.bazel
  vendor/github.com/googleapis/gnostic/OpenAPIv2/BUILD.bazel
  vendor/github.com/googleapis/gnostic/compiler/BUILD.bazel
  vendor/github.com/googleapis/gnostic/extensions/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/S

#752 Add owners for gh-pages branch
  OWNERS
Labels: cncf-cla: yes, size/XS

#753 Add OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: cncf-cla: yes

#754 fix of sed usage
  Makefile
  config/default/manager_image_patch.yaml-e
Labels: approved, cncf-cla: yes, lgtm, size/S

#750 Add directives for setting ClusterRole permissions in the book
  docs/book/provider_implementations/create_actuators.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#756 Make APIVersion/Kind mandatory for MachineList
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#759 config: Adjust to new version of kustomize.
  config/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#757 Set Machines ownerRef to cluster with foregroundDeletion
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#760 Add util.GetControlPlaneMachines / cleanup
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#766 Fix Bazel after Kustomize2 update
  config/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#767 Cleanup ownerRef on Machine upon pivot
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#755 Integration test with example provider (step 1)
  .gitignore
  Gopkg.lock
  Makefile
  cmd/example-provider/BUILD.bazel
  cmd/example-provider/main.go
  config/ci/kustomization.yaml
  config/ci/manager/kustomization.yaml
  config/ci/manager_image_patch.yaml
  config/ci/rbac/kustomization.yaml
  config/crds/kustomization.yaml
  config/default/kustomization.yaml
  config/kustomization.yaml
  config/manager/kustomization.yaml
  config/rbac/kustomization.yaml
  config/rbac/rbac_role.yaml
  pkg/controller/controller.go
  pkg/controller/machine/BUILD.bazel
  pkg/provider/example/actuators/cluster/BUILD.bazel
  pkg/provider/example/actuators/cluster/clusteractuator.go
  pkg/provider/example/actuators/machine/BUILD.bazel
  pkg/provider/example/actuators/machine/machineactuator.go
  pkg/provider/example/container/Dockerfile
  scripts/ci-integration.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#762 Cleanup MachineDeployment controller
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machinedeployment/controller_test.go
  pkg/controller/machinedeployment/rolling.go
  pkg/controller/machinedeployment/sync.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#763 Cleanup Machine controller
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#761 Cleanup MachineSet controller
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#771 Fix Kustomize2 usage after #755
  config/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#773 Move kustomization.yaml in default and use bases
  config/BUILD.bazel
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#774 add exec bit to integration shell
  scripts/ci-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#785 Add foregroundDeletion only if cluster is nil, move label in types
  pkg/apis/cluster/v1alpha1/machine_types.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#679 Add Kubernetes cluster validation
  cmd/clusterctl/cmd/validate_cluster.go
  cmd/clusterctl/validation/BUILD.bazel
  cmd/clusterctl/validation/validate_pods.go
  cmd/clusterctl/validation/validate_pods_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#782 Clarify kubebuilder minimal version is 1.0.5.
  docs/book/provider_implementations/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#779 [book] Fix rbac of the provider implementations in the book
  docs/book/provider_implementations/building_running_and_testing.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
