Repository kubernetes-sigs/cluster-api, pull requests merged in 2019-03, with the labels that each got.

#790 Added bootstrap-only components to clusterctl as an option
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  cmd/clusterctl/cmd/BUILD.bazel
  cmd/clusterctl/cmd/alpha_phase_apply_boostrap_components.go
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/cmd/delete_cluster.go
  cmd/clusterctl/phases/BUILD.bazel
  cmd/clusterctl/phases/applybootstrapcomponents.go
  cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-cluster-no-args.golden
  cmd/clusterctl/validation/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/L

#793 Set ownerRef / foregroundDeletion on MachineSets/Deployments
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machinedeployment/controller_test.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#797 MachineDeployment controller: expose errors
  pkg/controller/machinedeployment/BUILD.bazel
  pkg/controller/machinedeployment/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#796 docs: fix trailing period
  docs/book/getting_started/existing_providers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#801 Update gazel and rules_go bazel dependencies
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#799 Support MachineDeployment adoption of MachineSets
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machinedeployment/controller_test.go
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#802 Run gazelle after updating generated clientset
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#803 Fix `make verify` failure after #802
  Makefile
  hack/verify-bazel.sh
  hack/verify_clientset.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#804 Update Bazel rules_go to 0.18
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#805 Fix an issue with verify_client.sh
  Makefile
  hack/verify_clientset.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#806 Rev the version of golangci-lint used
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#768 Document release process
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#780 Add missing flag to manager in sample provider code
  docs/book/provider_implementations/register_schemes.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#813 Update RBAC to allow node controller to set noderef
  config/rbac/rbac_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#811 Integration test to verify controller pods status
  scripts/ci-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#810 Allow to record machine update error
  pkg/apis/cluster/common/consts.go
  pkg/errors/machines.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#731 Add pivot phase to clusterctl and unify pivoting approach
  Gopkg.lock
  cmd/clusterctl/clusterdeployer/BUILD.bazel
  cmd/clusterctl/clusterdeployer/clusterclient/BUILD.bazel
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  cmd/clusterctl/cmd/BUILD.bazel
  cmd/clusterctl/cmd/alpha_phase_pivot.go
  cmd/clusterctl/cmd/delete_cluster.go
  cmd/clusterctl/phases/BUILD.bazel
  cmd/clusterctl/phases/applymachines.go
  cmd/clusterctl/phases/pivot.go
  cmd/clusterctl/phases/pivot_test.go
  cmd/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/delete-cluster-no-args.golden
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#809 Delete node on machine deletion
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#814 Handle EOF in clusterctl kubectl apply
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#816 Fix GetMachinesForCluster returning duplicate results
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#818 clusterctl: check EOF using strings.Contains
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#819 add error log for machine update
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#817 Fix delete post pivoting changes
  cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  cmd/clusterctl/clusterdeployer/clusterdeployer.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#792 Update architecture diagram from AAs to CRDs. Fixes #786.
  README.md
  architecture.png
  docs/book/common_code/architecture.md
  docs/book/common_code/architecture.png
  docs/book/common_code/architecture.svg
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#829 Deleted cloud providers for clusterctl help.
  cmd/clusterctl/cmd/alpha_phase_get_kubeconfig.go
  cmd/clusterctl/cmd/create_cluster.go
  cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  cmd/clusterctl/testdata/create-cluster-no-args.golden
Labels: approved, cncf-cla: yes, lgtm, size/XS

#830 Updated github bug and feature template.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#765 link to the gitbook published version of the docs from README
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#832 README.md: Add bare metal provider.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#837 Add KinD --wait flag to ignoredOptions
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#838 Honour the KinD --name flag
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#840 refresh cluster object while waiting for kubeconfig
  cmd/clusterctl/phases/getkubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#845 Enable setting profile for minikube bootstrap cluster.
  cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#854 update docs to point to relevant google groups
  CONTRIBUTING.md
  cmd/clusterctl/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#846 Fix doc for --bootstrap-flags usage
  cmd/clusterctl/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#857 Update to Go 1.11.6
  Dockerfile
  WORKSPACE
  config/rbac/rbac_role.yaml
  pkg/controller/machine/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#847 Added kind support for README.
  cmd/clusterctl/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#835 Added more spec for machinedeployment.
  docs/book/common_code/machinedeployment_controller.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#834 Added diagrams illustrating the controller logic
  docs/book/SUMMARY.md
  docs/book/common_code/cluster_controller.md
  docs/book/common_code/images/activity_cluster_reconciliation.drawio
  docs/book/common_code/images/activity_cluster_reconciliation.svg
  docs/book/common_code/images/activity_machine_controller_reconciliation.drawio
  docs/book/common_code/images/activity_machine_controller_reconciliation.svg
  docs/book/common_code/images/activity_machine_deletion_block.drawio
  docs/book/common_code/images/activity_machine_deletion_block.svg
  docs/book/common_code/images/activity_machinedeployment_reconciliation.drawio
  docs/book/common_code/images/activity_machinedeployment_reconciliation.svg
  docs/book/common_code/images/activity_machineset_reconciliation.drawio
  docs/book/common_code/images/activity_machineset_reconciliation.svg
  docs/book/common_code/images/activity_node_reconciliation.drawio
  docs/book/common_code/images/activity_node_reconciliation.svg
  docs/book/common_code/images/sequence_cluster_creation.drawio
  docs/book/common_code/images/sequence_cluster_creation.svg
  docs/book/common_code/images/sequence_cluster_deletion.drawio
  docs/book/common_code/images/sequence_cluster_deletion.svg
  docs/book/common_code/images/sequence_machine_creation.drawio
  docs/book/common_code/images/sequence_machine_creation.svg
  docs/book/common_code/images/sequence_machine_deletion.drawio
  docs/book/common_code/images/sequence_machine_deletion.svg
  docs/book/common_code/machine_controller.md
  docs/book/common_code/machinedeployment_controller.md
  docs/book/common_code/machineset_controller.md
  docs/book/common_code/node_controller.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#851 Add status (phase and provider id) to get output
  config/crds/cluster_v1alpha1_machine.yaml
  pkg/apis/cluster/v1alpha1/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#856 Remove deprecated openshift link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#850 Update sample provider implementation
  docs/book/provider_implementations/register_schemes.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#726 Adds Oldest and Newest delete policies and annotation-based Simple delete policy
  config/crds/cluster_v1alpha1_machine.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
  pkg/apis/cluster/v1alpha1/machine_types.go
  pkg/apis/cluster/v1alpha1/machineset_types.go
  pkg/apis/cluster/v1alpha1/machineset_types_test.go
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/controller.go
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/delete_policy_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#651 Update `Taints` field comment in the machine spec
  pkg/apis/cluster/v1alpha1/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#836 allow machinesets that have clusters to continue reconciliation
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machineset/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#861 Release 0.1.0
  Makefile
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#863 Update CRDs
  config/crds/cluster_v1alpha1_machine.yaml
  config/crds/cluster_v1alpha1_machinedeployment.yaml
  config/crds/cluster_v1alpha1_machineset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
