Repository kubernetes-sigs/cluster-api, pull requests merged in 2019-12, with the labels that each got.

#1792 clusterctl/kind: return stdout and not combined output
  cmd/clusterctl/clusterdeployer/bootstrap/kind/kind.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-longterm, size/S

#1805 📖 Add GCP provider instructions to getting started
  docs/book/src/tasks/installation.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1791 📖 Add spec doc for cluster infra provider
  docs/book/src/SUMMARY.md
  docs/book/src/images/cluster-infra-provider.plantuml
  docs/book/src/images/cluster-infra-provider.png
  docs/book/src/providers/cluster-infrastructure.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, priority/important-soon, size/L

#1788 ✨ Add Validation webhooks to cluster api manager
  Makefile
  api/v1alpha3/machine_webhook.go
  api/v1alpha3/machine_webhook_test.go
  api/v1alpha3/machinedeployment_webhook.go
  api/v1alpha3/machinedeployment_webhook_test.go
  api/v1alpha3/machineset_webhook.go
  api/v1alpha3/machineset_webhook_test.go
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/webhook/manifests.yaml
  controllers/machine_controller_phases.go
  controllers/machine_controller_test.go
  controllers/machinedeployment_controller.go
  controllers/machineset_controller.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1821 :running: Fix bin-data binary not found in CI
  .gitignore
  Makefile
  cmd/clusterctl/config/crd_manifests.go
  cmd/clusterctl/config/generate.go
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1815 adding note about envsubst application
  docs/book/src/tasks/installation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1812 :warning: Update controller-runtime and client-go
  Makefile
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/crd_manifests.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/framework/go.mod
  test/framework/go.sum
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1682 :book: New Provider documentation
  docs/book/SUMMARY.md
  docs/book/src/SUMMARY.md
  docs/book/src/providers/implementers-guide/building_running_and_testing.md
  docs/book/src/providers/implementers-guide/cluster-email.png
  docs/book/src/providers/implementers-guide/configure.md
  docs/book/src/providers/implementers-guide/controllers_and_reconciliation.md
  docs/book/src/providers/implementers-guide/create_api.md
  docs/book/src/providers/implementers-guide/generate_crds.md
  docs/book/src/providers/implementers-guide/naming.md
  docs/book/src/providers/implementers-guide/overview.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XL

#1836 🏃 integration test: better cert-manager wait
  scripts/ci-integration.sh
Labels: approved, cncf-cla: yes, kind/failing-test, kind/flake, lgtm, priority/important-soon

#1838 🐛 capd: maintain go.mod/go.sum
  Makefile
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/L

#1839 📖 Fixes in infrastructure provider implementor guide
  docs/book/src/providers/implementers-guide/building_running_and_testing.md
  docs/book/src/providers/implementers-guide/create_api.md
  docs/book/src/providers/implementers-guide/generate_crds.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/important-soon, size/XS

#1822 📖 Renaming ErrorMessage and ErrorReason to FailureMessage and FailureReason in docs
  docs/book/src/architecture/controllers/cluster.md
  docs/book/src/architecture/controllers/machine.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1826 :sparkles: Start adding KubeadmControlPlane controller
  api/v1alpha3/kubeadm_control_plane_types.go
  config/rbac/role.yaml
  controllers/kubeadm_control_plane_controller.go
  docs/proposals/20191017-kubeadm-based-control-plane.md
  main.go
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/L

#1824 ✨Add defaulting webhooks to cluster api manager
  api/v1alpha3/cluster_webhook.go
  api/v1alpha3/cluster_webhook_test.go
  api/v1alpha3/defaults.go
  api/v1alpha3/machine_webhook.go
  api/v1alpha3/machine_webhook_test.go
  api/v1alpha3/machinedeployment_webhook.go
  api/v1alpha3/machinedeployment_webhook_test.go
  config/webhook/manifests.yaml
  controllers/machinedeployment_controller.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1843 :book: Add automatic redirects for the development docs book to Netlify config
  netlify.toml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#1825 Remove lint comments and fix issues
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  cmd/clusterctl/cmd/root.go
  controllers/machinedeployment_sync.go
  go.mod
  go.sum
  test/framework/go.sum
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.sum
  test/infrastructure/docker/hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1847 Revert ":book: Add automatic redirects for the development docs book to Netlify config"
  netlify.toml
Labels: approved, cncf-cla: yes, size/S

#1844 :bug: Update validations for KubeadmControlPlane and add webhook tests
  api/v1alpha3/kubeadm_control_plane_webhook.go
  api/v1alpha3/kubeadm_control_plane_webhook_default.go
  api/v1alpha3/kubeadm_control_plane_webhook_test.go
  api/v1alpha3/kubeadm_control_plane_webhook_validation.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1845 Makefiles: Support docker run on SELinux enabled systems
  Makefile
  docs/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1851 :bug: KubeadmConfig controller should look at GroupKind when reconciling
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1853 :book: Update docs to support KIND v0.6.x
  docs/book/src/tasks/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1848 :book: Re-add netlify redirects for development version of the Cluster API book
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1854 :warning: Sync InfraCluster.Status.Ready to Cluster object
  controllers/cluster_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1817 📖 dead contributor and conduct links on cluster-api.sigs.k8s.io website
  README.md
  docs/book/src/CONTRIBUTING.md
  docs/book/src/SUMMARY.md
  docs/book/src/code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1762 :warning: Clusterctlv2 low-level config library
  cmd/clusterctl/pkg/client/config/client.go
  cmd/clusterctl/pkg/client/config/provider.go
  cmd/clusterctl/pkg/client/config/providers_client.go
  cmd/clusterctl/pkg/client/config/providers_client_test.go
  cmd/clusterctl/pkg/client/config/reader_viper.go
  cmd/clusterctl/pkg/client/config/reader_viper_test.go
  cmd/clusterctl/pkg/client/config/variables_client.go
  cmd/clusterctl/pkg/client/config/variables_client_test.go
  cmd/clusterctl/pkg/internal/test/fake_reader.go
  cmd/clusterctl/pkg/internal/test/fake_variable_client.go
  go.mod
  go.sum
  test/framework/go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1857 🏃 Reenable building and testing CAPD
  Makefile
  scripts/ci-build.sh
  scripts/ci-test.sh
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/cloudinit/kindadapter.go
  test/infrastructure/docker/cloudinit/runcmd.go
  test/infrastructure/docker/cloudinit/runcmd_test.go
  test/infrastructure/docker/cloudinit/writefiles.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/e2e/docker_test.go
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
  test/infrastructure/docker/hack/tools/tools.go
  test/infrastructure/docker/hack/verify-boilerplate.sh
  test/infrastructure/docker/hack/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1841 ⚠️ Move Bootstrap data to a secret
  api/v1alpha2/conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/machine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  bootstrap/kubeadm/api/v1alpha2/conversion.go
  bootstrap/kubeadm/api/v1alpha2/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.deepcopy.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
  go.mod
  go.sum
  test/framework/go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1785 🏃 Move cloudinit module into internal
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/cloudinit/cloudinit.go
  bootstrap/kubeadm/internal/cloudinit/cloudinit_test.go
  bootstrap/kubeadm/internal/cloudinit/commands.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_init.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_join.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_test.go
  bootstrap/kubeadm/internal/cloudinit/files.go
  bootstrap/kubeadm/internal/cloudinit/node.go
  bootstrap/kubeadm/internal/cloudinit/ntp.go
  bootstrap/kubeadm/internal/cloudinit/users.go
  bootstrap/kubeadm/internal/cloudinit/utils.go
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1867 🐛 Be consistent with dataSecretName field
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1869 ✨ Update capd types to be v1a3 compliant
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/PROJECT
  test/infrastructure/docker/api/v1alpha3/dockercluster_types.go
  test/infrastructure/docker/api/v1alpha3/dockermachine_types.go
  test/infrastructure/docker/api/v1alpha3/dockermachinetemplate_types.go
  test/infrastructure/docker/api/v1alpha3/groupversion_info.go
  test/infrastructure/docker/api/v1alpha3/zz_generated.deepcopy.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/controllers/dockercluster_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller_test.go
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/e2e/docker_test.go
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1862 Fix cloud-init jinja templates 📖
  docs/book/src/user/quick-start.md
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1873 :bug: Handle CABPK secret case where status has been lost
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1877 :bug: [0.2] Wait for all descendants when deleting a cluster
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#1842 :warning: Clusterctlv2 add interfaces for the low-level Repository library
  cmd/clusterctl/pkg/client/repository/client.go
  cmd/clusterctl/pkg/client/repository/components.go
  cmd/clusterctl/pkg/client/repository/components_client.go
  cmd/clusterctl/pkg/client/repository/template.go
  cmd/clusterctl/pkg/client/repository/templates_client.go
  cmd/clusterctl/pkg/internal/test/fake_repository.go
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1874 📖 Add bootstrap provider spec doc
  docs/book/src/SUMMARY.md
  docs/book/src/images/bootstrap-provider.plantuml
  docs/book/src/images/bootstrap-provider.png
  docs/book/src/providers/bootstrap.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, priority/important-soon, size/L

#1875 :sparkles: add flag for disabling kubeadm controllers
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1703 📖CAEP: MachinePool API (provider agnostic scale types)
  docs/proposals/20190919-machinepool-api.md
  docs/proposals/images/machinepool-api/figure1.plantuml
  docs/proposals/images/machinepool-api/figure1.png
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, priority/important-soon, size/XL

#1797 Update documentation due to `kind get kubeconfig-path` deprecation
  docs/book/src/tasks/installation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1879 :running: Mass update of test cases, docs, and other outdated references to v1alpha2
  bootstrap/kubeadm/README.md
  bootstrap/kubeadm/docs/external-etcd.md
  controllers/cluster_controller_phases_test.go
  controllers/external/testing.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/machinedeployment_controller_test.go
  controllers/machineset_controller_test.go
  docs/book/src/user/quick-start.md
  test/infrastructure/docker/api/v1alpha3/groupversion_info.go
  test/infrastructure/docker/examples/simple-cluster.yaml
  util/patch/patch_test.go
  util/util_test.go
  util/yaml/yaml_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1865 📖 Add machine infra provider spec doc
  docs/book/src/SUMMARY.md
  docs/book/src/images/machine-infra-provider.plantuml
  docs/book/src/images/machine-infra-provider.png
  docs/book/src/providers/machine-infrastructure.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, priority/important-soon, size/L

#1886 🏃Update e2e test framework
  test/framework/convenience.go
  test/framework/management/kind/mgmt.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1883 :book: Add troubleshooting page to the doc
  docs/book/src/SUMMARY.md
  docs/book/src/user/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1888 🏃 Add clusterName to example machine spec
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1889 book/troubleshooting.md: amend the entry about node-role labels
  docs/book/src/user/troubleshooting.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, priority/backlog, size/S

#1892 🐛 A series of fixes for the testing framework and CAPD
  Makefile
  test/framework/generators/capi.go
  test/framework/multi_node_control_plane.go
  test/framework/one_node_cluster.go
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/config/rbac/role.yaml
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1887 🐛 Do not make a secret if a secret already exists
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1856 :sparkles: Start implementing create workflow for KubeadmControlPlane controller
  api/v1alpha2/conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/cluster_types.go
  api/v1alpha3/cluster_webhook.go
  api/v1alpha3/cluster_webhook_test.go
  api/v1alpha3/kubeadm_control_plane_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/internal/cloudinit/cloudinit_test.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_init.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_join.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
  controllers/external/util.go
  controllers/kubeadm_control_plane_controller.go
  util/kubeconfig/kubeconfig.go
  util/secret/certificates.go
  util/secret/certificates_test.go
  util/secret/consts.go
  util/secret/secret.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1896 🐛Fix e2e framework resource apply order
  test/framework/multi_node_control_plane.go
  test/framework/one_node_cluster.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#1893 📖 document providers conventions for clusterctl
  docs/book/src/providers/clusterctl.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1907 :bug: Properly set the cluster label name on bootstrap secrets
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1900 🐛 Remove relative import from e2e framework
  test/framework/go.mod
  test/framework/go.sum
  test/infrastructure/docker/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#1906 :bug: Fix validation on machine's bootstrap dataSecretName
  api/v1alpha3/machine_webhook.go
  api/v1alpha3/machine_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1899 :book: Initial control plane spec
  docs/book/src/architecture/controllers/control-plane.md
  docs/book/src/images/control-plane-controller.plantuml
  docs/book/src/images/control-plane-controller.svg
Labels: approved, cncf-cla: yes, lgtm, size/L

#1894 ✨ Add tilt-based development tooling
  .dockerignore
  .gitignore
  Dockerfile
  Tiltfile
  docs/book/src/SUMMARY.md
  docs/book/src/architecture/developer-guide.md
  docs/book/src/developer/tilt.md
  test/infrastructure/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/L

#1904 :running: Update Go 1.13
  Dockerfile
  Makefile
  cmd/example-provider/Dockerfile
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
  go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  test/framework/go.mod
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/hack/tools/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#1911 🏃 Let GCB build release images
  Makefile
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1891 :warning: clusterctlv2 add low-level library for the provider components YAML
  cmd/clusterctl/pkg/client/repository/client.go
  cmd/clusterctl/pkg/client/repository/components.go
  cmd/clusterctl/pkg/client/repository/components_client.go
  cmd/clusterctl/pkg/client/repository/components_client_test.go
  cmd/clusterctl/pkg/client/repository/components_test.go
  cmd/clusterctl/pkg/internal/scheme/scheme.go
  cmd/clusterctl/pkg/internal/test/fake_repository.go
  cmd/clusterctl/pkg/internal/util/cmd.go
  cmd/clusterctl/pkg/internal/util/yaml.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1912 🐛 Actually import (and enable) pprof
  .golangci.yml
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1914 🐛 Fix up the CAPD dockerfile
  test/infrastructure/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1859 🏃E2E Validation test
  Makefile
  test/e2e/capi_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/validation_test.go
  test/framework/convenience.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1916 :warning: Move kubeadmcontrolplane to it's own group and subdir
  Makefile
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/cluster_controller.go
  controlplane/kubeadm/PROJECT
  controlplane/kubeadm/api/v1alpha3/doc.go
  controlplane/kubeadm/api/v1alpha3/groupversion_info.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/api/v1alpha3/suite_test.go
  controlplane/kubeadm/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1919 Tiltfile tweaks
  Tiltfile
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1923 book: Add control plane controller to sidebar
  docs/book/src/SUMMARY.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1918 ⚠️ ClusterConfigration.Networking.* fields are now optional
  bootstrap/kubeadm/types/v1beta1/types.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1684 📖 CAEP: Machine health checking a.k.a node auto repair proposal
  docs/proposals/20191030-machine-health-checking.md
  docs/proposals/images/machine-health-check/mhc.plantuml
  docs/proposals/images/machine-health-check/mhc.png
  docs/proposals/images/machine-health-check/mhc.svg
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, ok-to-test, size/L

#1927 :book: Add GCP credentials doc for tilt
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1924 :runnning: Use distroless for Tilt / includes CA certs
  Tiltfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1928 🏃 adds capd e2e ci script
  scripts/ci-capd-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1913 ✨ Improve MD patching with helper
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_controller_test.go
  controllers/machinedeployment_sync.go
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1920 controlplane: Allow nil ClusterConfiguration
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1898 ⚠️ clusterctlv2: add interfaces for the management cluster low level library
  cmd/clusterctl/pkg/client/cluster/client.go
  cmd/clusterctl/pkg/client/cluster/components.go
  cmd/clusterctl/pkg/client/cluster/inventory.go
  cmd/clusterctl/pkg/client/cluster/inventory_test.go
  cmd/clusterctl/pkg/client/cluster/objects.go
  cmd/clusterctl/pkg/client/cluster/proxy.go
  cmd/clusterctl/pkg/internal/test/fake_proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1931 🐛 Install the dependencies for capd e2es
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/ensure-kustomize.sh
  scripts/ci-capd-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1935 🐛 Skip loading images if image does not exist locally
  test/framework/README.md
  test/framework/management/kind/mgmt.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1936 🏃remove outdated files from CABPK
  bootstrap/kubeadm/docs/release.md
  bootstrap/kubeadm/third_party/forked/README.md
  bootstrap/kubeadm/third_party/forked/rerun-process-wrapper/LICENSE
  bootstrap/kubeadm/third_party/forked/rerun-process-wrapper/README.md
  bootstrap/kubeadm/third_party/forked/rerun-process-wrapper/restart.sh
  bootstrap/kubeadm/third_party/forked/rerun-process-wrapper/start.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1937 🏃 tilt: fix restarting
  Tiltfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1929 ⚠️ MachinePool API Types and Scaffolding
  PROJECT
  api/v1alpha3/conversion.go
  api/v1alpha3/machinepool_types.go
  api/v1alpha3/machinepool_webhook.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_machinepools.yaml
  config/crd/patches/webhook_in_machinepools.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/machinepool_controller.go
  errors/consts.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1940 🏃 Increase timeout for capd e2es
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1939 ✨ Add defaulting webhook for KubeadmConfig
  bootstrap/kubeadm/types/v1beta1/types.go
  bootstrap/kubeadm/types/v1beta2/types.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1933 controlplane: Update finalizer and PROJECT domains to controlplane.cluster.x-k8s.io
  controlplane/kubeadm/PROJECT
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1942 🐛 Fix machinedeployment webhooks
  api/v1alpha3/machinepool_webhook.go
  config/webhook/manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1885 ✨ CBPK Use Unstructured to access Config Owner
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/util/configowner.go
  bootstrap/util/configowner_test.go
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1956 :bug: passwd is omitempty because it's optional
  bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1947 :sparkles: Add cluster owner references to external MS/MD objects
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
  controllers/external/testing.go
  controllers/external/util.go
  controllers/machine_controller.go
  controllers/machine_controller_phases.go
  controllers/machinedeployment_controller_test.go
  controllers/machineset_controller.go
  controllers/machineset_controller_test.go
  controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1954 🏃 [0.2] Add tilt support
  .dockerignore
  .gitignore
  Makefile
  Tiltfile
  docs/book/src/SUMMARY.md
  docs/book/src/developer/tilt.md
  go.mod
  hack/verify-starlark.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1955 🏃 hack/verify-starlark: better dir handling
  hack/verify-starlark.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1814 📖 External etcd doc improvement
  bootstrap/kubeadm/docs/external-etcd.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1958 🏃 Fix validation e2e test
  test/e2e/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1915 🏃E2e delete resources
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
  test/framework/clean_up.go
  test/framework/control_plane.go
  test/framework/convenience.go
  test/framework/go.mod
  test/framework/go.sum
  test/framework/one_node_cluster.go
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/e2e/docker_test.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1961 :bug: Add cluster label when creating kubeconfig secret
  util/kubeconfig/kubeconfig.go
  util/kubeconfig/kubeconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1959 :sparkles: Refactor template cloning for future use with kubeadmcontrolplane
  controllers/external/util.go
  controllers/external/util_test.go
  controllers/machineset_controller.go
  controllers/suite_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1962 :bug: fix NPEs when the user doesn't assign labels to MD
  controllers/machinedeployment_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1957 ✨ Adds pod logs for capd e2e tests
  scripts/ci-capd-e2e.sh
  test/framework/management/kind/mgmt.go
  test/infrastructure/docker/e2e/docker_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1965 :running: Update use of deprecated helpers
  controllers/cluster_controller_phases_test.go
  controllers/cluster_controller_test.go
  controllers/external/util_test.go
  controllers/machine_controller_noderef_test.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/machine_helpers_test.go
  controllers/machinedeployment_controller_test.go
  controllers/machineset_controller_test.go
  controllers/machineset_delete_policy_test.go
  controllers/remote/cluster_test.go
  controllers/suite_test.go
  controllers/suite_util_test.go
  util/kubeconfig/kubeconfig_test.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1925 :bug: Add tests for KubeadmControlPlane create workflow
  controlplane/kubeadm/controllers/generator/kubeadmconfiggenerator.go
  controlplane/kubeadm/controllers/generator/kubeadmconfiggenerator_test.go
  controlplane/kubeadm/controllers/generator/machinegenerator.go
  controlplane/kubeadm/controllers/generator/machinegenerator_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1944 :sparkles: Refactor MS controller status patching
  controllers/machineset_controller.go
  controllers/machineset_status.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1978 ✨clusterctl: add Repository.GetVersions method
  cmd/clusterctl/pkg/client/repository/client.go
  cmd/clusterctl/pkg/internal/test/fake_repository.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1976 ✨clusterctl: small refactor of fixNamespace
  cmd/clusterctl/pkg/client/repository/components.go
  cmd/clusterctl/pkg/client/repository/components_test.go
  cmd/clusterctl/pkg/internal/util/yaml.go
Labels: approved, cncf-cla: yes, lgtm, size/L
