Repository kubernetes-sigs/cluster-api, pull requests merged in 2019-11, with the labels that each got.

#1698 ✨ Use cluster name for admin user in kubeconfig
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
  util/kubeconfig/kubeconfig.go
  util/kubeconfig/kubeconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1717 🐛 Fix verify-shellcheck to report errors
  hack/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1571 📖 CAEP: e2e test framework
  docs/proposals/20191016-e2e-test-framework.md
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, size/L

#1558 📖 CAEP: Clusterctl redesign
  docs/proposals/20191016-clusterctl-redesign.md
  docs/proposals/images/clusterctl-redesign/components.png
  docs/proposals/images/clusterctl-redesign/config.plantuml
  docs/proposals/images/clusterctl-redesign/config.png
  docs/proposals/images/clusterctl-redesign/init.plantuml
  docs/proposals/images/clusterctl-redesign/init.png
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, size/L

#1711 ✨ Apply labels to Machines if they're part of a MD or MS
  api/v1alpha3/machine_types.go
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_controller_test.go
  controllers/machineset_controller.go
  controllers/machineset_controller_test.go
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1633 ⚠️ Change remote.NewClusterClient to return a controller-runtime client.Client
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machine_controller_noderef.go
  controllers/machine_controller_noderef_test.go
  controllers/machinedeployment_controller.go
  controllers/machineset_controller.go
  controllers/machineset_status.go
  controllers/remote/cluster.go
  controllers/remote/cluster_test.go
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1709 🐛 Check existence of MachineControlPlaneLabelName label instead of value
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  controllers/cluster_controller_test.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1654 📖 Add Azure tabs to quickstart book
  docs/book/src/tasks/installation.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1733 📖 Add MacOS instructions for CAPD [port]
  docs/book/src/tasks/installation.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1734 📖 Add Azure tabs to quickstart book [port]
  docs/book/src/tasks/installation.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1688 ✨Auto-select on cluster-name label in MachineDeployment and MachineSet
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_controller_test.go
  controllers/machinedeployment_sync.go
  controllers/machineset_controller.go
  controllers/machineset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1745 add alibaba cloud provider（cluster api v1alpha2）
  docs/book/src/reference/providers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1737 ✨Add the e2e framework
  test/framework/README.md
  test/framework/clean_up.go
  test/framework/convenience.go
  test/framework/exec/command.go
  test/framework/generators/capi.go
  test/framework/generators/cert_manager.go
  test/framework/go.mod
  test/framework/go.sum
  test/framework/interfaces.go
  test/framework/management/kind/mgmt.go
  test/framework/multi_node_control_plane.go
  test/framework/one_node_cluster.go
  test/framework/types.go
  test/framework/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1752 📖 Fix components file link for docker provider
  docs/book/src/tasks/installation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1736 ✨Add metrics to machine and cluster controller
  controllers/cluster_controller.go
  controllers/cluster_controller_phases_test.go
  controllers/cluster_controller_test.go
  controllers/machine_controller.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/metrics/metrics.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1758 📖 Fix typo in the definition of "Immutability"
  docs/book/src/reference/glossary.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1759 📖 Fix components file link for docker provider
  docs/book/src/tasks/installation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1720 :warning: Set Machine phase to provisioned regardless of infrastructure readiness
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1763 📖Add documentation for metrics
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1721 ✨ Set cluster status phase to Provisioned after APIEndpoints are set
  controllers/cluster_controller_phases.go
  controllers/cluster_controller_phases_test.go
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1613 📖 CAEP: ControlPlane
  docs/proposals/20191017-kubeadm-based-control-plane.md
  docs/proposals/images/controlplane/controlplane-init-1.plantuml
  docs/proposals/images/controlplane/controlplane-init-1.png
  docs/proposals/images/controlplane/controlplane-init-2.plantuml
  docs/proposals/images/controlplane/controlplane-init-2.png
  docs/proposals/images/controlplane/controlplane-init-3.plantuml
  docs/proposals/images/controlplane/controlplane-init-3.png
  docs/proposals/images/controlplane/controlplane-init-4.plantuml
  docs/proposals/images/controlplane/controlplane-init-4.png
  docs/proposals/images/controlplane/controlplane-init-6.plantuml
  docs/proposals/images/controlplane/controlplane-init-6.png
  docs/proposals/images/controlplane/controlplane-init-7.plantuml
  docs/proposals/images/controlplane/controlplane-init-7.png
  docs/proposals/images/machine-states-preboot/README.md
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, size/XL

#1764 :running: Update Kubeadm Control Plane CAEP - use label for upgrade selection
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1766 📖 Add Amy to KubeadmControlPlane CAEP
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, priority/important-soon, size/XS

#1777 :running: Update controller-tools version
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1778 🐛 Use go1.12 instead of go1.13 for the e2e framework
  test/framework/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1244 📖 Doc for updating v1a1 provider to v1a2
  docs/book/src/providers/v1alpha1-to-v1alpha2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#1771 🏃 add e2e framework to CI build
  Makefile
  scripts/ci-build.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1776 ⚠️ Rename ErrorMessage and ErrorReason to FailureMessage and FailureReason
  api/v1alpha2/conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/cluster_types.go
  api/v1alpha3/machine_types.go
  api/v1alpha3/machineset_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  cmd/clusterctl/validation/validate_cluster_api_objects.go
  cmd/clusterctl/validation/validate_cluster_api_objects_test.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
  controllers/cluster_controller_phases_test.go
  controllers/cluster_controller_test.go
  controllers/external/util.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controllers/machinedeployment_sync.go
  controllers/machinedeployment_sync_test.go
  controllers/machineset_delete_policy.go
  controllers/machineset_delete_policy_test.go
  controllers/metrics/metrics.go
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1786 🏃Update controller-tools version
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/api/v1alpha2/zz_generated.deepcopy.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1765 :sparkles: Add KubeadmControlPlane types / validation webhooks
  Makefile
  api/v1alpha3/kubeadm_control_plane_types.go
  api/v1alpha3/kubeadm_control_plane_webhook_default.go
  api/v1alpha3/kubeadm_control_plane_webhook_validation.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  errors/consts.go
  errors/kubeadmcontrolplane.go
  main.go
  scripts/ci-integration.sh
  test/framework/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1787 📖clarification of changed requirement in changelog v1alpha2 to v1alpa3
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/important-soon, size/XS

#1798 *: Consitently use DeletionTimestamp.IsZero
  cmd/clusterctl/phases/pivot.go
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_sync.go
  controllers/machineset_controller.go
  controllers/machineset_delete_policy.go
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1789 ⚠️ Move Status.APIEndpoints to Spec.ControlPlaneEndpoint
  api/v1alpha2/conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/cluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  controllers/cluster_controller_phases.go
  controllers/cluster_controller_phases_test.go
  docs/book/src/architecture/controllers/cluster.md
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
  util/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1806 🏃 kustomize: include KubeadmControlPlane
  config/crd/kustomization.yaml
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, priority/important-soon, size/XS

#1807 🐛 Fix webhooks
  api/v1alpha3/kubeadm_control_plane_webhook_default.go
  api/v1alpha3/kubeadm_control_plane_webhook_validation.go
  config/webhook/manifests.yaml
  config/webhook/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1809 🐛 Fix cert-manager annotation for mutating webhooks
  config/default/webhookcainjection_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
