Repository kubernetes-sigs/cluster-api, pull requests merged in 2020-08, with the labels that each got.

#3436 📖 Add ux note for using embedded metadata in cluserctl
  docs/book/src/clusterctl/provider-contract.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3389 📖 Update community section of readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3442 :seedling: Remove json-patch library replace
  go.mod
  go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#3443 🌱 Remove RequeueAfterError from CABPK reconcile discovery
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3452 🌱 Fix broken link
  docs/book/src/clusterctl/commands/generate-yaml.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3433 📖 Remove azure.json variable from quick start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3444 🌱 MHC should not remediate paused machines
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3456 🌱Remove unnecessary rbac rules from controlplane
  controlplane/kubeadm/config/rbac/role.yaml
  controlplane/kubeadm/controllers/controller.go
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/M

#3132 📖 CAEP: machine deletion phase hooks
  docs/proposals/20200602-machine-deletion-phase-hooks.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3313 ✨ Upgrade cert-manager
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/config/assets/cert-manager-test-resources.yaml
  cmd/clusterctl/config/assets/cert-manager.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3463 🐛 Fix CRS move test flakes
  cmd/clusterctl/internal/test/fake_objects.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3349 📖 Define testing guidelines and standards
  CONTRIBUTING.md
  REVIEWING.md
  docs/book/src/REVIEWING.md
  docs/book/src/SUMMARY.md
  docs/book/src/developer/testing.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3446 🐛 Include watching namespace for custom provider upgrades
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/client/config/provider.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/client/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3448 📖 Document how to upgrade a multi-tenant cluster
  docs/book/src/clusterctl/commands/upgrade.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3460 ✨ Add `get kubeconfig` clusterctl sub-command
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/workload_cluster.go
  cmd/clusterctl/client/cluster/workload_cluster_test.go
  cmd/clusterctl/client/get_kubeconfig.go
  cmd/clusterctl/client/get_kubeconfig_test.go
  cmd/clusterctl/cmd/get.go
  cmd/clusterctl/cmd/get_kubeconfig.go
  cmd/clusterctl/internal/test/fake_proxy.go
  docs/book/src/clusterctl/developers.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3468 🌱 [e2e] add debug output for deployment failures
  test/framework/alltypes_helpers.go
  test/framework/deployment_helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3337 :sparkles: support ability to move custom objects in clusterctl
  cmd/clusterctl/api/v1alpha3/labels.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/internal/test/fake_objects.go
  cmd/clusterctl/internal/test/fake_proxy.go
  cmd/clusterctl/internal/test/providers/external/generic_types.go
  cmd/clusterctl/internal/test/providers/external/groupversion_info.go
  cmd/clusterctl/internal/test/providers/external/zz_generated.deepcopy.go
  docs/book/src/clusterctl/provider-contract.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3470 Correct Type and Provider column information
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3454 🌱 Clusterctl init ignore pre releases
  cmd/clusterctl/client/cluster/upgrader_info.go
  cmd/clusterctl/client/cluster/upgrader_test.go
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
  cmd/clusterctl/client/repository/repository_local.go
  cmd/clusterctl/client/repository/repository_local_test.go
  cmd/clusterctl/internal/test/fake_github.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/commands/upgrade.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3478 🐛 fix cluster create not paused when paused log entry
  util/predicates/cluster_predicates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3472 🐛 Fix ClusterToKubeadmConfigs to include MachinePools
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3475 🐛 Default MachinePool replicas and MinReadySeconds
  exp/api/v1alpha3/machinepool_webhook.go
  exp/api/v1alpha3/machinepool_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3464 ⚠️ Remove old metrics from v1a3
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/machine_controller.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/metrics/metrics.go
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#3490 :book: Update Packet quickstart to better work with Calico CNI
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3495 🌱 Fix MHC conditions const
  api/v1alpha3/condition_consts.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_targets.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3462 🌱 Add hack to upgrade cert-manager in Tiltfile
  Tiltfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#3481 📖 Control Plane provider doc lists management of kubeconfig secret as a requirement
  docs/book/src/developer/architecture/controllers/control-plane.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3476 ✨ Set MachinePool phase to scaling when infra is scaling
  exp/api/v1alpha3/machinepool_types.go
  exp/controllers/machinepool_controller_noderef.go
  exp/controllers/machinepool_controller_phases.go
  exp/controllers/machinepool_controller_phases_test.go
  exp/controllers/machinepool_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3449 📖 Document clusterctl version support
  docs/book/src/reference/versions.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3489 :seedling: Add Cluster API icons to repo
  logos/icons/CAPI icons.ai
  logos/icons/README.md
  logos/icons/cluster.png
  logos/icons/cluster.svg
  logos/icons/machine-deployment.png
  logos/icons/machine-deployment.svg
  logos/icons/machine-set.png
  logos/icons/machine-set.svg
  logos/icons/machine.png
  logos/icons/machine.svg
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3445 🌱 Remove RequeueAfterError from cluster controller
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
  controllers/cluster_controller_phases_test.go
  controllers/cluster_controller_test.go
  controllers/external/types.go
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3473 🐛 avoid in-place capbk mutation, duplicate files
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3499 🐛 fix github repository testing
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3477 🌱 Remove RequeueAfterError from machine pool controller
  exp/controllers/machinepool_controller.go
  exp/controllers/machinepool_controller_noderef.go
  exp/controllers/machinepool_controller_phases.go
  exp/controllers/machinepool_controller_phases_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3503 🌱 add sidero to infrastructure providers
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/reference/providers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3501 🐛 Fixes issue with Windows, paths can't be escaped
  cmd/clusterctl/client/repository/repository_local.go
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, ok-to-test, priority/important-longterm, size/XS

#3364 🌱 clusterctl upgrade cert manager before upgrading providers
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/client/upgrade.go
  docs/book/src/clusterctl/commands/upgrade.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3500 🌱 Update CAPD examples to use MachineDeployment
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3510 📖 document clusterctl get kubeconfig
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3511 🌱 Start using cert-manager v0.16.1
  Tiltfile
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/config/assets/cert-manager.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3507 🐛 Retry getting list resources via discovery API
  cmd/clusterctl/client/cluster/proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3502 :bug: [clusterctl] accept prereleases when no releases published
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
  cmd/clusterctl/client/repository/repository_local.go
  cmd/clusterctl/client/repository/repository_local_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3455 🐛Remove ClusterResourceSet from bindings on deletion
  exp/addons/api/v1alpha3/clusterresourceset_types.go
  exp/addons/api/v1alpha3/clusterresourcesetbinding_types.go
  exp/addons/controllers/clusterresourceset_controller.go
  exp/addons/controllers/clusterresourceset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3467 📖 Update ClusterResourceSet CAEP
  docs/proposals/20200220-cluster-resource-set.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3190 📖 External Remediation Proposal
  docs/proposals/20191030-machine-health-checking.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#3521 🌱, Align print columns between machinedeployment and kubeadmcontrolplanes
  api/v1alpha3/machinedeployment_types.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3522 📖 Update concepts docs around v1alpha3
  docs/book/src/images/management-cluster.svg
  docs/book/src/user/concepts.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3298 🐛 Make KCP supporting external etcd
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/control_plane.go
  util/secret/certificates.go
  util/secret/certificates_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3508 🐛 Performs KCP version check on control plane update
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3350 🌱 Add get workload cluster test
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/suite_test.go
  test/helpers/envtest.go
  util/certs/certs.go
  util/certs/certs_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3531 :seedling: mhc: Ensure log output when returning errors to controller runtime
  controllers/machinehealthcheck_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3209 Enable webhooks in envtest
  Makefile
  api/v1alpha3/machinehealthcheck_webhook.go
  controllers/cluster_controller_test.go
  controllers/machinedeployment_controller_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/suite_test.go
  exp/addons/controllers/clusterresourceset_controller_test.go
  go.mod
  go.sum
  test/helpers/envtest.go
  test/infrastructure/docker/go.sum
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3532 🌱 Fix link to docker-provider
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3273 ✨ Implement deletion lifecycle hooks
  api/v1alpha3/machine_types.go
  controllers/machine_controller.go
  docs/proposals/20200602-machine-deletion-phase-hooks.md
  util/annotations/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3484 ✨ Clusterctl version check
  cmd/clusterctl/cmd/root.go
  cmd/clusterctl/cmd/version_checker.go
  cmd/clusterctl/cmd/version_checker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3408 🌱 Add test reconcile etcd members
  controlplane/kubeadm/internal/etcd/fake/client.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_etcd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3527 🌱 Add conditions for deletion workflows
  api/v1alpha3/condition_consts.go
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machine_controller_test.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/status.go
  test/infrastructure/docker/controllers/dockercluster_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  util/conditions/getter.go
  util/conditions/getter_test.go
  util/conditions/merge_strategies.go
  util/conditions/merge_strategies_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3543 🐛 Update coredns-migration library to v1.0.10
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#3544 :seedling: Expose CoreDNS errors to users when validation fails
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3541 🐛 add APIEndpoint IsValid() when both host and port are non-zero value
  api/v1alpha3/cluster_types.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  controllers/cluster_controller_phases.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3336 🐛 Ensure that etcd health check errors are logged in KCP
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/scale_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3545 🌱Update e2e Kubernetes versions
  test/e2e/config/docker-ci.yaml
  test/e2e/config/docker-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3546 🌱 Update to Controller Runtime v0.5.10
  go.mod
  go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#3550 📖 point users to owners_aliases file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3554 🌱 Bump cert-manager version on CI
  scripts/ci-e2e.sh
  test/e2e/config/docker-ci.yaml
  test/e2e/config/docker-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3529 📖 Add experimental features section
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/experimental-features/cluster-resource-set.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  docs/book/src/tasks/experimental-features/machine-pools.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3563 🌱[e2e] Revert e2e test Kubernetes version to 1.18.2
  test/e2e/config/docker-ci.yaml
  test/e2e/config/docker-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
