Repository kubernetes-sigs/cluster-api, pull requests merged in 2020-06, with the labels that each got.

#3094 📖 Update references to proper CAPBK location
  docs/book/src/developer/architecture/controllers/bootstrap.md
  docs/book/src/reference/providers.md
  test/infrastructure/docker/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3121 Add packet to list of default providers ✨
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/cmd/config_repositories_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3066 ✨ CABPK: Support disk_setup and mounts in cloud-init
  bootstrap/kubeadm/README.md
  bootstrap/kubeadm/api/v1alpha2/conversion.go
  bootstrap/kubeadm/api/v1alpha2/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.deepcopy.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/cloudinit/cloudinit.go
  bootstrap/kubeadm/internal/cloudinit/cloudinit_test.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_init.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_join.go
  bootstrap/kubeadm/internal/cloudinit/disk_setup.go
  bootstrap/kubeadm/internal/cloudinit/fs_setup.go
  bootstrap/kubeadm/internal/cloudinit/mounts.go
  bootstrap/kubeadm/internal/cloudinit/node.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3124 🏃‍♂️ Switch clusterctl logging to stderr
  cmd/clusterctl/client/repository/components_client.go
  cmd/clusterctl/log/logger.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3131 🌱 Opt for a more inclusive "other" category for our emoji
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  VERSIONING.md
  hack/tools/release/notes.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3130 🌱 Remove 1s full cache resync from envtest, use delegating client every…
  exp/controllers/suite_test.go
  main.go
  test/helpers/envtest.go
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3114 🐛 fix CAPBK conversion bug
  bootstrap/kubeadm/api/v1alpha2/conversion.go
  bootstrap/kubeadm/api/v1alpha2/conversion_test.go
  util/conversion/conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3120 🌱 Update golint-ci, fix warnings
  .golangci.yml
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/client/cluster/proxy_test.go
  cmd/clusterctl/client/cluster/template_test.go
  cmd/clusterctl/client/config/reader_viper_test.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_local_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  cmd/clusterctl/cmd/upgrade_plan.go
  cmd/clusterctl/internal/util/yaml.go
  controllers/mdutil/util.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/internal/machine_collection.go
  hack/tools/go.mod
  hack/tools/go.sum
  test/framework/alltypes_helpers.go
  test/framework/clusterctl/clusterctl_config.go
  test/framework/clusterctl/repository.go
  test/framework/deprecated.go
  test/framework/exec/command.go
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3135 🐛 Updated "Upgrade" test so that it does not report false-negatives while waiting for conditions
  test/framework/pod_helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3133 🌱 Move clusterctl internal yaml functions under `util/yaml`
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/inventory.go
  cmd/clusterctl/client/init_test.go
  cmd/clusterctl/client/repository/components.go
  cmd/clusterctl/client/repository/components_client_test.go
  cmd/clusterctl/client/repository/template.go
  cmd/clusterctl/internal/util/yaml.go
  cmd/clusterctl/internal/util/yaml_test.go
  util/yaml/yaml.go
  util/yaml/yaml_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3123 📖 added packet where needed across the cluster-api
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/user/quick-start.md
  docs/book/theme/css/general.css
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3122 🌱 Add conditions to the DockerMachine object
  test/infrastructure/docker/api/v1alpha3/condition_consts.go
  test/infrastructure/docker/api/v1alpha3/dockermachine_types.go
  test/infrastructure/docker/api/v1alpha3/zz_generated.deepcopy.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3118 🌱 Refactor patch helper to handle observedGeneration and Conditions
  controllers/external/testing.go
  go.mod
  go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  util/conditions/patch.go
  util/conditions/setter.go
  util/patch/options.go
  util/patch/patch.go
  util/patch/patch_test.go
  util/patch/suite_test.go
  util/patch/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2685 ✨Add kubeadm control plane manager role aggregation label
  controlplane/kubeadm/config/default/kustomization.yaml
  controlplane/kubeadm/config/default/manager_role_aggregation_patch.yaml
  controlplane/kubeadm/config/rbac/aggregated_role.yaml
  controlplane/kubeadm/config/rbac/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3148 🌱OwnerMachine lookup fix while upgrade
  util/util.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3142 🌱 Add conditions to the DockerCluster object
  test/infrastructure/docker/api/v1alpha3/condition_consts.go
  test/infrastructure/docker/api/v1alpha3/dockercluster_types.go
  test/infrastructure/docker/api/v1alpha3/zz_generated.deepcopy.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/controllers/dockercluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3129 🌱 Integrate shared remote cluster watching into MHC
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_cache_reconciler_test.go
  controllers/suite_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3155 📖 Update quick start about OpenStack
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3125 🌱 Add conditions to the KubeadmConfig object
  bootstrap/kubeadm/api/v1alpha2/conversion.go
  bootstrap/kubeadm/api/v1alpha2/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha3/condition_consts.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.deepcopy.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  test/helpers/client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3156 🌱 MHC mapper tests shouldn't create new test environments
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_targets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3147 🐛 Make MachineSpec Version validation consistent with KCP
  api/v1alpha3/machine_webhook.go
  api/v1alpha3/machine_webhook_test.go
  controllers/machinedeployment_controller_test.go
  controllers/machineset_controller_test.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types_test.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  test/e2e/common.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3162 🌱 Remove pr-integation presubmit files
  Makefile
  scripts/ci-integration.sh
  test/integration/cluster/cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3136 🌱 Add conditions to the Machine object
  api/v1alpha2/conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/condition_consts.go
  api/v1alpha3/machine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  controllers/cluster_controller_phases_test.go
  controllers/machine_controller.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  exp/controllers/suite_test.go
  test/helpers/envtest.go
  util/conditions/getter.go
  util/conditions/getter_test.go
  util/conditions/merge_test.go
  util/conditions/setter.go
  util/conditions/setter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3166 bump golang version to 1.13.12
  Dockerfile
  Makefile
  Tiltfile
  cmd/example-provider/Dockerfile
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3167 📖 Fix typo for "timeout"
  docs/book/src/tasks/healthcheck.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3165 ✨ Enable kubectl scale on MachinePool
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  exp/api/v1alpha3/machinepool_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3159 🌱 Refactor testenv and remove unused ones
  bootstrap/kubeadm/api/v1alpha2/kubeadmbootstrapconfig_types_test.go
  bootstrap/kubeadm/api/v1alpha2/suite_test.go
  bootstrap/kubeadm/api/v1alpha3/suite_test.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_reconciler_test.go
  bootstrap/kubeadm/controllers/suite_test.go
  bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controllers/remote/cluster_cache_reconciler_test.go
  controllers/remote/cluster_cache_tracker_test.go
  controllers/remote/suite_test.go
  controllers/suite_test.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types_test.go
  controlplane/kubeadm/api/v1alpha3/suite_test.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/suite_test.go
  exp/controllers/machinepool_controller_phases_test.go
  exp/controllers/suite_test.go
  go.mod
  scripts/ci-test.sh
  test/helpers/envtest.go
  test/infrastructure/docker/controllers/dockermachine_controller_test.go
  util/patch/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3169 🌱 Improve patch helper condition logic
  util/patch/patch.go
  util/patch/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3152 🌱 Improve conditions summary
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  controllers/machine_controller.go
  test/infrastructure/docker/controllers/dockercluster_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  util/conditions/getter.go
  util/conditions/getter_test.go
  util/conditions/merge_strategies.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3171 🌱 fix test/helpers.NewFakeClientWithScheme
  test/helpers/client.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3140 ✨ KCP regenerates kubeconfigs before client certs expire
  controlplane/kubeadm/controllers/helpers.go
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/tasks/kubeadm-control-plane.md
  util/certs/consts.go
  util/kubeconfig/kubeconfig.go
  util/kubeconfig/kubeconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3183 🐛 fix push images for CAPD
  Tiltfile
  docs/book/src/clusterctl/developers.md
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/config/manager/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3172 🐛 Fix support for dual-stack network ranges
  api/v1alpha3/cluster_types.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/v1beta1/types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3179 🐛 Apply conditions patch should preserve LastTransitionTime
  util/conditions/patch.go
  util/conditions/patch_test.go
  util/conditions/setter.go
  util/conditions/setter_test.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3188 🌱 Remove conditions counts
  api/v1alpha3/condition_consts.go
  test/infrastructure/docker/api/v1alpha3/condition_consts.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3154 ⚠️ Use cache tracker to get a client for remote clusters
  controllers/machine_controller.go
  controllers/machine_controller_noderef.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_targets.go
  controllers/machinehealthcheck_targets_test.go
  controllers/machineset_controller.go
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controllers/remote/cluster_cache_reconciler_test.go
  controllers/remote/cluster_cache_tracker_test.go
  controllers/suite_test.go
  main.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3180 📖 Add instructions for kind v0.8.x
  docs/book/src/clusterctl/developers.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/M

#3199 :bug: add finalizer to kcp in first reconcile to avoid race condition with delete
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  go.mod
  go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3157 ✨ Add MachinePool support for FailureDomains
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  docs/proposals/20190919-machinepool-api.md
  exp/api/v1alpha3/machinepool_types.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3208 🌱 Remove error and warning summary from conditions
  util/conditions/merge_strategies.go
  util/conditions/merge_strategies_test.go
  util/conditions/merge_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3211 📖 Fix typos for CABPK
  docs/book/src/developer/architecture/controllers/bootstrap.md
  docs/book/src/tasks/certs/using-custom-certificates.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#3206 🐛 Set sideEffects:None for cert-manager MutatingWebhookConfiguration
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/config/assets/cert-manager.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3210 🌱 Use docker build kit to reuse go cache
  Dockerfile
  Makefile
  cmd/example-provider/Dockerfile
  docs/Dockerfile
  hack/boilerplate/boilerplate.Dockerfile.txt
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3139 🌱 Add conditions to the KubeadmControlPlane object
  controlplane/kubeadm/api/v1alpha3/condition_consts.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/controllers/status.go
  controlplane/kubeadm/controllers/status_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/control_plane_test.go
  controlplane/kubeadm/internal/machine_collection.go
  controlplane/kubeadm/internal/machinefilters/machine_filters.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3213 🐛 Envtest should initialize controller runtime logger
  controllers/suite_test.go
  test/helpers/envtest.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3215 feat(bootstrap): initialize variable out of for range
  bootstrap/util/configowner.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3218 🌱 Document docker version requirements
  Dockerfile
  docs/book/src/clusterctl/developers.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/tilt.md
  test/infrastructure/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3191 📖 Update CONTRIBUTING.md with high-level review guidelines
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3201 🐛 Fix for watch info matching in cluster cache tracker
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_cache_tracker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3217 🌱 Add tests for ensureNamespace
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3194 📖 Add reviewing tips
  CONTRIBUTING.md
  REVIEWING.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3192 📖 Add more structure and details to roadmap document
  docs/book/src/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3207 🌱 Add conditions to cluster object
  api/v1alpha3/condition_consts.go
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3219 🌱 Rewrite MHC tests to be consistent with rest of codebase
  controllers/machinehealthcheck_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3220 🌱 update gcloud build image
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3221 🌱 fix-docker-experimental-annotation
  Dockerfile
  cmd/example-provider/Dockerfile
  docs/Dockerfile
  hack/boilerplate/boilerplate.Dockerfile.txt
  test/infrastructure/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3223 :seedling: Update gcloud image for cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3224 🌱 Adds a test for ensureNamespaces (plural)
  cmd/clusterctl/client/cluster/mover_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3228 :seedling: Update dependencies: controller-runtime v0.5.7 and json-patch
  go.mod
  go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3229 🌱 Increase test timeout
  Makefile
  controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3175 🌱 Add support for PKCS8 private keys in CA certs
  controlplane/kubeadm/internal/workload_cluster.go
  util/certs/certs.go
  util/certs/certs_test.go
  util/certs/types.go
  util/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3212 📖 Add AZURE_ENVIRONMENT env var to azure instructions in quick start guide
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3222 🐛 Prioritize deleting machine without NodeRef
  controllers/machineset_delete_policy.go
  controllers/machineset_delete_policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3231 :seedling: Use patch in tests instead of update
  controllers/machinehealthcheck_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3181 🌱Add infraref annotation to KCP machines
  api/v1alpha3/common_types.go
  controllers/external/util.go
  controllers/external/util_test.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/helpers_test.go
  controlplane/kubeadm/controllers/scale_test.go
  test/helpers/envtest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3232 🐛 Scope MHC machines to the cluster matching their clusterName
  api/v1alpha3/machinehealthcheck_webhook.go
  api/v1alpha3/machinehealthcheck_webhook_test.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_targets.go
  controllers/machinehealthcheck_targets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3116 📖 Update quickstart for clusterawsadm v2
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3235 🌱 Image builds should prepull experimental docker buildkit deps
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3237 :seedling: Make release-staging should pre-pull required images
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3238 :seedling: Use full path for golang images
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3236 :bug: Properly adopt cluster secrets on upgrade
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  docs/book/src/tasks/kubeadm-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3239 :seedling: Remove build --pull argument
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3241 :seedling: Pull images when building capd as well
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3245 🌱 Fix typo: kuberentes->kubernetes
  REVIEWING.md
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/v1beta1/types.go
  controllers/external/util.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3240 🐛 Test suites should create proper machines
  controllers/external/testing.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_controller_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machineset_controller_test.go
  controllers/suite_test.go
  controllers/suite_util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3186 🌱 Adds targets to MHC
  api/v1alpha3/machinehealthcheck_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3253 🐛 Fixes MHC test failures
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_status_matcher.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3115 ✨Add templating interface to clusterctl
  cmd/clusterctl/client/alias.go
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/client_test.go
  cmd/clusterctl/client/cluster/template.go
  cmd/clusterctl/client/cluster/template_test.go
  cmd/clusterctl/client/common.go
  cmd/clusterctl/client/config.go
  cmd/clusterctl/client/config/client.go
  cmd/clusterctl/client/config/variables_client.go
  cmd/clusterctl/client/config/variables_client_test.go
  cmd/clusterctl/client/delete.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/client/move.go
  cmd/clusterctl/client/repository/client.go
  cmd/clusterctl/client/repository/client_test.go
  cmd/clusterctl/client/repository/components.go
  cmd/clusterctl/client/repository/components_client.go
  cmd/clusterctl/client/repository/components_client_test.go
  cmd/clusterctl/client/repository/components_test.go
  cmd/clusterctl/client/repository/template.go
  cmd/clusterctl/client/repository/template_client.go
  cmd/clusterctl/client/repository/template_client_test.go
  cmd/clusterctl/client/repository/template_test.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/client/yamlprocessor/processor.go
  cmd/clusterctl/client/yamlprocessor/simple_processor.go
  cmd/clusterctl/client/yamlprocessor/simple_processor_test.go
  cmd/clusterctl/internal/test/fake_processor.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XXL

#3214 🐛 change controllers to add finalizers at the first reconciliation
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machine_controller_test.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  exp/controllers/machinepool_controller.go
  exp/controllers/machinepool_controller_test.go
  test/infrastructure/docker/controllers/dockercluster_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#3246 📖 Add known bug warning for clusterctl delete
  cmd/clusterctl/cmd/delete.go
  docs/book/src/clusterctl/commands/delete.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3250 🌱 CAPD Machines now reports `status.addresses`
  test/infrastructure/docker/api/v1alpha3/dockermachine_types.go
  test/infrastructure/docker/api/v1alpha3/zz_generated.deepcopy.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3258 :seedling: Allow Patch to specify options as well
  util/patch/patch.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3263 🌱 Packet provider is now part of kubernetes-sigs
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/reference/providers.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3262 test framework: Enable metrics collection
  test/e2e/config/docker-ci.yaml
  test/e2e/config/docker-dev.yaml
  test/framework/clusterctl/clusterctl_helpers.go
  test/framework/deployment_helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3233 🌱 Adds tests for InitImages
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/init_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3249 🌱 Add an error message if missing substitutions for kustomization
  Tiltfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3261 🌱 Allow incremental condition patch
  util/conditions/patch.go
  util/conditions/patch_test.go
  util/patch/options.go
  util/patch/patch.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3164 🐛 Removes MachineSet Controller owner for existing Machines
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controllers/suite_test.go
  util/util.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3226 🌱 Controllers should now populate `status.observedGeneration`
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/machine_controller.go
  controllers/machine_controller_test.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controlplane/kubeadm/controllers/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3266 🌱 MachinePool now has `status.observedGeneration`
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  exp/api/v1alpha3/machinepool_types.go
  exp/controllers/machinepool_controller.go
  exp/controllers/machinepool_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3268 🌱 Clusterctl supports ClusterRole/RoleBindings for webhooks
  cmd/clusterctl/client/repository/components.go
  cmd/clusterctl/client/repository/components_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
