Repository kubernetes-sigs/cluster-api, pull requests merged in 2020-10, with the labels that each got.

#3688 ✨ Changes priority of infrastructure failures in machine summary condition
  controllers/machine_controller.go
  controllers/machine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3685 🌱 feat: add EKS controlplane provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/cmd/config_repositories_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3740 Fix conditions counter in case of mismatching order of conditions between WithConditions and WithStepCounterIfOnly
  util/conditions/getter.go
  util/conditions/getter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3737 📖 Fix create-local-repository.py documentation
  cmd/clusterctl/hack/create-local-repository.py
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3691 ✨ go: update to use go 1.15
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/hack/tools/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#3745 :seedling: Update kubectl version to 1.19
  Tiltfile
  docs/book/src/developer/tilt.md
  hack/ensure-kubectl.sh
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
Labels: approved, cncf-cla: yes, lgtm, size/S

#3741 ⚠️ Remove deprecated functions from the e2e test framework
  test/framework/cluster_helpers.go
  test/framework/config.go
  test/framework/config_constants.go
  test/framework/config_test.go
  test/framework/convenience.go
  test/framework/deprecated.go
  test/framework/management/kind/mgmt.go
  test/framework/options/generic.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3744 🌱Retrieve kustomize release binary instead of building it
  Makefile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  hack/ensure-kustomize.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  scripts/ci-e2e.sh
  test/e2e/Makefile
  test/infrastructure/docker/config/crd/bases/exp.infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3750 🌱 e2e framework allows choosing the node image for the bootstrap cluster
  test/framework/bootstrap/kind_provider.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3746 ⚠️ Update management cluster minimum Kubernetes version to v1.19.1
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/cmd/config_cluster.go
  docs/book/src/tasks/kubeadm-bootstrap.md
  docs/book/src/user/quick-start.md
  go.mod
  go.sum
  scripts/ci-e2e.sh
  scripts/fetch_ext_bins.sh
  test/e2e/config/docker.yaml
  test/framework/config.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#3753 :seedling: Update controller-tools to main tip, use webhooks/v1
  api/v1alpha3/cluster_webhook.go
  api/v1alpha3/machine_webhook.go
  api/v1alpha3/machinedeployment_webhook.go
  api/v1alpha3/machinehealthcheck_webhook.go
  api/v1alpha3/machineset_webhook.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_webhook.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/config/webhook/manifests.yaml
  bootstrap/kubeadm/config/webhook/webhookcainjection_patch.yaml
  bootstrap/kubeadm/types/v1beta1/bootstraptokenstring.go
  bootstrap/kubeadm/types/v1beta2/bootstraptokenstring.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  config/webhook/manifests.yaml
  config/webhook/webhookcainjection_patch.yaml
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/webhook/manifests.yaml
  controlplane/kubeadm/config/webhook/webhookcainjection_patch.yaml
  exp/addons/api/v1alpha3/clusterresourceset_webhook.go
  exp/api/v1alpha3/machinepool_webhook.go
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/api/v1alpha3/dockermachinetemplate_webhook.go
  test/infrastructure/docker/config/crd/bases/exp.infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/config/webhook/manifests.yaml
  test/infrastructure/docker/config/webhook/webhookcainjection_patch.yaml
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#3755 :seedling: Use util.ManagerDelegatingClientFunc in all managers
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3756 :warning: Add required coordination/leases RBAC for v0.7 leader election
  bootstrap/kubeadm/config/rbac/leader_election_role.yaml
  config/ci/rbac/leader_election_role.yaml
  config/rbac/leader_election_role.yaml
  controlplane/kubeadm/config/rbac/leader_election_role.yaml
  test/infrastructure/docker/config/rbac/leader_election_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3758 :seedling: CAPD webhooks should use 9443 as port
  test/infrastructure/docker/config/webhook/manager_webhook_patch.yaml
  test/infrastructure/docker/config/webhook/service.yaml
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3757 :bug: util/patch tests shouldn't use a non-existent namespace
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3759 :bug: KubeadmControlPlane should use a live client when listing machines
  controlplane/kubeadm/controllers/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3723 🌱Remove RequeueAfterError from machine controller
  controllers/machine_controller.go
  controllers/machine_controller_noderef.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#3736 :book: move autoscaler scale from zero to 0.4.0 roadmap
  docs/book/src/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3724 📖 Add release guidelines and policies to contributing guide
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3592 Remove CAPD's machine deletion
  test/infrastructure/docker/controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3772 :seedling: [0.3] Backport 3740, 3759, and 3723
  controllers/machine_controller.go
  controllers/machine_controller_noderef.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controlplane/kubeadm/controllers/controller.go
  util/conditions/getter.go
  util/conditions/getter_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3774 🐛 CABPK should not log the token upon renewal
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3777 📖 Fix a typo in quick-start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3768 🌱 Add github action to check PR contents
  .github/workflows/verify.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3705 ✨ Adds machine health check conditions to Machine Ready condition
  controllers/machine_controller.go
  controllers/machine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3730 :seedling: kubernetesversions: Add option to inject CI artifacts into a KubeadmConfig for a MachinePool
  test/framework/kubernetesversions/template.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3788 🐛 Update `clusterctl init --help` command
  cmd/clusterctl/cmd/init.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3796 ✨ Adds machine health check conditions to Machine Ready condition
  controllers/machine_controller.go
  controllers/machine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3776 ⚠️capk generates kubadm config files under /run/kubeadm/ instead of /tmp
  bootstrap/kubeadm/internal/cloudinit/cloudinit.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_init.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_join.go
  bootstrap/kubeadm/internal/cloudinit/kubeadm-bootstrap-script.sh
  bootstrap/kubeadm/internal/cloudinit/node.go
  bootstrap/kubeadm/internal/cloudinit/zz_generated.bindata.go
  test/infrastructure/docker/cloudinit/kindadapter_test.go
  test/infrastructure/docker/cloudinit/runcmd_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3790 🌱 Rework skipped test
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  cmd/clusterctl/client/cluster/inventory_managementgroup_test.go
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/internal/test/fake_objects.go
  controllers/cluster_controller_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3809 :warning: infrastructure provider DigitaloOcean was renamed to digitalocean (previously do)
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/cmd/config_repositories_test.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XS

#3775 Use tilt cert_manager extension
  Tiltfile
  tilt_modules/cert_manager/README.md
  tilt_modules/cert_manager/Tiltfile
  tilt_modules/extensions.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3719 Reword docker readme
  test/infrastructure/docker/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3748 🌱Add Node watch to Machine controller
  api/v1alpha3/common_types.go
  controllers/machine_controller.go
  controllers/machine_controller_test.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3816 :warning: Infrastructure provider DigitalOcean was renamed to digitalocean (previously do)
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/cmd/config_repositories_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3819 🌱 0.3 Backport: CAPD webhooks should use 9443 as port
  test/infrastructure/docker/config/webhook/manager_webhook_patch.yaml
  test/infrastructure/docker/config/webhook/service.yaml
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3616 📖 Windows Support CAEP
  docs/proposals/20200804-windows-support.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3820 📖 remove single quote allows copy / paste to work with zsh
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3814 📖 Update required configurations for Metal³ provider
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3829 📖 Update required configurations for Metal³ provider
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3826 🌱 Add Node watch to Machine controller
  api/v1alpha3/common_types.go
  controllers/machine_controller.go
  controllers/machine_controller_test.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3827 📖 Add CAPDO quickstart in CAPI book
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/developer/tilt.md
  docs/book/src/reference/glossary.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3823 🌱 Include docker output in error when we receive a non-zero exit code
  test/infrastructure/docker/docker/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3841 🐛 fixes link to proposal root to /docs/proposals/
  docs/proposals/YYYYMMDD-template.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3842 🐛 CHERRY PICK release-0.3 - fixes link to proposal root to /docs/proposals/
  docs/proposals/YYYYMMDD-template.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3754 📖 Update the roadmap for v1alpha4
  docs/book/src/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3767 📖 Define proposal guidelines and policies
  CONTRIBUTING.md
  docs/proposals/YYYYMMDD-template.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3815 :warning: Update Kind to v0.9.0
  docs/book/src/clusterctl/developers.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/testing.md
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  go.mod
  go.sum
  hack/ensure-kind.sh
  scripts/ci-e2e.sh
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3606 ✨ MachineHealthCheck now supports external remediation templates
  api/v1alpha2/conversion.go
  api/v1alpha3/condition_consts.go
  api/v1alpha3/machinehealthcheck_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  controllers/external/testing.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  test/helpers/envtest.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#3844 🌱renamed machinehealthcheck_status_matcher to test file
  controllers/machinehealthcheck_status_matcher_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3852 :seedling: Update Go to 1.15.3
  Dockerfile
  Makefile
  Tiltfile
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3853 🌱Upgrade corefile migration to v1.0.11
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#3806 🌱Refactor controlplane health check in KCP
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/controllers/upgrade_test.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/machine_collection.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3726 ✨ Modifies DockerMachine condition status to report for control plane to be ready
  api/v1alpha3/condition_consts.go
  bootstrap/kubeadm/api/v1alpha3/condition_consts.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3856 🌱CHERRY PICK release-0.3 - upgrade corefile migration to v1.0.11
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#3372 ✨ Add `remediationsAllowed` field to MHC status
  api/v1alpha3/condition_consts.go
  api/v1alpha3/machinehealthcheck_types.go
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_status_matcher.go
  util/conditions/matcher.go
  util/conditions/matcher_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3846 :warning: E2E test now resolve CNI_RESOURCES without using env variables
  test/e2e/e2e_suite_test.go
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/repository.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3670 🌱 Add Node related condition to Machine conditions
  api/v1alpha3/condition_consts.go
  controllers/machine_controller.go
  controllers/machine_controller_noderef.go
  controllers/machine_controller_noderef_test.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/remote/cluster_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3817 📖Update spot instances proposal with interruptible label setting
  docs/proposals/20200330-spot-instances.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3713 🌱 Avoid MachineHealthCheck to return early on patch errors
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/remote/cluster_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3869 ✨ Forward-port modifies DockerMachine condition status to report for control plane to be ready
  api/v1alpha4/condition_consts.go
  bootstrap/kubeadm/api/v1alpha4/condition_consts.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3877 🌱 Add reverse conversion fuzz test
  util/conversion/conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3864 🌱 Avoid draining when KCP object is being deleted
  controllers/machine_controller.go
  controllers/machine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3870 🐛 Addresses workload coredns test flakes
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3871 🌱 Print provider type and name to match config file naming
  cmd/clusterctl/client/repository/components_client.go
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/client/repository/template_client.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XS
