Repository kubernetes-sigs/cluster-api, pull requests merged in 2020-03, with the labels that each got.

#2482 🏃 Refactors config reconciliation to the workload cluster and tests it
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2492 :running: Bump Go to 1.13.8
  Dockerfile
  Makefile
  Tiltfile
  cmd/example-provider/Dockerfile
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2500 :book: Fix KCP diagram link
  docs/book/src/developer/architecture/controllers/control-plane.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#2443 ✨Bootstrap secret type
  api/v1alpha3/common_types.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2498 :running: Refactor OWNERS files throughout the repo
  OWNERS_ALIASES
  bootstrap/kubeadm/OWNERS
  cmd/clusterctl/OWNERS
  docs/book/OWNERS
  test/infrastructure/docker/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/L

#2490 :running: kubeadmcontrolplane: clean up removeMemberForNode
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2392 :running: Update KCP hash to include KubeadmConfigSpec
  controlplane/kubeadm/internal/hash/hash.go
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/S

#2506 ✨ Adds kubernetes networking to capd e2es
  cmd/clusterctl/test/e2e/go.mod
  test/framework/apply.go
  test/framework/convenience.go
  test/framework/go.mod
  test/framework/go.sum
  test/framework/management/kind/mgmt.go
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/e2e/docker_test.go
  test/infrastructure/docker/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#2503 📖removing clusterctl adopt from the documentation
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/commands/adopt.md
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/clusterctl/provider-contract.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#2504 ✨clusterctl: upgrade to a specifc set of provider versions
  cmd/clusterctl/cmd/upgrade_apply.go
  cmd/clusterctl/pkg/client/cluster/upgrader.go
  cmd/clusterctl/pkg/client/cluster/upgrader_test.go
  cmd/clusterctl/pkg/client/upgrade.go
  cmd/clusterctl/pkg/client/upgrade_test.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XL

#2491 🐛 Fix the bug that clusterctl version command does not show correct output
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2511 🏃Disable Interfacer Linter
  .golangci.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#2509 🐛clusterctl: developer workflow with docker
  cmd/clusterctl/hack/local-overrides.py
  cmd/clusterctl/pkg/client/config/providers_client.go
  cmd/clusterctl/pkg/client/config_test.go
  cmd/clusterctl/pkg/client/repository/metadata_client.go
  docs/book/src/clusterctl/developers.md
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2487 ✨Excluded metadata in annotation during conversion
  api/v1alpha2/conversion.go
  util/conversion/conversion.go
  util/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2502 :running: Use controller-runtime's client ObjectKey instead of types.NamespacedName
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_reconciler_test.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/machine_controller_test.go
  controllers/machinedeployment_sync.go
  controllers/machinepool_controller_noderef.go
  controllers/machinepool_controller_test.go
  controllers/machineset_controller_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  test/framework/failure_domains.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/e2e/docker_test.go
  util/kubeconfig/kubeconfig.go
  util/secret/certificates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2493 ✨manager/docker: add liveness/readiness probes
  test/infrastructure/docker/config/manager/manager.yaml
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2462 📖 Rename Metal3.io provider from Baremetal to Metal3
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/repository/metadata_client.go
  docs/book/src/clusterctl/overview.md
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/reference/providers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2520 📖 Upgrade v1alpha2 to v1alpha3 documentation
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/tasks/upgrade.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#2526 🐛 clusterctl: improve connection error messages
  cmd/clusterctl/client/cluster/proxy.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/S

#2529 📖 Update controller images in book
  docs/book/src/developer/architecture/controllers/bootstrap.md
  docs/book/src/developer/architecture/controllers/cluster.md
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/architecture/controllers/machine-deployment.md
  docs/book/src/developer/architecture/controllers/machine-set.md
  docs/book/src/developer/architecture/controllers/machine.md
  docs/book/src/images/bootstrap-controller.svg
  docs/book/src/images/cluster-admission-cluster-controller.svg
  docs/book/src/images/cluster-admission-machine-controller.svg
  docs/book/src/images/cluster-admission-machineset-controller.svg
  docs/book/src/images/control-plane-controller.plantuml
  docs/book/src/images/control-plane-controller.png
  docs/book/src/images/control-plane-controller.svg
Labels: approved, cncf-cla: yes, lgtm, size/L

#2488 🏃 Wire up kubeadm control plane Ready status
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  test/framework/control_plane.go
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2517 🏃 cloud init package has reduced responsibilities
  test/infrastructure/docker/cloudinit/kindadapter.go
  test/infrastructure/docker/cloudinit/kindadapter_test.go
  test/infrastructure/docker/cloudinit/runcmd.go
  test/infrastructure/docker/cloudinit/runcmd_test.go
  test/infrastructure/docker/cloudinit/unknown.go
  test/infrastructure/docker/cloudinit/unknown_test.go
  test/infrastructure/docker/cloudinit/writefiles.go
  test/infrastructure/docker/cloudinit/writefiles_test.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/e2e/local-e2e.conf
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2532 Propose spot instances support for roadmap
  docs/book/src/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2524 🐛clusterctl: add retries on create objects
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/components.go
  cmd/clusterctl/client/cluster/inventory.go
  cmd/clusterctl/client/cluster/mover.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2533 🏃Set matchPolicy to Equivalent for validation and mutation webhooks
  api/v1alpha3/cluster_webhook.go
  api/v1alpha3/machine_webhook.go
  api/v1alpha3/machinedeployment_webhook.go
  api/v1alpha3/machinehealthcheck_webhook.go
  api/v1alpha3/machineset_webhook.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  config/webhook/manifests.yaml
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/webhook/manifests.yaml
  exp/api/v1alpha3/machinepool_webhook.go
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2531 🏃Fix all 404s in book and add a verify script to ensure there are no 404s
  Makefile
  README.md
  docs/book/src/SUMMARY.md
  docs/book/src/developer/architecture/controllers/cluster.md
  docs/book/src/developer/architecture/controllers/machine-deployment.md
  docs/book/src/developer/architecture/controllers/machine-set.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/testing.md
  docs/book/src/user/quick-start.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#2538 📖Add a section about matchPolicy to "v1alpha2 to v1apha3" doc
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2537 🏃 Adds context to CAPD with timeouts
  test/infrastructure/docker/controllers/dockercluster_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/loadbalancer.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/docker/types/node.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2540 🏃 Modify Metal3 provider repository
  cmd/clusterctl/client/config/providers_client.go
  docs/book/src/clusterctl/overview.md
  docs/book/src/reference/providers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2539 🐛 Update error message for clusterctl move
  cmd/clusterctl/cmd/move.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2494 ✨ Add MHC remediation logic
  api/v1alpha3/machinehealthcheck_webhook.go
  api/v1alpha3/machinehealthcheck_webhook_test.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_targets.go
  controllers/machinehealthcheck_targets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2534 :bug: Fix CAPD flakes
  test/infrastructure/docker/docker/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2547 🏃 continue improving management/workload abstraction
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2556 :running: Add a validation check in place against client-go@incompatible
  Makefile
  cmd/clusterctl/test/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2551 📖Add instructions for providers to upgrade to CRD v1
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2550 🏃Add NoExecute taint check for KubeadmControlPlane nodes
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2563 🐛clusterctl: fix wait cert-manager
  cmd/clusterctl/client/cluster/cert_manager.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XS

#2564 🐛 Fix CAPD Calico manifest URL
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2549 ✨ Register MachineHealthCheck controller and add RBAC
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_machinehealthchecks.yaml
  config/crd/patches/webhook_in_machinehealthchecks.yaml
  config/kustomization.yaml
  config/rbac/role.yaml
  controllers/machinehealthcheck_controller.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2464 ✨ Defaulting webhooks should always set label from Spec.ClusterName
  api/v1alpha3/machine_webhook.go
  api/v1alpha3/machine_webhook_test.go
  api/v1alpha3/machinedeployment_webhook.go
  api/v1alpha3/machinedeployment_webhook_test.go
  api/v1alpha3/machinehealthcheck_webhook.go
  api/v1alpha3/machinehealthcheck_webhook_test.go
  api/v1alpha3/machineset_webhook.go
  api/v1alpha3/machineset_webhook_test.go
  exp/api/v1alpha3/machinepool_webhook.go
  exp/api/v1alpha3/machinepool_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2568 🐛clusterctl: allow empty variables
  cmd/clusterctl/client/config/reader_viper.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XS

#2567 📖 Add documentation for MachineHealthChecks
  docs/book/src/SUMMARY.md
  docs/book/src/developer/architecture/controllers/machine-health-check.md
  docs/book/src/images/machinehealthcheck-controller.plantuml
  docs/book/src/images/machinehealthcheck-controller.png
  docs/book/src/tasks/healthcheck.md
  docs/book/src/user/concepts.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2569 :bug: Allow noderef setting to be re-entrant in CAPD
  .dockerignore
  .gitignore
  scripts/ci-capd-e2e.sh
  test/infrastructure/docker/.gitignore
  test/infrastructure/docker/api/v1alpha3/dockermachine_types.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2552 🏃 Clean up go modules across repository
  Makefile
  cmd/clusterctl/test/e2e/Makefile
  cmd/clusterctl/test/e2e/go.mod
  cmd/clusterctl/test/e2e/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/cloudinit/kindadapter.go
  test/infrastructure/docker/cloudinit/runcmd.go
  test/infrastructure/docker/cloudinit/writefiles.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2573 🐛 Update misleading logs
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2575 🏃 capd: Make ready an optional field
  test/infrastructure/docker/api/v1alpha3/dockermachine_types.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2576 :running: Pass a stripped down object to controller.Watch
  controllers/external/tracker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2558 ✨clusterctl: allow cert-manager image overrides
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/config/client.go
  cmd/clusterctl/client/config/imagemeta_client.go
  cmd/clusterctl/client/config/imagemeta_client_test.go
  cmd/clusterctl/internal/test/fake_reader.go
  cmd/clusterctl/internal/util/objs.go
  cmd/clusterctl/internal/util/objs_test.go
  cmd/clusterctl/test/e2e/go.sum
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XL

#2553 🏃 Loosen webhook validation on control plane to allow etcd changes
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#2579 ✨ Etcd version
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/internal/kubeadm_config_map.go
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2571 🏃tests: standardize gomega/ginkgo imports
  api/v1alpha2/conversion_test.go
  api/v1alpha3/cluster_webhook_test.go
  api/v1alpha3/machine_webhook_test.go
  api/v1alpha3/machinedeployment_webhook_test.go
  api/v1alpha3/machinehealthcheck_webhook_test.go
  api/v1alpha3/machineset_webhook_test.go
  bootstrap/kubeadm/api/v1alpha2/conversion_test.go
  bootstrap/kubeadm/api/v1alpha2/kubeadmbootstrapconfig_types_test.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types_test.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_reconciler_test.go
  bootstrap/kubeadm/controllers/suite_test.go
  bootstrap/util/configowner_test.go
  cmd/clusterctl/test/e2e/config_cluster_test.go
  controllers/cluster_controller_phases_test.go
  controllers/cluster_controller_test.go
  controllers/external/util_test.go
  controllers/machine_controller_noderef_test.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/machine_helpers_test.go
  controllers/machinedeployment_controller_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_targets_test.go
  controllers/machineset_controller_test.go
  controllers/machineset_delete_policy_test.go
  controllers/remote/cluster_test.go
  controllers/suite_test.go
  controllers/suite_util_test.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/failure_domain_test.go
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
  controlplane/kubeadm/internal/machine_filters_test.go
  exp/api/v1alpha3/machinepool_webhook_test.go
  exp/controllers/machinepool_controller_noderef_test.go
  exp/controllers/machinepool_controller_phases_test.go
  exp/controllers/machinepool_controller_test.go
  exp/controllers/suite_test.go
  test/framework/apply.go
  test/framework/config_test.go
  test/framework/control_plane.go
  test/framework/convenience.go
  test/framework/deprecated.go
  test/framework/failure_domains.go
  test/framework/management_cluster.go
  test/helpers/components/common.go
  test/helpers/kind/setup.go
  test/helpers/scheme/scheme.go
  test/infrastructure/docker/e2e/custom_assertions.go
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/integration/cluster/cluster_test.go
  util/conversion/conversion.go
  util/conversion/conversion_test.go
  util/kubeconfig/kubeconfig_test.go
  util/patch/patch_test.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2583 🏃 Fix flake test in KCP webhook TestPaths
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2582 :bug: Allow KCP spec.version to be mutable
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2588 📖 Add message about possible problem when doing clusterctl move
  docs/book/src/clusterctl/commands/move.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2548 ✨ Add e2e style tests for Machine HealthChecking
  controllers/machinehealthcheck_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2589 🏃 tests: standardize gomega imports - Follow up
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2592 🐛clusterctl: fix cert-manager timeout
  cmd/clusterctl/client/cluster/cert_manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2581 KCP etcd upgrade: handle conditional update & add tests
  controlplane/kubeadm/internal/kubeadm_config_map.go
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2586 ✨clusterctl: improve support for air-gapped environments all image overrides
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/installer.go
  cmd/clusterctl/client/cluster/installer_test.go
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/client/cluster/upgrader_info.go
  cmd/clusterctl/client/cluster/upgrader_info_test.go
  cmd/clusterctl/client/cluster/upgrader_test.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/delete_test.go
  cmd/clusterctl/client/init_test.go
  cmd/clusterctl/client/repository/client.go
  cmd/clusterctl/client/repository/client_test.go
  cmd/clusterctl/client/repository/components.go
  cmd/clusterctl/client/repository/components_client.go
  cmd/clusterctl/client/repository/components_client_test.go
  cmd/clusterctl/client/upgrade_test.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2604 🐛 Enable upgradeAfter field to be modifiable
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2559 ✨Upgrade `kube-proxy` daemonset as part of KCP upgrades
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
  test/infrastructure/docker/go.sum
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2598 🐛validation for not having both local and external etcd in control plane
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2605 :running: Remove private APIs from Kubeadm v1beta1 types
  Makefile
  bootstrap/kubeadm/types/v1beta1/types.go
  bootstrap/kubeadm/types/v1beta1/zz_generated.deepcopy.go
  bootstrap/kubeadm/types/v1beta2/zz_generated.deepcopy.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2590 📖clusterctl based quick-start
  docs/book/src/clusterctl/developers.md
  docs/book/src/clusterctl/overview.md
  docs/book/src/developer/architecture/controllers/machine-health-check.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
  docs/book/src/reference/glossary.md
  docs/book/src/tasks/installation.md
  docs/book/src/tooling/clusterctl.md
  docs/book/src/tooling/tooling.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2616 :bug: Fix NPE when validating KCP etcd settings
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2617 🏃Improve capd e2e artifact output
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2615 🏃cmd-clusterctl-api/tests: standardize gomega imports - follow up
  cmd/clusterctl/api/v1alpha3/provider_type_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2621 🐛small fix to quick-start
  docs/book/src/clusterctl/commands/config-cluster.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2574 ✨Upgrade CoreDNS image info during KCP reconcile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/v1beta1/types.go
  cmd/clusterctl/test/e2e/go.sum
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/kubeadm_config_map.go
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2607 📖 Add documentation around KubeadmControlPlane
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/kubeadm-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2595 📖clusterctl: doc config for air-gapped environments
  docs/book/src/clusterctl/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2623 :book: Update provider documentation for failureDomains
  docs/book/src/developer/providers/machine-infrastructure.md
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2624 🏃 Be consistent with versioning in KubeadmControlPlane
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2622 🏃 Do not kubeadm reset in capd any more
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2625 :running: Increase default KCP concurrency to 10
  controlplane/kubeadm/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2640 quick-start.md: fix typo related to clusterctl
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2631 🏃 Bump controller-tools to v0.2.6
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#2638 🏃cmd-clusterctl-client-config/tests: standardize gomega imports
  cmd/clusterctl/client/config/imagemeta_client_test.go
  cmd/clusterctl/client/config/providers_client_test.go
  cmd/clusterctl/client/config/reader_viper_test.go
  cmd/clusterctl/client/config/variables_client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2632 🏃cmd-clusterctl-client-cluster/tests: standardize gomega imports
  cmd/clusterctl/client/cluster/components_test.go
  cmd/clusterctl/client/cluster/installer_test.go
  cmd/clusterctl/client/cluster/inventory_managementgroup_test.go
  cmd/clusterctl/client/cluster/inventory_test.go
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/client/cluster/template_test.go
  cmd/clusterctl/client/cluster/upgrader_info_test.go
  cmd/clusterctl/client/cluster/upgrader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2614 🏃 bootstrap/tests: standardize gomega imports - follow up
  bootstrap/kubeadm/internal/cloudinit/cloudinit_test.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_test.go
  bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go
  bootstrap/kubeadm/types/v1beta1/bootstraptokenstring_test.go
  bootstrap/kubeadm/types/v1beta2/bootstraptokenstring_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2641 :bug: KCP: fix NPE if ClusterConfiguration is nil
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2496 🏃 Use controller-runtime cache for watching remote nodes over informers
  cmd/clusterctl/test/e2e/go.mod
  cmd/clusterctl/test/e2e/go.sum
  controllers/machinehealthcheck_controller.go
  go.mod
  go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#2648 🐛 Validate MHC MaxUnhealthy strings are percentages
  api/v1alpha3/machinehealthcheck_webhook.go
  api/v1alpha3/machinehealthcheck_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2649 :book: Update minimum tilt version
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2644 🏃Add tests for coredns upgrade
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2650 :running: Move KCP/internal machine filters in a package
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/machine_collection.go
  controlplane/kubeadm/internal/machinefilters/machine_filters.go
  controlplane/kubeadm/internal/machinefilters/machine_filters_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2647 🏃[KCP] Add KCP spec.version semver check
  cmd/clusterctl/test/e2e/go.sum
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
  test/infrastructure/docker/go.sum
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, ok-to-test, size/M

#2628 Update quick start guide for flow and update parameters for AWS, Azure and vSphere
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/installation.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2662 Remove links to installation.md/html
  docs/book/src/developer/guide.md
  docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2661 ✨clusterctl repository-local supports windows
  cmd/clusterctl/client/repository/repository_local.go
  cmd/clusterctl/client/repository/repository_local_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2390 🏃 Update KCP CAEP to reflect implementation changes
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/L

#2663 🏃 Update clusterctl overview to remove confusion on presence of GUI
  docs/book/src/clusterctl/overview.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2656 🏃KCP: Migrate from flags to pflags
  controlplane/kubeadm/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2643 🏃cmd-clusterctl-client-repository/test: standardize gomega imports
  cmd/clusterctl/client/repository/client_test.go
  cmd/clusterctl/client/repository/components_client_test.go
  cmd/clusterctl/client/repository/components_test.go
  cmd/clusterctl/client/repository/metadata_client_test.go
  cmd/clusterctl/client/repository/repository_github_test.go
  cmd/clusterctl/client/repository/repository_local_test.go
  cmd/clusterctl/client/repository/template_client_test.go
  cmd/clusterctl/client/repository/template_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2672 Separate tabs in quick start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2668 🏃 cmd-clusterctl-client/tests: update gomega expect
  cmd/clusterctl/client/repository/client_test.go
  cmd/clusterctl/client/repository/components_client_test.go
  cmd/clusterctl/client/repository/components_test.go
  cmd/clusterctl/client/repository/metadata_client_test.go
  cmd/clusterctl/client/repository/repository_github_test.go
  cmd/clusterctl/client/repository/repository_local_test.go
  cmd/clusterctl/client/repository/template_client_test.go
  cmd/clusterctl/client/repository/template_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#2673 🏃 controllers/test: standardize gomega imports
  controllers/machinedeployment_sync_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2666 🏃clusterctl: use exponential backoff
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/components.go
  cmd/clusterctl/client/cluster/inventory.go
  cmd/clusterctl/client/cluster/mover.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2670 📖 Update testing document
  docs/book/src/developer/testing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2660 🏃 speed up e2e image builds
  .dockerignore
  Tiltfile
  test/infrastructure/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#2686 📖typos: fix some typos
  VERSIONING.md
  cmd/clusterctl/test/README.md
  docs/book/src/clusterctl/commands/config-cluster.md
  docs/book/src/developer/providers/implementers-guide/configure.md
  docs/book/src/developer/providers/implementers-guide/controllers_and_reconciliation.md
  docs/book/src/developer/providers/implementers-guide/generate_crds.md
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
  docs/proposals/20181121-machine-api.md
  docs/proposals/20190709-cluster-spec-crds.md
  docs/proposals/20191030-machine-health-checking.md
  docs/proposals/images/controlplane/controlplane-init-2.plantuml
  docs/proposals/images/controlplane/controlplane-init-2.png
  docs/proposals/images/controlplane/controlplane-init-3.plantuml
  docs/proposals/images/controlplane/controlplane-init-3.png
  docs/proposals/images/controlplane/controlplane-init-6.plantuml
  docs/proposals/images/controlplane/controlplane-init-6.png
  docs/proposals/images/controlplane/controlplane-init-7.plantuml
  docs/proposals/images/controlplane/controlplane-init-7.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#2645 🏃 cmd-clusterctl-client/tests: standardize gomega imports
  cmd/clusterctl/client/common_test.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/delete_test.go
  cmd/clusterctl/client/init_test.go
  cmd/clusterctl/client/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2681 🏃 util/tests: standardize gomega imports
  util/kubeconfig/kubeconfig_test.go
  util/secret/certificates_test.go
  util/util_test.go
  util/yaml/yaml_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2680 🏃test/tests: standardize gomega imports
  test/framework/types_test.go
  test/infrastructure/docker/cloudinit/kindadapter_test.go
  test/infrastructure/docker/cloudinit/runcmd_test.go
  test/infrastructure/docker/cloudinit/unknown_test.go
  test/infrastructure/docker/cloudinit/writefiles_test.go
  test/infrastructure/docker/controllers/dockermachine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2687 🏃 clusterctl: log which value clusterctl mover is setting when pausing
  cmd/clusterctl/client/cluster/mover.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2667 🏃tests: standardize gomega imports for controllers/mdutil and controllers/noderefutil
  controllers/mdutil/util_test.go
  controllers/noderefutil/providerid_test.go
  controllers/noderefutil/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2692 :book: show Azure tab in Tilt docs
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2678 🏃mark defaulted fields as optional
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/v1beta1/types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#2570 :bug: Ensure infrastructure is destroyed before deleting the node
  controllers/machine_controller.go
  controllers/machine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2691 :bug: controlplane: Normalise image name for kube-proxy, and validate Kubernetes versions
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
  test/infrastructure/docker/e2e/docker_test.go
  util/util.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2674 🏃Add semver version validation rules to Machine type and fix KCP version validation
  api/v1alpha3/machine_webhook.go
  api/v1alpha3/machine_webhook_test.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2634 🏃 Add JoelSpeed as reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2676 :book: Update troubleshooting.md
  docs/book/src/user/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2525 ✨Forward etcd leadership from machine that is being deleted
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/internal/etcd/etcd.go
  controlplane/kubeadm/internal/etcd_client_generator.go
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2695 ✨ KCP: Move etcd leadership to newest Machine when upgrading
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/machine_collection.go
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/M

#2697 🐛CoreDNS validation should only look at major.minor.patch
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  util/util.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2699 :bug: KCP spec.clusterConfiguration.imageRepository should not have "coredns/"
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#2698 :bug: forward leadership by talking to new leader
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2696 🐛 Change the number of expected etcd members
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/etcd/fake/client.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2701 :running: Add log line when reconciling KubeadmControlPlane
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2706 :bug: Disable link checker for external links in book
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2700 :bug: leadership forwarding for removed members
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2711 🐛 Remove a troublesome annotation
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2664 ✨LeaderElection configuration as flags
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  main.go
  third_party/kubernetes-drain/README.md
  third_party/kubernetes-drain/drain.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2708 🐛 KCP should set a timeout when trying to connect to remote cluster
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/internal/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2704 📖 Fix the links in the quickstart
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2707 ✨Validates CoreDNS version update
  cmd/clusterctl/test/e2e/go.sum
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2719 ✨ Add CAPO to clusterctl embedded metadata
  cmd/clusterctl/client/repository/metadata_client.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2715 📖 Update providers list to supported v1alpha3 providers
  docs/book/src/reference/providers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2720 🏃 clean up tests
  controlplane/kubeadm/internal/failure_domain_test.go
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
  controlplane/kubeadm/internal/machine_collection.go
  controlplane/kubeadm/internal/machine_collection_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2714 🐛 update worker kubernetes version in capd test template
  cmd/clusterctl/test/testdata/docker/v0.3.0/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2679 ✨ Clusterctl local overrides
  cmd/clusterctl/client/config/variables_client_test.go
  cmd/clusterctl/client/repository/client.go
  cmd/clusterctl/client/repository/components_client.go
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/client/repository/metadata_client_test.go
  cmd/clusterctl/client/repository/overrides.go
  cmd/clusterctl/client/repository/overrides_test.go
  cmd/clusterctl/client/repository/template_client.go
  cmd/clusterctl/test/run-e2e.sh
  docs/book/src/clusterctl/configuration.md
  docs/book/src/clusterctl/developers.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2725 🐛 Allows dns image tag to be unset
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2726 🐛 Etcd should talk to leader when moving leadership
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2675 🏃 controlplane-kubeadm/test: standardize gomega imports
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2712 📖 update quickstart Azure variables
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2727 🏃 Increase a constantly failing timeout in capd
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2730 📖 clarify order of steps in quickstart to deploy workload cluster
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2728 🏃 Adds a control plane struct to clean up the reconciler
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/control_plane_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2729 🏃 Add a modified util function
  controllers/external/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2733 :running: Build binaries first during release
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2740 :bug: MachineDeployment controller should actually return errors
  controllers/machinedeployment_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2741 📖Add IAM pre-requisite notes to AWS quickstart
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2734 🏃 Start using control plane object just a little bit
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  controlplane/kubeadm/internal/control_plane.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2739 🏃 Improve Cluster.Spec.Paused watchers and provide utils
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machineset_controller.go
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
  util/util.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2745 🏃 rewrite kubeadm control plane logs for consistency
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machinehealthcheck_controller.go
  controllers/machineset_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/internal/kubeadm_config_map.go
  controlplane/kubeadm/internal/workload_cluster.go
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
  exp/controllers/machinepool_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2746 :bug: Avoid draining nodes when deleting a Cluster
  controllers/machine_controller.go
  controllers/machine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2747 📖 Update quick-start.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2750 📖 small fix for quick-start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2684 🏃 Add auth providers support to clusterctl
  cmd/clusterctl/main.go
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
