Repository kubernetes-sigs/cluster-api, pull requests merged in 2020-11, with the labels that each got.

#3890 🌱 Add Node related condition to Machine conditions
  api/v1alpha3/condition_consts.go
  api/v1alpha4/condition_consts.go
  controllers/machine_controller.go
  controllers/machine_controller_noderef.go
  controllers/machine_controller_noderef_test.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/remote/cluster_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3882 ✨ MHC external remediation
  api/v1alpha3/condition_consts.go
  api/v1alpha3/machinehealthcheck_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/condition_consts.go
  api/v1alpha4/machinehealthcheck_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  controllers/external/testing.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  test/helpers/envtest.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3883 🌱 Refactor controlplane health check in KCP
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/controllers/upgrade_test.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/machine_collection.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3893 :seedling: Update controller-runtime to latest main version v0.7.0-alpha.5
  Makefile
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/client/cluster/inventory.go
  controllers/machine_controller_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  controlplane/kubeadm/internal/workload_cluster_rbac.go
  exp/addons/controllers/clusterresourceset_controller.go
  exp/controllers/machinepool_controller_test.go
  go.mod
  go.sum
  test/framework/deployment_helpers.go
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  util/patch/patch.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3897 :bug: Fix Makefile docker targets by prepulling required images
  Makefile
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3905 📖 Remove leading colon between --infrastructure flag and provider
  docs/book/src/clusterctl/commands/config-cluster.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3899 :sparkles: Add GetLiveClient() to ClusterCacheTracker
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_cache_reconciler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3888 🌱 Fix typo in clusterctl client test
  cmd/clusterctl/client/repository/client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3896 ⚠️ E2E framework resolves CNI_RESOURCES without using env vars
  test/e2e/e2e_suite_test.go
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/repository.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3900 Add KCP conditions, split reconcileHealth into preflight and reconcileEtcdMembers, make both use conditions
  controlplane/kubeadm/api/v1alpha3/condition_consts.go
  controlplane/kubeadm/controllers/consts.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/controllers/upgrade_test.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/etcd/etcd.go
  controlplane/kubeadm/internal/etcd/util/set.go
  controlplane/kubeadm/internal/etcd/util/util.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
  controlplane/kubeadm/internal/workload_cluster_etcd_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3912 🐛 Backport of high cpu usage during kubectl drain
  third_party/kubernetes-drain/drain.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3830 ✨ KCP remediates unhealthy machines
  api/v1alpha3/condition_consts.go
  controllers/machine_controller.go
  controllers/machinehealthcheck_controller.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/remediation.go
  controlplane/kubeadm/controllers/remediation_test.go
  controlplane/kubeadm/controllers/suite_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/control_plane_test.go
  controlplane/kubeadm/internal/machinefilters/machine_filters.go
  controlplane/kubeadm/internal/machinefilters/machine_filters_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3915 🐛 Backport of high cpu usage during kubectl drain
  third_party/kubernetes-drain/drain.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3919 🐛 Prevents reconcileEtcdMember to remove etcd members when etcd starts slowly
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/S

#3918 ⚠️Remove hard code manifest version and hash
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/client/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3884 ✨ Add `remediationsAllowed` field to MHC status
  api/v1alpha3/condition_consts.go
  api/v1alpha3/machinehealthcheck_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/condition_consts.go
  api/v1alpha4/machinehealthcheck_types.go
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_status_matcher_test.go
  util/conditions/matcher.go
  util/conditions/matcher_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3927 🐛 Relax update validation to allow rotating ssh keys for KCP
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3928 🐛 relax update validation to allow rotating ssh keys for KCP
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3931 🐛 Update the docker cluster template to reference v1alpha4 resources
  test/infrastructure/docker/templates/cluster-template-development.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3936 ✨ Un-deprecate OwnedConditions and WithOwnedConditions
  util/patch/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3937 ✨ Un-deprecate WithOwnedConditions and OwnedConditions
  util/patch/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3932 📖 Add note about k8s version when using CAPD
  docs/book/src/clusterctl/developers.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3901 🌱Avoid MachineHealtchCheck to return early on patch errors
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/remote/cluster_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3934 ⚠️ Align flag names with upstream Kubernetes components
  bootstrap/kubeadm/config/manager/manager.yaml
  bootstrap/kubeadm/config/manager/manager_auth_proxy_patch.yaml
  bootstrap/kubeadm/config/webhook/manager_webhook_patch.yaml
  bootstrap/kubeadm/main.go
  config/ci/manager/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/manager/manager_auth_proxy_patch.yaml
  config/webhook/manager_webhook_patch.yaml
  controlplane/kubeadm/config/manager/manager.yaml
  controlplane/kubeadm/config/manager/manager_auth_proxy_patch.yaml
  controlplane/kubeadm/config/webhook/manager_webhook_patch.yaml
  controlplane/kubeadm/main.go
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
  docs/book/src/reference/ports.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  main.go
  test/e2e/config/docker.yaml
  test/framework/deployment_helpers.go
  test/infrastructure/docker/config/manager/manager.yaml
  test/infrastructure/docker/config/manager/manager_auth_proxy_patch.yaml
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3943 📖 Update CAPO variables in Quick Start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3945 🌱 Fix small typo in clusterctl command docs
  docs/book/src/clusterctl/commands/generate-yaml.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3952 📖 Backport of updating CAPO variables in Quick Start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3922 🌱 Add KCP conditions, split reconcileHealth into preflight and reconcileEtcdMembers, make both use conditions
  controlplane/kubeadm/api/v1alpha3/condition_consts.go
  controlplane/kubeadm/api/v1alpha4/condition_consts.go
  controlplane/kubeadm/controllers/consts.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/controllers/upgrade_test.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/etcd/etcd.go
  controlplane/kubeadm/internal/etcd/util/set.go
  controlplane/kubeadm/internal/etcd/util/util.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
  controlplane/kubeadm/internal/workload_cluster_etcd_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3949 🌱 Add embedded metadata for v1alpha4 in clusterctl
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/client/repository/metadata_client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3947 🐛 fetch_ext_bins should cleanup the temp file after downloading it
  scripts/fetch_ext_bins.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3953 :book: Fix a typo in the Healthcheck book.
  docs/book/src/tasks/healthcheck.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3925 ⚠️ Upgrade to kube-rbac-proxy:v0.5.0
  bootstrap/kubeadm/config/manager/manager_auth_proxy_patch.yaml
  cmd/clusterctl/client/init_test.go
  cmd/clusterctl/internal/util/objs_test.go
  config/ci/manager/manager_auth_proxy_patch.yaml
  config/manager/manager_auth_proxy_patch.yaml
  controlplane/kubeadm/config/manager/manager_auth_proxy_patch.yaml
  test/infrastructure/docker/config/manager/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3955 ⚠️ Remove deprecated DeleteNodeAnnotation annotation
  controllers/machineset_delete_policy.go
  controllers/machineset_delete_policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3956 ✨ KCP remediation
  api/v1alpha3/condition_consts.go
  api/v1alpha4/condition_consts.go
  controllers/machine_controller.go
  controllers/machinehealthcheck_controller.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/remediation.go
  controlplane/kubeadm/controllers/remediation_test.go
  controlplane/kubeadm/controllers/suite_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/control_plane_test.go
  controlplane/kubeadm/internal/machinefilters/machine_filters.go
  controlplane/kubeadm/internal/machinefilters/machine_filters_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3950 🌱 Add v1alpha3 test templates alongside v1alpha4 ones
  .gitignore
  test/e2e/Makefile
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1alpha3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1alpha3/bases/crs.yaml
  test/e2e/data/infrastructure-docker/v1alpha3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1alpha3/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/crs.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/mhc.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-adoption/step1/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-adoption/step2/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-machine-pool/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-mhc/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3940 🐛 Rotate MachinePool bootstrap token
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/controllers/token.go
  bootstrap/util/configowner.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3962 🐛 Prevent reconcileEtcdMember to remove etcd members when etcd starts slowly
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3965 🐛 Rotate MachinePool bootstrap token
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/controllers/token.go
  bootstrap/util/configowner.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3963 🐛 Skip spoke-hub-spoke conversion fuzz tests
  util/conversion/conversion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
