Repository kubernetes-sigs/cluster-api, pull requests merged in 2020-01, with the labels that each got.

#1982 :book: Fix broken tab in Quick Start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1975 ⚠️ clusterctl: allow config variable override
  cmd/clusterctl/pkg/client/config/client.go
  cmd/clusterctl/pkg/client/config/reader_viper.go
  cmd/clusterctl/pkg/client/config/reader_viper_test.go
  cmd/clusterctl/pkg/client/config/variables_client.go
  cmd/clusterctl/pkg/internal/test/fake_reader.go
  cmd/clusterctl/pkg/internal/test/fake_variable_client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1986 ✨clusterctl: fix RBAC rules and make multi-tenancy possible
  cmd/clusterctl/pkg/client/repository/components.go
  cmd/clusterctl/pkg/client/repository/components_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1991 :running: Remove TemplateCloner, MachineGenerator, and KubeadmConfigGenerator interfaces
  controllers/external/util.go
  controllers/external/util_test.go
  controllers/machineset_controller.go
  controllers/suite_test.go
  controlplane/kubeadm/controllers/generator/kubeadmconfiggenerator.go
  controlplane/kubeadm/controllers/generator/kubeadmconfiggenerator_test.go
  controlplane/kubeadm/controllers/generator/machinegenerator.go
  controlplane/kubeadm/controllers/generator/machinegenerator_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1973 :sparkles: Start populating KubeadmControlPlane Status
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1968 :sparkles: Implement scale up for KubeadmControlPlane
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1981 ✨clusterctl: add support for local override of files read from provider's repository
  cmd/clusterctl/pkg/client/config/reader_viper.go
  cmd/clusterctl/pkg/client/repository/client.go
  cmd/clusterctl/pkg/client/repository/components_client.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1909 :warning: clusterctl v2 add the low-level library for managing provider's repository using Github
  cmd/clusterctl/pkg/client/repository/repository_github.go
  cmd/clusterctl/pkg/client/repository/repository_github_test.go
  go.mod
  go.sum
  test/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1980 ✨Add manager role aggregation label
  .gitignore
  config/ci/kustomization.yaml
  config/ci/manager_role_aggregation_patch.yaml
  config/ci/rbac/kustomization.yaml
  config/core/kustomization.yaml
  config/core/manager_role_aggregation_patch.yaml
  config/rbac/aggregated_role.yaml
  config/rbac/kustomization.yaml
  docs/book/src/providers/cluster-infrastructure.md
  docs/book/src/providers/machine-infrastructure.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1999 🐛 Better use of docker cache
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2000 🐛 Bump cloud build timeout
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2001 🐛 Bump cloud init build to 45m
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1992 🐛Preserve data when performing down-conversions
  api/v1alpha2/conversion.go
  bootstrap/kubeadm/api/v1alpha2/conversion.go
  util/conversion/conversion.go
  util/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2003 further improve using docker cache for release
  .dockerignore
  Dockerfile
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#1977 ✨clusterctl: add test framework for move
  cmd/clusterctl/pkg/internal/scheme/scheme.go
  cmd/clusterctl/pkg/internal/test/fake_objects.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2004 :running: Use 8-core machines for cloud builds instead of 1
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2005 🐛 Fix typo in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2008 🐛clusterctl: fix-init
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/pkg/client/cluster/client.go
  cmd/clusterctl/pkg/client/cluster/inventory.go
  cmd/clusterctl/pkg/client/cluster/proxy.go
  cmd/clusterctl/pkg/client/config/providers_client.go
  cmd/clusterctl/pkg/client/config_test.go
  cmd/clusterctl/pkg/client/init.go
  cmd/clusterctl/pkg/client/init_test.go
  cmd/clusterctl/pkg/client/repository/client.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2007 :sparkles: Make sure KCP template resources have a Cluster owner
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2010 🐛 add a cluster-api label to the init lock configmap
  bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2011 🏃 Improve logs and fix an outstanding TODO
  bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2012 🏃Aggregate return errors instead of overwriting/ignoring
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  util/yaml/yaml_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2013 🏃Improve conversion webhook: add tests, fix preserve logic, remove inline nolint
  .golangci.yml
  api/v1alpha2/conversion.go
  api/v1alpha2/conversion_test.go
  bootstrap/kubeadm/api/v1alpha2/conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2019 Add Workload Cluster definition
  docs/book/src/reference/glossary.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2020 :running: Update kubebuilder tools to 1.16.4
  scripts/fetch_ext_bins.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1985 :sparkles: Add support to pause reconciliation
  api/v1alpha2/conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/cluster_types.go
  api/v1alpha3/common_types.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machinepool_controller.go
  controllers/machineset_controller.go
  controllers/machineset_controller_test.go
  docs/book/src/providers/v1alpha2-to-v1alpha3.md
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1995 ✨ Support multi-node control planes, MachineDeployments, and additional resources in the e2e framework
  test/framework/control_plane.go
  test/framework/types.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#2023 🏃 remove nolint:gocyclo
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2014 🏃 Add another permission to the kubeadm control plane controller
  controlplane/kubeadm/config/rbac/role.yaml
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2024 :book: Add kustomize standalone prereq to tilt doc
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2018 :running: Minor improvements to clusterctl codebase
  cmd/clusterctl/pkg/client/alias.go
  cmd/clusterctl/pkg/client/client.go
  cmd/clusterctl/pkg/client/cluster/client.go
  cmd/clusterctl/pkg/client/cluster/components.go
  cmd/clusterctl/pkg/client/cluster/installer.go
  cmd/clusterctl/pkg/client/cluster/inventory.go
  cmd/clusterctl/pkg/client/cluster/proxy.go
  cmd/clusterctl/pkg/client/config/client.go
  cmd/clusterctl/pkg/client/repository/components.go
  cmd/clusterctl/pkg/client/repository/repository_github.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2025 :bug: Tiltfile: union providers enabled in tilt-settings.json with those always enabled
  Tiltfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2026 :book: Add kustomize standalone prereq to tilt doc
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2017 ⚠️ clusterctl: installs cert-manager during init
  .golangci.yml
  Makefile
  cmd/clusterctl/config/crd_manifests.go
  cmd/clusterctl/config/zz_generated.bindata.go
  cmd/clusterctl/pkg/client/client_test.go
  cmd/clusterctl/pkg/client/cluster/cert_manager.go
  cmd/clusterctl/pkg/client/cluster/client.go
  cmd/clusterctl/pkg/client/cluster/inventory.go
  cmd/clusterctl/pkg/client/init.go
  cmd/clusterctl/pkg/internal/util/yaml.go
  hack/boilerplate/boilerplate.py
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2032 🏃 Minor cloudbuild clean up
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2027 ✨clusterctl: implements hack for generating local overrides
  .gitignore
  cmd/clusterctl/hack/local-overrides.py
  cmd/clusterctl/pkg/client/config/providers_client.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2039 📖 enable kubeadm providers in example tilt-settings.json
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2038 :bug: Ensure MachineSet controller won't orphan resources
  controllers/external/util.go
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1974 ⚠️ clusterctl: add metadata
  cmd/clusterctl/api/v1alpha3/metadata_type.go
  cmd/clusterctl/api/v1alpha3/zz_generated.deepcopy.go
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/kustomization.yaml
  cmd/clusterctl/pkg/client/client_test.go
  cmd/clusterctl/pkg/client/config/providers_client.go
  cmd/clusterctl/pkg/client/repository/client.go
  cmd/clusterctl/pkg/client/repository/metadata_client.go
  cmd/clusterctl/pkg/client/repository/metadata_client_test.go
  cmd/clusterctl/pkg/client/repository/templates_client.go
  cmd/clusterctl/pkg/internal/test/fake_repository.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2040 ✨clusterctl: rename config file
  cmd/clusterctl/cmd/config_cluster.go
  cmd/clusterctl/cmd/config_providers.go
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/hack/local-overrides.py
  cmd/clusterctl/pkg/client/config/reader_viper.go
  cmd/clusterctl/pkg/client/repository/client.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2022 :running: Fix more conversions / add tests
  api/v1alpha2/conversion.go
  api/v1alpha2/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1996 ✨clusterctl: implement cluster templates-low-level-lib
  cmd/clusterctl/pkg/client/client_test.go
  cmd/clusterctl/pkg/client/repository/client.go
  cmd/clusterctl/pkg/client/repository/template.go
  cmd/clusterctl/pkg/client/repository/template_client.go
  cmd/clusterctl/pkg/client/repository/template_client_test.go
  cmd/clusterctl/pkg/client/repository/template_test.go
  cmd/clusterctl/pkg/client/repository/templates_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2043 🏃‍♂️Pass Context parameter instead of calling context.TODO()
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2044 🏃 Aggregate the errors from machine deletion
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2033 :bug: Fix race condition and improve capd-e2e to build off actual changes
  Tiltfile
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  scripts/ci-capd-e2e.sh
  test/framework/control_plane.go
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/config/default/manager_auth_proxy_patch.yaml
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/e2e/docker_test.go
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1903 🏃 Run CAPD verify scripts in CI
  Makefile
  scripts/ci-make.sh
  test/infrastructure/docker/hack/verify-all.sh
  test/infrastructure/docker/hack/verify-docker-build.sh
  test/infrastructure/docker/hack/verify-gofmt.sh
  test/infrastructure/docker/hack/verify-goimports.sh
  test/infrastructure/docker/hack/verify-golint.sh
  test/infrastructure/docker/hack/verify-govet.sh
  test/infrastructure/docker/hack/verify-spelling.sh
  test/infrastructure/docker/hack/verify-whitespace.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#2054 Let GCB build release images
  Makefile
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2052 :book: Add contributing and code of conduct markdown to SUMMARY TOC referenc…
  README.md
  docs/book/src/CONTRIBUTING.md
  docs/book/src/SUMMARY.md
  docs/book/src/code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2053 🏃 Improve release notes utility / add -from flag
  Makefile
  hack/tools/release/notes.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2030 ✨ proxy: add proxy package for connecting to pods
  controlplane/kubeadm/internal/proxy/addr.go
  controlplane/kubeadm/internal/proxy/conn.go
  controlplane/kubeadm/internal/proxy/dial.go
  controlplane/kubeadm/internal/proxy/proxy.go
  go.sum
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/L

#2048 ✨clusterctl: add the config provider <provider-name> command
  cmd/clusterctl/cmd/config_providers.go
  cmd/clusterctl/pkg/client/client.go
  cmd/clusterctl/pkg/client/client_test.go
  cmd/clusterctl/pkg/client/config.go
  cmd/clusterctl/pkg/client/config_test.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2066 :bug: Kubeadm-based Control Plane: Fix error handling during cleanup
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/XS

#2069 🐛 Fix concatenation of cluster-api-components.yaml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2075 🐛fix clusterctl hack for python 3.0
  cmd/clusterctl/hack/local-overrides.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2061 ✨clusterctl: add version command
  Makefile
  cmd/clusterctl/cmd/config_providers.go
  cmd/clusterctl/cmd/version.go
  cmd/version/version.go
  hack/version.sh
Labels: approved, cncf-cla: yes, lgtm, lifecycle/active, size/L

#2047 ⚠️ clusterctl: add the clusterctl config cluster command
  cmd/clusterctl/cmd/config_cluster.go
  cmd/clusterctl/pkg/client/alias.go
  cmd/clusterctl/pkg/client/client.go
  cmd/clusterctl/pkg/client/client_test.go
  cmd/clusterctl/pkg/client/cluster/inventory.go
  cmd/clusterctl/pkg/client/common.go
  cmd/clusterctl/pkg/client/config.go
  cmd/clusterctl/pkg/client/config_test.go
  cmd/clusterctl/pkg/client/init_test.go
  cmd/clusterctl/pkg/client/repository/template_client.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XL

#2035 ✨ Adding an auth-proxy sidecar container to CAPI core controller manager
  .gitignore
  cmd/example-provider/main.go
  config/ci/kustomization.yaml
  config/ci/manager_auth_proxy_patch.yaml
  config/ci/rbac/kustomization.yaml
  config/core/kustomization.yaml
  config/core/manager_arguments.yaml
  config/core/manager_auth_proxy_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_arguments.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2071 🐛clusterctl: remove --force flag from init
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/pkg/client/client.go
  cmd/clusterctl/pkg/client/cluster/installer.go
  cmd/clusterctl/pkg/client/cluster/inventory.go
  cmd/clusterctl/pkg/client/init.go
  cmd/clusterctl/pkg/client/init_test.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/M

#2077 🐛 code clean and bug fix for Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2059 ✨clusterctl: improve move test framework
  Makefile
  cmd/clusterctl/pkg/internal/test/fake_objects.go
  cmd/clusterctl/pkg/internal/test/fake_proxy.go
  cmd/clusterctl/pkg/internal/test/providers/bootstrap/dummy_types.go
  cmd/clusterctl/pkg/internal/test/providers/bootstrap/groupversion_info.go
  cmd/clusterctl/pkg/internal/test/providers/bootstrap/zz_generated.deepcopy.go
  cmd/clusterctl/pkg/internal/test/providers/controlplane/dummy_types.go
  cmd/clusterctl/pkg/internal/test/providers/controlplane/groupversion_info.go
  cmd/clusterctl/pkg/internal/test/providers/controlplane/zz_generated.deepcopy.go
  cmd/clusterctl/pkg/internal/test/providers/infrastructure/dummy_types.go
  cmd/clusterctl/pkg/internal/test/providers/infrastructure/groupversion_info.go
  cmd/clusterctl/pkg/internal/test/providers/infrastructure/zz_generated.deepcopy.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XXL

#2079 ✨ Adds failure domain to machine spec
  api/v1alpha2/conversion.go
  api/v1alpha2/conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/machine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2084 🐛 Import (and enable) pprof
  .golangci.yml
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2085 docs(*): typo regulat -> regular
  docs/book/src/user/concepts.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2037 ✨ Implement delete for KubeadmControlPlane
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  util/util.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2076 🏃 Remove dependency on kind v0.5.1
  test/framework/interfaces.go
  test/framework/management/kind/mgmt.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/kind_manager.go
  test/infrastructure/docker/docker/loadbalancer.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/docker/types/node.go
  test/infrastructure/docker/docker/util.go
  test/infrastructure/docker/docs/kind.md
  test/infrastructure/docker/e2e/custom_management.go
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2088 🏃Refactor kubeadm control plane reconcile funcs
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2091 🏃Refactor CloneTemplate / propagate clone labels in MS
  controllers/external/util.go
  controllers/external/util_test.go
  controllers/machineset_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1994 📖 clusterctl: initial set of documentation
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/command-init.md
  docs/book/src/clusterctl/commands/adopt.md
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/clusterctl/commands/config-cluster.md
  docs/book/src/clusterctl/commands/delete.md
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/commands/move.md
  docs/book/src/clusterctl/commands/upgrade.md
  docs/book/src/clusterctl/configuration.md
  docs/book/src/clusterctl/developers.md
  docs/book/src/clusterctl/overview.md
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/providers/clusterctl.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2087 🏃Add remote fake client
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  controllers/remote/cluster.go
  controllers/remote/fake/cluster.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2094 ✨ Delete the ControlPlaneRef object if it exists
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/S

#2095 🏃 Fix Kubeadm Control Plane controller's concept of Ready
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  test/framework/control_plane.go
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2096 📖Remove link to broken REGISTRY env var doc
  docs/book/src/architecture/developer-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2093 📖 Fixing a small documentation typo
  docs/book/src/user/concepts.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#2098 🐛clusterctl: fix docker provider
  cmd/clusterctl/hack/local-overrides.py
  cmd/clusterctl/pkg/client/config/providers_client.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2103 :bug: Fix service port selector
  bootstrap/kubeadm/config/webhook/service.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2107 :running: Propagate KCP labels to cloned objects
  api/v1alpha3/machine_types.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2110 :running: Update ginkgo/gomega to latest releases
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#2060 ✨clusterctl: create the object graph for move
  cmd/clusterctl/pkg/client/cluster/move.go
  cmd/clusterctl/pkg/client/cluster/move_test.go
  cmd/clusterctl/pkg/internal/scheme/scheme.go
  cmd/clusterctl/pkg/internal/test/fake_objects.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XL

#2111 :running: Make gomega tests more readable
  api/v1alpha3/cluster_webhook_test.go
  api/v1alpha3/machine_webhook_test.go
  api/v1alpha3/machinedeployment_webhook_test.go
  api/v1alpha3/machineset_webhook_test.go
  controllers/external/util_test.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
  test/framework/control_plane.go
  test/helpers/components/common.go
  test/helpers/kind/setup.go
  test/helpers/scheme/scheme.go
  util/conversion/conversion_test.go
  util/kubeconfig/kubeconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2109 :running: Add test for KubeadmConfig conversion
  bootstrap/kubeadm/api/v1alpha2/conversion.go
  bootstrap/kubeadm/api/v1alpha2/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2116 📖 fix typo in '$ kind create cluster'
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2114 📖 Adding cert-manager prerequisite to the quick start
  docs/book/src/tasks/installation.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#2113 📖 fix doc typo in clusterctl init for --core flag
  cmd/clusterctl/cmd/init.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/S

#2106 :book: Fixing outdated documentation for bootstrap provider
  docs/book/src/architecture/controllers/machine.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2119 🐛 Set clusterctl user-agent
  cmd/clusterctl/pkg/client/cluster/proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2122 📖 Update README to point to 2020 meeting notes.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2123 📖 Add image builder section
  docs/book/src/tasks/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2124 :book: Fix bootstrap provider activity diagram url
  docs/book/src/providers/bootstrap.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#2127 🐛 clusterctl: remove duplicate errors, and silence usage on error
  cmd/clusterctl/cmd/root.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XS

#2125 ✨Stop the reconciliation when the external ref object is paused
  controllers/cluster_controller_phases.go
  controllers/cluster_controller_phases_test.go
  controllers/external/types.go
  controllers/machine_controller.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2136 :bug: Fix delete control plane bug
  controllers/cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2145 📖 fix spelling mistake in readme
  bootstrap/kubeadm/README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, priority/backlog, size/XS

#2112 ✨Backport clusterctl labels to CAPI components
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2142 🐛 fix the e2e tests
  Makefile
  scripts/ci-capi-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2100 :sparkles: Add ability to configure Tilt mode
  Tiltfile
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2144 ✨e2e config file and management cluster helpers
  test/framework/config.go
  test/framework/config_constants.go
  test/framework/config_test.go
  test/framework/convenience.go
  test/framework/go.mod
  test/framework/interfaces.go
  test/framework/management_cluster.go
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/docker/kind_manager.go
  test/infrastructure/docker/e2e/capd_generator.go
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/e2e/e2e.conf
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2078 ✨clusterctl: add the delete command
  cmd/clusterctl/cmd/delete.go
  cmd/clusterctl/pkg/client/client.go
  cmd/clusterctl/pkg/client/client_test.go
  cmd/clusterctl/pkg/client/cluster/client.go
  cmd/clusterctl/pkg/client/cluster/components.go
  cmd/clusterctl/pkg/client/cluster/components_test.go
  cmd/clusterctl/pkg/client/cluster/inventory.go
  cmd/clusterctl/pkg/client/cluster/proxy.go
  cmd/clusterctl/pkg/client/delete.go
  cmd/clusterctl/pkg/client/delete_test.go
  cmd/clusterctl/pkg/internal/test/fake_proxy.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XL

#2102 ✨Clusterctl: Add the ObjectMover service
  cmd/clusterctl/pkg/client/client_test.go
  cmd/clusterctl/pkg/client/cluster/client.go
  cmd/clusterctl/pkg/client/cluster/mover.go
  cmd/clusterctl/pkg/client/cluster/mover_test.go
  cmd/clusterctl/pkg/client/cluster/objectgraph.go
  cmd/clusterctl/pkg/client/cluster/objectgraph_test.go
  cmd/clusterctl/pkg/internal/test/fake_objects.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XXL

#2149 🏃Update Azure quickstart docs for new k8s version
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2155 :book: Update Azure quickstart docs for new k8s version
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2135 ✨ Add more print columns to machinedeployments
  api/v1alpha3/machinedeployment_types.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2070 ✨Add clusterctl labels to labels provider components
  bootstrap/kubeadm/config/default/kustomization.yaml
  config/core/kustomization.yaml
  controlplane/kubeadm/config/default/kustomization.yaml
  docs/book/src/clusterctl/commands/adopt.md
  docs/book/src/clusterctl/configuration.md
  docs/book/src/clusterctl/provider-contract.md
  test/infrastructure/docker/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2146 :book: Reorganize book folder structure
  docs/book/src/SUMMARY.md
  docs/book/src/developer/architecture/controllers.md
  docs/book/src/developer/architecture/controllers/bootstrap.md
  docs/book/src/developer/architecture/controllers/cluster.md
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/architecture/controllers/machine-deployment.md
  docs/book/src/developer/architecture/controllers/machine-set.md
  docs/book/src/developer/architecture/controllers/machine.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/providers/bootstrap.md
  docs/book/src/developer/providers/cluster-infrastructure.md
  docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
  docs/book/src/developer/providers/implementers-guide/cluster-email.png
  docs/book/src/developer/providers/implementers-guide/configure.md
  docs/book/src/developer/providers/implementers-guide/controllers_and_reconciliation.md
  docs/book/src/developer/providers/implementers-guide/create_api.md
  docs/book/src/developer/providers/implementers-guide/generate_crds.md
  docs/book/src/developer/providers/implementers-guide/naming.md
  docs/book/src/developer/providers/implementers-guide/overview.md
  docs/book/src/developer/providers/implementers.md
  docs/book/src/developer/providers/machine-infrastructure.md
  docs/book/src/developer/providers/v1alpha1-to-v1alpha2.md
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
  docs/book/src/developer/repository-layout.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#2152 ✨clusterctl: fix labels
  api/v1alpha3/common_types.go
  cmd/clusterctl/api/v1alpha3/labels.go
  cmd/clusterctl/pkg/client/cluster/cert_manager.go
  cmd/clusterctl/pkg/client/cluster/components.go
  cmd/clusterctl/pkg/client/cluster/components_test.go
  cmd/clusterctl/pkg/client/cluster/inventory.go
  cmd/clusterctl/pkg/client/repository/components.go
  cmd/clusterctl/pkg/client/repository/components_client_test.go
  cmd/clusterctl/pkg/client/repository/components_test.go
  cmd/clusterctl/pkg/internal/test/fake_proxy.go
  docs/book/src/clusterctl/commands/init.md
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/M

#2158 🏃 Use e2e config for capd e2es
  docs/book/src/developer/tests.md
  scripts/ci-capd-e2e.sh
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/e2e/ci-e2e.conf
  test/infrastructure/docker/e2e/local-e2e.conf
Labels: approved, cncf-cla: yes, lgtm, size/L

#2137 📖 Backport: document how to verify control-plane is running
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2160 🏃Fix provider label for docker
  test/infrastructure/docker/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2167 :bug: MachineReconciler.getNodeReference use continue token
  controllers/machine_controller_noderef.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2130 ✨clusterctl: add the clusterctl move command
  cmd/clusterctl/cmd/move.go
  cmd/clusterctl/pkg/client/client.go
  cmd/clusterctl/pkg/client/client_test.go
  cmd/clusterctl/pkg/client/move.go
  docs/book/src/clusterctl/commands/move.md
  docs/book/src/clusterctl/provider-contract.md
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2159 📖 Add port allocation documentation
  CONTRIBUTING.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/providers/bootstrap.md
  docs/book/src/reference/ports.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2174 fix quick start for Openstack
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2172 📖 Fix clusterctl developers doc
  docs/book/src/clusterctl/developers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2179 📖 Update docs to support KIND >= v0.6.x
  docs/book/src/tasks/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2180 🏃Fix clusterctl --config flag help
  cmd/clusterctl/cmd/root.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2099 ✨clusterctl: add support for the controlplane provider
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/cmd/config_cluster.go
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/hack/local-overrides.py
  cmd/clusterctl/pkg/client/client.go
  cmd/clusterctl/pkg/client/config.go
  cmd/clusterctl/pkg/client/config/providers_client.go
  cmd/clusterctl/pkg/client/config_test.go
  cmd/clusterctl/pkg/client/init.go
  cmd/clusterctl/pkg/client/init_test.go
  controlplane/kubeadm/config/default/kustomization.yaml
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/developers.md
  docs/book/src/clusterctl/overview.md
  docs/book/src/clusterctl/provider-contract.md
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2177 🐛 clusterctl: allow build releases
  cmd/clusterctl/pkg/client/repository/repository_github.go
  cmd/clusterctl/pkg/client/repository/repository_github_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2163 ✨ Add verbosity to kubeadm config
  bootstrap/kubeadm/api/v1alpha2/conversion.go
  bootstrap/kubeadm/api/v1alpha2/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.deepcopy.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/cloudinit/cloudinit.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_init.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_join.go
  bootstrap/kubeadm/internal/cloudinit/node.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2169 ✨ implement failure domain picking
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/internal/failure_domain.go
  controlplane/kubeadm/internal/failure_domain_test.go
  test/infrastructure/docker/api/v1alpha3/dockercluster_types.go
  test/infrastructure/docker/api/v1alpha3/zz_generated.deepcopy.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/controllers/dockercluster_controller.go
  test/infrastructure/docker/e2e/docker_suite_test.go
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2104 ✨clusterctl: inspect images in provider components
  cmd/clusterctl/cmd/config_providers.go
  cmd/clusterctl/pkg/client/repository/components.go
  cmd/clusterctl/pkg/client/repository/components_test.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#1963 :warning: clusterctlv2: add file system backend implementations for provider's repository
  cmd/clusterctl/pkg/client/repository/repository_local_unix.go
  cmd/clusterctl/pkg/client/repository/repository_local_unix_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#2156 :sparkles: Add liveness/readiness probes
  cmd/example-provider/main.go
  config/manager/manager.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2189 🐛 Add dependencies for capi-e2e tests
  scripts/ci-capi-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2188 :running: lint-full: increase timeout to 5m
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2190 :bug: Remove Version from references when comparing MachineTemplateSpec
  controllers/machinedeployment_sync.go
  controllers/mdutil/util.go
  controllers/mdutil/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2194 nit: fix an incorrect comments
  controllers/cluster_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2196 Rename v1 to metav1 in imports
  api/v1alpha3/machinedeployment_webhook_test.go
  api/v1alpha3/machineset_webhook_test.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  controllers/cluster_controller_phases_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2089 🏃 [e2e framework] Remove exec calls to kind
  scripts/ci-capd-e2e.sh
  test/e2e/go.mod
  test/e2e/go.sum
  test/framework/go.mod
  test/framework/go.sum
  test/framework/management/kind/mgmt.go
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2175 ✨clusterctl: add godoc and doc
  cmd/clusterctl/cmd/config_cluster.go
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/pkg/client/client.go
  cmd/clusterctl/pkg/client/config.go
  cmd/clusterctl/pkg/client/init.go
  cmd/clusterctl/pkg/client/init_test.go
  cmd/clusterctl/pkg/client/move.go
  docs/book/src/clusterctl/commands/delete.md
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/commands/move.md
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2199 🏃 Make the failure domain test easier to debug
  test/infrastructure/docker/e2e/docker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2204 :book: Add reference/ports link to the summary
  docs/book/src/SUMMARY.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#2197 🏃 Remove capi-e2e tests
  Makefile
  docs/book/src/developer/guide.md
  docs/book/src/developer/tests.md
  scripts/ci-capi-e2e.sh
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2205 ✨ cleanup use controller-runtime utilities for finalizers
  controllers/cluster_controller.go
  controllers/machine_controller.go
  test/infrastructure/docker/controllers/dockercluster_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#2207 🐛 Fix e2e Makefile targets
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2173 ✨ Added extra columns to print in kubectl get with (-o wide)
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2210 :bug: Enable linting of all our go modules
  Makefile
  test/framework/config.go
  test/framework/control_plane.go
  test/framework/management_cluster.go
  test/framework/types.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, size/S

#2215 🐛 Wait for the cluster infra to be ready
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2222 :book: Fix provider activity diagram URLs
  docs/book/src/developer/providers/bootstrap.md
  docs/book/src/developer/providers/cluster-infrastructure.md
  docs/book/src/developer/providers/machine-infrastructure.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, priority/important-soon, size/XS

#2224 🐛 Fix flake in capd
  test/infrastructure/docker/docker/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2216 🐛 clusterctl: Allow pre-release and metadata versions for local repos
  cmd/clusterctl/pkg/client/repository/repository_local_unix.go
  cmd/clusterctl/pkg/client/repository/repository_local_unix_test.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/S

#2154 :bug: Fix cluster name conversions a2 > a3
  api/v1alpha2/conversion.go
  api/v1alpha2/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2212 :sparkles: Refactor external objects & reduce code duplication
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
  controllers/external/tracker.go
  controllers/external/types.go
  controllers/machine_controller.go
  controllers/machine_controller_phases.go
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#2228 :bug: Enqueue request for the right owner in machine controller
  controllers/machine_controller_phases.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2211 🐛clusterctl: fix config provider command
  cmd/clusterctl/cmd/config_provider.go
  cmd/clusterctl/cmd/config_repositories.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/configuration.md
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#2213 :sparkles: Add support for pausing KubeadmControlPlane and its external references
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
  controllers/cluster_controller_phases_test.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go
  controlplane/kubeadm/controllers/kubeadm_control_plane_controller_test.go
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/L

#2229 ✨ Implement failureDomain on machine objects
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2147 📖Document how to verify control-plane is running
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2148 :book: Add initial roadmap draft
  docs/book/src/SUMMARY.md
  docs/book/src/roadmap.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#2161 ✨clusterctl: move shared objects
  cmd/clusterctl/pkg/client/cluster/client.go
  cmd/clusterctl/pkg/client/cluster/mover.go
  cmd/clusterctl/pkg/client/cluster/mover_test.go
  cmd/clusterctl/pkg/client/cluster/objectgraph.go
  cmd/clusterctl/pkg/client/cluster/objectgraph_test.go
  cmd/clusterctl/pkg/internal/test/fake_objects.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XXL

#2220 🐛clusterctl: fix public library inconsistencies
  cmd/clusterctl/pkg/client/client.go
  cmd/clusterctl/pkg/client/client_test.go
  cmd/clusterctl/pkg/client/cluster/client.go
  cmd/clusterctl/pkg/client/config/client.go
  cmd/clusterctl/pkg/client/repository/client.go
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/M

#2134 ✨clusterctl: add upgrader with the upgrade plan logic
  cmd/clusterctl/api/v1alpha3/metadata_type.go
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/pkg/client/cluster/client.go
  cmd/clusterctl/pkg/client/cluster/inventory.go
  cmd/clusterctl/pkg/client/cluster/inventory_managementgroup.go
  cmd/clusterctl/pkg/client/cluster/inventory_managementgroup_test.go
  cmd/clusterctl/pkg/client/cluster/upgrader.go
  cmd/clusterctl/pkg/client/cluster/upgrader_info.go
  cmd/clusterctl/pkg/client/cluster/upgrader_info_test.go
  cmd/clusterctl/pkg/client/cluster/upgrader_test.go
  cmd/clusterctl/pkg/internal/test/fake_repository.go
  docs/book/src/reference/glossary.md
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/XXL
