Repository kubernetes-sigs/cluster-api, pull requests merged in 2020-12, with the labels that each got.

#3966 :bug: Node deletion should check the cause of the error
  controllers/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3668 ✨ Label interruptible nodes
  api/v1alpha4/common_types.go
  controllers/machine_controller.go
  controllers/machine_controller_node_labels.go
  controllers/machine_controller_node_labels_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3941 ⚠️ make clusterctl use v1alpha4 api
  cmd/clusterctl/client/cluster/components.go
  cmd/clusterctl/client/cluster/components_test.go
  cmd/clusterctl/client/cluster/inventory_managementgroup_test.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/client/cluster/template_test.go
  cmd/clusterctl/client/cluster/workload_cluster_test.go
  cmd/clusterctl/client/repository/components.go
  cmd/clusterctl/client/repository/components_client_test.go
  cmd/clusterctl/client/repository/components_test.go
  cmd/clusterctl/client/upgrade_test.go
  cmd/clusterctl/internal/scheme/scheme.go
  cmd/clusterctl/internal/test/fake_objects.go
  cmd/clusterctl/internal/test/fake_proxy.go
  cmd/clusterctl/internal/test/providers/bootstrap/groupversion_info.go
  cmd/clusterctl/internal/test/providers/controlplane/groupversion_info.go
  cmd/clusterctl/internal/test/providers/external/groupversion_info.go
  cmd/clusterctl/internal/test/providers/infrastructure/groupversion_info.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3964 :bug: KCP reconcileEtcdMembers should use its own NodeRefs
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/internal/etcd_client_generator.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
  controlplane/kubeadm/internal/workload_cluster_etcd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3969 :bug: Properly check errors.Cause when checking with apierrors
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  cmd/clusterctl/client/cluster/cert_manager.go
  controllers/cluster_controller_phases.go
  controllers/machine_controller.go
  controllers/machinehealthcheck_targets.go
  controlplane/kubeadm/controllers/helpers.go
  exp/addons/controllers/clusterresourceset_controller.go
  exp/addons/controllers/clusterresourcesetbinding_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  util/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3959 🌱 Remove myself from reviewers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3971 :bug: KCP reconcileEtcdMembers should use its own NodeRefs
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/internal/etcd_client_generator.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
  controlplane/kubeadm/internal/workload_cluster_etcd_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/critical-urgent, size/L

#3972 🌱 Use 1.1 experimental dockerfile image and cache go/pkg/mod
  Dockerfile
  Makefile
  cmd/example-provider/Dockerfile
  docs/Dockerfile
  hack/boilerplate/boilerplate.Dockerfile.txt
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#3960 :book: Relax our backporting guidelines and policies
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3977 :bug: Scale down checks excludes machine about to be deleted
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3984 :bug: [0.3] Scale down checks excludes machine about to be deleted
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
Labels: approved, area/control-plane, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/L

#3981 :seedling: Update Controller Runtime to v0.7.0-alpha.8
  .golangci.yml
  bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go
  bootstrap/kubeadm/main.go
  bootstrap/util/configowner_test.go
  cmd/clusterctl/internal/test/fake_proxy.go
  controllers/cluster_controller_phases_test.go
  controllers/machine_controller_noderef_test.go
  controllers/machinedeployment_controller_test.go
  controllers/machinehealthcheck_targets_test.go
  controllers/machineset_controller_test.go
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_cache_fake.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  controlplane/kubeadm/internal/workload_cluster_etcd_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
  controlplane/kubeadm/main.go
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  exp/addons/controllers/clusterresourceset_helpers_test.go
  exp/controllers/machinepool_controller_noderef_test.go
  go.mod
  go.sum
  main.go
  test/helpers/client.go
  test/helpers/envtest.go
  test/infrastructure/docker/controllers/dockermachine_controller_test.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  util/util.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3948 ✨ Mark specific KCP machines with delete annotation for scaling down
  api/v1alpha4/common_types.go
  controllers/machineset_delete_policy.go
  controllers/machineset_delete_policy_test.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/machine_collection.go
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3990 ⚠️ Remove unused MachinePool deployment strategy
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/machinepool_types.go
  exp/api/v1alpha4/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3946 🐛 Generate etcd client if at least one member is healthy
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/etcd_client_generator.go
  controlplane/kubeadm/internal/etcd_client_generator_test.go
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
  controlplane/kubeadm/internal/workload_cluster_etcd_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3979 🌱 Update util functions for secret generation
  util/kubeconfig/kubeconfig.go
  util/kubeconfig/kubeconfig_test.go
  util/secret/certificates.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3986 :sparkles: Use uncached client and partial metadata for secret and configmaps
  bootstrap/kubeadm/main.go
  controllers/remote/cluster_cache.go
  controlplane/kubeadm/main.go
  exp/addons/controllers/clusterresourceset_controller.go
  exp/addons/controllers/suite_test.go
  go.mod
  go.sum
  main.go
  test/framework/convenience.go
  test/helpers/envtest.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4001 ✨ gcp: add capg to clusterctl providers list
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/cmd/config_repositories.go
  cmd/clusterctl/cmd/config_repositories_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4000 ⚠️ Remove deprecated Bootstrap Data
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/machine_types.go
  api/v1alpha4/machine_webhook_test.go
  api/v1alpha4/zz_generated.deepcopy.go
  bootstrap/kubeadm/api/v1alpha3/conversion.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha4/kubeadmbootstrapconfig_types.go
  bootstrap/kubeadm/api/v1alpha4/zz_generated.deepcopy.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  controllers/cluster_controller_test.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/machinehealthcheck_targets_test.go
  docs/book/src/developer/architecture/controllers/machine.md
  docs/book/src/images/bootstrap-controller.plantuml
  docs/book/src/images/bootstrap-controller.png
  exp/api/v1alpha4/machinepool_webhook_test.go
  exp/controllers/machinepool_controller_phases.go
  exp/controllers/machinepool_controller_phases_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3999 🐛 MHC sort mhc status targets to avoid status keep changing
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_status_matcher_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4008 Cherry-Pick gcp: add capg to clusterctl providers list
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/cmd/config_repositories.go
  cmd/clusterctl/cmd/config_repositories_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3992 ⚠️ Remove the example provider
  Makefile
  cmd/example-provider/Dockerfile
  cmd/example-provider/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3998 🐛 MHC sort mhc status targets to avoid status keep changing
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_status_matcher.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4009 🌱 Move ncdc to emeritus
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#4010 🌱 Move ncdc to emeritus
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#4021 :book: Update notes link due to VMware GSuite migration
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4018 📖 Add envsubst as prerequisite in developer guide
  docs/book/src/developer/guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4019 ✨ Mark specific KCP machines with delete annotation for scaling down
  api/v1alpha3/common_types.go
  controllers/machineset_delete_policy.go
  controllers/machineset_delete_policy_test.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/machine_collection.go
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4002 ⚠️ Use Kind's default network in CAPD
  docs/book/src/developer/testing.md
  docs/book/src/user/quick-start.md
  scripts/ci-e2e.sh
  test/infrastructure/docker/docker/kind_manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4003 📖 Add MachinePool controller architecture docs
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  docs/book/src/SUMMARY.md
  docs/book/src/developer/architecture/controllers/machine-pool.md
  docs/book/src/images/cluster-admission-machinepool-controller.plantuml
  docs/book/src/images/cluster-admission-machinepool-controller.png
  docs/book/src/tasks/experimental-features/machine-pools.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3434 🐛 Include machines in deleting status when calculate machineset replicas
  controllers/machineset_controller.go
  controllers/machineset_controller_test.go
  controllers/mdutil/util.go
  controllers/mdutil/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3799 🐛 Indicate in KCP conditions, when template cloning fails
  controlplane/kubeadm/api/v1alpha4/condition_consts.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/helpers.go
  controlplane/kubeadm/controllers/helpers_test.go
  controlplane/kubeadm/controllers/status.go
  controlplane/kubeadm/controllers/status_test.go
  util/conditions/getter_test.go
  util/conditions/matchers.go
  util/conditions/merge_test.go
  util/conditions/setter_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3811 🌱 Add Kubernetes conformance E2E test
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1alpha3/bases/cluster-with-kcp.yaml
  test/e2e/data/kubetest/conformance-fast.yaml
  test/e2e/data/kubetest/conformance.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/k8s_conformance.go
  test/e2e/k8s_conformance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3838 ✨ Add command and client for `clusterctl alpha rollout restart`
  cmd/clusterctl/client/alpha/client.go
  cmd/clusterctl/client/alpha/rollout.go
  cmd/clusterctl/client/alpha/rollout_restarter.go
  cmd/clusterctl/client/alpha/rollout_restarter_test.go
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/rollout.go
  cmd/clusterctl/client/rollout_test.go
  cmd/clusterctl/cmd/alpha.go
  cmd/clusterctl/cmd/rollout.go
  cmd/clusterctl/cmd/rollout/restart.go
  cmd/clusterctl/internal/util/resource_tuples.go
  cmd/clusterctl/internal/util/resource_tuples_test.go
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#3995 🌱Remove deprecated fake.NewFakeClient and fake.NewFakeClientWithScheme
  .golangci.yml
  controllers/cluster_controller_phases_test.go
  controllers/cluster_controller_test.go
  controllers/external/util_test.go
  controllers/machine_controller_noderef_test.go
  controllers/machine_controller_phases_test.go
  controllers/machine_helpers_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_targets_test.go
  controllers/machineset_controller_test.go
  controllers/remote/cluster_test.go
  exp/controllers/machinepool_controller_noderef_test.go
  exp/controllers/machinepool_controller_phases_test.go
  util/kubeconfig/kubeconfig_test.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3818 🌱 Add e2e test for node drain timeout feature
  test/e2e/Makefile
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-node-drain/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-node-drain/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-node-drain/md.yaml
  test/e2e/node_drain_timeout.go
  test/e2e/node_drain_timeout_test.go
  test/framework/clusterresourceset_helpers.go
  test/framework/control_plane.go
  test/framework/controlplane_helpers.go
  test/framework/deployment_helpers.go
  test/framework/machinedeployment_helpers.go
  test/framework/machinehealthcheck_helpers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4017 🌱 Collect pods logs from workload clusters in E2E tests
  test/framework/docker_logcollector.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
