Repository kubernetes-sigs/cluster-api, pull requests merged in 2021-02, with the labels that each got.

#4125 ⚠️ add result parameter to ApplyClusterTemplateAndWait
  test/e2e/common.go
  test/e2e/k8s_conformance.go
  test/e2e/kcp_upgrade.go
  test/e2e/machine_pool.go
  test/e2e/md_upgrades.go
  test/e2e/mhc_remediations.go
  test/e2e/node_drain_timeout.go
  test/e2e/quick_start.go
  test/e2e/self_hosted.go
  test/framework/clusterctl/clusterctl_helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4109 ⚠️ Updates controller-runtime version to v0.8.1
  Makefile
  cmd/clusterctl/client/cluster/inventory_managementgroup_test.go
  cmd/clusterctl/client/cluster/inventory_test.go
  cmd/clusterctl/internal/test/fake_proxy.go
  controllers/external/util_test.go
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  exp/addons/api/v1alpha3/zz_generated.conversion.go
  exp/addons/api/v1alpha3/zz_generated.deepcopy.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/exp/api/v1alpha3/dockermachinepool_types.go
  test/infrastructure/docker/exp/api/v1alpha3/zz_generated.conversion.go
  test/infrastructure/docker/exp/api/v1alpha3/zz_generated.deepcopy.go
  test/infrastructure/docker/exp/api/v1alpha4/dockermachinepool_types.go
  test/infrastructure/docker/exp/api/v1alpha4/zz_generated.deepcopy.go
  test/infrastructure/docker/exp/docker/nodepool.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.sum
  util/kubeconfig/kubeconfig_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4129 🐛Fix ClusterResourceSet not getting Secret/Configmap TypeMeta
  exp/addons/controllers/clusterresourceset_controller.go
  exp/addons/controllers/clusterresourceset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4141 🌱 Update Go to v1.15.7
  Dockerfile
  Makefile
  Tiltfile
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#4142 🐛 Fix ClusterResourceSet not getting Secret/Configmap TypeMeta
  exp/addons/controllers/clusterresourceset_controller.go
  exp/addons/controllers/clusterresourceset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4054 ✨ clusterctl alpha rollout pause/resume for MachineDeployments
  cmd/clusterctl/client/alpha/rollout.go
  cmd/clusterctl/client/alpha/rollout_pauser.go
  cmd/clusterctl/client/alpha/rollout_pauser_test.go
  cmd/clusterctl/client/alpha/rollout_restarter.go
  cmd/clusterctl/client/alpha/rollout_resumer.go
  cmd/clusterctl/client/alpha/rollout_resumer_test.go
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/rollout.go
  cmd/clusterctl/client/rollout_test.go
  cmd/clusterctl/cmd/rollout.go
  cmd/clusterctl/cmd/rollout/pause.go
  cmd/clusterctl/cmd/rollout/restart.go
  cmd/clusterctl/cmd/rollout/resume.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#4104 🌱 Switch KCP to use ClusterCacheTracker.GetClient for the workload cluster
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4144 📖 Update mdbook to 0.4.5 to fix CVE-2020-26297
  docs/book/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4140 :seedling: Use debian-based container for CAPD
  test/infrastructure/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4107 🌱 Migrate gcr.io/kubernetes-ci-images to gcr.io/k8s-staging-ci-images
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/v1beta1/types.go
  bootstrap/kubeadm/types/v1beta2/types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  test/framework/kubetest/run.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4143 🌱 Migrate gcr.io/kubernetes-ci-images to gcr.io/k8s-staging-ci-images
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/v1beta1/types.go
  bootstrap/kubeadm/types/v1beta2/types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh
  test/framework/kubernetesversions/zz_generated.bindata.go
  test/framework/kubetest/run.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3929 ⚠️ Remove RequeueAfterError
  controllers/machine_controller.go
  controllers/machine_controller_phases.go
  controllers/machine_controller_phases_test.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/helpers.go
  controlplane/kubeadm/controllers/helpers_test.go
  errors/controllers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4101 🌱 Release daily builds and manifests to staging bucket
  Makefile
  cloudbuild-nightly.yaml
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#4149 :seedling: Remove verbose log line from CRS controller
  exp/addons/controllers/clusterresourceset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4150 :seedling: Remove verbose log line from CRS controller
  exp/addons/controllers/clusterresourceset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4013 ⚠️ Upgrade cert-manager to v1.1.0
  Tiltfile
  bootstrap/kubeadm/config/certmanager/certificate.yaml
  bootstrap/kubeadm/config/default/kustomization.yaml
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/client/config/imagemeta_client_test.go
  cmd/clusterctl/client/upgrade_test.go
  cmd/clusterctl/config/assets/cert-manager-test-resources.yaml
  cmd/clusterctl/config/assets/cert-manager.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
  config/certmanager/certificate.yaml
  config/default/kustomization.yaml
  controlplane/kubeadm/config/certmanager/certificate.yaml
  controlplane/kubeadm/config/default/kustomization.yaml
  docs/book/src/clusterctl/configuration.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
  test/infrastructure/docker/config/certmanager/certificate.yaml
  test/infrastructure/docker/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4113 ⚠️ clusterctl completion zsh: Use native zsh completion
  cmd/clusterctl/cmd/completion.go
  docs/book/src/clusterctl/commands/completion.md
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4157 :bug: Book pre-requisites should all use realpath
  docs/book/Makefile
  docs/book/util-embed.sh
  docs/book/util-releaselink.sh
  docs/book/util-tabulate.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#4158 :bug: Book pre-requisites should all use realpath
  docs/book/Makefile
  docs/book/util-embed.sh
  docs/book/util-releaselink.sh
  docs/book/util-tabulate.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#4153 📖 add a cluster autoscaler page to the book
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/cluster-autoscaler.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4119 ⚠️ Add watch label to allow multiple manager instances
  api/v1alpha4/common_types.go
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machinehealthcheck_controller.go
  controllers/machineset_controller.go
  docs/book/src/developer/architecture/controllers/support-multiple-instances.md
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  exp/addons/controllers/clusterresourceset_controller.go
  exp/addons/controllers/clusterresourcesetbinding_controller.go
  exp/controllers/machinepool_controller.go
  main.go
  util/labels/helpers.go
  util/labels/helpers_test.go
  util/predicates/generic_predicates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4163 🌱 Clean up kube version parsing
  api/v1alpha4/machine_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  exp/api/v1alpha3/conversion.go
  util/util.go
  util/util_test.go
  util/version/version.go
  util/version/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4152 :seedling: Use a debian based container for CAPD
  test/infrastructure/docker/Dockerfile
Labels: approved, area/dependency, cncf-cla: yes, lgtm, size/XS

#4173 :seedling: Update controller runtime to v0.8.2
  go.mod
  go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#4169 🌱 Make clusterctl completion zsh work with sourcing
  cmd/clusterctl/cmd/completion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4167 🌱 Include metadata for the CAPI releases
  Makefile
  cmd/clusterctl/hack/create-local-repository.py
  metadata.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4175 🐛 Fix nil pointer dereference
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4164 🌱 Use openAPI scheme for defaulting replicas
  api/v1alpha4/machinedeployment_types.go
  api/v1alpha4/machinedeployment_webhook.go
  api/v1alpha4/machinedeployment_webhook_test.go
  api/v1alpha4/machineset_types.go
  api/v1alpha4/machineset_webhook.go
  api/v1alpha4/machineset_webhook_test.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controllers/schema_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4160 🌱 refactor failure domains logic out of controlplane internal package
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/remediation_test.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/controllers/status.go
  controlplane/kubeadm/controllers/upgrade.go
  controlplane/kubeadm/controllers/upgrade_test.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/control_plane_test.go
  controlplane/kubeadm/internal/filters.go
  controlplane/kubeadm/internal/filters_test.go
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
  util/collections/machine_collection.go
  util/collections/machine_collection_test.go
  util/collections/machine_filters.go
  util/collections/machine_filters_test.go
  util/failuredomains/failure_domains.go
  util/failuredomains/failure_domains_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4189 📖 docs: change to clusterctl instead of kubectl
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4188 :book: update quickstart doc
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4168 ✨ Add support to skip Machine remediation, and respect paused Machines in MHC
  api/v1alpha4/common_types.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_targets.go
  controllers/machinehealthcheck_targets_test.go
  docs/book/src/tasks/healthcheck.md
  util/annotations/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4148 🌱 add possibility to specify webhook cert dir
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  main.go
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4186 🐛 Fix ObjectTracker to allow retry on error
  controllers/external/tracker.go
  controllers/external/tracker_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4204 🌱 Align kubeadm types
  bootstrap/kubeadm/types/v1beta2/groupversion_info.go
  bootstrap/kubeadm/types/v1beta2/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4211 🌱 Restore Fuzzer tests
  api/v1alpha3/conversion_test.go
  bootstrap/kubeadm/api/v1alpha3/conversion_test.go
  util/conversion/conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4214 🌱 Switch published artifacts to k8s.gcr.io
  Makefile
  cmd/clusterctl/client/init_test.go
  docs/Makefile
  docs/developer/releasing.md
  test/framework/kubetest/run.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4208 🐛 Fix docker machine pool status update
  test/infrastructure/docker/exp/docker/nodepool.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4212 ⚠️ Add GVK object validation to patch helper
  util/patch/patch.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4187 🌱 Remove verbose flag from make test
  Makefile
  scripts/ci-test.sh
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4215 📖 some minor fixes for the v1alpha4 migration doc
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4228 📖 Update MHC documentation
  docs/book/src/tasks/healthcheck.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4231 📖 Backport MHC documentation to release-0.3
  docs/book/src/tasks/healthcheck.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
