Repository kubernetes-sigs/cluster-api, pull requests merged in 2021-07, with the labels that each got.

#4881 🌱 Remove dependabot.yml
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4882 :seedling: Update dependencies for July 2021
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#4883 :bug: Ensure /finalizer permissions for OwnerReferencesPermissionEnforcement admission controller
  Makefile
  bootstrap/kubeadm/config/rbac/role.yaml
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  config/rbac/role.yaml
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machinehealthcheck_controller.go
  controllers/machineset_controller.go
  exp/addons/controllers/clusterresourceset_controller.go
  exp/controllers/machinepool_controller.go
  test/infrastructure/docker/config/rbac/role.yaml
  test/infrastructure/docker/controllers/dockercluster_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/exp/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/exp/controllers/exp.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4884 ⚠️ generate capk kubadm config files under /run/kubeadm/ instead of /tmp
  bootstrap/kubeadm/internal/cloudinit/cloudinit.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_init.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_join.go
  bootstrap/kubeadm/internal/cloudinit/kubeadm-bootstrap-script.sh
  bootstrap/kubeadm/internal/cloudinit/node.go
  bootstrap/kubeadm/internal/cloudinit/zz_generated.bindata.go
  test/infrastructure/docker/cloudinit/kindadapter_test.go
  test/infrastructure/docker/cloudinit/runcmd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4678 📖 Proposal for ClusterClass & managed topologies
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
  docs/proposals/images/cluster-class/create.plantuml
  docs/proposals/images/cluster-class/create.png
  docs/proposals/images/cluster-class/update.plantuml
  docs/proposals/images/cluster-class/update.png
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4890 🐛 fix metric collection in e2e test
  bootstrap/kubeadm/config/manager/manager.yaml
  config/manager/manager.yaml
  controlplane/kubeadm/config/manager/manager.yaml
  test/e2e/config/docker.yaml
  test/infrastructure/docker/config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4892 📖 Update quickstart clusterctl install instructions to v0.4
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4894 🐛 fix golangci-lint nolint:ifshort
  controllers/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4911 🐛 e2e tests: fix fix-kubeconfig for mac
  test/framework/cluster_proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4898 📖 improve quickstart documentation
  docs/book/src/clusterctl/developers.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4920 🐛 Fix the observedGeneration update
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4921 📖 Add capz identity instructions to quick start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4923 🐛 clusterctl: use newest release series of same contract
  cmd/clusterctl/api/v1alpha3/metadata_type.go
  cmd/clusterctl/api/v1alpha3/metadata_type_test.go
  cmd/clusterctl/client/repository/repository_github_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4912 🐛 clusterctl: use newest release series of same contract
  cmd/clusterctl/api/v1alpha3/metadata_type.go
  cmd/clusterctl/api/v1alpha3/metadata_type_test.go
  cmd/clusterctl/client/repository/repository_github_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4925 :book: Add back base64 encoded CAPZ quickstart variables for creds
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4924 🐛 fix DefaultValidateTest ensuring old object gets defaulted too
  util/defaulting/defaulting.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4420 🌱 test/framework: improve the way we inject the ci-artifacts script
  test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl
  test/framework/kubernetesversions/data/kustomization.yaml
  test/framework/kubernetesversions/template.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4413 ✨ Use docker API instead of exec'ing docker cmds
  Tiltfile
  test/framework/docker_logcollector.go
  test/infrastructure/container/docker.go
  test/infrastructure/container/interface.go
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
  test/infrastructure/docker/docker/kind_manager.go
  test/infrastructure/docker/docker/loadbalancer.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/docker/types/node.go
  test/infrastructure/docker/docker/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#4907 🌱 Upgrade quickstart and e2e tests to Kubernetes v1.21.2
  docs/book/src/user/quick-start.md
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/framework/machine_helpers.go
  test/infrastructure/container/docker.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4808 ✨ Implements Backup and Restore for objectMover
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/client/move.go
  cmd/clusterctl/client/move_test.go
  cmd/clusterctl/cmd/backup.go
  cmd/clusterctl/cmd/restore.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#4918 📖 Add detail about ClusterClass reconciliation in ClusterClass proposal
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4942 :bug: Webhook registration should accept both v1 and v1beta1 admissions
  api/v1alpha4/cluster_webhook.go
  api/v1alpha4/machine_webhook.go
  api/v1alpha4/machinedeployment_webhook.go
  api/v1alpha4/machinehealthcheck_webhook.go
  api/v1alpha4/machineset_webhook.go
  bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_webhook.go
  bootstrap/kubeadm/config/webhook/manifests.yaml
  config/webhook/manifests.yaml
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/config/webhook/manifests.yaml
  exp/addons/api/v1alpha4/clusterresourceset_webhook.go
  exp/api/v1alpha4/machinepool_webhook.go
  test/infrastructure/docker/api/v1alpha4/dockermachinetemplate_webhook.go
  test/infrastructure/docker/config/webhook/manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4899 📖 Document test matrix in the book
  CONTRIBUTING.md
  docs/book/src/SUMMARY.md
  docs/book/src/reference/jobs.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4944 🐛 validate namespace of MHC remediation template
  api/v1alpha4/machinehealthcheck_webhook.go
  api/v1alpha4/machinehealthcheck_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4893 📖 Fix incorrect indents
  docs/proposals/20200220-cluster-resource-set.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4919 🐛 Move operator API to v1alpha1
  exp/operator/PROJECT
  exp/operator/api/v1alpha1/bootstrapprovider_types.go
  exp/operator/api/v1alpha1/conditions_consts.go
  exp/operator/api/v1alpha1/controlplaneprovider_types.go
  exp/operator/api/v1alpha1/coreprovider_types.go
  exp/operator/api/v1alpha1/groupversion_info.go
  exp/operator/api/v1alpha1/infrastructureprovider_types.go
  exp/operator/api/v1alpha1/provider_types.go
  exp/operator/api/v1alpha1/zz_generated.deepcopy.go
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  exp/operator/controllers/genericprovider/bootstrapprovider_wrapper.go
  exp/operator/controllers/genericprovider/controlplaneprovider_wrapper.go
  exp/operator/controllers/genericprovider/coreprovider_wrapper.go
  exp/operator/controllers/genericprovider/genericprovider_interfaces.go
  exp/operator/controllers/genericprovider/infrastructureprovider_wrapper.go
  exp/operator/controllers/genericprovider_controller.go
  exp/operator/controllers/genericprovider_controller_test.go
  exp/operator/controllers/preflight_checks.go
  exp/operator/controllers/preflight_checks_test.go
  exp/operator/controllers/suite_test.go
  exp/operator/main.go
  exp/operator/util/util.go
  test/helpers/envtest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4895 🐛 fix unhandled errors
  .golangci.yml
  cmd/clusterctl/client/config/reader_viper_test.go
  cmd/clusterctl/cmd/config_provider.go
  cmd/clusterctl/cmd/config_repositories.go
  cmd/clusterctl/cmd/generate_yaml_test.go
  cmd/clusterctl/cmd/upgrade_plan.go
  cmd/clusterctl/cmd/util.go
  cmd/clusterctl/cmd/version_checker_test.go
  controllers/machinedeployment_sync.go
  controllers/mdutil/util.go
  controllers/remote/cluster_cache_healthcheck_test.go
  internal/envtest/environment.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4625 ✨ Adds `AvailableCondition` and `ReadyCondition` Conditions to MachineDeployment
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/condition_consts.go
  api/v1alpha4/machinedeployment_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_controller_test.go
  controllers/machinedeployment_sync.go
  controllers/machinedeployment_sync_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4937 🐛 update CoreDNS ClusterRole for Kubernetes >= 1.22 and CoreDNS >= 1.8.1
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  test/infrastructure/container/docker.go
  test/infrastructure/container/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4952 🐛 fix KCP ClusterRole aggregation
  controlplane/kubeadm/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4955 📖 Fixes incorrect diagram links for CC proposal
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4958 🌱 Use dl.k8s.io instead of hardcoded GCS URIs
  docs/book/src/developer/providers/implementers-guide/overview.md
  hack/ensure-kubectl.sh
  scripts/ci-e2e-lib.sh
  test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl
  test/framework/kubernetesversions/versions.go
  test/infrastructure/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#4964 ✨ Switch to non-alpine kindest/haproxy version
  test/infrastructure/docker/third_party/forked/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4957 🐛 cherry-pick: update CoreDNS ClusterRole (Kubernetes>=1.22,CoreDNS >= 1.8.1)
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  util/version/version.go
  util/version/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4929 🐛 Missing watch label to allow multiple manager instances
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/main.go
  controllers/remote/cluster_cache_reconciler.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/main.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4521 🌱 Add providerID index to get nodes
  controllers/machine_controller_noderef.go
  controllers/machine_controller_noderef_test.go
  controllers/noderefutil/indexer.go
  controllers/noderefutil/providerid.go
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controllers/remote/cluster_cache_tracker_test.go
  controllers/suite_test.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/main.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4928 ⚠️ Add ClusterClass types
  PROJECT
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/cluster_types.go
  api/v1alpha4/cluster_webhook.go
  api/v1alpha4/cluster_webhook_test.go
  api/v1alpha4/clusterclass_types.go
  api/v1alpha4/clusterclass_webhook.go
  api/v1alpha4/clusterclass_webhook_test.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clusterclasses.yaml
  config/crd/patches/webhook_in_clusterclasses.yaml
  config/manager/manager.yaml
  config/webhook/manifests.yaml
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
  feature/feature.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4968 🌱 Switch to non-alpine kindest/haproxy version
  test/infrastructure/docker/third_party/forked/loadbalancer/const.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4976 🌱 Adds topology check to cluster controller
  controllers/cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4977 📖 Update links for kustomize installation
  docs/book/src/developer/guide.md
  docs/book/src/developer/providers/implementers-guide/overview.md
  docs/book/src/developer/tilt.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4987 :seedling: Update Controller Runtime v0.9.3
  Tiltfile
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#4990 ✨ upgrade cert-manager to v1.4.0
  Tiltfile
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/commands/upgrade.md
  docs/book/src/clusterctl/configuration.md
  docs/book/src/developer/guide.md
  docs/book/src/user/quick-start.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4995 🌱 upgrade clusterctl used for e2e test upgrade tests to v0.3.22
  test/e2e/config/docker.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4975 :book: Update how we generate release notes
  Makefile
  docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4965 ✨Add ClusterTopologyController scaffolding
  config/rbac/role.yaml
  controllers/clustertopology_controller.go
  controllers/clustertopology_controller_compute.go
  controllers/clustertopology_controller_sync.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4947 🐛 Drop aggressive requeue=true and find machines to nodes by providerID
  api/v1alpha4/common_types.go
  controllers/machine_controller.go
  controllers/machine_controller_noderef.go
  controllers/noderefutil/indexer.go
  controllers/noderefutil/indexer_test.go
  controllers/suite_test.go
  exp/addons/controllers/suite_test.go
  exp/controllers/suite_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4903 ✨ CAPD: add DockerClusterTemplate type
  test/infrastructure/docker/PROJECT
  test/infrastructure/docker/api/v1alpha4/dockercluster_webhook.go
  test/infrastructure/docker/api/v1alpha4/dockerclustertemplate_types.go
  test/infrastructure/docker/api/v1alpha4/dockerclustertemplate_webhook.go
  test/infrastructure/docker/api/v1alpha4/dockermachinetemplate_webhook.go
  test/infrastructure/docker/api/v1alpha4/zz_generated.deepcopy.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/kustomization.yaml
  test/infrastructure/docker/config/crd/patches/cainjection_in_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockerclustertemplates.yaml
  test/infrastructure/docker/config/default/webhookcainjection_patch.yaml
  test/infrastructure/docker/config/webhook/manifests.yaml
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5009 🐛 cherry pick pin cgroupDriver to cgroupfs in CAPD
  test/e2e/data/infrastructure-docker/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/bases/md.yaml
  test/e2e/data/infrastructure-docker/bases/mp.yaml
  test/e2e/data/infrastructure-docker/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
  test/infrastructure/docker/templates/cluster-template-development.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4997 🐛 Surface etcd node check error in KCP
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5000 🌱 Align ClusterClass ControlPlane with the rest of the fields
  api/v1alpha4/clusterclass_types.go
  api/v1alpha4/clusterclass_webhook_test.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#4989 ✨ add webhook readiness and health check
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  main.go
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4986 🌱 Add test utils for cluster class
  controllers/clustertopology_controller_compute.go
  controllers/clustertopology_controller_compute_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4904 ✨ KCP: add KubeadmControlPlaneTemplate type
  controlplane/kubeadm/PROJECT
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadmcontrolplanetemplate_types.go
  controlplane/kubeadm/api/v1alpha4/kubeadmcontrolplanetemplate_webhook.go
  controlplane/kubeadm/api/v1alpha4/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  controlplane/kubeadm/config/crd/kustomization.yaml
  controlplane/kubeadm/config/crd/patches/cainjection_in_kubeadmcontrolplanetemplates.yaml
  controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanetemplates.yaml
  controlplane/kubeadm/config/webhook/manifests.yaml
  controlplane/kubeadm/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4949 🌱 Extend the ControlPlane contract defining version and infrastructure machine fields for ClusterClass compat
  docs/book/src/developer/architecture/controllers/control-plane.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4993 🌱 Make Cluster.spec.topology.controlPlane.replicas optional
  api/v1alpha4/cluster_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5023 🌱 Upgrade mdbook to v0.4.11
  docs/book/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5021 ✨ CAPD: set container restartPolicy to unless-stopped
  test/infrastructure/container/docker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5017 🌱 explicitly ignore command injection (in tests)
  .golangci.yml
  test/framework/clusterctl/client.go
  test/framework/docker_logcollector.go
  test/framework/kubernetesversions/template.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5028 🌱 Update Controller Runtime to v0.9.5
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
  test/infrastructure/docker/config/crd/bases/exp.infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4961 🌱 Randomly generated namespace in controlplane pkg tests
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/helpers_test.go
  controlplane/kubeadm/controllers/remediation_test.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/controllers/status_test.go
  controlplane/kubeadm/controllers/upgrade_test.go
  controlplane/kubeadm/internal/cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4960 🌱 Randomly generated namespace in bootstrap pkg tests
  bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_types_test.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_reconciler_test.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  bootstrap/util/configowner_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4962 🌱 Randomly generated namespace in exp pkg tests
  exp/addons/controllers/clusterresourceset_controller_test.go
  exp/addons/controllers/clusterresourceset_helpers_test.go
  exp/controllers/machinepool_controller_phases_test.go
  exp/controllers/machinepool_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4963 🌱 Randomly generated namespace in util pkg tests
  util/patch/patch_test.go
  util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4984 ✨ v0.3.x: block clusterctl init and move on Kubernetes v1.22
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/proxy.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/client/move.go
  cmd/clusterctl/internal/test/fake_proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5012 📖 update supported Kubernetes versions
  docs/book/src/reference/versions.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5033 🌱 KCP: stop caching ConfigMap, Secret, Pod, Deployment and DaemonSet of workload clusters
  controlplane/kubeadm/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5013 ✨ v0.3.x: KCP: block mgmt cluster updates to v1.22.0
  controlplane/kubeadm/controllers/upgrade.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4959 🌱 Randomly generated namespace in controllers pkg tests
  controllers/cluster_controller_test.go
  controllers/external/util_test.go
  controllers/machine_controller_node_labels_test.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/machinedeployment_controller_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machineset_controller_test.go
  controllers/mdutil/util_test.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controllers/remote/cluster_cache_reconciler_test.go
  controllers/remote/cluster_cache_tracker_test.go
  controllers/remote/cluster_test.go
  controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#5014 🐛 Fix webhook service references when the namespace is changed
  cmd/clusterctl/client/repository/components.go
  cmd/clusterctl/client/repository/components_test.go
  cmd/clusterctl/client/repository/template.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5039 📖 update generate cluster link
  docs/book/src/clusterctl/overview.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
