Repository kubernetes-sigs/cluster-api, pull requests merged in 2021-04, with the labels that each got.

#4402 📖 Add a warning that only CoreDNS is supported in KCP
  docs/book/src/tasks/kubeadm-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#4424 🌱 Fix typo
  Dockerfile
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4398 🌱 [capd] Ensure Loadbalancer IP is not empty
  test/infrastructure/docker/docker/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4317 🐛 Cleanup recent work with `clusterctl alpha rollout` command
  cmd/clusterctl/client/alpha/client.go
  cmd/clusterctl/client/alpha/machinedeployment.go
  cmd/clusterctl/client/alpha/rollout.go
  cmd/clusterctl/client/alpha/rollout_pauser.go
  cmd/clusterctl/client/alpha/rollout_pauser_test.go
  cmd/clusterctl/client/alpha/rollout_restarter.go
  cmd/clusterctl/client/alpha/rollout_restarter_test.go
  cmd/clusterctl/client/alpha/rollout_resumer.go
  cmd/clusterctl/client/alpha/rollout_resumer_test.go
  cmd/clusterctl/client/alpha/rollout_rollbacker.go
  cmd/clusterctl/client/alpha/rollout_rollbacker_test.go
  cmd/clusterctl/client/rollout.go
  cmd/clusterctl/internal/util/obj_refs.go
  cmd/clusterctl/internal/util/obj_refs_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#4414 🌱 gather more Docker and containerd data/logs in ci-e2e.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#4328 📖 Add CAPI book section on `clusterctl alpha rollout`
  docs/book/src/clusterctl/commands/alpha-rollout.md
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/clusterctl/overview.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4425 🌱 Remove duplicate upgrade word
  cmd/clusterctl/cmd/upgrade_plan.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4421 🌱 kcp: include node list error in KCP and control plane machine conditions
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4378 🌱Remove go-bindata
  Makefile
  cmd/clusterctl/client/cluster/inventory.go
  cmd/clusterctl/config/embedded_manifest.go
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  test/framework/kubernetesversions/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4230 ✨ Extra validations for v1alpha3 -> v1alpha4 upgrade
  cmd/clusterctl/client/cluster/components.go
  cmd/clusterctl/client/cluster/components_test.go
  cmd/clusterctl/client/cluster/inventory.go
  cmd/clusterctl/client/cluster/inventory_test.go
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/client/cluster/upgrader_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4431 🌱 upgrade cloudbuild to use gcb-docker-gcloud with go 1.16
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4255 ⚠️ Add CAPI owned kubeadm types
  Makefile
  bootstrap/kubeadm/api/v1alpha3/conversion.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_types.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha4/conversion.go
  bootstrap/kubeadm/api/v1alpha4/kubeadm_types.go
  bootstrap/kubeadm/api/v1alpha4/kubeadm_types_test.go
  bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_types.go
  bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_types_test.go
  bootstrap/kubeadm/api/v1alpha4/zz_generated.deepcopy.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/types/utils.go
  bootstrap/kubeadm/types/utils_test.go
  bootstrap/kubeadm/types/v1beta1/conversion.go
  bootstrap/kubeadm/types/v1beta1/conversion_test.go
  bootstrap/kubeadm/types/v1beta1/doc.go
  bootstrap/kubeadm/types/v1beta1/groupversion_info.go
  bootstrap/kubeadm/types/v1beta1/utils.go
  bootstrap/kubeadm/types/v1beta1/utils_test.go
  bootstrap/kubeadm/types/v1beta1/zz_generated.conversion.go
  bootstrap/kubeadm/types/v1beta2/conversion.go
  bootstrap/kubeadm/types/v1beta2/conversion_test.go
  bootstrap/kubeadm/types/v1beta2/doc.go
  bootstrap/kubeadm/types/v1beta2/groupversion_info.go
  bootstrap/kubeadm/types/v1beta2/zz_generated.conversion.go
  bootstrap/kubeadm/types/v1beta2/zz_generated.deepcopy.go
  controlplane/kubeadm/api/v1alpha3/conversion_test.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/helpers_test.go
  controlplane/kubeadm/internal/filters.go
  controlplane/kubeadm/internal/filters_test.go
  controlplane/kubeadm/internal/kubeadm_config_map.go
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
  test/framework/controlplane_helpers.go
  util/conversion/conversion.go
  util/secret/certificates.go
  util/secret/certificates_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4442 🐛 Make conversion-gen output dir explicit
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4393 🐛 Fix the observedGeneration update
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4432 🌱 capd: print debug infos on container creation error
  cmd/clusterctl/client/cluster/mover.go
  test/infrastructure/docker/docker/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4439 🐛 Fix KCP spec.rolloutStrategy fields to be mutable
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, kind/release-blocking, lgtm, ok-to-test, size/M

#4438 🐛 Fix KCP maxSurge field to be mutable
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4448 🐛 Add validation testing for defaulting
  api/v1alpha4/cluster_webhook_test.go
  api/v1alpha4/machine_webhook_test.go
  api/v1alpha4/machinedeployment_webhook_test.go
  api/v1alpha4/machinehealthcheck_webhook_test.go
  api/v1alpha4/machineset_webhook_test.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
  exp/addons/api/v1alpha4/clusterresourceset_webhook.go
  exp/addons/api/v1alpha4/clusterresourceset_webhook_test.go
  exp/api/v1alpha4/machinepool_webhook_test.go
  util/defaulting/defaulting.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4451 🌱 Removing ginkgo from Kubeadm Controller tests
  controlplane/kubeadm/controllers/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4452 :bug: Adds a test helper to all mutating webhooks to ensure defaulting passes validation (0.3 backport)
  api/v1alpha3/cluster_webhook_test.go
  api/v1alpha3/machine_webhook_test.go
  api/v1alpha3/machinedeployment_webhook_test.go
  api/v1alpha3/machinehealthcheck_webhook_test.go
  api/v1alpha3/machineset_webhook_test.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  exp/addons/api/v1alpha3/clusterresourceset_webhook.go
  exp/addons/api/v1alpha3/clusterresourceset_webhook_test.go
  exp/api/v1alpha3/machinepool_webhook_test.go
  util/defaulting/defaulting.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4453 🐛 capd: do not reconcile machine if cluster or machine is paused
  test/infrastructure/docker/controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4459 📖 Improve project news docs statement
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4465 🐛 Fix Canonical import paths err
  bootstrap/kubeadm/types/v1beta2/doc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4466 🐛 Disable test Observed Generation in KCP
  controlplane/kubeadm/controllers/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4470 🌱 Fix upgrade test (CoreDNS verification)
  test/framework/deployment_helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4460 ✨ Add healthprobe for bootstrap and controlplane
  bootstrap/kubeadm/config/manager/manager.yaml
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/config/manager/manager.yaml
  controlplane/kubeadm/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4455 🌱 include deamonsets in list images in clusterctl
  cmd/clusterctl/internal/util/objs.go
  cmd/clusterctl/internal/util/objs_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4333 📖 Add information on using kustomize with CAPI
  docs/book/src/tasks/using-kustomize.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4427 📖 Link architecture and code walkthrough videos in docs
  docs/book/src/developer/guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4475 🌱Fix linting issues for operator
  exp/operator/api/v1alpha4/bootstrapprovider_types.go
  exp/operator/api/v1alpha4/controlplaneprovider_types.go
  exp/operator/api/v1alpha4/coreprovider_types.go
  exp/operator/api/v1alpha4/groupversion_info.go
  exp/operator/api/v1alpha4/infrastructureprovider_types.go
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  exp/operator/controllers/coreprovider_controller.go
  exp/operator/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4327 📖 Fix figure 1 not found
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4346 ✨ OnDelete rollout strategy
  api/v1alpha4/common_types.go
  api/v1alpha4/machinedeployment_types.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  controllers/machinedeployment_controller.go
  controllers/machinedeployment_rollout_ondelete.go
  controllers/machineset_controller.go
  controllers/mdutil/util.go
  docs/book/src/images/cluster-admission-machinedeployment-controller.plantuml
  docs/book/src/images/cluster-admission-machinedeployment-controller.png
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4476 🐛 Fix CoreDNS upgrade from v1.20 to v1.21
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4480 📖 correct a word
  docs/book/src/clusterctl/commands/upgrade.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4481 🐛 Fix CoreDNS upgrade from v1.20 to v1.21
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4478 🌱 Add fabriziopandini to cluster-api-maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#4487 🌱 Fixes typo in machine types description
  api/v1alpha4/machine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4479 🌱 Add sbueringer to cluster-api-reviewers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4494 🌱 Fix redundant judgment for reterr==nil
  controlplane/kubeadm/controllers/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4492 📖 Move detiber to emeritus status, update security contacts
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#4496 📖 Docs improvement for AWS
  docs/book/src/reference/providers.md
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#4501 📖 Improve links to main Kubernetes docs
  docs/book/src/user/concepts.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4135 📖 CAEP: Add support for infrastructure cluster resources to be managed externally
  docs/proposals/20210203-externally-managed-cluster-infrastructure.md
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, size/L

#4495 🌱 Add unit test coverage for machineDeployments. reconcileNewMachineSet
  controllers/machinedeployment_rolling.go
  controllers/machinedeployment_rolling_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4504 📖 Update Azure Provider Prerequisites link in quick start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4505 🌱 Rename unit test to TestCalculateStatus
  controllers/machinedeployment_sync.go
  controllers/machinedeployment_sync_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4510 🌱correct filenames
  docs/book/src/clusterctl/configuration.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4523 🌱 Fix comment for UpdateImageRepositoryInKubeadmConfigMap
  controlplane/kubeadm/internal/workload_cluster.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#4524 📖 Fix typo in docs/proposals/20191017-kubeadm-based-control-plane.md
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#4511 🐛 Check Strategy is not nil to avoid panic
  controllers/machinedeployment_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4515 🌱 Fix flaky upgrade e2e test
  test/e2e/cluster_upgrade.go
  test/e2e/config/docker.yaml
  test/framework/daemonset_helpers.go
  test/framework/node_helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4530 📖 Fix anchor issue in docs/scope-and-objectives.md
  docs/scope-and-objectives.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4528 📖 Replace ExternalRemdiationTemplate with RemediationTemplate in MHC proposal
  docs/proposals/20191030-machine-health-checking.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4538 🌱 Update Controller Runtime v0.9.0-beta.0 and Tools to v0.6.0-beta.0
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/config/crd/bases/exp.infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, area/dependency, cncf-cla: yes, lgtm, size/XXL

#4539 Update Azure Provider Prerequisites link in quick start
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4540 🌱 Fix comment issue in method `MachineSetToDeployments`
  controllers/machinedeployment_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4529 🌱 use golangci lint v1.38.0
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#4516 ⚠️ remove DNS type from v1alpha4
  bootstrap/kubeadm/api/v1alpha3/conversion.go
  bootstrap/kubeadm/api/v1alpha3/conversion_test.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha4/kubeadm_types.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/v1beta1/conversion.go
  bootstrap/kubeadm/types/v1beta1/conversion_test.go
  bootstrap/kubeadm/types/v1beta1/zz_generated.conversion.go
  bootstrap/kubeadm/types/v1beta2/conversion.go
  bootstrap/kubeadm/types/v1beta2/conversion_test.go
  bootstrap/kubeadm/types/v1beta2/zz_generated.conversion.go
  controlplane/kubeadm/api/v1alpha3/conversion_test.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4544 :seedling: Add a fuzzer function for *metav1.Time
  util/conversion/conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4535 ⚠️ Rename KubeadmControlPlane spec.upgradeAfter to rolloutAfter
  controlplane/kubeadm/api/v1alpha3/conversion.go
  controlplane/kubeadm/api/v1alpha3/zz_generated.conversion.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/api/v1alpha4/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/filters.go
  docs/book/src/tasks/upgrading-clusters.md
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, area/api, cncf-cla: yes, kind/release-blocking, lgtm, size/M

#4545 ⚠️ remove ClusterConfiguration.UseHyperKubeImage from v1alpha4
  bootstrap/kubeadm/api/v1alpha3/conversion.go
  bootstrap/kubeadm/api/v1alpha3/conversion_test.go
  bootstrap/kubeadm/api/v1alpha4/kubeadm_types.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/v1beta1/conversion.go
  bootstrap/kubeadm/types/v1beta1/conversion_test.go
  bootstrap/kubeadm/types/v1beta1/zz_generated.conversion.go
  bootstrap/kubeadm/types/v1beta2/conversion.go
  bootstrap/kubeadm/types/v1beta2/conversion_test.go
  bootstrap/kubeadm/types/v1beta2/zz_generated.conversion.go
  controlplane/kubeadm/api/v1alpha3/conversion_test.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4547 ⚠️ Remove unused DNSAddOnType constants from kubeadm/v1alpha4
  bootstrap/kubeadm/api/v1alpha4/kubeadm_types.go
  controlplane/kubeadm/internal/kubeadm_config_map.go
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4549 🐛 Fix KubeadmControlPlane conversion upgradeAfter <=> rolloutAfter
  controlplane/kubeadm/api/v1alpha3/conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4551 📖 Fix misspelling in some docs files
  docs/book/src/developer/guide.md
  docs/book/src/developer/tilt.md
  docs/book/src/reference/ports.md
  docs/proposals/20181121-machine-api.md
  docs/proposals/20200511-clusterctl-extensible-template-processing.md
  docs/proposals/20200602-machine-deletion-phase-hooks.md
  docs/proposals/20201020-capi-provider-operator.md
  docs/proposals/20210203-externally-managed-cluster-infrastructure.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4550 📖 Fix html tag issue in developer/architecture/controllers/control-plane.md
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/architecture/controllers/support-multiple-instances.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4553 🐛 Allow clusterctl config cluster --from on empty clusters
  cmd/clusterctl/client/config.go
  cmd/clusterctl/client/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4532 ⚠️ Drop usage of GetValueFromIntOrPercent in favour of GetScaledValueFromIntOrPercent
  api/v1alpha4/machinedeployment_webhook.go
  api/v1alpha4/machinedeployment_webhook_test.go
  api/v1alpha4/machinehealthcheck_webhook.go
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  controllers/mdutil/util.go
  controllers/mdutil/util_test.go
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  docs/book/src/tasks/upgrading-clusters.md
Labels: approved, cncf-cla: yes, lgtm, size/L
