Repository kubernetes-sigs/cluster-api, pull requests merged in 2021-03, with the labels that each got.

#4217 🐛 hack: fix semver comparison in ensure-kind
  hack/ensure-kind.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4200 🌱 clusterctl v1alpha4 should not install v1alpha3 providers
  cmd/clusterctl/client/cluster/installer.go
  cmd/clusterctl/client/cluster/installer_test.go
  cmd/clusterctl/client/init_test.go
  cmd/clusterctl/internal/test/contracts.go
  test/e2e/config/docker.yaml
  test/e2e/data/shared/v1alpha4/metadata.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4225 ⚠️ Upgrade cert manager to v1.1.0
  Tiltfile
  bootstrap/kubeadm/config/certmanager/certificate.yaml
  bootstrap/kubeadm/config/webhook/kustomization.yaml
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/client/config/imagemeta_client_test.go
  cmd/clusterctl/client/upgrade_test.go
  cmd/clusterctl/config/assets/cert-manager-test-resources.yaml
  cmd/clusterctl/config/assets/cert-manager.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
  config/certmanager/certificate.yaml
  config/webhook/kustomization.yaml
  controlplane/kubeadm/config/certmanager/certificate.yaml
  controlplane/kubeadm/config/webhook/kustomization.yaml
  docs/book/src/clusterctl/configuration.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e.sh
  test/e2e/config/docker.yaml
  test/infrastructure/docker/config/certmanager/certificate.yaml
  test/infrastructure/docker/config/webhook/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4171 🐛Add check for empty maps in machineset controller
  controllers/machineset_controller.go
  controllers/machineset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4238 :warning: Update controller runtime v0.9 (main) and Go 1.16
  Dockerfile
  Makefile
  Tiltfile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/config/webhook/manifests.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  config/webhook/manifests.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/webhook/manifests.yaml
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/config/crd/bases/exp.infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/config/webhook/manifests.yaml
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
  test/infrastructure/docker/hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4240 🐛 Fix KCP remediation when node Name & etcd member Name != machine Name
  controlplane/kubeadm/controllers/remediation.go
  controlplane/kubeadm/controllers/remediation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4242 🐛 Fix KCP remediation when node Name & etcd member Name != machine Name
  controlplane/kubeadm/controllers/remediation.go
  controlplane/kubeadm/controllers/remediation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4249 🌱 update golangci-lint config to use disable-all/enable
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4251 🐛 Change CI bucket for conformance tests to the non-bazel build
  test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh
  test/framework/kubernetesversions/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4250 🐛Change CI bucket for conformance tests to the non-bazel build
  test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh
  test/framework/kubernetesversions/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4245 ⚠️ Use individual service accounts
  bootstrap/kubeadm/config/manager/manager.yaml
  bootstrap/kubeadm/config/rbac/auth_proxy_role_binding.yaml
  bootstrap/kubeadm/config/rbac/kustomization.yaml
  bootstrap/kubeadm/config/rbac/leader_election_role_binding.yaml
  bootstrap/kubeadm/config/rbac/role_binding.yaml
  bootstrap/kubeadm/config/rbac/service_account.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  controlplane/kubeadm/config/manager/manager.yaml
  controlplane/kubeadm/config/rbac/auth_proxy_role_binding.yaml
  controlplane/kubeadm/config/rbac/kustomization.yaml
  controlplane/kubeadm/config/rbac/leader_election_role_binding.yaml
  controlplane/kubeadm/config/rbac/role_binding.yaml
  controlplane/kubeadm/config/rbac/service_account.yaml
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  test/infrastructure/docker/config/manager/manager.yaml
  test/infrastructure/docker/config/rbac/auth_proxy_role_binding.yaml
  test/infrastructure/docker/config/rbac/kustomization.yaml
  test/infrastructure/docker/config/rbac/leader_election_role_binding.yaml
  test/infrastructure/docker/config/rbac/role_binding.yaml
  test/infrastructure/docker/config/rbac/service_account.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4220 :book: misc fix for developer doc
  docs/book/src/clusterctl/developers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4237 📖 Document policy for workloads on KCP controlled machines
  docs/book/src/tasks/kubeadm-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4267 🌱 Updates conversion error message with reasoning
  util/conversion/conversion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4272 🌱 Update operator to use certmanager v1 resources
  exp/operator/config/certmanager/certificate.yaml
  exp/operator/config/certmanager/kustomization.yaml
  exp/operator/config/certmanager/kustomizeconfig.yaml
Labels: approved, area/operator, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#4202 ⚠️ clusterctl v1alpha4 should not upgrade to v1alpha3 contract
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/client/cluster/upgrader_info.go
  cmd/clusterctl/client/cluster/upgrader_info_test.go
  cmd/clusterctl/client/cluster/upgrader_test.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/client/upgrade_test.go
  cmd/clusterctl/cmd/upgrade_apply.go
  cmd/clusterctl/cmd/upgrade_plan.go
  cmd/clusterctl/internal/test/contracts.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4216 🐛 Fix a panic when getExternalRemediationRequest returns nil
  controllers/machinehealthcheck_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4073 ✨ Add rollout strategy support for KCP
  controlplane/kubeadm/api/v1alpha3/conversion.go
  controlplane/kubeadm/api/v1alpha3/conversion_test.go
  controlplane/kubeadm/api/v1alpha3/zz_generated.conversion.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/api/v1alpha4/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/remediation_test.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/controllers/upgrade.go
  controlplane/kubeadm/controllers/upgrade_test.go
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4280 📖 Document policy for workloads on KCP controlled machines - 0.3 branch
  docs/book/src/tasks/kubeadm-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4277 :bug: Add back tolerations to cert-manager Deployments
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/config/assets/cert-manager.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4128 ✨ Support range of values for unhealthy machines in machine health check spec
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/machinehealthcheck_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  docs/book/src/tasks/healthcheck.md
  docs/proposals/20191030-machine-health-checking.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4274 🌱 Update Cert Manager Tilt module to v1.1.0 as default
  tilt_modules/cert_manager/README.md
  tilt_modules/cert_manager/Tiltfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4213 :seedling: Enable ClusterResourceSet by default
  feature/feature.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4236 ⚠️ Default Kubelet cgroupDriver to systemd for Kubernetes >= 1.21
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/L

#4170 📖 CAEP: Insulate users from kubeadm API version changes
  docs/proposals/20210210-insulate-users-from-kubeadm-API-changes.md
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, size/L

#4161 🌱 Add test for listDescendents fetch MachinePools
  controllers/cluster_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4286 📖 update quickstart doc
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4291 🌱 Delete samples from operator repo
  exp/operator/config/samples/operator_v1alpha4_bootstrapprovider.yaml
  exp/operator/config/samples/operator_v1alpha4_controlplaneprovider.yaml
  exp/operator/config/samples/operator_v1alpha4_coreprovider.yaml
  exp/operator/config/samples/operator_v1alpha4_infrastructureprovider.yaml
Labels: approved, area/operator, cncf-cla: yes, lgtm, size/S

#4290 🌱Remove unnecessary boilerplate in operator
  exp/operator/hack/boilerplate.go.txt
Labels: approved, area/operator, cncf-cla: yes, lgtm, size/S

#3752 ⚠️ MHC: require control plane initialized, cluster infrastructure ready for node startup timeout
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/cluster_types.go
  api/v1alpha4/condition_consts.go
  bootstrap/kubeadm/api/v1alpha3/conversion_test.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  controllers/cluster_controller.go
  controllers/cluster_controller_phases.go
  controllers/cluster_controller_test.go
  controllers/machine_controller.go
  controllers/machine_controller_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machinehealthcheck_targets.go
  controllers/machinehealthcheck_targets_test.go
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controllers/remote/cluster_cache_tracker_test.go
  controlplane/kubeadm/api/v1alpha3/conversion_test.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  util/conversion/conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4295 :bug: Include machinepools in descendant count
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4300 :seedling: fix the typo in error message
  bootstrap/kubeadm/internal/cloudinit/cloudinit.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4299 :bug: Include machinepools in descendant count
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4301 📖 Fix version support doc
  docs/book/src/reference/versions.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4098 ✨ Clusterctl alpha rollout undo for MachineDeployments
  cmd/clusterctl/client/alpha/rollout.go
  cmd/clusterctl/client/alpha/rollout_pauser.go
  cmd/clusterctl/client/alpha/rollout_pauser_test.go
  cmd/clusterctl/client/alpha/rollout_restarter.go
  cmd/clusterctl/client/alpha/rollout_restarter_test.go
  cmd/clusterctl/client/alpha/rollout_resumer.go
  cmd/clusterctl/client/alpha/rollout_resumer_test.go
  cmd/clusterctl/client/alpha/rollout_rollbacker.go
  cmd/clusterctl/client/alpha/rollout_rollbacker_test.go
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/rollout.go
  cmd/clusterctl/client/rollout_test.go
  cmd/clusterctl/cmd/rollout.go
  cmd/clusterctl/cmd/rollout/undo.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#4078 ⚠️ Clean up "deprecated" variables/functions in v1alpha4
  bootstrap/kubeadm/api/v1alpha4/condition_consts.go
  controllers/machinehealthcheck_targets.go
  hack/tools/release/notes.go
  test/helpers/envtest.go
  util/kubeconfig/testing.go
  util/secret/certificates.go
  util/secret/certificates_test.go
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4126 🌱 Add make commands for CAPI operator
  exp/operator/.gitignore
  exp/operator/Dockerfile
  exp/operator/Makefile
  exp/operator/api/v1alpha4/zz_generated.deepcopy.go
  exp/operator/config/default/kustomization.yaml
  exp/operator/config/default/manager_image_patch.yaml
  exp/operator/config/default/manager_pull_policy.yaml
  exp/operator/config/default/manager_webhook_patch.yaml
  exp/operator/config/manager/manager.yaml
  exp/operator/controllers/coreprovider_controller.go
  exp/operator/controllers/suite_test.go
  exp/operator/go.mod
  exp/operator/go.sum
  exp/operator/main.go
Labels: approved, area/operator, cncf-cla: yes, lgtm, size/XXL

#4284 ⚠️ Update klog dependency to v2
  bootstrap/kubeadm/main.go
  controllers/machine_controller.go
  controllers/mdutil/util_test.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/status_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/main.go
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  go.mod
  main.go
  test/helpers/envtest.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/main.go
  util/failuredomains/failure_domains.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#4305 ⚠️ 🐛 Update envsubst to 2.0 to fix escaping of namedpipes
  Makefile
  cmd/clusterctl/client/yamlprocessor/simple_processor.go
  cmd/clusterctl/client/yamlprocessor/simple_processor_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, area/dependency, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#4306 📖 Fix link 404 in 20190610-machine-states-preboot-bootstrapping.md
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4302 🌱 Make RegisterClusterResourceSetConfigMapTransformation to be general (not only for CNI)
  test/framework/clusterctl/repository.go
Labels: approved, area/testing, cncf-cla: yes, lgtm, size/S

#4312 ✨Generate operator manifests
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  exp/operator/config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  exp/operator/config/rbac/role.yaml
Labels: approved, area/operator, cncf-cla: yes, lgtm, size/L

#4313 🌱Remove zap and use klogr in operator
  exp/operator/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4298 🌱Use distroless for CAPD
  test/infrastructure/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#4252 🌱clusterctl v1alpha3 should not install v1alpha4 providers
  cmd/clusterctl/client/cluster/installer.go
  cmd/clusterctl/client/cluster/installer_test.go
  cmd/clusterctl/client/init_test.go
  cmd/clusterctl/internal/test/contracts.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4308 :seedling: Update CR dependencies and Kubernetes 0.21.0-beta.1
  bootstrap/kubeadm/controllers/suite_test.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/remote/suite_test.go
  controllers/suite_test.go
  controlplane/kubeadm/controllers/suite_test.go
  controlplane/kubeadm/internal/suite_test.go
  docs/book/src/developer/testing.md
  exp/addons/controllers/suite_test.go
  exp/controllers/machinepool_controller_test.go
  exp/controllers/suite_test.go
  go.mod
  go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  util/patch/patch.go
  util/patch/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4316 ✨Switch to go test in operator suite test
  exp/operator/controllers/suite_test.go
Labels: approved, area/operator, cncf-cla: yes, lgtm, size/M

#4323 🌱 Use variables in Makefile consistently
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4326 📖 Fix version support doc
  docs/book/src/reference/versions.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4314 ✨Add CI script for running make verify
  scripts/ci-verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#4294 ⚠️ Default Kubelet cgroupDriver to systemd for Kubernetes >= 1.21
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, area/control-plane, cncf-cla: yes, lgtm, size/L

#4292 ✨ [CABPK] Support using kubeadm v1beta2 types internally
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/types/v1beta1/utils.go
  bootstrap/kubeadm/types/v1beta1/utils_test.go
  bootstrap/kubeadm/types/v1beta2/groupversion_info.go
  bootstrap/util/configowner.go
  bootstrap/util/configowner_test.go
  controlplane/kubeadm/internal/kubeadm_config_map.go
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4330 🌱Add leases to leader election role in operator
  exp/operator/config/rbac/leader_election_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4339 🐛 scripts/ci-verify.sh: set executable bit
  scripts/ci-verify.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4331 📖 Quickstart doc update
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4332 🌱 Normalizing flags from _ to -
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  main.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4335 🌱 Sets InfraReady condition for MachinePool for incorrect external reference
  api/v1alpha4/condition_consts.go
  exp/controllers/machinepool_controller_phases.go
  exp/controllers/machinepool_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4348 📖 update MHC docs to comply with current impl.
  docs/book/src/tasks/healthcheck.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4207 🌱 refactor: standardize machine filter functions and improve testing
  controllers/cluster_controller.go
  controllers/machine_controller.go
  controllers/machine_controller_test.go
  controllers/machine_helpers.go
  controllers/machine_helpers_test.go
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/fakes_test.go
  controlplane/kubeadm/controllers/scale.go
  controlplane/kubeadm/controllers/scale_test.go
  controlplane/kubeadm/controllers/status.go
  controlplane/kubeadm/controllers/status_test.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  util/collections/helpers.go
  util/collections/machine_collection.go
  util/collections/machine_filters.go
  util/collections/machine_filters_test.go
  util/conversion/conversion.go
  util/deprecated.go
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4350 :seedling: Remove most of bindata targets in favor of Go 1.16 embed
  Makefile
  bootstrap/kubeadm/internal/cloudinit/cloudinit.go
  bootstrap/kubeadm/internal/cloudinit/zz_generated.bindata.go
  cmd/clusterctl/client/cluster/assets/cert-manager-test-resources.yaml
  cmd/clusterctl/client/cluster/assets/cert-manager.yaml
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/config/zz_generated.bindata.go
  hack/boilerplate/boilerplate.py
  hack/tools/go.mod
  hack/tools/go.sum
  test/framework/kubernetesversions/template.go
  test/infrastructure/docker/config/crd/bases/exp.infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4340 📖 General docs cleanup
  docs/book/src/clusterctl/commands/completion.md
  docs/book/src/clusterctl/commands/config-cluster.md
  docs/book/src/clusterctl/commands/delete.md
  docs/book/src/clusterctl/commands/describe-cluster.md
  docs/book/src/clusterctl/commands/generate-yaml.md
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/commands/move.md
  docs/book/src/clusterctl/configuration.md
  docs/book/src/clusterctl/developers.md
  docs/book/src/clusterctl/overview.md
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/developer/architecture/controllers/cluster.md
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/architecture/controllers/machine-pool.md
  docs/book/src/developer/architecture/controllers/machine-set.md
  docs/book/src/developer/architecture/controllers/machine.md
  docs/book/src/developer/e2e.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
  docs/book/src/developer/providers/implementers-guide/controllers_and_reconciliation.md
  docs/book/src/developer/providers/implementers-guide/create_api.md
  docs/book/src/developer/providers/implementers-guide/generate_crds.md
  docs/book/src/developer/providers/implementers-guide/naming.md
  docs/book/src/developer/providers/implementers-guide/overview.md
  docs/book/src/developer/providers/machine-infrastructure.md
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
  docs/book/src/developer/testing.md
  docs/book/src/developer/tilt.md
  docs/book/src/introduction.md
  docs/book/src/reference/glossary.md
  docs/book/src/reference/ports.md
  docs/book/src/reference/providers.md
  docs/book/src/reference/versions.md
  docs/book/src/roadmap.md
  docs/book/src/tasks/certs/generate-kubeconfig.md
  docs/book/src/tasks/certs/index.md
  docs/book/src/tasks/change-machine-template.md
  docs/book/src/tasks/experimental-features/cluster-resource-set.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  docs/book/src/tasks/experimental-features/machine-pools.md
  docs/book/src/tasks/external-etcd.md
  docs/book/src/tasks/healthcheck.md
  docs/book/src/tasks/index.md
  docs/book/src/tasks/kubeadm-control-plane.md
  docs/book/src/tasks/upgrading-cluster-api-versions.md
  docs/book/src/tasks/upgrading-clusters.md
  docs/book/src/user/concepts.md
  docs/book/src/user/personas.md
  docs/book/src/user/quick-start.md
  docs/book/src/user/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#4285 📖 Document `UpgradeAfter`
  docs/book/src/tasks/upgrading-clusters.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4265 ⚠️ Clustectl v1alpha3 should block on v1alpha4 clusters
  cmd/clusterctl/client/cluster/inventory.go
  cmd/clusterctl/client/cluster/inventory_test.go
  cmd/clusterctl/client/config.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/delete.go
  cmd/clusterctl/client/delete_test.go
  cmd/clusterctl/client/describe.go
  cmd/clusterctl/client/get_kubeconfig.go
  cmd/clusterctl/client/get_kubeconfig_test.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/client/move.go
  cmd/clusterctl/client/move_test.go
  cmd/clusterctl/client/repository/metadata_client_test.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/client/upgrade_test.go
  cmd/clusterctl/internal/test/contracts.go
  cmd/clusterctl/internal/test/fake_proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4199 ⚠️ clustectl v1alpha4 should block when used with v1alpha3 management clusters
  cmd/clusterctl/client/cluster/inventory.go
  cmd/clusterctl/client/cluster/inventory_test.go
  cmd/clusterctl/client/config.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/delete.go
  cmd/clusterctl/client/delete_test.go
  cmd/clusterctl/client/describe.go
  cmd/clusterctl/client/get_kubeconfig.go
  cmd/clusterctl/client/get_kubeconfig_test.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/client/move.go
  cmd/clusterctl/client/move_test.go
  cmd/clusterctl/client/repository/metadata_client_test.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/client/upgrade_test.go
  cmd/clusterctl/internal/test/fake_proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4353 🌱 Update CR v0.9.0-alpha.0 and golint 1.32 dependencies
  .golangci.yml
  api/v1alpha3/machine_types.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/types/v1beta1/bootstraptokenstring.go
  bootstrap/kubeadm/types/v1beta1/utils.go
  bootstrap/kubeadm/types/v1beta2/bootstraptokenstring.go
  bootstrap/kubeadm/types/v1beta2/types.go
  cmd/clusterctl/client/cluster/template.go
  cmd/clusterctl/client/cluster/template_test.go
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
  cmd/clusterctl/cmd/version_checker.go
  cmd/clusterctl/internal/test/fake_github.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  controllers/mdutil/util_test.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/etcd_client_generator_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
  test/infrastructure/docker/hack/tools/go.sum
  util/conditions/patch.go
  util/deprecated.go
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4307 🐛 E2E framework: support 'file' scheme in component source
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/repository.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4349 🐛 Make conversion-gen output location explicit
  Makefile
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4354 🌱 E2E test: Allow extra args to be passed during kubectl apply
  test/framework/cluster_proxy.go
  test/framework/clusterctl/clusterctl_helpers.go
  test/framework/exec/kubectl.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4369 🌱 Update Go to 1.16.2
  Dockerfile
  Makefile
  Tiltfile
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/Dockerfile.dev
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#4366 🐛 register kcp's scale subresource to validate scaling
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/config/webhook/manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4368 🐛 Avoid masking possible errors in flaky CRS test
  exp/addons/controllers/clusterresourceset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4363 ⚠️ clusterv1.ObjectMeta should only expose labels and annotations
  api/v1alpha3/common_types.go
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/common_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/exp.cluster.x-k8s.io_machinepools.yaml
  controllers/mdutil/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4372 :seedling: Update controller-runtime to v0.9.0-alpha.1
  go.mod
  go.sum
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#4371 🐛 Fix clusterproxy interface in e2e: regression
  test/e2e/kcp_adoption.go
  test/e2e/kcp_adoption_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4373 🐛 Fix annotations.AddAnnotations (if annotations has been nil before)
  util/annotations/helpers.go
  util/annotations/helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4362 🌱 Reorganize Make generate targets
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#4281 :bug: Add back tolerations to cert-manager Deployments (backport to release-0.3)
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/config/assets/cert-manager.yaml
  cmd/clusterctl/config/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#4374 :seedling: Add github action to run golangci-lint
  .github/workflows/golangci-lint.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4367 🐛 pass the cluster in to the get targets
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_targets.go
  controllers/machinehealthcheck_targets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4376 🐛 Change KCP upgrade to use machinelist for scaling decision
  controlplane/kubeadm/controllers/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4329 ✨Make operator main.go and flags similar to CAPI
  exp/operator/config/default/manager_auth_proxy_patch.yaml
  exp/operator/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4375 🐛 Flaky ClusterResourceSet test fix
  exp/addons/controllers/clusterresourceset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4387 📖 update MHC docs to comply with current implementation
  docs/book/src/tasks/healthcheck.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4388 🌱 Annotate nodes with cluster and owner info
  api/v1alpha3/common_types.go
  controllers/machine_controller_noderef.go
  exp/controllers/machinepool_controller_noderef.go
  util/annotations/helpers.go
  util/annotations/helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4391 :seedling: Include 'edited' to the list of PR types for golangci action
  .github/workflows/golangci-lint.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4385 📖 Update tilt development instructions
  docs/book/src/developer/tilt.md
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4293 ✨ Backport KCP Rollout Strategy to v1alpha3 api
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/controllers/controller_test.go
  controlplane/kubeadm/controllers/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4268 ⚠️ Clusterctl v1alpha3 should not upgrade to v1alpha4
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/client/cluster/upgrader_info.go
  cmd/clusterctl/client/cluster/upgrader_info_test.go
  cmd/clusterctl/client/cluster/upgrader_test.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/client/upgrade_test.go
  cmd/clusterctl/cmd/upgrade_plan.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4347 ✨ Add E2E for scale in rollout
  test/e2e/Makefile
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-scale-in/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-scale-in/kustomization.yaml
  test/e2e/kcp_upgrade.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4412 🌱 Remove CAPD hack/tools directory and run ensure-kustomize script
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/hack/tools/go.mod
  test/infrastructure/docker/hack/tools/go.sum
  test/infrastructure/docker/hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4410 🌱 generate JUnit report in ci-test.sh
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  scripts/ci-test.sh
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#4345 📖 docs: Add installation guide with homebrew
  docs/book/src/user/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4415 ⚠️ Wait for all the machine to exist again after remediation
  test/framework/machinehealthcheck_helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4397 🌱 fallback on build if kindest images are missing
  scripts/ci-e2e-lib.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#4411 🐛 make manifest to use cert-manager.io/v1alpha2
  bootstrap/kubeadm/config/certmanager/certificate.yaml
  bootstrap/kubeadm/config/webhook/kustomization.yaml
  config/certmanager/certificate.yaml
  config/webhook/kustomization.yaml
  controlplane/kubeadm/config/certmanager/certificate.yaml
  controlplane/kubeadm/config/webhook/kustomization.yaml
  test/infrastructure/docker/config/certmanager/certificate.yaml
  test/infrastructure/docker/config/webhook/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4418 🌱 Minor CAPD Makefile cleanup
  Makefile
  test/infrastructure/docker/Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S
