Repository kubernetes-sigs/cluster-api, pull requests merged in 2021-10, with the labels that each got.

#5366 📖 Add clusterclass contract changes to v1alpha3-v1alpha4 conversion guide
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#5376 :book: Redirect on curl k8s stable version and kustomize install
  docs/book/src/developer/providers/implementers-guide/overview.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5358 🐛 Use the watch filter label when watching resources
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  controllers/machine_controller.go
  controllers/machinedeployment_controller.go
  controllers/machinehealthcheck_controller.go
  controllers/machineset_controller.go
  exp/controllers/machinepool_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#5372 🐛 clusterctl: fix Certificate target namespace
  cmd/clusterctl/client/repository/components.go
  cmd/clusterctl/client/repository/components_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5382 🌱 Upgrade to controller-runtime v0.10.2
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#5386 🌱 clusterctl upgrade: enforce that --contract or provider flags have to be set
  cmd/clusterctl/cmd/upgrade_apply.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5384 📖 Fix make commands in clusterctl for developers doc
  docs/book/src/clusterctl/developers.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#5377 🌱 Allow passing in provider contract and clusterctl binary in the clusterctl upgrade spec
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#5374 📖 Add clusterclass quickstart guide
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/experimental-features/cluster-classes.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  docs/book/src/tasks/experimental-features/yamls/clusterclass-quickstart.yaml
  docs/book/src/tasks/experimental-features/yamls/clusterclass.yaml
  docs/book/src/tasks/experimental-features/yamls/kindnet-clusterresourceset.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#5387 🌱 add organizations to certificates
  bootstrap/kubeadm/config/certmanager/certificate.yaml
  config/certmanager/certificate.yaml
  controlplane/kubeadm/config/certmanager/certificate.yaml
  docs/book/src/developer/providers/v1alpha4-to-v1beta1.md
  test/infrastructure/docker/config/certmanager/certificate.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#5381 🐛 KCP should cleanup OwnerRemediated condition if the machine goes back to healthy
  controlplane/kubeadm/controllers/remediation.go
  controlplane/kubeadm/controllers/remediation_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5391 ⚠️ ClusterToObjectsMapper: replace runtime.Object parameter with client.ObjectList
  util/util.go
  util/util_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5395 🌱 Clusterctl Upgrade Spec: Add details on how to use it
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/M, approved
