Repository kubernetes-sigs/cluster-api, pull requests merged in 2021-01, with the labels that each got.

#4025 📖 Add envsubst as prerequisite in developer guide
  docs/book/src/developer/guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#3951 ⚠️ E2E test support definition of test files for each version
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_util.go
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/repository.go
  test/framework/config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4042 🐛 E2E conformance tests now use kind network
  test/e2e/data/infrastructure-docker/v1alpha4/bases/cluster-with-kcp.yaml
  test/framework/kubetest/run.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4023 ✨ Use uncached client and partial metadata for secret and configmaps
  bootstrap/kubeadm/main.go
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_cache_fake.go
  controllers/remote/cluster_cache_reconciler_test.go
  controlplane/kubeadm/main.go
  exp/addons/controllers/clusterresourceset_controller.go
  exp/addons/controllers/suite_test.go
  go.mod
  go.sum
  main.go
  test/framework/convenience.go
  test/infrastructure/docker/go.mod
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#4034 🐛 KubeadmControlPlane should adopt v1alpha2 kubeconfig secrets
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/helpers.go
  controlplane/kubeadm/controllers/helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3773 ✨ Support deletePolicy in MachineDeployment
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/machinedeployment_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  controllers/machinedeployment_controller_test.go
  controllers/machinedeployment_sync.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3921 🌱 DockerMachinePool should not use Status.instances from previous reconciliation
  Tiltfile
  test/framework/machinepool_helpers.go
  test/infrastructure/docker/controllers/dockercluster_controller.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/loadbalancer.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/exp/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/exp/docker/nodepool.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4050 🐛 KubeadmControlPlane should adopt v1alpha2 kubeconfig secrets
  controlplane/kubeadm/controllers/controller.go
  controlplane/kubeadm/controllers/helpers.go
  controlplane/kubeadm/controllers/helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4045 🐛 Fix APIEndpoint for IPv6
  api/v1alpha3/cluster_types.go
  api/v1alpha4/cluster_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3994 ✨ Make KubeadmControlPlane Spec mutable
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/controllers/upgrade.go
  controlplane/kubeadm/internal/kubeadm_config_map.go
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#4051 📖 Update README to point to new agenda document.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4052 🌱 Move davidewatson to emeritus since he has not contributed for too
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3857 📖 Update KCP proposal with scale in
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, ok-to-test, size/L

#4048 🌱 Annotate nodes with cluster info
  api/v1alpha4/common_types.go
  controllers/machine_controller_noderef.go
  exp/controllers/machinepool_controller_noderef.go
  util/annotations/helpers.go
  util/annotations/helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4033 ⚠️ Remove embedded metadata from clusterctl
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/client/repository/metadata_client_test.go
  docs/book/src/clusterctl/provider-contract.md
  test/e2e/config/docker.yaml
  test/e2e/data/shared/v1alpha4/metadata.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#3980 :seedling: Increase leader election lease values for KCP
  controlplane/kubeadm/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3942 🌱 Add clusterctl describe cluster command
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/describe.go
  cmd/clusterctl/client/tree/annotations.go
  cmd/clusterctl/client/tree/discovery.go
  cmd/clusterctl/client/tree/discovery_test.go
  cmd/clusterctl/client/tree/doc.go
  cmd/clusterctl/client/tree/options.go
  cmd/clusterctl/client/tree/tree.go
  cmd/clusterctl/client/tree/tree_test.go
  cmd/clusterctl/client/tree/util.go
  cmd/clusterctl/cmd/describe.go
  cmd/clusterctl/cmd/describe_cluster.go
  cmd/clusterctl/cmd/describe_cluster_test.go
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4066 🐛 Fix APIEndpoint for IPv6
  api/v1alpha3/cluster_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4067 🐛 Avoid reporting health check error when the cache is stopped
  controllers/remote/cluster_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4076 🐛 Increase timeout in clusterresourceset controller unit tests
  exp/addons/controllers/clusterresourceset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4072 🐛 Fix typo for "cluster"
  cmd/clusterctl/cmd/rollout/restart.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4083 🐛 Skip E2E Conformance tests labeled as Serial
  test/e2e/data/kubetest/conformance.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#3916 🌱 Add e2e tests for workload cluster with Kubernetes from ci/latest
  scripts/ci-e2e-lib.sh
  scripts/ci-e2e.sh
  test/e2e/config/docker.yaml
  test/e2e/kcp_upgrade_test.go
  test/e2e/machine_pool_test.go
  test/e2e/md_upgrades_test.go
  test/e2e/quick_start_test.go
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/repository.go
  test/framework/daemonset_helpers.go
  test/framework/machinepool_helpers.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/exp/docker/nodepool.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4071 🐛 Handle stopped containers in capd
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/errors.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/docker/types/node.go
  test/infrastructure/docker/docker/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#3904 🌱 Move MachineSet patching to a defer call
  controllers/machineset_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4069 🌱 Add optional parameter for using repolist to the kubetest library
  test/framework/kubetest/run.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4086 :bug: Test environments should wait for manager before running tests
  bootstrap/kubeadm/controllers/suite_test.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controllers/remote/cluster_cache_reconciler_test.go
  controllers/remote/cluster_cache_tracker_test.go
  controllers/remote/suite_test.go
  controllers/suite_test.go
  controlplane/kubeadm/controllers/suite_test.go
  controlplane/kubeadm/internal/suite_test.go
  docs/book/src/developer/testing.md
  exp/addons/controllers/suite_test.go
  exp/controllers/suite_test.go
  util/patch/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4074 📖 Document multi-tenancy contract
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/commands/upgrade.md
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/developer/architecture/controllers/multi-tenancy.md
  docs/book/src/developer/architecture/controllers/support-multiple-instances.md
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  docs/book/src/reference/glossary.md
Labels: approved, area/clusterctl, cncf-cla: yes, lgtm, size/L

#3833 📖 Add CAPI Provider Operator CAEP
  docs/proposals/20201020-capi-provider-operator.md
  docs/proposals/images/capi-provider-operator/fig1.plantuml
  docs/proposals/images/capi-provider-operator/fig1.png
  docs/proposals/images/capi-provider-operator/fig2.plantuml
  docs/proposals/images/capi-provider-operator/fig2.png
  docs/proposals/images/capi-provider-operator/fig3.png
  docs/proposals/images/capi-provider-operator/fig4.png
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, size/XXL

#4064 🐛 Use nonroot user with id
  Dockerfile
  bootstrap/kubeadm/config/manager/manager_auth_proxy_patch.yaml
  cmd/clusterctl/client/init_test.go
  cmd/clusterctl/internal/util/objs_test.go
  config/ci/manager/manager_auth_proxy_patch.yaml
  config/manager/manager_auth_proxy_patch.yaml
  controlplane/kubeadm/config/manager/manager_auth_proxy_patch.yaml
  docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md
  test/infrastructure/docker/config/manager/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4094 🌱 Add E2E test for KCP remediation
  test/e2e/Makefile
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/mhc.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-remediation/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-remediation/mhc.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-md-remediation/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-md-remediation/md.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-md-remediation/mhc.yaml
  test/e2e/mhc_remediations.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4100 📖 Update testing.md
  docs/book/src/developer/testing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4088 🌱 Add clusterctl describe cluster command
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/describe.go
  cmd/clusterctl/client/tree/annotations.go
  cmd/clusterctl/client/tree/discovery.go
  cmd/clusterctl/client/tree/discovery_test.go
  cmd/clusterctl/client/tree/doc.go
  cmd/clusterctl/client/tree/options.go
  cmd/clusterctl/client/tree/tree.go
  cmd/clusterctl/client/tree/tree_test.go
  cmd/clusterctl/client/tree/util.go
  cmd/clusterctl/cmd/describe.go
  cmd/clusterctl/cmd/describe_cluster.go
  cmd/clusterctl/cmd/describe_cluster_test.go
  go.mod
  go.sum
  test/infrastructure/docker/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4093 📖 Update kcp proposal disambiguating healthcheck
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4102 🌱 Cherry-pick: Add optional parameter for using repolist
  test/framework/kubetest/run.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4081 🐛 Use a different object name for each ClusterResultSet test case
  exp/addons/controllers/clusterresourceset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4079 🐛 Set error_exit code arg in kubeadm bootstrap script
  bootstrap/kubeadm/internal/cloudinit/kubeadm-bootstrap-script.sh
  bootstrap/kubeadm/internal/cloudinit/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4080 ✨ KCP spec mutation for ApiServer, ControllerManager, and Scheduler
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/controllers/upgrade.go
  controlplane/kubeadm/internal/kubeadm_config_map.go
  controlplane/kubeadm/internal/kubeadm_config_map_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#4106 🐛 Set error_exit code arg in kubeadm bootstrap script
  bootstrap/kubeadm/internal/cloudinit/kubeadm-bootstrap-script.sh
  bootstrap/kubeadm/internal/cloudinit/zz_generated.bindata.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4084 ✨ Add sentinel file to signal successful bootstrapping
  bootstrap/kubeadm/internal/cloudinit/cloudinit.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_init.go
  bootstrap/kubeadm/internal/cloudinit/controlplane_join.go
  bootstrap/kubeadm/internal/cloudinit/node.go
  docs/book/src/developer/providers/bootstrap.md
  test/infrastructure/docker/api/v1alpha4/condition_consts.go
  test/infrastructure/docker/cloudinit/runcmd.go
  test/infrastructure/docker/cloudinit/runcmd_test.go
  test/infrastructure/docker/controllers/dockermachine_controller.go
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/exp/docker/nodepool.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4108 :seedling: Remove the image placeholder in release notes
  hack/tools/release/notes.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4070 ⚠️ [cleanup] move version package from cmd to version/
  bootstrap/kubeadm/main.go
  cmd/clusterctl/client/cluster/proxy.go
  cmd/clusterctl/client/cluster/proxy_test.go
  cmd/clusterctl/cmd/version.go
  cmd/clusterctl/cmd/version_checker.go
  cmd/clusterctl/cmd/version_checker_test.go
  controlplane/kubeadm/main.go
  hack/version.sh
  main.go
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4092 📖 Document clusterctl describe
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/clusterctl/commands/describe-cluster.md
  docs/book/src/images/describe-cluster-disable-grouping.png
  docs/book/src/images/describe-cluster-disable-no-echo.png
  docs/book/src/images/describe-cluster-how-grouping-works.png
  docs/book/src/images/describe-cluster-show-conditions.png
  docs/book/src/images/describe-cluster.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#4123 📖 Document clusterctl describe
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/clusterctl/commands/describe-cluster.md
  docs/book/src/images/describe-cluster-disable-grouping.png
  docs/book/src/images/describe-cluster-disable-no-echo.png
  docs/book/src/images/describe-cluster-how-grouping-works.png
  docs/book/src/images/describe-cluster-show-conditions.png
  docs/book/src/images/describe-cluster.png
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4127 📖 Update mdbook to 0.4.5 to fix CVE-2020-26297
  docs/book/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4059 🌱 Bump kustomize version to 3.9.1
  cmd/clusterctl/config/zz_generated.bindata.go
  hack/ensure-kustomize.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4121 📖 Fix cert-manager version in the developer's guide
  docs/book/src/developer/guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4060 ⚠️ Set user agent and timeout for remote cluster client
  bootstrap/kubeadm/controllers/kubeadmconfig_controller.go
  controllers/machine_controller.go
  controllers/remote/cluster.go
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_test.go
  controllers/remote/fake/cluster.go
  controllers/remote/restconfig.go
  controlplane/kubeadm/internal/cluster.go
  exp/controllers/machinepool_controller.go
  exp/controllers/machinepool_controller_noderef.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4133 📖 Update mdbook to 0.4.5 to fix CVE-2020-26297
  docs/book/install-and-build.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
