Repository kubernetes-sigs/cluster-api, pull requests merged in 2021-08, with the labels that each got.

#5040 🌱 Introduce new test CRDs
  controllers/cluster_controller_phases_test.go
  controllers/external/testing.go
  controllers/machine_controller_node_labels_test.go
  controllers/machine_controller_phases_test.go
  controllers/machine_controller_test.go
  controllers/machinedeployment_controller_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/machineset_controller_test.go
  controlplane/kubeadm/controllers/controller_test.go
  internal/envtest/environment.go
  internal/testtypes/bootstrap.go
  internal/testtypes/controlplane.go
  internal/testtypes/crds.go
  internal/testtypes/doc.go
  internal/testtypes/infrastructure.go
  internal/testtypes/remediation.go
  util/patch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4945 🐛 Wait for volume detach after node drain
  api/v1alpha4/condition_consts.go
  controllers/machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5007 🌱 cluster topology controller: read clusterclass
  controllers/clustertopology_controller_compute.go
  controllers/clustertopology_controller_compute_test.go
  controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5022 📖 Clarify template conventions and template reconciliation rules in the ClusterClass proposal
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5034 🌱 Implement twoWayPatchHelper for ClusterClass reconciliation
  controllers/clustertopology_controller_mergepatch.go
  controllers/clustertopology_controller_mergepatch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4905 ✨ support NodeRegistrationOptions.IgnorePreflightErrors
  bootstrap/kubeadm/api/v1alpha3/conversion.go
  bootstrap/kubeadm/api/v1alpha3/conversion_test.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha4/kubeadm_types.go
  bootstrap/kubeadm/api/v1alpha4/zz_generated.deepcopy.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/utils_test.go
  bootstrap/kubeadm/types/v1beta1/conversion.go
  bootstrap/kubeadm/types/v1beta1/conversion_test.go
  bootstrap/kubeadm/types/v1beta1/zz_generated.conversion.go
  bootstrap/kubeadm/types/v1beta2/conversion.go
  bootstrap/kubeadm/types/v1beta2/conversion_test.go
  bootstrap/kubeadm/types/v1beta2/types.go
  bootstrap/kubeadm/types/v1beta2/zz_generated.conversion.go
  bootstrap/kubeadm/types/v1beta3/zz_generated.conversion.go
  controlplane/kubeadm/api/v1alpha3/conversion.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#5048 🐛 Update envtest listen address to localhost
  internal/envtest/environment.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5042 🌱 Deprecate partial upgrade tests
  test/e2e/cluster_upgrade.go
  test/e2e/kcp_upgrade.go
  test/e2e/machine_pool.go
  test/e2e/md_rollout.go
  test/e2e/md_rollout_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5050 🐛 fix panic in clusterctl backup
  cmd/clusterctl/client/cluster/mover.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5027 📖 doc: add update bootstrap template doc
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/updating-machine-templates.md
  docs/book/src/tasks/upgrading-clusters.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5051 🐛 Fix clusterctl upgrade cert-manager version detection previously detecting v0.11 when using EndpointSlices
  cmd/clusterctl/client/cluster/cert_manager.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#4992 🌱 add additional validations for clusterclass type
  api/v1alpha4/clusterclass_webhook.go
  api/v1alpha4/clusterclass_webhook_test.go
  api/v1alpha4/common_types.go
  controllers/external/util.go
  controllers/machinehealthcheck_controller.go
  controllers/machineset_controller.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/controllers/helpers.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5063 🌱 test/framework: disable metrics collection should not disable watching deployment logs
  test/framework/clusterctl/clusterctl_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#5002 🌱 Compute desired Cluster and its referenced objects for a managed topology
  api/v1alpha4/common_types.go
  controllers/clustertopology_controller_compute.go
  controllers/clustertopology_controller_compute_test.go
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5069 🌱 gate DockerClusterTemplate usage with ClusterTopology feature gate
  test/infrastructure/docker/api/v1alpha4/dockerclustertemplate_webhook.go
  test/infrastructure/docker/api/v1alpha4/dockerclustertemplate_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5004 ✨ add api/v1alpha4/index package
  api/v1alpha4/common_types.go
  api/v1alpha4/index/index.go
  api/v1alpha4/index/machine.go
  api/v1alpha4/index/machine_test.go
  api/v1alpha4/index/node.go
  api/v1alpha4/index/node_test.go
  controllers/machine_controller.go
  controllers/machine_controller_noderef.go
  controllers/machine_controller_noderef_test.go
  controllers/machinehealthcheck_controller.go
  controllers/noderefutil/indexer.go
  controllers/noderefutil/machine.go
  controllers/remote/cluster_cache.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controllers/remote/cluster_cache_tracker_test.go
  controllers/remote/index.go
  controllers/suite_test.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/main.go
  exp/addons/controllers/suite_test.go
  exp/controllers/suite_test.go
  main.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5071 🌱 Move the ClusterTopologyReconciler to a separated package
  controllers/clustertopology_controller_compute_test.go
  controllers/topology/cluster_class.go
  controllers/topology/cluster_class_test.go
  controllers/topology/controller.go
  controllers/topology/current_state.go
  controllers/topology/desired_state.go
  controllers/topology/desired_state_test.go
  controllers/topology/doc.go
  controllers/topology/mergepatch.go
  controllers/topology/mergepatch_test.go
  controllers/topology/object_builders_test.go
  controllers/topology/reconcile_state.go
  controllers/topology/suite_test.go
  controllers/topology/types.go
  controllers/topology/util.go
  controllers/topology/util_test.go
  main.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#5068 🌱 gate KubeadmControlPlaneTemplate usage with ClusterTopology feature gate
  controlplane/kubeadm/api/v1alpha4/kubeadmcontrolplanetemplate_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadmcontrolplanetemplate_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5030 🌱 Migrate envtest setup to envtest.Run, add CAPI_DISABLE_TEST_ENV option
  api/v1alpha3/suite_test.go
  bootstrap/kubeadm/api/v1alpha3/suite_test.go
  bootstrap/kubeadm/controllers/suite_test.go
  bootstrap/util/suite_test.go
  controllers/remote/suite_test.go
  controllers/suite_test.go
  controlplane/kubeadm/api/v1alpha3/suite_test.go
  controlplane/kubeadm/controllers/suite_test.go
  controlplane/kubeadm/internal/suite_test.go
  exp/addons/api/v1alpha3/suite_test.go
  exp/addons/controllers/suite_test.go
  exp/api/v1alpha3/suite_test.go
  exp/controllers/suite_test.go
  internal/envtest/environment.go
  util/collections/suite_test.go
  util/patch/suite_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5061 ✨ Make local etcd's extra args in KCP mutable
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/controllers/upgrade.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
  controlplane/kubeadm/internal/workload_cluster_etcd_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#5074 🌱 Update Controller Runtime v0.9.6 / envtest Kubernetes 1.22.0
  Makefile
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#4967 ✨ create index for cluster.spec.topology.class
  api/v1alpha4/index/cluster.go
  api/v1alpha4/index/cluster_test.go
  api/v1alpha4/index/index.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#4981 ✨Add a MemoryRepository for the operator
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  cmd/clusterctl/client/cluster/installer_test.go
  cmd/clusterctl/client/cluster/upgrader_info_test.go
  cmd/clusterctl/client/cluster/upgrader_test.go
  cmd/clusterctl/client/repository/client.go
  cmd/clusterctl/client/repository/client_test.go
  cmd/clusterctl/client/repository/components_client_test.go
  cmd/clusterctl/client/repository/metadata_client_test.go
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
  cmd/clusterctl/client/repository/repository_local.go
  cmd/clusterctl/client/repository/repository_memory.go
  cmd/clusterctl/client/repository/repository_memory_test.go
  cmd/clusterctl/client/repository/repository_versions.go
  cmd/clusterctl/client/repository/template_client_test.go
  cmd/clusterctl/internal/test/fake_repository.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test, area/operator

#5077 🐛 Increase polling interval and timeout in ClusterCacheHealthCheck
  controllers/remote/cluster_cache_healthcheck_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#5052 🌱 Reconcile infrastructure cluster for managed topologies
  controllers/topology/cluster_class_test.go
  controllers/topology/object_builders_test.go
  controllers/topology/reconcile_state.go
  controllers/topology/reconcile_state_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5075 📖 add maas to infra provider list
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#5080 🌱 Upgrade quickstart and e2e tests to Kubernetes v1.22.0
  docs/book/src/user/quick-start.md
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/docker/machine.go
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#5045 ✨ Implement getClusterState for topology controller
  api/v1alpha4/common_types.go
  controllers/topology/cluster_class.go
  controllers/topology/controller.go
  controllers/topology/current_state.go
  controllers/topology/current_state_test.go
  controllers/topology/object_builders_test.go
  controllers/topology/types.go
  controllers/topology/util.go
  controllers/topology/util_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test

#5088 🌱 Pass the ClusterTopology feature flag to CAPD and KCP
  controlplane/kubeadm/config/manager/manager.yaml
  controlplane/kubeadm/main.go
  test/infrastructure/docker/config/manager/manager.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5082 ✨ implement ClusterReconciler.clusterClassToCluster function
  controllers/topology/controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/topology

#5079 :seedling: Add Status.NodeInfo to Machine objects
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/machine_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  controllers/machine_controller_noderef.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5084 🌱 Add ykakarap to cluster-api-topology-reviewers
  OWNERS_ALIASES
  controllers/topology/OWNERS
Labels: size/S, cncf-cla: yes, lgtm, approved

#4934 ⚠️ clusterctl init: wait for deployments to be ready
  cmd/clusterctl/client/cluster/installer.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/internal/util/objs.go
  cmd/clusterctl/internal/util/objs_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5031 🌱 add version to KubeadmControlPlaneStatus
  controlplane/kubeadm/api/v1alpha3/conversion.go
  controlplane/kubeadm/api/v1alpha3/zz_generated.conversion.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha4/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/controllers/status.go
  util/collections/machine_collection.go
  util/collections/machine_collection_test.go
  util/collections/machine_filters.go
  util/collections/machine_filters_test.go
  util/version/version.go
  util/version/version_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5095 :book: Remove "latest release"
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#5092 :sparkles: [e2e framework] Allow cluster upgrade spec to work without MachinePools
  test/e2e/cluster_upgrade.go
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5081 🌱 e2e tests: make the management cluster Kubernetes version configurable
  scripts/ci-e2e-lib.sh
  test/e2e/common.go
  test/e2e/config/docker.yaml
  test/e2e/e2e_suite_test.go
  test/framework/bootstrap/kind_provider.go
  test/framework/bootstrap/kind_util.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5103 📖 Update job overview in CAPI book
  docs/book/src/reference/jobs.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#5093 :sparkles: [e2e framework] Add ability to run pre and post actions during clusterctl upgrade spec
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5096 🐛 clusterctl: fix target namespace in v1beta1 CRDs and WebhookConfigurations
  cmd/clusterctl/client/repository/components.go
  cmd/clusterctl/client/repository/components_test.go
  cmd/clusterctl/internal/scheme/scheme.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5070 🌱 Adds logic to generate machine deployments
  controllers/topology/cluster_class.go
  controllers/topology/cluster_class_test.go
  controllers/topology/desired_state.go
  controllers/topology/desired_state_test.go
  controllers/topology/object_builders_test.go
  controllers/topology/types.go
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/topology

#5106 🌱 Intentionally ignore Deferring unsafe method Close on type *os.File
  .golangci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5072 ✨ Reconcile MachineDeployment topologies
  api/v1alpha4/common_types.go
  controllers/topology/current_state_test.go
  controllers/topology/desired_state.go
  controllers/topology/object_builders_test.go
  controllers/topology/reconcile_state.go
  controllers/topology/reconcile_state_test.go
  controllers/topology/util.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/topology

#5107 📖 doc: update Azure provider links to reference main branch
  docs/book/src/tasks/using-kustomize.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#5111 🐛 Fix panic in cluster class reconcile
  controllers/topology/desired_state.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5101 🌱 Reconcile control plane resources in ClusterClass
  controllers/topology/controller.go
  controllers/topology/reconcile_state.go
  controllers/topology/reconcile_state_test.go
  controllers/topology/util.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/topology

#5113 📖 doc: mention clusterctl download for darwin-arm64
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5114 :seedling: Cleanup controllers/topology code, add more comments
  controllers/topology/cluster_class.go
  controllers/topology/cluster_class_test.go
  controllers/topology/controller.go
  controllers/topology/current_state.go
  controllers/topology/current_state_test.go
  controllers/topology/desired_state.go
  controllers/topology/desired_state_test.go
  controllers/topology/reconcile_state.go
  controllers/topology/reconcile_state_test.go
  controllers/topology/types.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5090 🌱 Add namespace defaulting for ClusterClass ControlPlane MachineInfrastructure
  api/v1alpha4/clusterclass_webhook.go
  api/v1alpha4/clusterclass_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5116 🌱 Make the MergePatchHelper skip metadata fields computed by the system and status
  controllers/topology/mergepatch.go
  controllers/topology/mergepatch_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/topology

#5100 🌱 Fix clusterctl upgrade e2e test
  test/e2e/clusterctl_upgrade.go
  test/e2e/config/docker.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#5117 🌱 Move topology/mergepatch helper to an internal package
  controllers/topology/internal/mergepatch/mergepatch.go
  controllers/topology/internal/mergepatch/mergepatch_test.go
  controllers/topology/reconcile_state.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5104 :book: Update Quick Start doc to include GCP env variables.
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#5119 ⚠️ Refactor the ClusterClass codebase and reconciler around a scope
  api/v1alpha4/cluster_types.go
  api/v1alpha4/common_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  controllers/topology/blueprint.go
  controllers/topology/blueprint_test.go
  controllers/topology/cluster_class.go
  controllers/topology/controller.go
  controllers/topology/current_state.go
  controllers/topology/current_state_test.go
  controllers/topology/desired_state.go
  controllers/topology/desired_state_test.go
  controllers/topology/internal/scope/blueprint.go
  controllers/topology/internal/scope/doc.go
  controllers/topology/internal/scope/scope.go
  controllers/topology/internal/scope/state.go
  controllers/topology/reconcile_state.go
  controllers/topology/reconcile_state_test.go
  controllers/topology/types.go
  controllers/topology/util.go
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#5129 🌱 add mergehelper IgnorePath option
  controllers/topology/internal/mergepatch/doc.go
  controllers/topology/internal/mergepatch/mergepatch.go
  controllers/topology/internal/mergepatch/mergepatch_test.go
  controllers/topology/internal/mergepatch/options.go
  controllers/topology/reconcile_state.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5127 🌱 fix nil pointer in ClusterClass webhook ref validation
  api/v1alpha4/clusterclass_webhook.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5118 ⚠️ Upgrade cert-manager to 1.5.0
  Tiltfile
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/commands/upgrade.md
  docs/book/src/clusterctl/configuration.md
  docs/book/src/developer/guide.md
  docs/book/src/user/quick-start.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#5105 📖 Added documentation for setting up vs code debugger
  docs/book/src/developer/testing.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#5126 🌱 envtest: enable ClusterClass webhook
  internal/envtest/environment.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5128 🐛 Fix blueprint.HasMachineDeployments
  controllers/topology/desired_state.go
  controllers/topology/internal/scope/blueprint.go
  controllers/topology/internal/scope/scope.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5138 :bug: KubeadmControlPlane rolloutstrategy should be defaulted in openapi
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5139 :bug: KubeadmControlPlane rolloutstrategy should be defaulted in openapi
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/controllers/upgrade.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5135 🌱 Create internal/check package for ClusterClass
  controllers/topology/internal/check/compatibility.go
  controllers/topology/internal/check/compatibility_test.go
  controllers/topology/reconcile_state.go
  controllers/topology/reconcile_state_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5109 📖 Update testing docs
  docs/book/src/developer/testing.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#5144 🌱 bump clusterctl upgrade test to CAPI v0.3.23
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#5140 🌱 create internal/contract package for ClusterClass
  controllers/topology/current_state.go
  controllers/topology/desired_state.go
  controllers/topology/desired_state_test.go
  controllers/topology/internal/contract/controlplane.go
  controllers/topology/internal/contract/controlplane_template.go
  controllers/topology/internal/contract/controlplane_template_test.go
  controllers/topology/internal/contract/controlplane_test.go
  controllers/topology/internal/contract/doc.go
  controllers/topology/internal/contract/infrastructure_cluster.go
  controllers/topology/internal/contract/infrastructure_cluster_test.go
  controllers/topology/internal/contract/references.go
  controllers/topology/internal/contract/references_test.go
  controllers/topology/internal/contract/types.go
  controllers/topology/internal/mergepatch/mergepatch.go
  controllers/topology/internal/mergepatch/mergepatch_test.go
  controllers/topology/internal/mergepatch/options.go
  controllers/topology/object_builders_test.go
  controllers/topology/reconcile_state.go
  controllers/topology/reconcile_state_test.go
  controllers/topology/util.go
  controllers/topology/util_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5131 :bug: KubeadmControlPlane should allow to change the machineTemplate's apiVersion
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/release-blocking

#5102 🌱 Enable envtest with kind
  hack/setup-envtest-with-kind.sh
  internal/envtest/environment.go
  internal/envtest/webhooks.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#4985 📖 Add validation for ClusterClass compatibility
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/topology

#5148 🌱 Move Predicates allow logs to V6
  util/predicates/cluster_predicates.go
  util/predicates/generic_predicates.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5150 📖 Fix typo in `clusterctl generate cluster` book docs
  docs/book/src/clusterctl/commands/generate-cluster.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#5177 :bug: log in restore cmd causing crashes
  cmd/clusterctl/client/cluster/mover.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#5173 🐛 ClusterClass : fix propagate metadata to machines, KCP fix propagate annotations
  api/v1alpha4/cluster_types.go
  api/v1alpha4/clusterclass_types.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  controllers/topology/current_state.go
  controllers/topology/desired_state.go
  controllers/topology/desired_state_test.go
  controllers/topology/internal/contract/controlplane.go
  controllers/topology/internal/contract/controlplane_template.go
  controllers/topology/internal/contract/controlplane_test.go
  controllers/topology/internal/contract/metadata.go
  controllers/topology/object_builders_test.go
  controllers/topology/reconcile_state.go
  controllers/topology/reconcile_state_test.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/controllers/helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5134 🌱 Cleanup topology reconcile logs
  controllers/remote/cluster_cache.go
  controllers/topology/internal/mergepatch/mergepatch.go
  controllers/topology/reconcile_state.go
  controllers/topology/util.go
  util/predicates/cluster_predicates.go
Labels: cncf-cla: yes, lgtm, size/L, approved
