Repository kubernetes-sigs/cluster-api, pull requests merged in 2022-05, with the labels that each got.

#6463 📖 book: Add note about Tiltfile syntax highlighting
  docs/book/src/developer/tilt.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6473 🐛 CAPD: Add containerd socket to worker nodes
  test/infrastructure/docker/templates/cluster-template-development.yaml
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6478 🌱 test: tolerate zero pods in WaitForPodListCondition
  test/framework/pod_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6425 :bug: Fix cluster reconcilation predicates
  internal/controllers/machine/machine_controller.go
  util/predicates/cluster_predicates.go
  util/predicates/cluster_predicates_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#6449 ✨ RuntimeSDK: add registry
  internal/runtime/catalog/catalog.go
  internal/runtime/registry/doc.go
  internal/runtime/registry/registry.go
  internal/runtime/registry/registry_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/runtime-sdk

#6000 📖 add ipam integration proposal
  docs/proposals/20220125-ipam-integration.md
  docs/proposals/images/ipam-integration/consumption.png
  docs/proposals/images/ipam-integration/sequence.png
  docs/proposals/images/ipam-integration/sequence.txt
Labels: cncf-cla: yes, lgtm, size/L, approved

#5942 🌱 Replace uitable with tablewriter in clusterctl describe cluster command
  cmd/clusterctl/cmd/describe_cluster.go
  cmd/clusterctl/cmd/describe_cluster_test.go
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6439 🌱 clusterctl: support disable version check
  cmd/clusterctl/cmd/root.go
  docs/book/src/clusterctl/configuration.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6496 🌱 docs: add capmvm to the providers list
  .markdownlinkcheck.json
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6491 🌱 internal/topology migrate reconcile_state tests to envtest
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/test/builder/builders.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6422 📖 Improve ClusterClass docs
  docs/book/src/tasks/experimental-features/cluster-class/change-clusterclass.md
  docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
  docs/book/src/user/troubleshooting.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#6455 ✨ Runtime SDK client and Discovery
  .golangci.yml
  Makefile
  exp/runtime/hooks/api/v1alpha1/common_types.go
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/doc.go
  exp/runtime/hooks/api/v1alpha1/groupversion_info.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.deepcopy.go
  internal/runtime/catalog/catalog.go
  internal/runtime/catalog/test/v1alpha1/conversion.go
  internal/runtime/catalog/test/v1alpha1/conversion_test.go
  internal/runtime/catalog/test/v1alpha1/doc.go
  internal/runtime/catalog/test/v1alpha1/fake_types.go
  internal/runtime/catalog/test/v1alpha1/zz_generated.conversion.go
  internal/runtime/catalog/test/v1alpha2/fake_types.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/runtime-sdk

#6472 🐛 CABPK: Add Ignition base64 and file ownership support, reject gzipped content and fix unit tests
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook_test.go
  bootstrap/kubeadm/internal/ignition/clc/clc.go
  bootstrap/kubeadm/internal/ignition/clc/clc_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6502 🐛 ClusterResourceSet: apply objects in sorted order
  exp/addons/internal/controllers/clusterresourceset_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6498 🌱 Makefile: Split core conversion targets
  Makefile
Labels: size/S, cncf-cla: yes, lgtm, approved, area/runtime-sdk

#6462 ✨ introduce runtime-openapi-gen to generate openapi spec on release
  .golangci.yml
  Makefile
  api/v1beta1/doc.go
  api/v1beta1/zz_generated.openapi.go
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/groupversion_info.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/runtime-openapi-gen/main.go
  hack/tools/runtime-openapi-gen/vendored_openapi.go
  internal/runtime/catalog/builder.go
  internal/runtime/catalog/catalog.go
  internal/runtime/catalog/openapi.go
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/runtime-sdk

#6475 ✨ webhooks: defaulting and validation for ExtensionConfig
  internal/webhooks/cluster_test.go
  internal/webhooks/clusterclass_test.go
  internal/webhooks/runtime/extensionconfig_webhook.go
  internal/webhooks/runtime/extensionconfig_webhook_test.go
  internal/webhooks/util/util.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/runtime-sdk

#6525 :seedling: Update migration corefile to 1.0.16
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#6524 :seedling: Update golangci-lint action to 3.2
  .github/workflows/golangci-lint.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6347 :bug: skip templating step if `describe` flag is used
  cmd/clusterctl/cmd/generate_provider.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6399 :bug: Delete unused ControlPlane InfrastructureMachineTemplates on rotation
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6342 :seedling: Add docs for conditions in machine infra provider implementer
  docs/book/src/developer/providers/machine-infrastructure.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6474 🌱 make clusterctl init idempotent
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/client/init_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6485 🌱 retryable errors in test/framework
  test/framework/cluster_helpers.go
  test/framework/cluster_proxy.go
  test/framework/cluster_topology_helpers.go
  test/framework/clusterresourceset_helpers.go
  test/framework/controlplane_helpers.go
  test/framework/deployment_helpers.go
  test/framework/machine_helpers.go
  test/framework/machinedeployment_helpers.go
  test/framework/machinepool_helpers.go
  test/framework/namespace_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6349 📖 Topology Mutation Hook proposal
  docs/proposals/20220330-topology-mutation-hook.md
  docs/proposals/images/topology-mutation-hook/runtime-sdk-openapi.yaml
  docs/proposals/images/topology-mutation-hook/topology-reconciliation.plantuml
  docs/proposals/images/topology-mutation-hook/topology-reconciliation.png
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/runtime-sdk

#6530 📖 Update documentation for max CoreDNS version
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6532 🌱 Silence error in go_install.sh when trying to remove nonexisting files
  scripts/go_install.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6541 📖 Add IBM VPC environment variables
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6418 📖 Runtime Hooks for Add-on management proposal
  docs/proposals/20220414-runtime-hooks.md
  docs/proposals/images/runtime-hooks/runtime-hooks-openapi.yaml
  docs/proposals/images/runtime-hooks/runtime-hooks.png
Labels: cncf-cla: yes, lgtm, size/XXL, approved, kind/proposal, area/runtime-sdk

#6088 📖 Add proposal for MachinePool Machines
  docs/proposals/20220209-machinepool-machines.md
  docs/proposals/images/machinepool-machines/infraref-changed-sequence.png
  docs/proposals/images/machinepool-machines/infraref-changed-sequence.puml
Labels: cncf-cla: yes, lgtm, size/L, approved

#6548 🐛 Update docker distribution to fix go sum error
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6513 🐛 Use Kubernetes 1.24 in quickstart and CAPD, bump to kind v0.14
  docs/book/src/developer/providers/v1.1-to-v1.2.md
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  hack/tools/go.sum
  test/e2e/Makefile
  test/e2e/cluster_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1alpha3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1alpha3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1beta1/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-kcp-scale-in/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-kcp-scale-in/kcp-scale-in-variable.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-kcp-scale-in/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-topology/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-cgroupfs/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-cgroupfs/mp-default-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
  test/framework/bootstrap/kind_provider.go
  test/framework/machinepool_helpers.go
  test/go.mod
  test/go.sum
  test/infrastructure/container/docker.go
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/docker/templates/cluster-template-development-topology.yaml
  test/infrastructure/docker/templates/cluster-template-development.yaml
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6547 :seedling: Change ExtensionConfig to Cluster scoped
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  docs/proposals/20220221-runtime-SDK.md
  exp/runtime/api/v1alpha1/extensionconfig_types.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/runtime-sdk

#6552 🌱 Update docker to v20.10.16
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6421 🌱 Add automated machine management section to docs tasks
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/automated-machine-management/autoscaling.md
  docs/book/src/tasks/automated-machine-management/healthchecking.md
  docs/book/src/tasks/automated-machine-management/index.md
  docs/book/src/tasks/automated-machine-management/scaling.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6550 📖 Replace :warning: with ⚠️ in Contributing Guidelines documentation
  CONTRIBUTING.md
  docs/book/src/developer/providers/v0.3-to-v0.4.md
  docs/book/src/developer/providers/v0.4-to-v1.0.md
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved

#6553 :book: added vcluster infrastructure provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/reference/glossary.md
  docs/book/src/reference/providers.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6557 🐛 e2e: fix cgroup branching in cluster upgrade test
  test/e2e/cluster_upgrade_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6510 :seedling: integrate controller for ExtensionConfig
  config/rbac/role.yaml
  exp/runtime/api/v1alpha1/extensionconfig_types.go
  exp/runtime/controllers/alias.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/suite_test.go
  exp/runtime/internal/controllers/warmup.go
  exp/runtime/internal/controllers/warmup_test.go
  internal/test/envtest/environment.go
  main.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/runtime-sdk

#6562 🌱 Fix misspelled word in Makefile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6561 🌱 RuntimeSDK: standardize import names
  .golangci.yml
  exp/runtime/controllers/alias.go
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/groupversion_info.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/warmup_test.go
  hack/tools/runtime-openapi-gen/main.go
  internal/runtime/catalog/test/catalog_test.go
  internal/runtime/catalog/test/v1alpha1/conversion.go
  internal/runtime/catalog/test/v1alpha1/conversion_test.go
  internal/runtime/catalog/test/v1alpha1/fake_types.go
  internal/runtime/catalog/test/v1alpha2/fake_types.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
  internal/runtime/registry/registry.go
  internal/runtime/registry/registry_test.go
  internal/test/envtest/environment.go
  main.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6560 🐛 Use Kubernetes 1.24 in quickstart and CAPD, bump to kind v0.14
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/Makefile
  test/e2e/cluster_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1alpha3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1alpha3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1alpha4/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1beta1/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-kcp-scale-in/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-kcp-scale-in/kcp-scale-in-variable.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-kcp-scale-in/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-topology/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-cgroupfs/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-cgroupfs/mp-default-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
  test/framework/bootstrap/kind_provider.go
  test/framework/machinepool_helpers.go
  test/go.mod
  test/go.sum
  test/infrastructure/container/docker.go
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/docker/templates/cluster-template-development-topology.yaml
  test/infrastructure/docker/templates/cluster-template-development.yaml
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6564 📖 Fix resource name in cluster-topology-controller diagram
  docs/book/src/images/cluster-topology-controller.plantuml
  docs/book/src/images/cluster-topology-controller.png
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6569 📖 Fix grammar and spelling in clusterctl documentation
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/developers.md
  docs/book/src/clusterctl/provider-contract.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6572 ✨ envtest: add PatchAndWait helper function for server-side apply
  internal/test/envtest/environment.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6573 ✨ Introduce typed CRDs for testing purposes to replace the untyped ones
  internal/test/builder/bootstrap.go
  internal/test/builder/builders.go
  internal/test/builder/controlplane.go
  internal/test/builder/crds.go
  internal/test/builder/infrastructure.go
  internal/test/builder/remediation.go
  internal/test/envtest/environment.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6566 🌱 Sync owners alias on release-1.1 with main
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6567 📖 Update job documentation
  docs/book/src/reference/jobs.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6568 📖 proposals: fix swagger links in runtime hooks proposal
  docs/proposals/20220414-runtime-hooks.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6514 ✨ Topology Mutation: Add types for Topology Mutation Hook
  exp/runtime/hooks/api/v1alpha1/topologymutation_types.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.deepcopy.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6490 🌱 more retryable errors in test/framework
  test/framework/alltypes_helpers.go
  test/framework/cluster_helpers.go
  test/framework/cluster_proxy.go
  test/framework/clusterresourceset_helpers.go
  test/framework/controller_helpers.go
  test/framework/controlplane_helpers.go
  test/framework/deployment_helpers.go
  test/framework/machine_helpers.go
  test/framework/machinedeployment_helpers.go
  test/framework/machinehealthcheck_helpers.go
  test/framework/machinepool_helpers.go
  test/framework/machines.go
Labels: cncf-cla: yes, lgtm, size/L, approved
