Repository kubernetes-sigs/cluster-api, pull requests merged in 2022-04, with the labels that each got.

#6361 :seedling: Update golangci-lint action to v3
  .github/workflows/golangci-lint.yml
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6367 :sparkles: Add CAPX Nutanix Provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/reference/glossary.md
  docs/book/src/reference/providers.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6181 📖 Runtime SDK proposal
  docs/proposals/20220221-runtime-SDK.md
  docs/proposals/YYYYMMDD-template.md
  docs/proposals/images/runtime-sdk/overview.png
  docs/proposals/images/runtime-sdk/swagger-ui.png
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6371 :seedling: Update golangci-lint action
  .github/workflows/golangci-lint.yml
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6372 :seedling: Update golangci-lint action
  .github/workflows/golangci-lint.yml
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6373 :seedling: Update golangci-lint action
  .github/workflows/golangci-lint.yml
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6369 🌱 ClusterClass: implement map variables
  api/v1alpha4/conversion_test.go
  api/v1beta1/clusterclass_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
  docs/proposals/20210526-cluster-class-and-managed-topologies.md
  internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
  internal/topology/variables/cluster_variable_defaulting_test.go
  internal/topology/variables/cluster_variable_validation_test.go
  internal/topology/variables/clusterclass_variable_validation.go
  internal/topology/variables/clusterclass_variable_validation_test.go
  internal/topology/variables/schema.go
  internal/topology/variables/schema_test.go
  internal/webhooks/clusterclass_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6378 :sparkles: Add Nutanix Provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/reference/glossary.md
  docs/book/src/reference/providers.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6351 :bug: Downgrade golangci-lint to address gci autolint issues
  .github/workflows/golangci-lint.yml
  internal/webhooks/cluster_test.go
  internal/webhooks/clusterclass_test.go
  util/container/image.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6368 🌱 Add field.Path aggregation for Machine webhook
  api/v1beta1/machine_webhook.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6376 🌱 Add field.Path aggregation for MachineHealthCheck webhook
  api/v1beta1/machinehealthcheck_webhook.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6379 🌱 ClusterClass: Add topology field for NodeDrainTimeout
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/cluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/patches/engine.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6389 :seedling: Update coredns corefile migration to 1.0.15
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#6386 KubeadmConfig: add support passwd from secret
  bootstrap/kubeadm/api/v1alpha3/conversion.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha4/conversion.go
  bootstrap/kubeadm/api/v1alpha4/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook_test.go
  bootstrap/kubeadm/api/v1beta1/zz_generated.deepcopy.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  controlplane/kubeadm/api/v1alpha3/conversion.go
  controlplane/kubeadm/api/v1alpha4/conversion.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test

#6377 🌱 Add field.Path for MachineDeployment and MachinePool Webhooks
  api/v1beta1/machinedeployment_webhook.go
  exp/api/v1beta1/machinepool_webhook.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6406 :seedling: Add coredns corefile to dependabot config
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5762 ✨Add `clusterctl` options to show templates and cluster resource sets
  cmd/clusterctl/client/describe.go
  cmd/clusterctl/client/tree/annotations.go
  cmd/clusterctl/client/tree/discovery.go
  cmd/clusterctl/client/tree/discovery_test.go
  cmd/clusterctl/client/tree/options.go
  cmd/clusterctl/client/tree/tree.go
  cmd/clusterctl/client/tree/tree_test.go
  cmd/clusterctl/client/tree/util.go
  cmd/clusterctl/cmd/describe_cluster.go
  cmd/clusterctl/internal/scheme/scheme.go
  cmd/clusterctl/internal/test/fake_objects.go
  cmd/clusterctl/internal/test/providers/controlplane/generic_types.go
  cmd/clusterctl/internal/test/providers/controlplane/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test

#6414 :bug: [etcd] Bump go package to v3.5.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
  test/go.mod
  test/go.sum
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6419 :book: Correct a typo in the `MachinesSpecUpToDate` condition comment
  controlplane/kubeadm/api/v1alpha3/condition_consts.go
  controlplane/kubeadm/api/v1alpha4/condition_consts.go
  controlplane/kubeadm/api/v1beta1/condition_consts.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6392 :book: Update controlplane example in book
  docs/book/src/developer/architecture/controllers/control-plane.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6424 📖 Updated command to check provider expected variables
  docs/book/src/clusterctl/commands/init.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6426 📖 Add IBM Cloud provider quick start
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6420 🌱 update cert-manager to v1.7.2
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  docs/book/src/user/quick-start.md
  docs/book/src/user/troubleshooting.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#6431 🌱 test: retry controller-runtime client instantiation
  test/framework/cluster_proxy.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6436 🌱 fix linting
  bootstrap/util/configowner_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6435 📖 allow up to 20 tabs in book
  docs/book/theme/css/custom.css
Labels: size/S, cncf-cla: yes, lgtm, approved

#6441 🌱 Makefile: re-enable hack/tools on make help
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6383 ✨ Add API types for Runtime SDK ExtensionConfig
  .golangci.yml
  Makefile
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  config/manager/manager.yaml
  config/webhook/manifests.yaml
  exp/runtime/api/v1alpha1/doc.go
  exp/runtime/api/v1alpha1/extensionconfig_types.go
  exp/runtime/api/v1alpha1/groupversion_info.go
  exp/runtime/api/v1alpha1/zz_generated.deepcopy.go
  feature/feature.go
  internal/webhooks/runtime/doc.go
  internal/webhooks/runtime/extensionconfig_webhook.go
  internal/webhooks/runtime/extensionconfig_webhook_test.go
  main.go
  test/e2e/config/docker.yaml
Labels: cncf-cla: yes, lgtm, kind/feature, size/XXL, approved, area/runtime-sdk

#6446 🐛 use WaitForMachinePools to configure machine pool test waits
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6393 ✨ Implement Catalog for Runtime SDK
  go.mod
  go.sum
  hack/tools/go.sum
  internal/runtime/catalog/builder.go
  internal/runtime/catalog/catalog.go
  internal/runtime/catalog/doc.go
  internal/runtime/catalog/test/catalog_test.go
  internal/runtime/catalog/test/v1alpha1/fake_types.go
  internal/runtime/catalog/test/v1alpha2/fake_types.go
  test/go.sum
Labels: cncf-cla: yes, lgtm, kind/feature, size/XL, approved, area/runtime-sdk

#6451 📖 book: fix link to GitHub doc
  .markdownlinkcheck.json
  docs/book/src/clusterctl/provider-contract.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6390 :sparkles: Apply PodSecurityStandard in Secure Cluster Class
  docs/book/src/SUMMARY.md
  docs/book/src/security/index.md
  docs/book/src/security/pod-security-standards.md
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
  docs/book/src/user/quick-start.md
  test/infrastructure/docker/templates/cluster-template-development-topology.yaml
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#6430 🐛 clusterctl: retry github i/o operations
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6456 🐛 RuntimeSDK: include ExtensionConfig CRD in generated core manifest
  config/crd/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6460 🌱 CAPD: Add docker mount to worker nodes
  test/infrastructure/docker/templates/cluster-template-development.yaml
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#6461 🐛 clusterctl: retry github i/o operations
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6452 🌱 Update promote-images to filter by image and sort by tag
  Makefile
  scripts/go_install.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6453 🌱 Replace deprecated strings.Title with cases.Title
  go.mod
  util/record/recorder.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6437 🌱 test: actually retry controller-runtime client instantiation
  test/framework/cluster_proxy.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6411 ✨ RuntimeSDK: Add extension config controller skeleton
  Makefile
  config/rbac/role.yaml
  exp/runtime/controllers/alias.go
  exp/runtime/controllers/doc.go
  exp/runtime/internal/controllers/doc.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  main.go
Labels: cncf-cla: yes, lgtm, size/L, approved
