Repository kubernetes-sigs/cluster-api, pull requests merged in 2022-09, with the labels that each got.

#7110 📖 Add release team process
  CONTRIBUTING.md
  docs/developer/release-team.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#7135 🌱 Upgrade golang version (1.18.3 -> 1.19.0)
  .github/workflows/dependabot.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/release.yml
  .golangci.yml
  Makefile
  Tiltfile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  hack/ensure-go.sh
  netlify.toml
Labels: cncf-cla: yes, lgtm, size/M, approved

#7141 [release-1.2] 🌱 test/e2e: Extend ClusterClass changes test to cover InfrastructureMachineTemplate rotation
  test/e2e/clusterclass_changes.go
  test/e2e/clusterclass_changes_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7142 📖 Fix third_party link to version 1.2
  docs/book/src/developer/repository-layout.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7095 ✨ Integrate kube-state-metrics and CR config into tilt.
  Makefile
  Tiltfile
  docs/book/src/developer/tilt.md
  hack/observability/kube-state-metrics/chart/kustomization.yaml
  hack/observability/kube-state-metrics/chart/values.yaml
  hack/observability/kube-state-metrics/crd-config.yaml
  hack/observability/kube-state-metrics/kustomization.yaml
  hack/observability/kube-state-metrics/metrics/README.md
  hack/observability/kube-state-metrics/metrics/cluster.yaml
  hack/observability/kube-state-metrics/metrics/common_metrics.yaml
  hack/observability/kube-state-metrics/metrics/header.yaml
  hack/observability/kube-state-metrics/metrics/kubeadmcontrolplane.yaml
  hack/observability/kube-state-metrics/metrics/machine.yaml
  hack/observability/kube-state-metrics/metrics/machinedeployment.yaml
  hack/observability/kube-state-metrics/metrics/machinehealthcheck.yaml
  hack/observability/kube-state-metrics/metrics/machineset.yaml
  hack/observability/kube-state-metrics/metrics/owner_metric.yaml
Labels: cncf-cla: yes, lgtm, size/XXL, approved, needs-triage

#7144 📖 book: fix broken link in Contributing
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7018 🌱 Update Cluster API Visualizer chart to v1.0.0
  hack/observability/visualizer/kustomization.yaml
  hack/observability/visualizer/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#7139 🌱 tilt: fix promtail values.yaml tow work with loki
  hack/observability/promtail/values.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#7153 🐛 Fix Makefile target
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6934 ✨ Add `clusterctl init list-images` command
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/cmd/init_list_images.go
  docs/book/src/clusterctl/commands/additional-commands.md
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/developer/providers/v1.2-to-v1.3.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#7097 🌱 Add make targets for setting up Tilt
  Makefile
  docs/book/src/developer/tilt.md
  hack/kind-install-for-capd.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-triage

#6918 :seedling: Add more patches to test extension
  internal/controllers/topology/cluster/patches/variables/errors.go
  internal/controllers/topology/cluster/patches/variables/value.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-topology.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/cluster-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/mp-default-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start-runtimesdk.yaml
  test/extension/config/tilt/hookresponses-configmap.yaml
  test/extension/handlers/topologymutation/handler.go
  test/extension/handlers/topologymutation/handler_test.go
  test/extension/handlers/topologymutation/lib.go
  test/extension/main.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#7159 🐛 util/record: fix usage of case.Title in util/record
  util/record/recorder.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7163 🌱 Fix typo in godoc
  internal/controllers/machine/machine_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved

#7166 ✨ Add missing status_replicas_ready metric for MachineDeployments at kube-state-metrics
  hack/observability/kube-state-metrics/crd-config.yaml
  hack/observability/kube-state-metrics/metrics/machinedeployment.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#7152 🌱 logging: adjust reconcilers to log object owners
  Tiltfile
  bootstrap/kubeadm/config/rbac/role.yaml
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  docs/book/src/developer/logging.md
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  exp/internal/controllers/machinepool_controller_phases.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  test/infrastructure/docker/config/rbac/role.yaml
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  util/log/doc.go
  util/log/log.go
  util/log/log_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7164 🌱 remove image tag pinning for kube-state-metrics
  hack/observability/kube-state-metrics/chart/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7156 ⚠️ Use Kubernetes 1.25 in Quick Start docs and CAPD.
  .gitignore
  Tiltfile
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/framework/deployment_helpers.go
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
  test/infrastructure/docker/internal/docker/machine.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7169 🌱 Update shellcheck version (0.7.0->0.8.0)
  hack/verify-shellcheck.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7026 🌱 Improve logging for the MachineSet scale up/down workflow
  internal/controllers/machineset/machineset_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved, triage/accepted

#7181 🌱 hack/observability: pin charts
  hack/observability/grafana/kustomization.yaml
  hack/observability/kube-state-metrics/chart/kustomization.yaml
  hack/observability/loki/kustomization.yaml
  hack/observability/prometheus/kustomization.yaml
  hack/observability/promtail/kustomization.yaml
  hack/observability/visualizer/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7184 🌱 make clusterctl in tiltprepare
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7146 📖 book: set v1.1.x EOL date
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7190 🌱 hack/observability: disable PSP for Grafana to support Kubernetes v1.25
  hack/observability/grafana/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7189 :book: Add "KCP" to glossary
  docs/book/src/reference/glossary.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#7193 🌱 Update kubebuilder envtest (1.24.2 -> 1.25.0)
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7194 🌱 Update versions doc adding Kubernetes 1.25
  docs/book/src/developer/providers/version-migration.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#7196 📖 docs update jobs.md
  docs/book/src/reference/jobs.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#7195 [release-1.2] 🌱 Update versions doc adding Kubernetes 1.25
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#7203 :bug: Update book to properly set label in tilt file
  docs/book/src/developer/tilt.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7206 📖 🌱 DR --> disaster recovery
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#7207 📖 Update Equinix Metal quick start tab.
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#7205 🌱 CAPD: add columns to DockerMachine CRD
  test/infrastructure/docker/api/v1beta1/dockermachine_types.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7211 🌱 Bump controller-runtime to use new Kubernetes Go libraries
  .golangci.yml
  Makefile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go
  bootstrap/kubeadm/main.go
  cmd/clusterctl/client/cluster/internal/dryrun/client.go
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/controllers/fakes_test.go
  controlplane/kubeadm/main.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  test/extension/main.go
  test/framework/interfaces.go
  test/go.mod
  test/go.sum
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#7185 🌱 tilt-prepare: cleanup outdated Charts automatically
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tilt-prepare/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7208 ✨ Enable linters: asasalint, bidichk, durationcheck, errchkjson. Fix findings
  .golangci.yml
  docs/Dockerfile
  test/infrastructure/docker/Dockerfile
  util/conditions/matcher.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#7200 🌱 Update references following Flatcar GitHub org rename
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/internal/ignition/clc/clc.go
  bootstrap/kubeadm/internal/ignition/clc/clc_test.go
  docs/book/src/tasks/experimental-features/ignition.md
  go.mod
  go.sum
  test/go.mod
  test/go.sum
  test/infrastructure/docker/internal/provisioning/ignition/kindadapter.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7217 [release-1.2] 🌱 Update references following Flatcar GitHub org rename
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/internal/ignition/clc/clc.go
  bootstrap/kubeadm/internal/ignition/clc/clc_test.go
  docs/book/src/tasks/experimental-features/ignition.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.mod
  test/go.sum
  test/infrastructure/docker/internal/provisioning/ignition/kindadapter.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7172 🌱 test/e2e: Drop support for Kubernetes < v1.24.0 in the RuntimeSDK upgrade test
  test/e2e/Makefile
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/cluster_upgrade_runtimesdk_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/cluster-template-upgrades-runtimesdk-cgroupfs/mp-default-cgroupfs.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#7183 📖 Sync cluster-api-state-metrics proposal to match implementation state.
  docs/proposals/20220411-cluster-api-state-metrics.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#7219 🌱 Add makefile test targets for test extension
  Makefile
  scripts/ci-test.sh
Labels: size/S, cncf-cla: yes, lgtm, approved

#7220 📖 docs/releasing: add note about homebrew PR commit message
  docs/developer/releasing.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7218 🌱 Replace CAPI Matcher with Controller Runtime implementation
  docs/book/src/developer/testing.md
  internal/controllers/machine/machine_controller_test.go
  internal/controllers/machinedeployment/machinedeployment_sync_test.go
  internal/controllers/topology/cluster/blueprint_test.go
  internal/controllers/topology/cluster/current_state_test.go
  internal/controllers/topology/cluster/patches/engine_test.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/util_test.go
  internal/test/matchers/doc.go
  internal/test/matchers/matchers.go
  internal/test/matchers/matchers_test.go
  test/extension/handlers/topologymutation/handler_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#7223 🌱 Enable more gocritic diagnostic and performance linters
  .golangci.yml
  exp/internal/controllers/machinepool_controller.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  test/framework/bootstrap/kind_provider.go
  test/framework/kubetest/run.go
  test/infrastructure/docker/exp/internal/docker/nodepool.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7225 🐛 Fix bug in Tilt where Cluster template namespace is ignored
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7232 🌱 Fix spelling in log message (cluter -> cluster)
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/clusterclass.go
  cmd/clusterctl/client/repository/client.go
  main.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7236 🌱 grammar: replace all occurrences of "the the" with "the"
  Dockerfile
  Makefile
  cmd/clusterctl/Dockerfile
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/cluster/components.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/internal/test/fake_proxy.go
  docs/proposals/20200804-windows-support.md
  internal/controllers/topology/cluster/scope/state.go
  test/e2e/e2e_suite_test.go
  test/extension/Dockerfile
  test/framework/alltypes_helpers.go
  test/framework/controlplane_helpers.go
  util/conditions/getter.go
  util/conditions/merge.go
  util/conditions/setter.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6983 ✨ Automatically renew control plane machine certificates before expiration through machine repave
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/machine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  controlplane/kubeadm/api/v1alpha3/conversion.go
  controlplane/kubeadm/api/v1alpha3/zz_generated.conversion.go
  controlplane/kubeadm/api/v1alpha4/conversion.go
  controlplane/kubeadm/api/v1alpha4/zz_generated.conversion.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_types.go
  controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_webhook.go
  controlplane/kubeadm/api/v1beta1/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  controlplane/kubeadm/internal/control_plane.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/machine/machine_controller_phases_test.go
  test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
  util/collections/machine_filters.go
  util/collections/machine_filters_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#7249 :book: update quickstart with link to the new Nutanix doc website
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#7251 📖 Fix link for complex variable types
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6413 ✨ Add nodeVolumeDetachTimeout property to Machine
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/machine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controlplane/kubeadm/api/v1alpha3/conversion.go
  controlplane/kubeadm/api/v1alpha4/conversion.go
  controlplane/kubeadm/api/v1alpha4/zz_generated.conversion.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_types.go
  controlplane/kubeadm/api/v1beta1/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha4/conversion.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#7254 📖 Add CAPM3 to glossary
  docs/book/src/reference/glossary.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7253 [release-1.2] 📖🌱 Collection of fixes and improvements for provider implementer's guide and Tilt workflow
  docs/book/src/developer/providers/contracts.md
  docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
  docs/book/src/developer/providers/implementers-guide/configure.md
  docs/book/src/developer/providers/implementers-guide/controllers_and_reconciliation.md
  docs/book/src/developer/providers/implementers-guide/generate_crds.md
  docs/book/src/developer/providers/implementers-guide/naming.md
  docs/book/src/developer/tilt.md
  hack/tools/tilt-prepare/main.go
  util/conversion/conversion.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7264 🐛 Tiltfile: remove USER instruction from Dockerfile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7240 📖Add GitHub PAT doc
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/configuration.md
  docs/book/src/clusterctl/overview.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#7262 🌱 Upgrade to controller-tools v0.10, finalize upgrade to kind v0.15.0
  Makefile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#7228 :seedling: support clusterctl generate cluster with templates from stdin
  cmd/clusterctl/client/cluster/template.go
  cmd/clusterctl/client/cluster/template_test.go
  cmd/clusterctl/cmd/generate_cluster.go
  docs/book/src/clusterctl/commands/generate-cluster.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#7267 🌱 Fix the lint error on main
  cmd/clusterctl/client/cluster/template_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7269 🌱 Improve logging in test/framework
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  test/framework/clusterctl/client.go
  test/framework/clusterctl/logger/log_file.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#7261 🐛 test/e2e: fix duplicate mount in CAPD test
  test/e2e/clusterclass_changes_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7271 🌱 CAPD: make Machine bootstrap reentrant
  test/infrastructure/docker/api/v1beta1/dockermachine_types.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/exp/api/v1beta1/dockermachinepool_types.go
  test/infrastructure/docker/exp/internal/docker/nodepool.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/docker/internal/docker/machine.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7275 🌱 Loki: increase Loki ingestion limits for log-push
  hack/observability/loki/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7005 ✨ clusterctl: Add move --to-directory and --from-directory flags
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/move.go
  cmd/clusterctl/client/move_test.go
  cmd/clusterctl/cmd/backup.go
  cmd/clusterctl/cmd/move.go
  cmd/clusterctl/cmd/restore.go
  docs/book/src/clusterctl/commands/additional-commands.md
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/developer/providers/v1.2-to-v1.3.md
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-triage

#7277 🌱 Update typo in cert_manager.go
  cmd/clusterctl/client/config/cert_manager.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#7276 🌱 Bump kind to v0.16.0
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#7270 📖 document how to manually test Runtime Extensions
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#7282 🌱 grammar: remove duplicate words
  api/v1alpha3/machineset_types.go
  api/v1alpha4/machineset_types.go
  api/v1beta1/machineset_types.go
  api/v1beta1/zz_generated.openapi.go
  bootstrap/kubeadm/api/v1alpha3/condition_consts.go
  bootstrap/kubeadm/api/v1alpha4/condition_consts.go
  bootstrap/kubeadm/api/v1beta1/condition_consts.go
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/proxy.go
  cmd/clusterctl/client/config/client.go
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  cmd/clusterctl/log/doc.go
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controlplane/kubeadm/api/v1alpha3/condition_consts.go
  controlplane/kubeadm/api/v1alpha4/condition_consts.go
  controlplane/kubeadm/api/v1beta1/condition_consts.go
  docs/book/src/clusterctl/developers.md
  hack/ensure-golangci-lint.sh
  test/e2e/config/docker.yaml
  test/framework/clusterctl/e2e_config.go
  util/conditions/unstructured.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7235 ✨ add NodeVolumeDetachTimeout support for Cluster Topology
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/cluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  internal/contract/controlplane.go
  internal/contract/controlplane_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/patches/engine.go
  test/e2e/data/infrastructure-docker/v1beta1/bases/cluster-with-topology.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#7242 🌱 ClusterClass: make patch selector validation more robust
  internal/webhooks/patch_validation.go
  internal/webhooks/patch_validation_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7285 📖 add link to Kubernetes proxies in Runtime Extensions doc
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7167 📖 clarify backport-policy
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7209 🌱 Add oscr to cluster-api-docs-reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7199 ✨ Add support to configure MachineHealthChecks for managed Clusters
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/cluster_types.go
  api/v1beta1/clusterclass_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  hack/tools/runtime-openapi-gen/vendored_openapi.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/scope/blueprint.go
  internal/controllers/topology/cluster/scope/blueprint_test.go
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
  internal/webhooks/clusterclass.go
  internal/webhooks/clusterclass_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#7243 🌱 ClusterClass: relax validation of MD variables overrides of opt variables
  internal/topology/variables/cluster_variable_validation.go
  internal/topology/variables/cluster_variable_validation_test.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7284 📖 book: update job documentation + add test-infra config
  docs/book/src/reference/jobs.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#7299 🌱 Bump flect to v0.3.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#7303 🐛 bump kindnetd to v20220927-ce36d7c0 to fix routes on self-hosted upgrades
  test/e2e/data/cni/kindnet/kindnet.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7231 ✨ ClusterClass: use exact versions from ClusterClass, stop api bump in CC
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/topology/cluster/current_state.go
  internal/controllers/topology/cluster/current_state_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/dryrun_test.go
  internal/controllers/topology/cluster/util.go
  internal/controllers/topology/cluster/util_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#7306 [release-1.2] ✨ ClusterClass: use exact versions from ClusterClass, stop api bump in CC
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/topology/cluster/current_state.go
  internal/controllers/topology/cluster/current_state_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/dryrun_test.go
  internal/controllers/topology/cluster/util.go
  internal/controllers/topology/cluster/util_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#7304 🌱 Bump kpromo to v3.4.5
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7290 📖 document migrating to user-managed cert-manager
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/configuration.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#7244 🌱 test/e2e: Add clusterctl upgrade with ClusterClass test
  .gitignore
  test/e2e/Makefile
  test/e2e/clusterctl_upgrade.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/README.md
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/cluster-with-topology.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/crs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-ignition/ignition.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-ignition/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-ipv6/cluster-ipv6.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-ipv6/kcp-ipv6.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-ipv6/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-ipv6/md-ipv6.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-kcp-adoption/step1/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-kcp-adoption/step2/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-kcp-remediation/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-kcp-remediation/mhc.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-kcp-scale-in/kcp-scale-in-variable.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-kcp-scale-in/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-machine-pool/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-md-remediation/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-md-remediation/md.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-md-remediation/mhc.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-node-drain/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-node-drain/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-node-drain/md.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-topology/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-upgrades-cgroupfs/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-upgrades-cgroupfs/mp-default-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-upgrades-runtimesdk/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-upgrades/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/clusterclass-quick-start-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-docker/v1beta1/v1.2/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/v1.2/bases/cluster-with-topology.yaml
  test/e2e/data/infrastructure-docker/v1beta1/v1.2/bases/crs.yaml
  test/e2e/data/infrastructure-docker/v1beta1/v1.2/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1beta1/v1.2/cluster-template-topology/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/v1.2/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/v1.2/clusterclass-quick-start.yaml
  test/e2e/data/shared/v1beta1/main/metadata.yaml
  test/e2e/data/shared/v1beta1/v1.2/metadata.yaml
  test/framework/clusterctl/client.go
  test/framework/clusterctl/clusterctl_config.go
  test/framework/clusterctl/clusterctl_helpers.go
  test/framework/clusterctl/repository.go
  test/framework/machinedeployment_helpers.go
  test/infrastructure/docker/internal/docker/types/node.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#7310 🐛 Update ClusterResourceSetBinding owner references
  exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7315 📖 Fix spelling of enhancement
  CONTRIBUTING.md
  docs/proposals/YYYYMMDD-template.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6636 🌱 add preCreateCluster hook and CNIPath to e2e clusterctl upgrade test
  test/e2e/clusterctl_upgrade.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#7316 🌱 add PreWaitForCluster hook and CNIPath to e2e clusterctl upgrade test
  test/e2e/clusterctl_upgrade.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#7298 📖 book: add doc about Cluster API updates with ClusterClass
  docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#7323 🌱 teste/e2e: tag clusterctl ClusterClass test with [ClusterClass]
  test/e2e/clusterctl_upgrade_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7297 ⚠️ contract: add CRD naming requirements
  cmd/clusterctl/client/cluster/topology.go
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/architecture/controllers/machine-pool.md
  docs/book/src/developer/providers/bootstrap.md
  docs/book/src/developer/providers/cluster-infrastructure.md
  docs/book/src/developer/providers/machine-infrastructure.md
  internal/test/builder/crds.go
  util/contract/contract.go
  util/contract/doc.go
  util/util.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7260 📖 Improve provider definition in the glossary
  docs/book/src/reference/glossary.md
  docs/book/src/user/concepts.md
  docs/proposals/20220221-runtime-SDK.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#7317 ✨ Update ginkgo (2.1.4 -> 2.2.0) and set poll-progress-after and poll-p…
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/Makefile
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved
