Repository kubernetes-sigs/cluster-api, pull requests merged in 2022-01, with the labels that each got.

#5887 📖 Add OPENSTACK_EXTERNAL_NETWORK_ID for openstack
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5889 🌱 Add timeout to check if KCP object exists
  test/framework/controlplane_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#5821 🌱 modify providerid struct string method to receive value
  controllers/noderefutil/providerid.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#5869 ✨Set default KubeadmConfig format to cloud-config✨
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5895 📖 Update link to community meeting notes
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5900 🌱 test/e2e/framework: log kind output during cluster creation
  test/framework/bootstrap/kind_provider.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5901 🐛 capd: fix logContainerDebugInfo
  test/infrastructure/docker/internal/docker/machine.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#5902 🌱 test/clusterctl-upgrade: also cleanup v1alpha4 clusters
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5904 🐛 kcp: make KubeadmConfig format mutable
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
  test/e2e/clusterctl_upgrade.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#5909 🌱 Add timeout to check if KCP object exists
  test/framework/controlplane_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#5911 :seedling: OWNERS: Remove randomvariable (Naadir Jeewa)
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5905 📖 Update quick start doc for CAPZ
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#5907 🌱 Add timeout to check if KCP object exists
  test/framework/controlplane_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#5903 🌱 Upgrade to kustomize v4.4.1
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  hack/ensure-kustomize.sh
  hack/observability/.gitignore
  hack/observability/kustomization.yaml
  hack/tools/tilt-prepare/main.go
  test/e2e/Makefile
Labels: cncf-cla: yes, lgtm, size/M, approved

#5912 🌱 Upgrade to controller-tools v0.8.0
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#5908 🌱 test/framework: improve logging of RunErrors occurring when bootstrap cluster creation fails
  test/framework/bootstrap/kind_provider.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#5913 🌱 Move controllers to internal - part2
  controllers/alias.go
  controllers/schema_test.go
  controllers/topology/internal/scope/state.go
  docs/book/src/developer/providers/v1.0-to-v1.1.md
  internal/controllers/machinedeployment/doc.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller_test.go
  internal/controllers/machinedeployment/machinedeployment_rolling.go
  internal/controllers/machinedeployment/machinedeployment_rolling_test.go
  internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
  internal/controllers/machinedeployment/machinedeployment_sync.go
  internal/controllers/machinedeployment/machinedeployment_sync_test.go
  internal/controllers/machinedeployment/mdutil/doc.go
  internal/controllers/machinedeployment/mdutil/util.go
  internal/controllers/machinedeployment/mdutil/util_test.go
  internal/controllers/machinedeployment/suite_test.go
  internal/controllers/machinehealthcheck/doc.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_status_matcher_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
  internal/controllers/machinehealthcheck/suite_test.go
  internal/controllers/machineset/doc.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_controller_test.go
  internal/controllers/machineset/machineset_delete_policy.go
  internal/controllers/machineset/machineset_delete_policy_test.go
  internal/controllers/machineset/suite_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5915 🌱 ClusterClass: make ControlPlane.spec.machineTemplate.nodeDrainTimeout patchable
  controllers/topology/internal/extensions/patches/engine.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5841 📖 Restructure ClusterClass documentation
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/experimental-features/cluster-class/change-clusterclass.md
  docs/book/src/tasks/experimental-features/cluster-class/index.md
  docs/book/src/tasks/experimental-features/cluster-class/upgrade-cluster.md
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
  docs/book/src/tasks/experimental-features/cluster-classes.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  docs/book/src/tasks/experimental-features/yamls/clusterclass-quickstart.yaml
  docs/book/src/tasks/experimental-features/yamls/clusterclass.yaml
  docs/book/src/tasks/experimental-features/yamls/kindnet-clusterresourceset.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5910 🌱 Collect kind logs when e2e bootstrap fails
  docs/book/src/developer/providers/v1.0-to-v1.1.md
  test/e2e/e2e_suite_test.go
  test/framework/bootstrap/kind_provider.go
  test/framework/bootstrap/kind_util.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#5922 🌱 Improve managed field annotation encoding
  internal/controllers/topology/cluster/mergepatch/managed_paths.go
  internal/controllers/topology/cluster/mergepatch/managed_paths_test.go
  internal/controllers/topology/cluster/mergepatch/mergepatch.go
  internal/controllers/topology/cluster/mergepatch/mergepatch_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5511 📖 Add MHCClass spec and details to proposal
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#5923 📖Added KubeVirt to the providers list
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#5926 🐛 test/e2e/cluster-upgrade: skip worker upgrades if worker count is 0
  test/e2e/cluster_upgrade.go
  test/framework/cluster_topology_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5573 🌱 Check for build metadata in cert-manager version
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
  internal/contract/controlplane.go
  util/version/version.go
  util/version/version_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#5929 🌱 Move KCP controllers to internal
  Makefile
  controlplane/kubeadm/controllers/alias.go
  controlplane/kubeadm/internal/controllers/consts.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/doc.go
  controlplane/kubeadm/internal/controllers/fakes_test.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/remediation_test.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/controllers/status.go
  controlplane/kubeadm/internal/controllers/status_test.go
  controlplane/kubeadm/internal/controllers/suite_test.go
  controlplane/kubeadm/internal/controllers/upgrade.go
  controlplane/kubeadm/internal/controllers/upgrade_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5925 🐛 ClusterClass: allow accessing nestedFields via valueFrom.variable
  internal/webhooks/patch_validation.go
  internal/webhooks/patch_validation_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5873 ✨ add MHC generation from ClusterClass
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/clusterclass_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/rbac/role.yaml
  internal/controllers/topology/cluster/blueprint.go
  internal/controllers/topology/cluster/blueprint_test.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/current_state.go
  internal/controllers/topology/cluster/current_state_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/scope/blueprint.go
  internal/controllers/topology/cluster/scope/state.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller_test.go
  internal/test/builder/builders.go
  internal/webhooks/clusterclass.go
  internal/webhooks/clusterclass_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#5846 🌱 ClusterClass: Add reconcile repeatedly test
  internal/controllers/topology/cluster/mergepatch/managed_paths.go
  internal/controllers/topology/cluster/mergepatch/managed_paths_test.go
  internal/controllers/topology/cluster/mergepatch/mergepatch.go
  internal/controllers/topology/cluster/mergepatch/mergepatch_test.go
  internal/controllers/topology/cluster/reconcile_state_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#5943 🐛 Drop links to Kubernetes discuss forum.
  CONTRIBUTING.md
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5935 🌱 block +2 minor version upgrade in cluster topology
  docs/book/src/tasks/experimental-features/cluster-class/upgrade-cluster.md
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5950 🐛 Make Topology controller authoritative on MachineDeployment failuredomain
  internal/controllers/topology/cluster/reconcile_state.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5951 🌱 ClusterClass: validate MachineDeployment topology name not empty
  internal/topology/check/compatibility.go
  internal/topology/check/compatibility_test.go
  internal/webhooks/cluster.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5947 📖 Add steps to resolve Docker Desktop inotify limit issues
  docs/book/src/user/troubleshooting.md
Labels: size/S, cncf-cla: yes, lgtm, kind/documentation, approved

#5897 ✨ Add Patches field in InitConfiguration and JoinConfiguration
  bootstrap/kubeadm/api/v1alpha3/conversion.go
  bootstrap/kubeadm/api/v1alpha4/conversion.go
  bootstrap/kubeadm/api/v1alpha4/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
  bootstrap/kubeadm/api/v1beta1/zz_generated.deepcopy.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  bootstrap/kubeadm/types/upstreamv1beta1/conversion.go
  bootstrap/kubeadm/types/upstreamv1beta1/conversion_test.go
  bootstrap/kubeadm/types/upstreamv1beta1/zz_generated.conversion.go
  bootstrap/kubeadm/types/upstreamv1beta2/conversion.go
  bootstrap/kubeadm/types/upstreamv1beta2/conversion_test.go
  bootstrap/kubeadm/types/upstreamv1beta2/zz_generated.conversion.go
  bootstrap/kubeadm/types/upstreamv1beta3/types.go
  bootstrap/kubeadm/types/upstreamv1beta3/zz_generated.conversion.go
  bootstrap/kubeadm/types/upstreamv1beta3/zz_generated.deepcopy.go
  controlplane/kubeadm/api/v1alpha3/conversion.go
  controlplane/kubeadm/api/v1alpha4/conversion.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  docs/book/src/tasks/kubeadm-bootstrap.md
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test

#5928 ✨ ClusterClass: implement MachineDeployment variable overrides
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/cluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  internal/controllers/topology/cluster/patches/variables/variables.go
  internal/controllers/topology/cluster/patches/variables/variables_test.go
  internal/test/builder/builders.go
  internal/topology/variables/cluster_variable_defaulting.go
  internal/topology/variables/cluster_variable_defaulting_test.go
  internal/topology/variables/cluster_variable_validation.go
  internal/topology/variables/cluster_variable_validation_test.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
  internal/webhooks/clusterclass.go
  internal/webhooks/clusterclass_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#5932 🐛 Fix to improper formatting of UnhealthyRange
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5949 🐛 Make MHC ClusterClass authoritative on paths
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5934 🌱 Test rolling update scale-in doesn't race machine deletion
  internal/controllers/machinedeployment/machinedeployment_rolling_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#5954 📖 ClusterClass: restructure documentation
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/commands/alpha-topology-plan.md
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/clusterctl/commands/config-cluster.md
  docs/book/src/tasks/experimental-features/cluster-class/index.md
  docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#5958 🌱 book: add API conversion code walkthrough video
  docs/book/src/developer/guide.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5962 🌱 make release-notes for pre-releases
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5960 ✨ improvements to `clusterctl alpha topology plan`
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/assets/topology-test/existing-my-cluster.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/existing-my-second-cluster.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/mock-CRDs.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/modified-CP-dockermachinetemplate.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/modified-my-cluster.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/my-cluster-class.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/objects-in-different-namespaces.yaml
  cmd/clusterctl/client/cluster/topology.go
  cmd/clusterctl/client/cluster/topology_test.go
  cmd/clusterctl/client/topology.go
  cmd/clusterctl/cmd/alpha.go
  cmd/clusterctl/cmd/topology.go
  cmd/clusterctl/cmd/topology_plan.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#5955 🌱 envtest: use Kubernetes 1.23.1
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5972 🌱 Update Docker and containerd dependencies
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#5964 🌱 Validate OWNERS files - remove sections about emeritus reviewers.
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/cleanup, ok-to-test

#5959 🌱 linter: enable noctx and unused
  .golangci.yml
  cmd/clusterctl/client/config/reader_viper.go
  cmd/clusterctl/client/repository/repository_github.go
  hack/tools/mdbook/embed/embed.go
  hack/tools/mdbook/releaselink/releaselink.go
  test/e2e/clusterctl_upgrade.go
  test/framework/clusterctl/repository.go
  test/framework/kubernetesversions/versions.go
  test/infrastructure/container/docker.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5974 🌱 Fix a typo in remediation.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/remediation_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#5977 🐛 Fix spelling errors
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/config.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5979 🌱 book: add TGIK ClusterClass video
  docs/book/src/developer/guide.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5976 🌱 ClusterClass: add MD variables to the ClusterClass proposal
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#5980 📖 Add HasPausedAnnotation and HasSkipRemediationAnnotation func deprecation notes to v1.0-v1.1 migration doc
  docs/book/src/developer/providers/v1.0-to-v1.1.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#5971 🐛 Remove generated names from error messages to reduce reconciliation
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#5969 🐛 handle error in case ownerRef is not set on crs binding
  exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#5994 📖 ClusterClass: fix YAMLs in proposal
  docs/proposals/202105256-cluster-class-and-managed-topologies.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6002 🌱 Remove pull-cluster-api-make-main job related script
  docs/book/src/reference/jobs.md
  scripts/ci-make.sh
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#5998 📖 book: Add note about Kubernetes v1.23.{0-2} CRD issue and ClusterClass
  docs/book/src/reference/versions.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#5986 🐛 Allow KCP to Update when CoreDNS version doesn't change
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#5999 :sparkles: Upgrade to Kubernetes 1.23.3 in Quickstart and CI
  CONTRIBUTING.md
  docs/book/src/user/quick-start.md
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/infrastructure/docker/Dockerfile
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
  test/infrastructure/docker/internal/docker/machine.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6013 🌱 Use kubebuilder envtest v1.23.3
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6003 🐛 Allow KCP to Update when CoreDNS version doesn't change
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6004 🐛 Allow KCP to Update when CoreDNS version doesn't change
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#5987 🐛 inline builders in test for MHC reconcilation
  Makefile
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/test/builder/builders.go
  internal/test/builder/doc.go
  internal/test/builder/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6009 📖 documentation for `clusterctl alpha topology plan`
  docs/book/src/clusterctl/commands/alpha-topology-plan.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#5997 📖 book: add Writing a ClusterClass doc
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6018 📖 book: add v1.1=>v1.2 migration doc
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/v0.3-to-v0.4.md
  docs/book/src/developer/providers/v0.4-to-v1.0.md
  docs/book/src/developer/providers/v1.1-to-v1.2.md
  docs/book/src/developer/providers/v1alpha1-to-v1alpha2.md
  docs/book/src/developer/providers/v1alpha2-to-v1alpha3.md
  docs/book/src/tasks/upgrading-cluster-api-versions.md
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6028 🐛 Point broken links to older book version
  docs/book/src/developer/providers/implementers-guide/generate_crds.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6014 🌱 Upgrade to golangci-lint v1.44 and fix findings
  .github/workflows/golangci-lint.yml
  .golangci.yml
  cmd/clusterctl/client/alpha/rollout_pauser.go
  cmd/clusterctl/client/alpha/rollout_restarter.go
  cmd/clusterctl/client/alpha/rollout_resumer.go
  cmd/clusterctl/client/client_test.go
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/common.go
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config/reader_viper.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/delete.go
  cmd/clusterctl/cmd/config_repositories.go
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
  internal/webhooks/clusterclass_test.go
  test/framework/clusterctl/logger/log_file.go
  test/framework/docker_logcollector.go
  test/framework/ginkgoextensions/output.go
  test/framework/kubetest/setup.go
  test/infrastructure/container/docker.go
  test/infrastructure/docker/api/v1beta1/dockercluster_webhook.go
  test/infrastructure/docker/internal/docker/machine.go
Labels: cncf-cla: yes, lgtm, size/L, approved
