Repository kubernetes-sigs/cluster-api, pull requests merged in 2022-10, with the labels that each got.

#7334 🌱 Add ok-to-test label to dependabot prs
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7288 ✨ Support IPAM and runtime extension providers
  Makefile
  Tiltfile
  cmd/clusterctl/api/v1alpha3/labels.go
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/delete.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/cmd/delete.go
  cmd/clusterctl/cmd/generate_provider.go
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/cmd/init_list_images.go
  cmd/clusterctl/cmd/upgrade_apply.go
  cmd/clusterctl/hack/create-local-repository.py
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/developer/tilt.md
  hack/tools/tilt-prepare/main.go
  test/e2e/Makefile
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/clusterctl_upgrade.go
  test/e2e/config/docker.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/self_hosted.go
  test/extension/Dockerfile
  test/extension/config/certmanager/certificate.yaml
  test/extension/config/default/kustomization.yaml
  test/extension/config/default/manager.yaml
  test/extension/config/default/manager_image_patch.yaml
  test/extension/config/default/manager_pull_policy.yaml
  test/extension/config/default/manager_webhook_patch.yaml
  test/extension/config/default/namespace.yaml
  test/extension/config/default/role.yaml
  test/extension/config/default/rolebinding.yaml
  test/extension/config/default/service.yaml
  test/extension/config/default/service_account.yaml
  test/extension/config/tilt/extensionconfig.yaml
  test/extension/config/tilt/hookresponses-configmap.yaml
  test/extension/handlers/lifecycle/handlers.go
  test/framework/clusterctl/client.go
  test/framework/clusterctl/clusterctl_helpers.go
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/repository.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#7350 🌱 Bump to Go 1.18.7
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7345 :bug: Remove unique patch ID from TopologyReconcile conditions
  internal/controllers/topology/cluster/patches/engine.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#7329 🌱 Remove test/e2e/Makefile and move targets to root Makefile
  Makefile
  docs/book/src/developer/testing.md
  scripts/ci-e2e.sh
  test/e2e/Makefile
Labels: cncf-cla: yes, lgtm, size/L, approved

#7351 :seedling: Make KCP diskSetup field mutable
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6336 ✨Add logging for machine node watcher
  internal/controllers/machine/machine_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#7349 🌱 Bump to Go 1.19.2
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7356 :bug: Don't retry health check when Unauthorized is returned
  controllers/remote/cluster_cache_tracker.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#7239 ✨ adjust self-hosted e2e test to also upgrade the cluster
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/cluster-with-topology.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/clusterclass-quick-start.yaml
  test/e2e/self_hosted.go
  test/e2e/self_hosted_test.go
  test/framework/cluster_proxy.go
  test/framework/clusterctl/client.go
  test/framework/clusterctl/clusterctl_helpers.go
  test/framework/convenience.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7259 🌱 ClusterClass: add condition for references with outdated apiVersions
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/clusterclass_types.go
  api/v1beta1/condition_consts.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/rbac/role.yaml
  internal/controllers/clusterclass/clusterclass_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7363 🐛 Bump gcb-docker-gcloud image to fix nightly image/manifest push
  cloudbuild-nightly.yaml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7355 🌱 Detect certificate expiry from kube-apiserver serving cert
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/fakes_test.go
  controlplane/kubeadm/internal/etcd_client_generator.go
  controlplane/kubeadm/internal/proxy/proxy.go
  controlplane/kubeadm/internal/workload_cluster.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7364 [release-1.2] 🌱 clusterctl: support envsubst in clusterctl config
  cmd/clusterctl/client/config/cert_manager_client.go
  cmd/clusterctl/client/config/cert_manager_client_test.go
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config/providers_client_test.go
  cmd/clusterctl/client/repository/overrides.go
  cmd/clusterctl/client/repository/overrides_test.go
  docs/book/src/clusterctl/configuration.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#7354 📖 Add side-by-side comparison of MachinePools and MachineDeployments in docs
  docs/book/src/tasks/experimental-features/machine-pools.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#7375 🐛 clusterctl: support Windows paths in overridesFolder
  cmd/clusterctl/client/repository/overrides.go
  cmd/clusterctl/client/repository/repository_local.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#7383 📖 Fix typos in word Cluster and through
  cmd/clusterctl/client/clusterclass.go
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  docs/proposals/20210526-cluster-class-and-managed-topologies.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7384 📖 Fix correct ginkgo and gomega verison in release notes
  docs/book/src/developer/providers/v1.2-to-v1.3.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7256 ✨ Add 3DS outscale provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/reference/glossary.md
  docs/book/src/reference/providers.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#7377 📖 Added a single line linux command in quick-start for installing clusterctl
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#7177 :book: Include CABPM and CACPM in the book
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/tasks/bootstrap/index.md
  docs/book/src/tasks/bootstrap/kubeadm-bootstrap.md
  docs/book/src/tasks/bootstrap/microk8s-bootstrap.md
  docs/book/src/tasks/control-plane/index.md
  docs/book/src/tasks/control-plane/kubeadm-control-plane.md
  docs/book/src/tasks/control-plane/microk8s-control-plane.md
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#7365 🌱 Simplify Makefile targets
  Makefile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  docs/book/src/clusterctl/developers.md
  docs/book/src/developer/guide.md
  docs/book/src/reference/jobs.md
  scripts/ci-e2e-lib.sh
  scripts/ci-test.sh
  test/infrastructure/docker/README.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#7393 [release-1.2] ✨ Add 3DS outscale provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/reference/glossary.md
  docs/book/src/reference/providers.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#7387 🌱 Implement single-node cluster self-hosted upgrade test
  Makefile
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-topology-single-node-cluster/disable-control-plane-taint-variable.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/cluster-template-topology-single-node-cluster/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1beta1/main/clusterclass-quick-start.yaml
  test/e2e/self_hosted_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6905 📖 Cluster API Add-on Orchestration proposal
  docs/proposals/20220712-cluster-api-addon-orchestration.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#6555 :book: Amend CRS proposal to include Reconcile mode
  docs/proposals/20200220-cluster-resource-set.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#7392 :book: Add Docker specific get kubeconfig to quickstart
  docs/book/src/clusterctl/developers.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#7341 🌱 Add custom upgrade option to e2e
  test/e2e/clusterctl_upgrade.go
  test/framework/clusterctl/client.go
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#7362 :sparkles: Add topology field for MinReadySeconds
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/cluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  test/e2e/data/infrastructure-docker/v1beta1/main/bases/cluster-with-topology.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#7369 🌱 clusterctl: adjust Overrider interface so Path can return an error
  cmd/clusterctl/client/repository/overrides.go
  docs/book/src/developer/providers/v1.2-to-v1.3.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#7390 :bug: Fix/clusterctl describe color
  cmd/clusterctl/cmd/describe_cluster.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#7398 🐛 Remove extra slash in hack/ensure-kind script
  hack/ensure-kind.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7400 [release-1.2] 🌱 Add custom upgrade option to e2e
  test/e2e/clusterctl_upgrade.go
  test/framework/clusterctl/client.go
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#7405 [release-1.2] 🐛 ClusterClass: fix reconciliation of MD delete
  internal/controllers/topology/cluster/current_state.go
  internal/controllers/topology/cluster/current_state_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7406 :seedling: Add deleting MachineDeploymentTopology to ClusterClass changes test
  test/e2e/clusterclass_changes.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7422 🌱 Fix grammar in pull request instructions
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7419 ✨ Update cert-manager version (v1.9.1 -> v1.10.0)
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  docs/book/src/user/quick-start.md
  docs/book/src/user/troubleshooting.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#7425 🌱 Bump dependencies to fix CVEs
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6412 ⚠️ Machine ProviderID equality is now strictly enforced
  controllers/noderefutil/providerid.go
  controllers/noderefutil/providerid_test.go
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  internal/controllers/machine/machine_controller_noderef_test.go
  internal/controllers/machine/machine_controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7426 🌱 Use the Go SDK context package consistently
  cmd/clusterctl/client/cluster/crd_migration_test.go
  controllers/alias.go
  go.mod
  hack/tools/go.mod
  hack/tools/tilt-prepare/main.go
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#7436 :book: Fix broken book links
  docs/book/src/security/pod-security-standards.md
  docs/book/src/tasks/control-plane/kubeadm-control-plane.md
  docs/book/src/tasks/updating-machine-templates.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7391 📖 doc: add release cycle doc
  docs/developer/release-cycle-overview.png
  docs/developer/release-cycle.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#7438 🌱 KCP: make rolloutBefore.certificatesExpiryDays mutable
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7296 📖 Label Sync Between Machine and underlying Kubernetes Nodes
  docs/proposals/20220927-label-sync-between-machine-and-nodes.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#7435 📖 Clarify clusterctl move supported use case and limitations
  docs/book/src/clusterctl/commands/move.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#7437 ✨ golangci-lint: set go version in run configuration instead of for eac…
  .golangci.yml
Labels: size/S, cncf-cla: yes, lgtm, approved

#7397 :seedling: Update Deprecated comments to correctly trigger staticcheck linter
  .golangci.yml
  api/v1alpha4/common_types.go
  api/v1beta1/common_types.go
  api/v1beta1/condition_consts.go
  bootstrap/kubeadm/api/v1alpha4/kubeadm_types.go
  bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/move.go
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  controllers/external/util.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  test/infrastructure/docker/api/v1beta1/dockermachine_types.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/exp/api/v1beta1/dockermachinepool_types.go
Labels: cncf-cla: yes, lgtm, size/M, approved, kind/cleanup

#7433 📖 Document multiple providers support
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/multiple-providers.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#7414 🌱 Move make target
  Makefile
Labels: cncf-cla: yes, lgtm, size/L, approved

#7328 📖 Update optional fields in docs for Machine and Cluster controllers
  docs/book/src/developer/architecture/controllers/cluster.md
  docs/book/src/developer/architecture/controllers/machine.md
  docs/book/src/developer/providers/cluster-infrastructure.md
  docs/book/src/developer/providers/machine-infrastructure.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#7442 ✨ golangci-lint enable most recommended revive checks and fix findings
  .golangci.yml
  exp/addons/internal/controllers/clusterresourceset_controller_test.go
  internal/controllers/machine/machine_controller_test.go
  util/patch/patch_test.go
  util/version/version.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7454 🌱 Set golangci-lint path-prefix when linting test and hack/tools
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7374 🌱 remove redundant license
  test/infrastructure/docker/LICENSE
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#7463 ✨ Update github.com/joelanford/go-apidiff version (0.4.0 -> 0.5.0)
  Makefile
  docs/book/src/developer/providers/v1.2-to-v1.3.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7361 📖 update cert-manager label searching command
  docs/book/src/clusterctl/configuration.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#7470 📖Release cycle leads & shadow name added
  docs/developer/release-cycle.md
Labels: cncf-cla: yes, lgtm, size/XS, approved
