Repository kubernetes-sigs/cluster-api, pull requests merged in 2022-06, with the labels that each got.

#6499 ✨ Implement Call and CallAll in RuntimeClient
  Makefile
  exp/runtime/api/v1alpha1/extensionconfig_types.go
  exp/runtime/hooks/api/v1alpha1/common_types.go
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.deepcopy.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/warmup_test.go
  internal/runtime/catalog/catalog.go
  internal/runtime/catalog/openapi.go
  internal/runtime/catalog/test/catalog_test.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
  internal/runtime/test/v1alpha1/conversion.go
  internal/runtime/test/v1alpha1/conversion_test.go
  internal/runtime/test/v1alpha1/doc.go
  internal/runtime/test/v1alpha1/fake_types.go
  internal/runtime/test/v1alpha1/zz_generated.conversion.go
  internal/runtime/test/v1alpha1/zz_generated.deepcopy.go
  internal/runtime/test/v1alpha2/fake_types.go
Labels: cncf-cla: yes, lgtm, kind/feature, size/XL, approved, area/runtime-sdk

#6537 🌱 Add lifecycle hook types
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.deepcopy.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/runtime-sdk

#6580 🌱 RuntimeSDK: change webhook default port to 443
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  exp/runtime/api/v1alpha1/extensionconfig_types.go
  internal/runtime/registry/registry.go
  internal/webhooks/runtime/extensionconfig_webhook.go
  internal/webhooks/runtime/extensionconfig_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6587 📖 book: add videos from KubeCon and Let's chat about sessions
  docs/book/src/developer/guide.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6591 :book: add missing namespace qualifier
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6543 :book: update supported Kubernetes versions
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6585 🐛 cloudbuild: upgrade to latest cloudbuild image to fix image push
  cloudbuild-nightly.yaml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#5558 :book: add documentation for the provider specific setup in quick start docs
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6586 ✨ Make KCP's patches option mutable
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6540 🐛 Close etcd leaky connection if client is not initialized properly
  controlplane/kubeadm/internal/etcd/etcd.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6597 ⚠️ Bump mink8s mgmt cluster version to 1.20.2
  cmd/clusterctl/client/cluster/client.go
  docs/book/src/developer/providers/v1.1-to-v1.2.md
  docs/book/src/reference/versions.md
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6575 🌱 bump kubebuilder-release-tools GitHub action to v0.2.0
  .github/workflows/verify.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6467 :seedling: Upgrade to controller-runtime v0.12.2 and k8s.io/* v0.24.*
  bootstrap/kubeadm/main.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controlplane/kubeadm/main.go
  docs/book/src/developer/providers/v1.1-to-v1.2.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  internal/topology/variables/clusterclass_variable_validation.go
  internal/topology/variables/clusterclass_variable_validation_test.go
  internal/webhooks/clusterclass.go
  main.go
  test/go.mod
  test/go.sum
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6601 🐛 Support Go 1.18: Bump apidiff to v0.4.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6605 🐛 test/e2e add tag to e2e tests which use ClusterClass
  docs/book/src/developer/testing.md
  docs/book/src/reference/jobs.md
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterclass_changes_test.go
  test/e2e/quick_start_test.go
  test/e2e/self_hosted_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6600 🌱 Bump corefile-migration to v1.0.17
  docs/book/src/developer/providers/v1.1-to-v1.2.md
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#6602 🌱 logging: use klog.Background
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  docs/book/src/developer/providers/v1.1-to-v1.2.md
  main.go
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6282 📖 Added repository layout in ClusterAPI book
  docs/book/src/developer/repository-layout.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#6405 ✨ prebuilt container for clusterctl in image based pipelines
  .dockerignore
  Makefile
  cmd/clusterctl/Dockerfile
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6604 🌱 bump envtest to v1.24.1
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6289 ✨ Topology Mutation: use API types for inline patching
  internal/controllers/topology/cluster/patches/api/interface.go
  internal/controllers/topology/cluster/patches/engine.go
  internal/controllers/topology/cluster/patches/engine_test.go
  internal/controllers/topology/cluster/patches/inline/json_patch_generator.go
  internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
  internal/controllers/topology/cluster/patches/patch.go
  internal/controllers/topology/cluster/patches/template.go
  internal/controllers/topology/cluster/patches/variables/value.go
  internal/controllers/topology/cluster/patches/variables/value_test.go
  internal/controllers/topology/cluster/patches/variables/variables.go
  internal/controllers/topology/cluster/patches/variables/variables_test.go
  test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/runtime-sdk

#6578 :seedling: Add client defaulting and validation for DiscoveryResponse
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/warmup_test.go
  internal/runtime/catalog/catalog.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6607 🐛 dependabot: implement workaround to run generate-go-openapi in GOPATH
  .github/workflows/dependabot.yml
Labels: size/S, cncf-cla: yes, lgtm, approved

#6617 🌱 cloudbuild: bump to Go 1.18
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  docs/book/src/developer/providers/v1.1-to-v1.2.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6618 :bug: Change tiltfile to work with go 1.18
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6443 🌱 consolidate test/infrastructure/docker/Makefile to Makefile
  Makefile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  docs/book/src/clusterctl/developers.md
  docs/book/src/developer/guide.md
  docs/book/src/reference/jobs.md
  scripts/ci-build.sh
  scripts/ci-e2e-lib.sh
  scripts/ci-test.sh
  test/infrastructure/docker/Makefile
  test/infrastructure/docker/README.md
  test/infrastructure/docker/hack/verify-all.sh
  test/infrastructure/docker/hack/verify-build.sh
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6622 🌱 Update docker distribution
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#6495 ✨ Add Server Side Apply helper to the topology controller
  api/v1beta1/common_types.go
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/proxy.go
  docs/book/src/clusterctl/commands/alpha-topology-plan.md
  docs/book/src/developer/providers/v1.1-to-v1.2.md
  docs/book/src/reference/versions.md
  docs/book/src/tasks/experimental-features/cluster-class/change-clusterclass.md
  docs/book/src/tasks/experimental-features/cluster-class/index.md
  internal/contract/types.go
  internal/contract/types_test.go
  internal/controllers/topology/cluster/blueprint_test.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/controllers/topology/cluster/current_state_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/mergepatch/managed_paths.go
  internal/controllers/topology/cluster/mergepatch/managed_paths_test.go
  internal/controllers/topology/cluster/mergepatch/mergepatch.go
  internal/controllers/topology/cluster/mergepatch/mergepatch_test.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/structuredmerge/doc.go
  internal/controllers/topology/cluster/structuredmerge/drop_diff.go
  internal/controllers/topology/cluster/structuredmerge/drop_diff_test.go
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/dryrun_test.go
  internal/controllers/topology/cluster/structuredmerge/filterintent.go
  internal/controllers/topology/cluster/structuredmerge/filterintent_test.go
  internal/controllers/topology/cluster/structuredmerge/interfaces.go
  internal/controllers/topology/cluster/structuredmerge/options.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
  internal/controllers/topology/cluster/structuredmerge/suite_test.go
  internal/controllers/topology/cluster/structuredmerge/twowayspatchhelper.go
  internal/controllers/topology/cluster/structuredmerge/twowayspatchhelper_test.go
  internal/controllers/topology/cluster/suite_test.go
  internal/controllers/topology/cluster/util_test.go
  internal/test/builder/infrastructure.go
  internal/test/envtest/environment.go
  main.go
  version/version.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#6521 📖 Reformat shell command and output in the book
  CONTRIBUTING.md
  docs/book/src/clusterctl/commands/alpha-rollout.md
  docs/book/src/clusterctl/commands/alpha-topology-plan.md
  docs/book/src/clusterctl/commands/completion.md
  docs/book/src/clusterctl/commands/delete.md
  docs/book/src/clusterctl/commands/generate-cluster.md
  docs/book/src/clusterctl/commands/get-kubeconfig.md
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/commands/move.md
  docs/book/src/clusterctl/commands/upgrade.md
  docs/book/src/clusterctl/configuration.md
  docs/book/src/clusterctl/developers.md
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
  docs/book/src/developer/providers/implementers-guide/configure.md
  docs/book/src/developer/providers/implementers-guide/generate_crds.md
  docs/book/src/developer/providers/implementers-guide/overview.md
  docs/book/src/developer/tilt.md
  docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  docs/book/src/tasks/experimental-features/ignition.md
  docs/book/src/tasks/external-etcd.md
  docs/book/src/tasks/using-kustomize.md
  docs/book/src/user/quick-start.md
  docs/book/src/user/troubleshooting.md
  docs/proposals/20191016-clusterctl-redesign.md
  test/infrastructure/docker/exp/README.md
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#6627 🐛 Fix cloudbuild definitions due to invalid syntax
  cloudbuild-nightly.yaml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6631 🐛 Add entrypoint to cloudbuild again
  cloudbuild-nightly.yaml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6630 🐛 Fix Tiltfile for newer tilt versions
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6624 📖 Toleration of v1.24 control plane taints
  docs/book/src/developer/providers/v1.1-to-v1.2.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6638 🐛 RuntimeSDK: some bugfixes
  config/rbac/role.yaml
  exp/runtime/internal/controllers/extensionconfig_controller.go
  main.go
  test/e2e/cluster_upgrade_runtimesdk.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6632 ✨ RuntimeSDK: Add caBundle injection to Extension controller
  exp/runtime/api/v1alpha1/extensionconfig_types.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/warmup.go
  exp/runtime/internal/controllers/warmup_test.go
  test/e2e/cluster_upgrade_runtimesdk.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/runtime-sdk

#6608 ✨ RuntimeSDK: BeforeClusterCreate, BeforeClusterUpgrade implementation
  api/v1beta1/condition_consts.go
  controllers/alias.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/controllers/topology/cluster/conditions.go
  internal/controllers/topology/cluster/conditions_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/scope/hookresponsetracker.go
  internal/controllers/topology/cluster/scope/hookresponsetracker_test.go
  internal/controllers/topology/cluster/scope/scope.go
  internal/runtime/catalog/catalog.go
  internal/runtime/catalog/test/catalog_test.go
  internal/runtime/client/fake/fake_client.go
  main.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/runtime-sdk

#6637 :bug: Use APIReader to fix flaky MachinePool test
  exp/internal/controllers/machinepool_controller_phases_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6487 ✨ Provider repositories on GitLab
  cmd/clusterctl/client/repository/client.go
  cmd/clusterctl/client/repository/client_test.go
  cmd/clusterctl/client/repository/repository_gitlab.go
  cmd/clusterctl/client/repository/repository_gitlab_test.go
  docs/book/src/clusterctl/configuration.md
  docs/book/src/clusterctl/provider-contract.md
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test

#6645 🌱 RuntimeSDK: enforce https for extensions
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  exp/runtime/api/v1alpha1/extensionconfig_types.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/warmup_test.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
  internal/webhooks/runtime/extensionconfig_webhook.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/runtime-sdk

#6635 🌱 test/extension: add first version of server lib & topology mutation
  exp/runtime/hooks/api/v1alpha1/topologymutation_types.go
  internal/controllers/topology/cluster/patches/inline/json_patch_generator.go
  internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
  internal/controllers/topology/cluster/patches/variables/merge.go
  internal/controllers/topology/cluster/patches/variables/merge_test.go
  internal/controllers/topology/cluster/patches/variables/variables.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start-runtimesdk.yaml
  test/extension/handlers/topologymutation/handler.go
  test/extension/handlers/topologymutation/lib.go
  test/extension/main.go
  test/extension/server/server.go
  test/go.mod
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/runtime-sdk

#6623 ✨ Topology Mutation Hook: Implement external patching
  api/v1beta1/clusterclass_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/patches/api/interface.go
  internal/controllers/topology/cluster/patches/engine.go
  internal/controllers/topology/cluster/patches/engine_test.go
  internal/controllers/topology/cluster/patches/external/external_patch_generator.go
  internal/controllers/topology/cluster/patches/external/external_validator.go
  internal/controllers/topology/cluster/patches/inline/json_patch_generator.go
  internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
  internal/webhooks/patch_validation.go
  internal/webhooks/patch_validation_test.go
  test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start-runtimesdk.yaml
  test/extension/server/server.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/runtime-sdk

#6629 ✨ Implements AfterControlPlaneInitialized, AfterControlPlaneUpgrade and AfterClusterUpgrade hooks
  exp/runtime/api/v1alpha1/extensionconfig_types.go
  exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/scope/upgradetracker.go
  internal/hooks/tracking.go
  internal/hooks/tracking_test.go
  internal/runtime/client/fake/fake_client.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/runtime-sdk

#6658 :seedling: Add tests for external patch apply
  internal/controllers/topology/cluster/patches/engine_test.go
  internal/controllers/topology/cluster/patches/template.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6660 🐛 Stop adding parent object owner reference for MachineHealthChecks in managed topologies
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  test/e2e/data/infrastructure-docker/v1beta1/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#6662 🌱 RuntimeSDK: improve discovery error message
  internal/runtime/client/client.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6649 🐛 Fix version comparison for pre release versions
  bootstrap/kubeadm/types/utils.go
  bootstrap/kubeadm/types/utils_test.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6665 🌱 RuntimeSDK/client: use random port for unit test server
  internal/runtime/client/client_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6640 ✨ making SetNodeProviderID no more blocking although Control Plane is externally managed
  test/infrastructure/docker/internal/docker/machine.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6668 🐛 use the kubernetes decoder in the patch engine
  internal/controllers/topology/cluster/patches/template.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6673 🐛 ClusterClass: reconcile InfrastructureCluster controlPlaneEndpoint
  internal/contract/infrastructure_cluster.go
  internal/contract/infrastructure_cluster_test.go
  internal/controllers/topology/cluster/reconcile_state.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6666 📖 Use consistent naming for minikube, kind, kOps and Kubespray in documentation
  .github/ISSUE_TEMPLATE/bug_report.md
  docs/book/src/clusterctl/commands/move.md
  docs/book/src/introduction.md
  docs/book/src/tasks/experimental-features/ignition.md
  docs/book/src/user/personas.md
  docs/book/src/user/quick-start.md
  docs/proposals/20191017-kubeadm-based-control-plane.md
  docs/proposals/20210203-externally-managed-cluster-infrastructure.md
  docs/scope-and-objectives.md
  hack/kind-install-for-capd.sh
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6681 🐛 Restore yq targets accidentally removed in 5785
  Makefile
  hack/get-project-maintainers.sh
Labels: size/S, cncf-cla: yes, lgtm, approved

#6683 🐛 fix typo in clusterctl function name
  cmd/clusterctl/client/alpha/machinedeployment.go
  cmd/clusterctl/client/alpha/rollout_pauser.go
  cmd/clusterctl/client/alpha/rollout_restarter.go
  cmd/clusterctl/client/alpha/rollout_resumer.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6466 ✨clusterctl upgrade apply: wait for providers to be ready
  cmd/clusterctl/client/cluster/installer.go
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/client/cluster/upgrader_test.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/cmd/upgrade_apply.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6686 🌱 Bump dependencies: cluster-bootstrap, cobra, viper, grpc, ..
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6680 📖 Remove outdated capi book roadmap
  docs/book/src/roadmap.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6628 :book: More generic explanation about issue getting kubeconfig on certain systems using Docker
  docs/book/src/clusterctl/developers.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6697 📖 Add release 1.2 book link
  docs/book/src/introduction.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6700 🌱 Migrate more topology tests to Test* CRD
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/test/builder/bootstrap.go
  internal/test/builder/builders.go
  internal/test/builder/controlplane.go
  internal/test/builder/infrastructure.go
  internal/test/envtest/environment.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6664 🌱 Initial e2e test for Runtime SDK lifecycle hook
  test/e2e/cluster_upgrade_runtimesdk.go
  test/extension/config/default/extension.yaml
  test/extension/config/default/kustomization.yaml
  test/extension/config/default/role.yaml
  test/extension/config/default/rolebinding.yaml
  test/extension/config/default/service_account.yaml
  test/extension/handlers/lifecycle/handlers.go
  test/extension/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6705 🐛 fix disable verify action for cherry-pick bot
  .github/workflows/verify.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6703 🌱 Update go-github from v33.0.0 to v45.2.0
  cmd/clusterctl/client/cluster/template.go
  cmd/clusterctl/client/cluster/template_test.go
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
  cmd/clusterctl/cmd/version_checker.go
  cmd/clusterctl/internal/test/fake_github.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6698 📖 add v1.2 -> v1.3 migration doc
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/v1.2-to-v1.3.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6704 📖 Add link to videos in the Getting started section
  docs/book/src/developer/providers/webhooks.md
  docs/book/src/introduction.md
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved

#6715 🌱 bump controller-runtime v0.12.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#6728 🌱 Update CoreDNS version for release v1.1
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6727 🌱 Update CoreDNS version for release v1.1
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6726 🌱 Update CoreDNS migration library to v1.0.17
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#6730 📖 Revert "[release-1.2] 📖 add v1.2 -> v1.3 migration doc"
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/v1.2-to-v1.3.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6725 📖 fix link to RuntimeSDK CAEP
  docs/book/src/tasks/experimental-features/runtime-sdk.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6701 :book: add notes about cert-managers CRD storage version deprecation
  docs/book/src/user/troubleshooting.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6713 🌱 make TestControlPlaneTemplate deepcopy-able
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6734 📖 Add requirement to squash pr commits to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6551 :book: Update document regarding overrides
  docs/book/src/clusterctl/configuration.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6722 🐛 Improve to get error stack trace for machine reconcile
  internal/controllers/machine/machine_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6670 🌱 Make InfrastructureMachineTemplateBuilder DeepCopy-able
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6693 🌱 RuntimeSDK: improve error wrapping and godoc
  api/v1beta1/clusterclass_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  exp/runtime/api/v1alpha1/extensionconfig_types.go
  exp/runtime/hooks/api/v1alpha1/common_types.go
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/groupversion_info.go
  exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
  exp/runtime/hooks/api/v1alpha1/topologymutation_types.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  exp/runtime/internal/controllers/warmup.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/hooks/tracking.go
  internal/runtime/catalog/builder.go
  internal/runtime/catalog/catalog.go
  internal/runtime/catalog/openapi.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
  internal/runtime/client/fake/fake_client.go
  internal/runtime/registry/registry.go
  internal/runtime/test/v1alpha1/fake_types.go
  internal/runtime/test/v1alpha1/groupversion_info.go
  internal/runtime/test/v1alpha2/fake_types.go
  internal/runtime/test/v1alpha2/groupversion_info.go
  internal/webhooks/runtime/extensionconfig_webhook.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6753 🌱 export util packages for Runtime SDK
  .golangci.yml
  exp/runtime/catalog/builder.go
  exp/runtime/catalog/catalog.go
  exp/runtime/catalog/doc.go
  exp/runtime/catalog/openapi.go
  exp/runtime/catalog/test/catalog_test.go
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/groupversion_info.go
  exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
  exp/runtime/hooks/api/v1alpha1/topologymutation_types.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/warmup_test.go
  exp/runtime/server/server.go
  hack/tools/runtime-openapi-gen/main.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/patches/engine_test.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/scope/hookresponsetracker.go
  internal/controllers/topology/cluster/scope/hookresponsetracker_test.go
  internal/hooks/tracking.go
  internal/hooks/tracking_test.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
  internal/runtime/client/fake/fake_client.go
  internal/runtime/registry/registry.go
  internal/runtime/registry/registry_test.go
  internal/runtime/test/v1alpha1/conversion_test.go
  internal/runtime/test/v1alpha1/fake_types.go
  internal/runtime/test/v1alpha1/groupversion_info.go
  internal/runtime/test/v1alpha2/fake_types.go
  internal/runtime/test/v1alpha2/groupversion_info.go
  main.go
  test/extension/handlers/lifecycle/handlers.go
  test/extension/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6735 🌱 Make TestInfrastructureMachineTemplateBuilder deepcopy-able
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6695 🐛 Ensure controlplane coredns update deploys the ClusterRole if CoreDNS was already updated
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6760 [release-1.1] 🐛 Ensure controlplane coredns update deploys the ClusterRole if CoreDNS was already updated
  controlplane/kubeadm/internal/workload_cluster_coredns.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6762 🌱 runtime sdk catalog path fix
  exp/runtime/catalog/catalog.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6542 🌱 Upgrade controller-tools to v0.9.1
  Makefile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  config/webhook/manifests.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  docs/book/src/developer/providers/v1.1-to-v1.2.md
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#6764 🌱 Add deepcopy methods to remaining builders
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6772 📖 Fix typo in the kubelet authentication proposal
  docs/proposals/20210222-kubelet-authentication.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6773 🐛 Adjust structuredmerge patch helper options to set correct allow list for Cluster objects to prevent co-ownership
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/structuredmerge/options.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6779 🌱 Remove code deprecated in v1.2
  controllers/remote/cluster_cache_reconciler.go
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  util/util.go
Labels: size/S, cncf-cla: yes, lgtm, approved, kind/cleanup

#6783 :seedling: Update stale link in PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6742 🐛 Carry over metadata.uid at ServerSidePatchHelper
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/structuredmerge/options.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/topology

#6787 🌱 Fix spelling in clusterctl command help text
  cmd/clusterctl/cmd/config_repositories.go
  cmd/clusterctl/cmd/root.go
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved

#6789 :bug: Retry Apply workloadClusterTemplate to fix flake
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6749 ✨ clusterctl: migrate CRDs during clusterctl upgrade
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/crd_migration.go
  cmd/clusterctl/client/cluster/crd_migration_test.go
  cmd/clusterctl/client/cluster/upgrader.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#6794 :seedling: Use 'Byf' instead of 'By(fmt.Sprintf())' across e2e tests
  test/e2e/clusterctl_upgrade.go
  test/framework/alltypes_helpers.go
  test/framework/cluster_helpers.go
  test/framework/clusterctl/repository.go
  test/framework/deployment_helpers.go
  test/framework/machine_helpers.go
  test/framework/machinedeployment_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6785 🐛 fix structuredmerge filterintent to cleanup nested empty maps
  internal/controllers/topology/cluster/structuredmerge/filterintent.go
  internal/controllers/topology/cluster/structuredmerge/filterintent_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved
