Repository kubernetes-sigs/cluster-api, pull requests merged in 2022-07, with the labels that each got.

#6781 📖 Add missing clusterctl commands in CAPI book
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/commands/additional-commands.md
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/clusterctl/commands/generate-provider.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6782 :book: Add cluster-resource-set-controller to docs
  docs/book/src/SUMMARY.md
  docs/book/src/developer/architecture/controllers.md
  docs/book/src/developer/architecture/controllers/cluster-resource-set.md
  docs/book/src/images/cluster-resource-set-controller.plantuml
  docs/book/src/images/cluster-resource-set-controller.png
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6761 🌱 Add blocking end-to-end tests for lifecycle hooks
  test/e2e/cluster_upgrade_runtimesdk.go
  test/extension/handlers/lifecycle/handlers.go
  test/framework/cluster_topology_helpers.go
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/runtime-sdk

#6644 ✨ Implements BeforeClusterDelete hook
  exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
  exp/runtime/api/v1alpha1/extensionconfig_types.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/cluster/cluster_controller_test.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/hooks/tracking.go
  internal/hooks/tracking_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/runtime-sdk

#6684 🌱 patching Docker-based nodes provider ID using client-runtime
  test/infrastructure/docker/controllers/alias.go
  test/infrastructure/docker/exp/controllers/alias.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/exp/internal/docker/nodepool.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/docker/internal/docker/types/node.go
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#6780 🌱 Better error handling for tracking utilities
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/hooks/tracking.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/runtime-sdk

#6806 📖 Update repository-layout with missing folders
  docs/book/src/developer/repository-layout.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6808 🌱 Use consistent punctuation in the clusterctl cmd short descriptions
  cmd/clusterctl/cmd/alpha.go
  cmd/clusterctl/cmd/backup.go
  cmd/clusterctl/cmd/config.go
  cmd/clusterctl/cmd/config_repositories.go
  cmd/clusterctl/cmd/delete.go
  cmd/clusterctl/cmd/describe.go
  cmd/clusterctl/cmd/describe_cluster.go
  cmd/clusterctl/cmd/generate.go
  cmd/clusterctl/cmd/generate_cluster.go
  cmd/clusterctl/cmd/generate_provider.go
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/cmd/move.go
  cmd/clusterctl/cmd/topology.go
  cmd/clusterctl/cmd/topology_plan.go
  cmd/clusterctl/cmd/upgrade.go
  cmd/clusterctl/cmd/version.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6799 🐛 Improve TestE2E error output and create artifacts dir if not exists
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6733 📖 Remove Alibaba and Baidu Cloud from providers list
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6801 📖 Add script to find files missing in SUMMARY.md
  Makefile
  docs/book/src/SUMMARY.md
  docs/book/src/user/guide.md
  hack/verify-capi-book-summary.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6816 🌱 Remove homebrew action
  .github/workflows/update-homebrew-formula-on-release.yml
Labels: size/S, cncf-cla: yes, lgtm, approved

#6820 🌱 Run dependabot action outside of GOPATH again
  .github/workflows/dependabot.yml
Labels: size/S, cncf-cla: yes, lgtm, approved

#6756 📖 Runtime SDK: extend documentation & update proposals accordingly
  docs/book/src/SUMMARY.md
  docs/book/src/images/runtime-sdk-lifecycle-hooks.png
  docs/book/src/images/runtime-sdk-topology-mutation.plantuml
  docs/book/src/images/runtime-sdk-topology-mutation.png
  docs/book/src/tasks/experimental-features/cluster-class/index.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  docs/book/src/tasks/experimental-features/runtime-sdk.md
  docs/book/src/tasks/experimental-features/runtime-sdk/deploy-runtime-extension.md
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-lifecycle-hooks.md
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.md
  docs/book/src/tasks/experimental-features/runtime-sdk/index.md
  docs/proposals/20220221-runtime-SDK.md
  docs/proposals/20220330-topology-mutation-hook.md
  docs/proposals/20220414-runtime-hooks.md
  test/extension/main.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#6768 🌱 pull non-existent images when building kind bootstrap cluster
  test/framework/bootstrap/kind_util.go
  test/infrastructure/container/docker.go
  test/infrastructure/container/fake.go
  test/infrastructure/container/interface.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6826 [release-1.1] 🌱 Restrict permissions of GitHub actions
  .github/workflows/dependabot.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/release.yml
  .github/workflows/verify.yml
Labels: size/S, cncf-cla: yes, lgtm, approved

#6827 :book: Update config paths in docs
  docs/book/src/developer/guide.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6844 🐛 ci: use KUBERNETES_VERSION in kubeadm script
  test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6846 ✨ Bump to controller-runtime v0.12.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#6843 🌱 Bump kpromo to 3.4.4
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6830 📖 add disclaimer about clusterctl topology dryrun RuntimeSDK support
  docs/book/src/clusterctl/commands/alpha-topology-plan.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6834 🌱 Bump versions to v1.3
  cmd/clusterctl/hack/create-local-repository.py
  hack/tools/tilt-prepare/main.go
  metadata.yaml
  test/e2e/config/docker.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#6862 🌱 Improve clusterctl generate cluster error message
  cmd/clusterctl/cmd/generate_cluster.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6865 🌱 Fix old comment about filteredMachines
  internal/controllers/machineset/machineset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6871 [release-1.1] :seedling: Update verify action to ignore cherry-picks
  .github/workflows/verify.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6868 🌱 Improve clusterctl describe cluster error message
  cmd/clusterctl/cmd/describe_cluster.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6872 📖 Set linkchecker base branch to main
  .github/workflows/lint-docs-pr.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6850 📖 update supported versions for v1.3
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6881 :book: Remove Exoscale provider
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#6254 ✨ Add support for deploying Cluster templates and ClusterClasses on Tilt
  Tiltfile
  docs/book/src/developer/tilt.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#6895 🐛 ClusterClass: reconcile InfrastructureCluster controlPlaneEndpoint fields
  internal/contract/infrastructure_cluster.go
  internal/contract/infrastructure_cluster_test.go
  internal/contract/types.go
  internal/controllers/topology/cluster/reconcile_state.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6817 :seedling: Runtime sdk/flaky e2e fix
  test/e2e/cluster_upgrade_runtimesdk.go
  test/extension/handlers/lifecycle/handlers.go
  test/framework/cluster_helpers.go
  test/framework/cluster_topology_helpers.go
  test/framework/controlplane_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6896 🌱 fix in openapi doc
  exp/runtime/catalog/openapi.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/runtime-sdk

#6892 🌱 test/e2e stream runtime SDK extension controller logs to artifacts
  test/e2e/cluster_upgrade_runtimesdk.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6839 📖 Add short description for each clusterctl command in CAPI book
  docs/book/src/clusterctl/commands/commands.md
  docs/book/src/clusterctl/overview.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6890 :bug: fix: bootstrap typos
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/topology/cluster/desired_state.go
  internal/test/builder/bootstrap.go
  test/e2e/self_hosted.go
Labels: size/S, cncf-cla: yes, lgtm, needs-ok-to-test, approved

#6875 📖 add note ClusterClass compatibility info to validating webhooks section
  docs/book/src/developer/providers/webhooks.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6893 🌱 SSA: improve comment about metadata.uid
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6914 🐛 SSA: create cluster-shim with regular client, use ignorePaths on create
  internal/controllers/topology/cluster/reconcile_state.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6845 :book: Add Clusterclass and RuntimeSDK terms to glossary
  docs/book/src/reference/glossary.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6593 ✨ Add Cluster API Visualizer to Tilt observability
  Tiltfile
  docs/book/src/developer/tilt.md
  hack/observability/visualizer/kustomization.yaml
  hack/observability/visualizer/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#6920 🐛 fix log formatting in runtime client
  internal/runtime/client/client.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6938 🌱 Deprecate experimentalRetryJoin
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  docs/book/src/developer/providers/v1.1-to-v1.2.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6885 🌱 bump to v1.2.0 tag for clusterctl upgrade tests
  test/e2e/config/docker.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#6931 📖 docs: update install instructions for kustomize and kubebuilder
  docs/book/src/developer/providers/implementers-guide/overview.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#6949 📖 add Netlify instructions to releasing doc
  docs/developer/releasing.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6933 :bug: Remove message from Runtime SDK FailureResponses
  internal/runtime/client/client.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/runtime-sdk

#6876 ✨ clusterctl: add flag to force color output on `describe cluster`
  cmd/clusterctl/cmd/describe_cluster.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6954 🌱 clusterctl: cleanup unused cmd/clusterctl/internal/util/cmd.go
  cmd/clusterctl/internal/util/cmd.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6646 ✨ Add checks for not topology owned templates to never reconcile.
  internal/controllers/topology/cluster/current_state.go
  internal/controllers/topology/cluster/current_state_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6932 :book: Add section on Fuzzing to testing guide
  docs/book/src/developer/testing.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6937 🌱 Update example version of core CAPI used in clusterctl
  cmd/clusterctl/client/delete.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/cmd/delete.go
  cmd/clusterctl/cmd/generate_provider.go
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/cmd/upgrade_apply.go
  docs/book/src/clusterctl/configuration.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#6939 🌱 Clusterctl support for VMware Cloud Director as Infrastructure Provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/reference/glossary.md
  docs/book/src/reference/providers.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#6963 :book: Add klog.Background PR to migration guide
  docs/book/src/developer/providers/v1.1-to-v1.2.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6967 🌱 Add providerID workflow clarification
  docs/book/src/developer/providers/machine-infrastructure.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#6973 🐛 Update make release process to correctly tag CAPD
  Makefile
Labels: size/S, cncf-cla: yes, lgtm, approved

#6971 🐛 Fix machinepool instance id bug
  exp/internal/controllers/machinepool_controller_noderef.go
  exp/internal/controllers/machinepool_controller_noderef_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#6964 🌱 Add ControlPlaneWaiters to input for e2e specs
  test/e2e/cluster_upgrade.go
  test/e2e/clusterclass_changes.go
  test/e2e/clusterctl_upgrade.go
  test/e2e/k8s_conformance.go
  test/e2e/machine_pool.go
  test/e2e/md_rollout.go
  test/e2e/md_scale.go
  test/e2e/mhc_remediations.go
  test/e2e/node_drain_timeout.go
  test/e2e/quick_start.go
  test/e2e/self_hosted.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#6886 🌱 Add Dockerfile linter
  Dockerfile
  Makefile
  cmd/clusterctl/Dockerfile
  docs/Dockerfile
  scripts/ci-lint-dockerfiles.sh
  test/extension/Dockerfile
  test/infrastructure/docker/Dockerfile
Labels: cncf-cla: yes, lgtm, size/M, approved

#6836 ✨ ClusterCacheTracker: access controller cluster directly
  config/manager/manager.yaml
  controllers/remote/cluster_cache_reconciler.go
  controllers/remote/cluster_cache_tracker.go
  controllers/remote/cluster_cache_tracker_fake.go
  controllers/remote/cluster_cache_tracker_test.go
  controlplane/kubeadm/config/manager/manager.yaml
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/main.go
  test/infrastructure/docker/config/manager/manager.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#6150 🌱 Improve key value pairs consistency in logging
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go
  bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go
  bootstrap/util/configowner.go
  cmd/clusterctl/client/cluster/mover.go
  controllers/external/tracker.go
  controllers/remote/cluster_cache_tracker.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/status.go
  controlplane/kubeadm/internal/controllers/upgrade.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/internal/controllers/machinepool_controller.go
  exp/internal/controllers/machinepool_controller_noderef.go
  exp/internal/controllers/machinepool_controller_phases.go
  exp/util/util.go
  hack/observability/promtail/values.yaml
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
  internal/controllers/machinedeployment/mdutil/util.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/log/log.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/docker/internal/docker/loadbalancer.go
  util/predicates/cluster_predicates.go
  util/util.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6987 🌱 Add error messages for all e2e Ginkgo expects
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/internal/test/fake_objects.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/clusterclass_changes.go
  test/e2e/clusterctl_upgrade.go
  test/e2e/common.go
  test/e2e/self_hosted.go
  test/extension/handlers/lifecycle/handlers.go
  test/framework/alltypes_helpers.go
  test/framework/cluster_helpers.go
  test/framework/cluster_proxy.go
  test/framework/cluster_topology_helpers.go
  test/framework/clusterresourceset_helpers.go
  test/framework/control_plane.go
  test/framework/controlplane_helpers.go
  test/framework/deployment_helpers.go
  test/framework/machine_helpers.go
  test/framework/machinedeployment_helpers.go
  test/framework/machinehealthcheck_helpers.go
  test/framework/machinepool_helpers.go
  test/framework/machines.go
  test/framework/namespace_helpers.go
  test/infrastructure/docker/exp/internal/docker/nodepool.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#6828 🌱 improve how do we perform issue triage and milestone management
  CONTRIBUTING.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#6969 🌱 Add logging guidelines
  REVIEWING.md
  docs/book/src/SUMMARY.md
  docs/book/src/developer/logging.md
Labels: cncf-cla: yes, lgtm, size/L, approved
