Repository kubernetes-sigs/cluster-api, pull requests merged in 2023-02, with the labels that each got.

#8035 🌱 remove KCP as a valid resource type for rollback
  cmd/clusterctl/client/alpha/rollout.go
  cmd/clusterctl/client/alpha/rollout_rollbacker.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7991 :seedling: Add ClusterClass variables to status on reconcile
  api/v1beta1/clusterclass_types.go
  api/v1beta1/common_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.md
  docs/proposals/20220330-topology-mutation-hook.md
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/clusterclass/clusterclass_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7996 ✨ Add more reviewers and maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/M, approved

#8043 🌱 Add introduction.png image
  docs/book/src/images/introduction.png
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8046 🌱 Update golangci-lint to v1.51.0
  .github/workflows/golangci-lint.yml
  util/container/image.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7995 🌱 MachinePool: automatically bump apiVersions like in our other controllers
  exp/controllers/alias.go
  exp/internal/controllers/machinepool_controller.go
  exp/internal/controllers/machinepool_controller_phases.go
  exp/internal/controllers/machinepool_controller_phases_test.go
  exp/internal/controllers/machinepool_controller_test.go
  main.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8015 📖 Move release timeline docs
  docs/release/releases/release-1.3.md
  docs/release/releases/release-1.4.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7678 :bug: Fix unit test coverage in KubeadmConfig
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8042 🌱 envtest: add env var to allow writing envtest kubeconfig
  docs/book/src/developer/testing.md
  internal/test/envtest/environment.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#7956 :sparkles: add response metrics for RuntimeSDK hook client
  internal/runtime/client/client.go
  internal/runtime/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#8056 🌱 Bump controller-tools to v0.11.3
  Makefile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#8062 🐛 ClusterCacheTracker: fix panic in error creation
  controllers/remote/cluster_cache_tracker.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8069 [release-1.2] :sparkles: Update owners file
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/M, approved

#8070 [release-1.3] :sparkles: sparkles Update owners file
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/M, approved

#8068 [release-1.2] 🐛 ClusterCacheTracker: fix panic in error creation
  controllers/remote/cluster_cache_tracker.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8066 🐛 Added nodeVolumeDetachTimeout to CP machine
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#7935 🌱 test/e2e use informer to stream pod logs
  test/e2e/e2e_suite_test.go
  test/e2e/self_hosted.go
  test/framework/cluster_proxy.go
  test/framework/clusterctl/clusterctl_helpers.go
  test/framework/deployment_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8058 🌱 Bump golangci-lint (v1.51.1) and enable some ginkgolinter checks
  .github/workflows/golangci-lint.yml
  .golangci.yml
  bootstrap/util/configowner_test.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  internal/contract/bootstrap_test.go
  internal/contract/controlplane_test.go
  internal/contract/infrastructure_cluster_test.go
  internal/contract/infrastructure_machine_test.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
  util/patch/utils_test.go
  util/util_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8074 :sparkles: Update coredns corefile migration to v1.0.19
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#8041 ⚠️ Stop supporting CRDs with invalid names
  cmd/clusterctl/client/cluster/installer.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/suite_test.go
  docs/book/src/developer/providers/v1.3-to-v1.4.md
  docs/book/src/reference/labels_and_annotations.md
  exp/internal/controllers/machinepool_controller_phases.go
  internal/controllers/cluster/cluster_controller_phases.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machineset/machineset_controller.go
  util/conversion/conversion.go
  util/util.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8037 :bug: KCP: Allow unsetting fields if their child fields are mutable
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8067 🌱 ClusterClass: catch panics when applying patches
  internal/controllers/topology/cluster/patches/engine.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7954 :seedling: Add clusterclass validation to topology reconciler
  internal/controllers/topology/cluster/blueprint.go
  internal/controllers/topology/cluster/blueprint_test.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/topology/variables/cluster_variable_defaulting.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7990 🌱 MD: improve replica defaulting for autoscaler
  .golangci.yml
  api/v1beta1/machinedeployment_types.go
  api/v1beta1/machinedeployment_webhook.go
  api/v1beta1/machinedeployment_webhook_test.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  docs/book/src/developer/providers/v1.3-to-v1.4.md
  docs/book/src/tasks/automated-machine-management/autoscaling.md
  internal/test/builder/builders.go
  util/defaulting/defaulting.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8077 [release-1.2] :seedling: Update coredns corefile migration to v1.0.19
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#8079 :book: Update coredns version support
  docs/book/src/reference/versions.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8078 [release-1.3] :seedling: Update coredns corefile migration to v1.0.19
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#8083 [release-1.2] 🐛 KCP: Allow unsetting fields if their child fields are mutable
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8084 [release-1.2] 🌱 ClusterClass: catch panics when applying patches
  internal/controllers/topology/cluster/patches/engine.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8006 ✨ Add discoverVariables runtime hook to ClusterClass reconcile loop
  api/v1beta1/clusterclass_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  cmd/clusterctl/client/alpha/rollout_pauser.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  controllers/alias.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/clusterclass/clusterclass_controller_test.go
  main.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8023 :seedling: Add ClusterClass generation check to Cluster Topology reconciler
  api/v1beta1/condition_consts.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/conditions.go
  internal/controllers/topology/cluster/conditions_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8089 🐛 uplift helm dependency
  hack/tools/go.mod
  hack/tools/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#8072 🌱 test/e2e: Add v1.0=>main clusterctl upgrade test
  .gitignore
  Makefile
  docs/release/release-tasks.md
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/README.md
  test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/crs.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.0/cluster-template/kustomization.yaml
  test/e2e/data/shared/v1.0/metadata.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#8063 🌱 ClusterClass: also consider MD unavailableReplicas for rollout
  internal/controllers/topology/cluster/conditions_test.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/scope/state.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8090 🌱 CAPD: reduce noisy error logs during machine reconciliation
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8031 :seedling: Add DefinitionFrom field to ClusterVariable
  api/v1beta1/cluster_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#8087 🌱 Enable ginkgolinter len assertion check and fix findings
  .golangci.yml
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  cmd/clusterctl/client/cluster/components_test.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/client/cluster/topology_test.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/repository/template_test.go
  cmd/clusterctl/internal/util/obj_refs_test.go
  controllers/remote/keyedmutex_test.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/etcd/etcd_test.go
  exp/addons/internal/controllers/clusterresourceset_helpers_test.go
  exp/internal/controllers/machinepool_controller_noderef_test.go
  exp/internal/controllers/machinepool_controller_test.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/warmup_test.go
  internal/controllers/machine/machine_controller_phases_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/machineset/util_test.go
  internal/runtime/registry/registry_test.go
  test/e2e/clusterclass_changes.go
  test/infrastructure/docker/internal/provisioning/cloudinit/unknown_test.go
  util/conversion/conversion_test.go
  util/resource/resource_test.go
  util/yaml/yaml_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8108 🌱 improve logging during Machine deletion
  internal/controllers/machine/machine_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8126 🐛 uplift golang and x/net
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#8076 :seedling: Default and Validate Cluster variables based on ClusterClass status
  api/v1beta1/condition_consts.go
  cmd/clusterctl/client/cluster/assets/topology-test/new-clusterclass-and-cluster.yaml
  cmd/clusterctl/client/cluster/topology.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
  internal/topology/variables/cluster_variable_validation.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
  internal/webhooks/test/clusterclass_test.go
  internal/webhooks/test/suite_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#7497 ✨ Implement Reconcile mode for ClusterResourceSet
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  docs/book/src/tasks/experimental-features/cluster-resource-set.md
  exp/addons/api/v1beta1/clusterresourceset_types.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_types_test.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/addons/internal/controllers/clusterresourceset_controller_test.go
  exp/addons/internal/controllers/clusterresourceset_helpers.go
  exp/addons/internal/controllers/clusterresourceset_scope.go
  exp/addons/internal/controllers/clusterresourceset_scope_test.go
  exp/addons/internal/controllers/predicates/resource_predicates.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#8073 📖 Add note about clusterctl upgrade test coverage
  docs/book/src/clusterctl/commands/upgrade.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8127 🌱 Update Go to 1.19.6
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#8133 :seedling: Remove generation check for clusterclass to fix e2e test
  internal/webhooks/cluster.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8125 🐛 KCP: fix rollout after upgrade
  bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8102 🌱 ClusterClass: Allow fine-granular control of MachineDeployment upgrades
  api/v1beta1/common_types.go
  api/v1beta1/condition_consts.go
  docs/book/src/reference/labels_and_annotations.md
  internal/controllers/topology/cluster/conditions.go
  internal/controllers/topology/cluster/conditions_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/scope/upgradetracker.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8138 🌱 test/e2e: disable rollout check for ClusterClass-based cluster in clusterctl upgrade test
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8140 🌱 test/e2e: disable rollout check for ClusterClass-based cluster in clusterctl ugprade tests II
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8142 🌱 test/framework: ensure ApplyClusterTemplateAndWait always returns a cluster
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8044 🌱 Move machine controller tests to envtest, drop disableNodeLabelSync
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machine/machine_controller_phases_test.go
  internal/controllers/machine/machine_controller_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8055 🌱 Add envtest unit tests for node label sync
  internal/controllers/machine/machine_controller_noderef_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8139 🐛 ClusterClass: run dry-run on original and modified object
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8136 :seedling: Make Cluster webhook less strict for out of date ClusterClasses
  cmd/clusterctl/client/cluster/mover.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7963 ✨ Add support for KCP remediation during cluster provisioning
  controlplane/kubeadm/api/v1alpha3/conversion.go
  controlplane/kubeadm/api/v1alpha3/zz_generated.conversion.go
  controlplane/kubeadm/api/v1alpha4/conversion.go
  controlplane/kubeadm/api/v1alpha4/zz_generated.conversion.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_types.go
  controlplane/kubeadm/api/v1beta1/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/remediation_test.go
  controlplane/kubeadm/internal/controllers/status.go
  docs/book/src/developer/providers/v1.3-to-v1.4.md
  docs/book/src/reference/labels_and_annotations.md
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/mhc.yaml
  test/e2e/kcp_remediations.go
  test/e2e/kcp_remediations_test.go
  test/e2e/md_remediations.go
  test/e2e/md_remediations_test.go
  test/infrastructure/container/docker.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#8117 📖 docs: document plan to remove v1alpha3 and v1alpha4 apiVersions
  CONTRIBUTING.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8118 📖 docs: document test coverage for release branches
  CONTRIBUTING.md
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8111 ⚠️ in-place propagation from MS to Machines
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_controller_test.go
  internal/util/ssa/managedfields.go
  internal/util/ssa/managedfields_test.go
  internal/util/ssa/matchers.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8036 📖 update autoscaling from zero proposal
  docs/proposals/20210310-opt-in-autoscaling-from-zero.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8122 :bug: Requeue health check during the creation of a new cluster accessor
  controllers/remote/cluster_cache_tracker.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8162 ✨ docs: fix command-line-tools links in book
  docs/book/src/user/concepts.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8128 :warning: Add filter to associate variables with specific patches
  internal/controllers/topology/cluster/patches/engine.go
  internal/controllers/topology/cluster/patches/engine_test.go
  internal/controllers/topology/cluster/patches/variables/variables.go
  internal/controllers/topology/cluster/patches/variables/variables_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8130 🌱 Use errors.Is to check for a specific error
  hack/tools/log-push/main.go
  util/yaml/yaml.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8148 📖 Preliminary release dates for v1.5
  docs/release/release-cycle.md
  docs/release/releases/release-1.5.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8134 📖 docs: document new Kubernetes support policy
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#8157 🌱 align CAPD docker run flags with kind
  test/infrastructure/container/docker.go
  test/infrastructure/docker/internal/docker/kind_manager.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8161 :seedling: Set fail-fast: false for weekly md link check
  .github/workflows/lint-docs-weekly.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8165 :book: Add breaking changes section to introduction.md
  docs/book/src/introduction.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8166 🐛 Fix flaky TestServerSideApplyWithDefaulting test
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8168 📖 book: remove old versions from versions.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8169 📖 book: update jobs documentation
  docs/book/src/reference/jobs.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8094 🌱 hack: add support for date ranges to notes.go script
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8182 🌱 CAPD: drop kubectl from image
  Tiltfile
  test/infrastructure/docker/Dockerfile
Labels: size/S, cncf-cla: yes, lgtm, approved

#8181 🌱 test/extension: push to staging registry
  Makefile
  test/extension/config/default/manager_pull_policy.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#8153 :seedling: Weaken ClusterClass webhook variable validation on update
  internal/webhooks/clusterclass.go
  internal/webhooks/clusterclass_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#8196 [release-1.3] :seedling: Bump github.com/coredns/corefile-migration from 1.0.19 to 1.0.20
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#8197 [release-1.2] :seedling: Bump github.com/coredns/corefile-migration from 1.0.19 to 1.0.20
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#8107 :sparkles: Handle variable definition conflicts for external variables
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/clusterclass/clusterclass_controller_test.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/topology/variables/cluster_variable_defaulting.go
  internal/topology/variables/cluster_variable_defaulting_test.go
  internal/topology/variables/cluster_variable_validation.go
  internal/topology/variables/cluster_variable_validation_test.go
  internal/topology/variables/utils.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#8060 ⚠️ in-place propagation from MS to InfraMachine and BootstrapConfig
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_controller_test.go
  internal/controllers/topology/cluster/structuredmerge/drop_diff_test.go
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/filterintent.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
  internal/controllers/topology/cluster/structuredmerge/twowayspatchhelper.go
  internal/util/ssa/filterintent.go
  internal/util/ssa/filterintent_test.go
  internal/util/ssa/managedfields.go
  internal/util/ssa/managedfields_test.go
  internal/util/ssa/matchers.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#8199 :bug: Fix git config in release-binary builds
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8202 :seedling: Clarify condition message for unreconciled clusterclass
  internal/controllers/topology/cluster/conditions.go
  internal/controllers/topology/cluster/conditions_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
