Repository kubernetes-sigs/cluster-api, pull requests merged in 2023-06, with the labels that each got.

#8767 🐛 test/e2e fix fail-swap-on=false flag not being part of kind images anymore
  test/e2e/data/infrastructure-docker/main/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/bases/md.yaml
  test/e2e/data/infrastructure-docker/main/bases/mp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1.3/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-docker/v1.4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1.4/clusterclass-quick-start.yaml
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#8777 [release-1.4] :bug: fix fail-swap-on=false flag not being part of kind images anymore
  test/e2e/data/infrastructure-docker/main/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/bases/md.yaml
  test/e2e/data/infrastructure-docker/main/bases/mp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.2/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.2/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.2/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1.3/clusterclass-quick-start.yaml
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/provider/infrastructure-docker

#8781 :book: Changed inconsistency with kubernetes version in doc
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8779 :book: Update tested upgrade paths in docs
  docs/book/src/clusterctl/commands/upgrade.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8787 :book: Release CI tasks: Remove IPv6, add deep dive sessions
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#8669 🌱 surface failed preflight checks on MachineSet in `MachinesCreated` condition
  api/v1beta1/condition_consts.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_controller_test.go
  internal/controllers/machineset/machineset_preflight.go
  internal/controllers/machineset/machineset_preflight_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8760 📖 Update Runtime Extension CAPI Book
  docs/book/src/tasks/experimental-features/runtime-sdk/deploy-runtime-extension.md
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#8775 📖 update MachineSet PreflightChecks documentation
  docs/book/src/tasks/experimental-features/machineset-preflight-checks.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8789 🐛 CAPD: Implement watch filter
  test/infrastructure/docker/controllers/alias.go
  test/infrastructure/docker/exp/controllers/alias.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/provider/infrastructure-docker

#8795 🌱 hack/observability: move charts so they are ignored by go mod
  hack/observability/.gitignore
  hack/observability/grafana/chart/kustomization.yaml
  hack/observability/kube-state-metrics/chart/kustomization.yaml
  hack/observability/loki/kustomization.yaml
  hack/observability/parca/kustomization.yaml
  hack/observability/prometheus/kustomization.yaml
  hack/observability/promtail/kustomization.yaml
  hack/observability/visualizer/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#8798 :book: Update e2e jobs list to reflect dualstack + IPv6 consolidation
  docs/book/src/reference/jobs.md
  test/e2e/quick_start_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8800 🌱 test/e2e: also dump workload cluster kube-system pods
  controlplane/kubeadm/internal/controllers/status.go
  docs/book/src/developer/logging.md
  test/e2e/common.go
  test/framework/alltypes_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8801 🌱 ClusterCacheTracker: improve error when workload cluster is not reachable
  controllers/remote/cluster_cache_tracker.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clustercachetracker

#8802 :book: Add minor release prefix for title polishing
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#8772 🐛 ignition: start kubeadm after network.target
  bootstrap/kubeadm/internal/ignition/clc/clc.go
  bootstrap/kubeadm/internal/ignition/clc/clc_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8805 :book: Remove use of deprecated clusterctl flag in docs
  docs/book/src/clusterctl/commands/describe-cluster.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8812 :book: add in-cluster ipam and helm addon providers
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#8818 🐛 fix cluster deletion in the in-memory API server
  test/infrastructure/inmemory/internal/controllers/goofycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/goofymachine_controller.go
  test/infrastructure/inmemory/internal/server/api/handler.go
  test/infrastructure/inmemory/internal/server/mux.go
  test/infrastructure/inmemory/internal/server/mux_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8780 🌱 Add area label lookup for prefixes to release notes tool
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#8830 🌱 test/infra/inmemory: rename controller files
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8628 🐛 topology controller should avoid unnecessary rollouts during upgrades
  api/v1beta1/condition_consts.go
  internal/controllers/topology/cluster/conditions.go
  internal/controllers/topology/cluster/conditions_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/scope/hookresponsetracker.go
  internal/controllers/topology/cluster/scope/hookresponsetracker_test.go
  internal/controllers/topology/cluster/scope/upgradetracker.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/clusterclass

#8778 🌱 Validating the warnings in tests
  api/v1beta1/machine_webhook_test.go
  api/v1beta1/machinedeployment_webhook_test.go
  api/v1beta1/machinehealthcheck_webhook_test.go
  api/v1beta1/machineset_webhook_test.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook_test.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfigtemplate_webhook_test.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
  controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_webhook_test.go
  exp/addons/api/v1beta1/clusterresourceset_webhook_test.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_webhook_test.go
  exp/api/v1beta1/machinepool_webhook_test.go
  exp/ipam/internal/webhooks/ipaddress_test.go
  exp/ipam/internal/webhooks/ipaddressclaim_test.go
  internal/webhooks/cluster_test.go
  internal/webhooks/runtime/extensionconfig_webhook_test.go
  test/infrastructure/docker/api/v1beta1/dockerclustertemplate_webhook_test.go
  test/infrastructure/docker/api/v1beta1/dockermachinetemplate_webhook_test.go
  util/defaulting/defaulting.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#8782 📖 update lifecycle hooks documentation with new upgrade rules
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-lifecycle-hooks.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8743 🌱 Remove unnecessary requeues
  controllers/external/tracker.go
  exp/internal/controllers/machinepool_controller.go
  exp/internal/controllers/machinepool_controller_phases.go
  exp/internal/controllers/machinepool_controller_phases_test.go
  internal/controllers/cluster/cluster_controller_phases.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/machine/machine_controller_phases_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8744 🌱 Use ClusterCacheTracker consistently (instead of NewClusterClient)
  bootstrap/kubeadm/controllers/alias.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/main.go
  controllers/remote/cluster_cache_tracker.go
  controlplane/kubeadm/main.go
  exp/internal/controllers/machinepool_controller.go
  exp/internal/controllers/machinepool_controller_noderef.go
  exp/internal/controllers/machinepool_controller_phases_test.go
  internal/controllers/machineset/machineset_controller.go
  main.go
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8831 🌱 Add startup timeout to the in memory provider
  test/infrastructure/inmemory/api/v1alpha1/inmemorymachine_types.go
  test/infrastructure/inmemory/api/v1alpha1/zz_generated.deepcopy.go
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachines.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachinetemplates.yaml
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#6913 :warning: Follow XDG Directory standard for config/data/... files
  cmd/clusterctl/client/config.go
  cmd/clusterctl/client/config/client.go
  cmd/clusterctl/client/config/reader_viper.go
  cmd/clusterctl/client/config/reader_viper_test.go
  cmd/clusterctl/client/repository/overrides.go
  cmd/clusterctl/client/repository/overrides_test.go
  cmd/clusterctl/cmd/config_repositories.go
  cmd/clusterctl/cmd/config_repositories_test.go
  cmd/clusterctl/cmd/generate_cluster.go
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/cmd/root.go
  cmd/clusterctl/cmd/version_checker.go
  cmd/clusterctl/cmd/version_checker_test.go
  cmd/clusterctl/hack/create-local-repository.py
  docs/book/src/clusterctl/commands/additional-commands.md
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/configuration.md
  docs/book/src/clusterctl/developers.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  docs/book/src/user/troubleshooting.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/clusterctl

#8807 🌱 add ClusterClass support for in-memory provider
  test/infrastructure/inmemory/api/v1alpha1/inmemoryclustertemplate_types.go
  test/infrastructure/inmemory/api/v1alpha1/inmemoryclustertemplate_webhook.go
  test/infrastructure/inmemory/api/v1alpha1/zz_generated.deepcopy.go
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclustertemplates.yaml
  test/infrastructure/inmemory/config/crd/kustomization.yaml
  test/infrastructure/inmemory/config/crd/patches/cainjection_in_inmemoryclustertemplates.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclustertemplates.yaml
  test/infrastructure/inmemory/config/webhook/manifests.yaml
  test/infrastructure/inmemory/main.go
  test/infrastructure/inmemory/templates/cluster-template-inmemory-development.yaml
  test/infrastructure/inmemory/templates/clusterclass-in-memory-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8822 🐛 fix inmemory provider docker build
  Makefile
  test/infrastructure/inmemory/Dockerfile
Labels: cncf-cla: yes, lgtm, size/M, approved

#8843 :book: Small doc fixes for XDG_CONFIG_HOME
  cmd/clusterctl/hack/create-local-repository.py
  docs/book/src/clusterctl/developers.md
  docs/book/src/user/quick-start.md
  docs/book/src/user/troubleshooting.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl, area/documentation

#8850 :bug: ClusterCacheTracker: Stop pod caching when checking workload cluster
  controllers/remote/cluster_cache_tracker.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clustercachetracker

#8698 🌱 add E2E test for MachineSet Preflight checks
  test/e2e/cluster_upgrade_runtimesdk.go
  test/framework/machineset_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8853 🌱 CAPIM: use consistent spelling for release artifacts
  Makefile
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/cmd/config_repositories_test.go
  test/infrastructure/inmemory/templates/cluster-template-in-memory-development.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/clusterctl

#8854 :book: Fix formatting error on proposals
  docs/proposals/20220927-label-sync-between-machine-and-nodes.md
  docs/proposals/20221003-In-place-propagation-of-Kubernetes-objects-only-changes.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#8817 🌱 Make release notes generation concurrent
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release, area/clusterctl

#8855 :seedling: Deprecate DefaultIndex usage and remove where not needed
  bootstrap/kubeadm/main.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controllers/remote/cluster_cache_tracker_test.go
  controllers/remote/index.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/main.go
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
  internal/controllers/cluster/suite_test.go
  internal/controllers/machine/machine_controller_noderef_test.go
  internal/controllers/machine/suite_test.go
  internal/controllers/machinedeployment/suite_test.go
  internal/controllers/machinehealthcheck/suite_test.go
  internal/controllers/machineset/suite_test.go
  main.go
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clustercachetracker

#8826 🌱 Improve release notes formatting
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#8862 🌱 KCP: avoid panic if etcd server misbehaves
  controlplane/kubeadm/internal/workload_cluster_conditions.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8863 🌱 KCP: fix noisy error log triggered by missing patch helper
  controlplane/kubeadm/internal/control_plane.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8860 🐛 Pin kindest/node images to known good versions in clusterctl upgrade tests
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/mhc.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v0.4/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1.3/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-docker/v1.4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1.4/clusterclass-quick-start.yaml
  test/infrastructure/docker/internal/docker/machine.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8859 :bug: Always build Kind images for upgrade tests
  scripts/ci-e2e-lib.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8873 :bug: Ensure ALWAYS_BUILD_KIND_IMAGES is defaulted correctly in ci script
  scripts/ci-e2e-lib.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8861 🌱 hack/observability: improve Grafana dashboards
  hack/observability/grafana/dashboards/cluster-api.json
  hack/observability/grafana/dashboards/controller-runtime.json
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#8868 [release-1.4] :bug: Use known kindest/node image versions by sha for e2e upgrade tests
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/mhc.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v0.4/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.2/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.2/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.2/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.3/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1.3/clusterclass-quick-start.yaml
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#8879 🐛 test/e2e/in-memory: set providerID after VM is provisioned
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8883 :seedling: Update cert-manager to v1.12.2
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#8886 🌱 test/e2e/in-memory: enable unit tests
  scripts/ci-test.sh
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
  test/infrastructure/inmemory/internal/server/mux.go
  test/infrastructure/inmemory/internal/server/mux_test.go
  test/infrastructure/inmemory/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8892 🌱 test/e2e/in-memory: sync in-memory provider ClusterClass with test
  .gitignore
  test/infrastructure/inmemory/templates/clusterclass-in-memory-quick-start.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#8867 :sparkles: Use caching read for bootstrap config owner
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/util/configowner.go
  bootstrap/util/configowner_test.go
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#8851 :seedling: Add watch to in-memory server multiplexer
  test/infrastructure/inmemory/internal/cloud/runtime/cache/cache.go
  test/infrastructure/inmemory/internal/cloud/runtime/cache/client.go
  test/infrastructure/inmemory/internal/cloud/runtime/cache/client_test.go
  test/infrastructure/inmemory/internal/cloud/runtime/cache/informer.go
  test/infrastructure/inmemory/internal/cloud/runtime/controller/controller_test.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
  test/infrastructure/inmemory/internal/server/api/handler.go
  test/infrastructure/inmemory/internal/server/api/watch.go
  test/infrastructure/inmemory/internal/server/listener.go
  test/infrastructure/inmemory/internal/server/mux_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8895 🌱 test/e2e/in-memory: improve performance by fixing locking issues
  test/infrastructure/inmemory/internal/server/certs.go
  test/infrastructure/inmemory/internal/server/mux.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8898 :seedling: Fixups for watch in in-memory apiServer
  test/infrastructure/inmemory/internal/cloud/runtime/cache/client.go
  test/infrastructure/inmemory/internal/server/api/handler.go
  test/infrastructure/inmemory/internal/server/api/watch.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8894 🌱 Use rest config from ClusterCacheTracker consistently
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  internal/controllers/machine/machine_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8880 🐛 Add kind mapper
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/extension/handlers/topologymutation/handler.go
  test/infrastructure/container/docker.go
  test/infrastructure/container/interface.go
  test/infrastructure/docker/exp/internal/docker/nodepool.go
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/docker/internal/docker/manager.go
  test/infrastructure/docker/internal/docker/manager_test.go
  test/infrastructure/kind/mapper.go
  test/infrastructure/kind/mapper_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8904 :bug: Update clean-charts make target for new paths
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8905 🌱 fix readme for in-memory provider
  test/README.md
  test/infrastructure/inmemory/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8903 [release-1.4] :bug: Add kind mapper
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/extension/handlers/topologymutation/handler.go
  test/infrastructure/container/docker.go
  test/infrastructure/container/interface.go
  test/infrastructure/docker/exp/internal/docker/nodepool.go
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/docker/internal/docker/manager.go
  test/infrastructure/docker/internal/docker/manager_test.go
  test/infrastructure/kind/mapper.go
  test/infrastructure/kind/mapper_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8852 🌱 optimize `reconcileInterruptibleNodeLabel` of machine controller
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_node_labels.go
  internal/controllers/machine/machine_controller_node_labels_test.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machine/machine_controller_noderef_test.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/machine/machine_controller_phases_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8902 🌱 modify scale e2e test defaults
  test/e2e/data/infrastructure-inmemory/main/clusterclass-in-memory.yaml
  test/e2e/scale_test.go
  test/infrastructure/inmemory/templates/clusterclass-in-memory-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#8899 :seedling: CAPIM: Enable update for coreDNS and kube-proxy
  test/e2e/data/infrastructure-inmemory/main/clusterclass-in-memory.yaml
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
  test/infrastructure/inmemory/internal/server/api/const.go
  test/infrastructure/inmemory/internal/server/api/handler.go
  test/infrastructure/inmemory/main.go
  test/infrastructure/inmemory/templates/clusterclass-in-memory-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#8908 :seedling: Update KIND to v0.20.0
  Tiltfile
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/go.mod
  test/go.sum
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#8906 🌱 Improve etcd management in CAPIM
  test/infrastructure/inmemory/internal/cloud/api/v1alpha1/etcdcluster_annotations.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
  test/infrastructure/inmemory/internal/server/etcd/handler.go
  test/infrastructure/inmemory/internal/server/mux_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8900 🌱 Kcp use one workload cluster for reconcile
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/remediation_test.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/controllers/status.go
  controlplane/kubeadm/internal/controllers/status_test.go
  controlplane/kubeadm/internal/controllers/suite_test.go
  controlplane/kubeadm/internal/controllers/upgrade.go
  controlplane/kubeadm/internal/controllers/upgrade_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8909 🌱 Change endpoints to endpoint in the etcd client
  controlplane/kubeadm/internal/etcd/etcd.go
  controlplane/kubeadm/internal/etcd_client_generator.go
  controlplane/kubeadm/internal/etcd_client_generator_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8901 📖 add release-1.6 schedule document
  docs/release/releases/release-1.6.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8896 🌱 controller/machine: use unstructured caching client
  controllers/alias.go
  internal/controllers/cluster/suite_test.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_noderef_test.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/machine/machine_controller_phases_test.go
  internal/controllers/machine/machine_controller_test.go
  internal/controllers/machine/suite_test.go
  internal/controllers/machinehealthcheck/suite_test.go
  internal/controllers/machineset/suite_test.go
  main.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8914 🐛 test/capd: fix kind mapper entry for v1.25.11
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8912 🌱 KCP: drop redundant get machines
  controlplane/kubeadm/internal/controllers/scale.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/control-plane

#8881 🌱 Automatically set kubelet args for capd
  bootstrap/kubeadm/types/utils.go
  bootstrap/kubeadm/types/utils_test.go
  docs/book/src/clusterctl/commands/alpha-topology-plan.md
  docs/book/src/tasks/bootstrap/kubeadm-bootstrap.md
  docs/book/src/tasks/experimental-features/ignition.md
  test/e2e/data/infrastructure-docker/main/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/bases/md.yaml
  test/e2e/data/infrastructure-docker/main/bases/mp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-ignition/ignition.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/go.mod
  test/infrastructure/docker/exp/internal/docker/nodepool.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/docker/internal/provisioning/cloudinit/adapter.go
  test/infrastructure/docker/internal/provisioning/cloudinit/adapter_test.go
  test/infrastructure/docker/internal/provisioning/cloudinit/runcmd.go
  test/infrastructure/docker/internal/provisioning/cloudinit/runcmd_test.go
  test/infrastructure/docker/internal/provisioning/cloudinit/unknown.go
  test/infrastructure/docker/internal/provisioning/cloudinit/unknown_test.go
  test/infrastructure/docker/internal/provisioning/cloudinit/writefiles.go
  test/infrastructure/docker/internal/provisioning/cloudinit/writefiles_test.go
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8916 🌱 Cache unstructured in Cluster, MD and MS controller
  controllers/alias.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/cluster/cluster_controller_phases.go
  internal/controllers/cluster/cluster_controller_phases_test.go
  internal/controllers/cluster/cluster_controller_test.go
  internal/controllers/cluster/suite_test.go
  internal/controllers/machine/suite_test.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinedeployment/suite_test.go
  internal/controllers/machinehealthcheck/suite_test.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_controller_test.go
  internal/controllers/machineset/machineset_preflight.go
  internal/controllers/machineset/machineset_preflight_test.go
  internal/controllers/machineset/suite_test.go
  internal/test/envtest/environment.go
  main.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8919 🐛 tilt: set CR logger in tilt-prepare, fix allowed contexts
  Tiltfile
  hack/tools/tilt-prepare/main.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8913 🌱 KCP: cache unstructured
  controlplane/kubeadm/controllers/alias.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/controllers/upgrade_test.go
  controlplane/kubeadm/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/control-plane

#8724 🐛 handle nil pointer in clusterctl describe
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/client/tree/discovery.go
  cmd/clusterctl/client/tree/discovery_test.go
  cmd/clusterctl/internal/test/fake_objects.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/clusterctl

#8920 🌱 hack/observability: add tempo (for traces)
  Tiltfile
  docs/book/src/developer/tilt.md
  hack/observability/grafana/chart/values.yaml
  hack/observability/grafana/dashboards/cluster-api.json
  hack/observability/grafana/dashboards/controller-runtime.json
  hack/observability/prometheus/values.yaml
  hack/observability/tempo/kustomization.yaml
  hack/observability/tempo/values.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8918 🌱 util: cache list calls in cluster to objects mapper
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/util/configowner.go
  bootstrap/util/configowner_test.go
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
  exp/internal/controllers/machinepool_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machineset/machineset_controller.go
  main.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
  util/util.go
  util/util_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8924 :bug: Fix deprecation marker for RolloutAfter
  api/v1beta1/cluster_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8922 🌱 cluster/topology: use cached MD list in get current state
  internal/controllers/topology/cluster/current_state.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8927 :bug: Use CreateAndWait in MP ScaleFromZero test
  exp/internal/controllers/machinepool_controller_phases_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#8921 🌱 Drop cgroup-driver patch for CAPD
  Makefile
  cmd/clusterctl/client/cluster/assets/topology-test/existing-my-cluster.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/existing-my-second-cluster.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/my-cluster-class.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/new-clusterclass-and-cluster.yaml
  test/e2e/cluster_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-default-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/extension/handlers/topologymutation/handler.go
  test/framework/machinepool_helpers.go
  test/infrastructure/docker/internal/provisioning/cloudinit/writefiles.go
  test/infrastructure/docker/internal/provisioning/cloudinit/writefiles_test.go
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterctl

#8926 🌱 KCP: cache secrets between LookupOrGenerate and ensureCertificatesOwnerRef
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/suite_test.go
  util/secret/certificates.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/provider/control-plane-kubeadm

#8932 📖 Update 1.5.0-beta.x release date
  docs/release/releases/release-1.5.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8931 🌱 hack/observability: skip preload images on non-kind clusters
  hack/tools/tilt-prepare/main.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8933 🌱 Build golangci-lint locally
  Makefile
  hack/ensure-golangci-lint.sh
Labels: cncf-cla: yes, lgtm, size/L, approved

#8910 🌱 add improvements to scale e2e
  test/e2e/config/docker.yaml
  test/e2e/scale.go
  test/e2e/scale_test.go
  test/framework/namespace_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8929 [release-1.4] :seedling: Set Kubelet args internally in CAPD
  Makefile
  bootstrap/kubeadm/types/utils.go
  bootstrap/kubeadm/types/utils_test.go
  cmd/clusterctl/client/cluster/assets/topology-test/existing-my-cluster.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/existing-my-second-cluster.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/my-cluster-class.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/new-clusterclass-and-cluster.yaml
  docs/book/src/clusterctl/commands/alpha-topology-plan.md
  docs/book/src/tasks/bootstrap/kubeadm-bootstrap.md
  docs/book/src/tasks/experimental-features/ignition.md
  test/e2e/cluster_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/main/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/bases/md.yaml
  test/e2e/data/infrastructure-docker/main/bases/mp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-ignition/ignition.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-adoption/step1/cluster-with-cp0.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-remediation/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-cgroupfs/mp-default-cgroupfs.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/extension/handlers/topologymutation/handler.go
  test/framework/machinepool_helpers.go
  test/go.mod
  test/infrastructure/docker/exp/internal/docker/nodepool.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/docker/internal/provisioning/cloudinit/adapter.go
  test/infrastructure/docker/internal/provisioning/cloudinit/adapter_test.go
  test/infrastructure/docker/internal/provisioning/cloudinit/runcmd.go
  test/infrastructure/docker/internal/provisioning/cloudinit/runcmd_test.go
  test/infrastructure/docker/internal/provisioning/cloudinit/unknown.go
  test/infrastructure/docker/internal/provisioning/cloudinit/unknown_test.go
  test/infrastructure/docker/internal/provisioning/cloudinit/writefiles.go
  test/infrastructure/docker/internal/provisioning/cloudinit/writefiles_test.go
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/provider/infrastructure-docker

#8941 🌱 test/e2e: increase apply timeout to 1m
  test/e2e/scale.go
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8463 🌱 add MachineFinalizer during machine computation
  internal/controllers/machinedeployment/suite_test.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_controller_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/machineset

#8936 🌱 cluster/topology: use cached Cluster get in Reconcile
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/reconcile_state.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8945 🌱 test/e2e/in-memory: improve locking, return errors instead of panic
  test/infrastructure/inmemory/internal/server/api/handler.go
  test/infrastructure/inmemory/internal/server/api/watch.go
  test/infrastructure/inmemory/internal/server/etcd/handler.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8940 🌱 cache secrets in KCP, CABPK and ClusterCacheTracker
  bootstrap/kubeadm/controllers/alias.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_reconciler_test.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/internal/controllers/suite_test.go
  bootstrap/kubeadm/main.go
  controllers/remote/cluster_cache_tracker.go
  controlplane/kubeadm/controllers/alias.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/cluster_test.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/controllers/suite_test.go
  controlplane/kubeadm/internal/controllers/upgrade_test.go
  controlplane/kubeadm/internal/suite_test.go
  controlplane/kubeadm/main.go
  main.go
  test/infrastructure/docker/main.go
  util/secret/certificates.go
Labels: cncf-cla: yes, lgtm, size/XL, approved
