Repository kubernetes-sigs/cluster-api, pull requests merged in 2023-11, with the labels that each got.

#9540 🌱 Add WaitForMachinePoolToBeUpgraded to self-hosted test
  test/e2e/self_hosted.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/testing

#9653 :seedling: Bump cert-manager to v1.13.2
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9563 🌱 Give permissions for release notes tool to release team
  docs/release/release-team.md
  hack/tools/release/OWNERS
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9559 📖 Add In-place upgrades feature group
  docs/community/20231016-in-place-upgrades.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/documentation

#9619 🐛 Fix bug where MachinePool Machine ownerRefs weren't updating
  exp/internal/controllers/machinepool_controller.go
  exp/internal/controllers/machinepool_controller_phases.go
  exp/internal/controllers/machinepool_controller_phases_test.go
  internal/controllers/machine/machine_controller.go
  internal/webhooks/machine.go
  test/framework/ownerreference_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/machinepool

#9667 🌱 test/conformance: add variables to overwrite parralelization of kubetest runs
  test/e2e/k8s_conformance.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#9665 🌱 Bump kubebuilder tools to v0.4.2
  .github/workflows/pr-verify.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9343 🌱 hack: add weekly update script for Slack
  Makefile
  docs/release/release-tasks.md
  hack/tools/release/internal/constants.go
  hack/tools/release/notes/main.go
  hack/tools/release/notes/main_test.go
  hack/tools/release/weekly/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#9675 [release-1.5] :seedling: Bump github.com/docker/docker from 24.0.5 to 24.0.7
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9674 [release-1.4] :seedling: Bump github.com/docker/docker from 24.0.5 to 24.0.7
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9676 :bug: Fix reporting bug in verify-container-image script
  hack/verify-container-images.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9671 :seedling: Bump Trivy to v0.47.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9577 🌱 Add k3s providers to cluster-api book
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#9635 📖 Add Cluster API release-1.7 timeline document
  docs/release/releases/release-1.7.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/M, approved, area/release

#9622 🌱 Bump golangci-lint to v1.55.1
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  cmd/clusterctl/client/move.go
  controllers/remote/cluster_cache_tracker_test.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
  controlplane/kubeadm/internal/workload_cluster_coredns_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
  exp/internal/controllers/machinepool_controller_test.go
  exp/internal/webhooks/machinepool_test.go
  exp/ipam/internal/webhooks/ipaddress_test.go
  exp/ipam/internal/webhooks/ipaddressclaim_test.go
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
  internal/controllers/machine/machine_controller_test.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller_test.go
  internal/controllers/machinedeployment/mdutil/util_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
  internal/controllers/machineset/machineset_controller_test.go
  internal/topology/check/compatibility.go
  internal/webhooks/cluster.go
  internal/webhooks/machine_test.go
  internal/webhooks/machinedeployment_test.go
  internal/webhooks/patch_validation_test.go
  test/framework/machinedeployment_helpers.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
  test/infrastructure/inmemory/internal/server/mux_test.go
  util/predicates/cluster_predicates_test.go
  util/version/version.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/dependency

#9682 :seedling: Support admin config for Kubeadm v1.29
  controlplane/kubeadm/internal/controllers/fakes_test.go
  controlplane/kubeadm/internal/controllers/upgrade.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_rbac.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/provider/control-plane-kubeadm

#9683 🌱 Bump Go version to v1.20.11
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9687 [release-1.4] 🌱 Bump Go version to v1.20.11
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9697 :seedling: CAPD: Set Condition, if creating external LB failed.
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/provider/infrastructure-docker

#9709 🌱 Bump opentelemetry to fix CVEs
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#9701 [release-1.4] :seedling: Fix delve version in Tiltfile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9437 :seedling: propagate ctx to retryWithExponentialBackoff in clusterctl
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/components.go
  cmd/clusterctl/client/cluster/crd_migration.go
  cmd/clusterctl/client/cluster/inventory.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/ownergraph.go
  cmd/clusterctl/client/cluster/proxy.go
  cmd/clusterctl/client/cluster/upgrader.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterctl

#8500 📖 CAEP: Flexible Managed Kubernetes Endpoints
  docs/book/src/reference/glossary.md
  docs/proposals/20220725-managed-kubernetes.md
  docs/proposals/20230407-flexible-managed-k8s-endpoints.md
Labels: cncf-cla: yes, lgtm, size/XL, approved

#9703 🌱 Add MachinePools to Runtime SDK and Rollout tests
  test/e2e/cluster_upgrade.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/clusterclass_changes.go
  test/e2e/clusterclass_rollout.go
  test/e2e/self_hosted.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/testing

#9718 🌱 Add adilGhaffarDev to release-team owner alias
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9706 :book: Add CAPI Operator Quickstart
  docs/book/src/SUMMARY.md
  docs/book/src/user/quick-start-operator.md
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#9720 ✨ Add RKE2 bootstrap provider to clusterctl
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#9723 🌱 Add MP timeouts to cluster upgrade tests
  test/e2e/cluster_upgrade.go
  test/e2e/cluster_upgrade_runtimesdk.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#8842 ✨ Add MachinePool Machine implementation to CAPD components
  exp/internal/controllers/machinepool_controller_phases.go
  internal/webhooks/machine.go
  internal/webhooks/machine_test.go
  test/e2e/clusterclass_rollout.go
  test/framework/ownerreference_helpers.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/rbac/role.yaml
  test/infrastructure/docker/exp/api/v1alpha4/conversion.go
  test/infrastructure/docker/exp/api/v1alpha4/zz_generated.conversion.go
  test/infrastructure/docker/exp/api/v1beta1/dockermachinepool_types.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller_phases.go
  test/infrastructure/docker/exp/internal/docker/nodepool.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  util/labels/helpers.go
  util/labels/helpers_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/clusterctl, area/provider/infrastructure-docker

#9730 🌱 Enforce IPAM import alias
  .golangci.yml
  exp/ipam/api/v1alpha1/conversion.go
  exp/ipam/api/v1alpha1/conversion_test.go
Labels: cncf-cla: yes, lgtm, approved, area/ipam

#9728 🌱 Add additional test cases for nested variable defaulting
  internal/topology/variables/cluster_variable_defaulting_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterclass

#9729 🌱 Add age also to v1beta1 IPAM types
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
  exp/ipam/api/v1beta1/ipaddress_types.go
  exp/ipam/api/v1beta1/ipaddressclaim_types.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ipam

#9404 :seedling: allow non-provider Deployments in Tilt
  Tiltfile
  hack/tools/internal/tilt-prepare/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#9694 :bug: fix provider namespace secret not included in clusterctl move
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/clusterctl

#9719 🌱 Follow-up fixes: Add MachinePools to Runtime SDK and Rollout tests
  internal/contract/infrastructure_machinepool_template.go
  test/e2e/clusterclass_changes.go
  test/e2e/clusterclass_changes_test.go
  test/e2e/clusterclass_rollout.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/testing

#9740 🌱 Bump golangci-lint to v1.55.2
  .github/workflows/pr-golangci-lint.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/dependency

#9744 🌱 Avoid cd'ing into test folders when building Docker images
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9748 🐛 Set User Agent for test extension correctly
  test/extension/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/runtime-sdk

#9753 🌱 Revert "Improve release staging build speed"
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9747 🌱 Release v1.6.0-rc.0
  CHANGELOG/v1.6.0-rc.0.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#9708 🌱 Update GH actions to work with new release-1.6 branch
  .github/workflows/weekly-md-link-check.yaml
  .github/workflows/weekly-security-scan.yaml
  .github/workflows/weekly-test-release.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9737 🌱 Improve output of exec.KubectlApply
  cmd/clusterctl/cmd/topology_plan.go
  test/framework/cluster_proxy.go
  test/framework/clusterctl/client.go
  test/framework/exec/kubectl.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#9766 [release-1.4] 🌱 Improve output of exec.KubectlApply
  cmd/clusterctl/cmd/topology_plan.go
  test/framework/cluster_proxy.go
  test/framework/clusterctl/client.go
  test/framework/exec/kubectl.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#9765 [release-1.5] 🌱 Improve output of exec.KubectlApply
  cmd/clusterctl/cmd/topology_plan.go
  test/framework/cluster_proxy.go
  test/framework/clusterctl/client.go
  test/framework/exec/kubectl.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#9749 [release-1.4] 🐛 fix provider namespace secret not included in clusterctl move
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#9746 [release-1.5] 🐛 fix provider namespace secret not included in clusterctl move
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#9767 :book: add release 1.5 book link
  docs/book/src/introduction.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9771 :book: typo fix in microk8s-bootstrap.md
  docs/book/src/tasks/bootstrap/microk8s-bootstrap.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#9769 🐛 Fix documentation area comparison in release notes
  hack/tools/release/notes/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9649 🌱 MS: improve replica defaulting for autoscaler
  api/v1beta1/machineset_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  docs/book/src/tasks/automated-machine-management/autoscaling.md
  internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/webhooks/machinedeployment.go
  internal/webhooks/machinedeployment_test.go
  internal/webhooks/machineset.go
  internal/webhooks/machineset_test.go
  webhooks/alias.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/machineset

#9772 :seedling: KCP/MS remove hardcoded WithStepCounterIf(false)
  controlplane/kubeadm/internal/controllers/controller.go
  internal/controllers/machineset/machineset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/provider/control-plane-kubeadm, area/machineset

#9782 📖 [release] adds a clarifying note regarding netlify updates
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9784 🐛 Fix Community meeting area formatting in release notes
  hack/tools/release/notes/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9777 🐛 clusterresourceset: requeue after 1 minute if ErrClusterLocked got hit
  exp/addons/internal/controllers/clusterresourceset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/clusterresourceset

#9783 🌱 Release v1.6.0-rc.1
  CHANGELOG/v1.6.0-rc.1.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#9786 📖 Reflect a week of delay in the release-1.6/1.7 timelines
  docs/release/releases/release-1.6.md
  docs/release/releases/release-1.7.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#9640 📖 Remove maintainer role in release team and improve release team docs
  .github/ISSUE_TEMPLATE/release_tracking.md
  docs/proposals/20230407-flexible-managed-k8s-endpoints.md
  docs/release/release-tasks.md
  docs/release/release-team.md
  docs/release/releases/release-1.7.md
  hack/generate-doctoc.sh
Labels: cncf-cla: yes, lgtm, kind/documentation, size/L, approved, area/release

#9725 🌱 Remove requeues in DockerMachinePool
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller_phases.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/provider/infrastructure-docker
