Repository kubernetes-sigs/cluster-api, pull requests merged in 2023-09, with the labels that each got.

#9349 🌱 Bump autoscaler to v1.28.0
  test/e2e/autoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9350 :seedling: Bump trivy to v0.45.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9352 🌱 hack: bump kube-state-metrics and prometheus charts
  hack/observability/kube-state-metrics/chart/kustomization.yaml
  hack/observability/prometheus/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/metrics

#9345 :seedling: Remove Kubeadm upstream v1beta1 types
  Makefile
  bootstrap/kubeadm/api/v1alpha4/conversion_test.go
  bootstrap/kubeadm/types/upstreamv1beta1/bootstraptokenstring.go
  bootstrap/kubeadm/types/upstreamv1beta1/bootstraptokenstring_test.go
  bootstrap/kubeadm/types/upstreamv1beta1/conversion.go
  bootstrap/kubeadm/types/upstreamv1beta1/conversion_test.go
  bootstrap/kubeadm/types/upstreamv1beta1/doc.go
  bootstrap/kubeadm/types/upstreamv1beta1/groupversion_info.go
  bootstrap/kubeadm/types/upstreamv1beta1/types.go
  bootstrap/kubeadm/types/upstreamv1beta1/zz_generated.conversion.go
  bootstrap/kubeadm/types/upstreamv1beta1/zz_generated.deepcopy.go
  bootstrap/kubeadm/types/utils.go
  bootstrap/kubeadm/types/utils_test.go
  controlplane/kubeadm/api/v1alpha4/conversion_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
  test/infrastructure/docker/internal/provisioning/cloudinit/adapter_test.go
  test/infrastructure/docker/internal/provisioning/cloudinit/writefiles_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/provider/bootstrap-kubeadm

#9344 :seedling: Remove files and markers for Kubebuilder
  PROJECT
  bootstrap/kubeadm/PROJECT
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/PROJECT
  controlplane/kubeadm/main.go
  exp/PROJECT
  exp/addons/PROJECT
  exp/addons/internal/controllers/suite_test.go
  exp/internal/controllers/suite_test.go
  internal/controllers/cluster/suite_test.go
  internal/controllers/machine/suite_test.go
  internal/controllers/machinedeployment/suite_test.go
  internal/controllers/machinehealthcheck/suite_test.go
  internal/controllers/machineset/suite_test.go
  main.go
  test/infrastructure/docker/PROJECT
  test/infrastructure/docker/exp/PROJECT
  test/infrastructure/docker/main.go
  test/infrastructure/inmemory/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#9338 :seedling: Improve ClusterClass watch for ExtensionConfigs
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/clusterclass/clusterclass_controller_test.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/runtime-sdk

#9353 🐛 Fix autoscaler image repo
  test/e2e/data/autoscaler/autoscaler-to-workload-workload.yaml
  test/framework/autoscaler_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9358 :seedling: Bump cert-manager to v1.12.4
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9247 :seedling: Add additional blocks to release note generation
  hack/tools/release/notes.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9364 📖 Fix link to KCP v1alpha3 types
  docs/proposals/20191017-kubeadm-based-control-plane.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9346 :seedling: Add MachinePool Builders
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  internal/test/builder/builders.go
  internal/test/builder/infrastructure.go
  internal/test/builder/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/machinepool

#9363 🌱 Verify plantuml image generation in CI
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/ci

#9305 📖 document verification steps for capi images
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/verify-container-images.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/documentation

#9294 🌱 Add Release Team OWNERS file to docs/release folder
  docs/release/OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9386 📖 Improve comment on MachineDeploymentStrategyType
  api/v1beta1/machinedeployment_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/api, area/documentation

#9382 [release-1.4]🌱 Bump to Go 1.19.13
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9388 🌱 Fail tests if test env version check fails
  internal/test/envtest/environment.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9400 🌱 Improve message for TopologyReconciledCondition
  internal/controllers/topology/cluster/conditions.go
  internal/controllers/topology/cluster/conditions_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass

#9407 :seedling: Add verify-import-restrictions to enforce import restrictions
  Makefile
  api/.import-restrictions
  api/v1alpha4/cluster_types.go
  api/v1alpha4/clusterclass_types.go
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/machine_types.go
  api/v1alpha4/machinedeployment_types.go
  api/v1alpha4/machinehealthcheck_types.go
  api/v1alpha4/machineset_types.go
  api/v1beta1/.import-restrictions
  api/v1beta1/index/.import-restrictions
  hack/verify-import-restrictions.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#9408 🌱 Bump cert-manager to v1.13.0
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#9390 🌱 observability: move metrics to config and use sidecar in kube-state-metrics
  Makefile
  Tiltfile
  config/metrics/crd-clusterrole.yaml
  config/metrics/crd-metrics-config.yaml
  config/metrics/kustomization.yaml
  config/metrics/templates/README.md
  config/metrics/templates/cluster.yaml
  config/metrics/templates/clusterclass.yaml
  config/metrics/templates/common_metrics.yaml
  config/metrics/templates/header.yaml
  config/metrics/templates/kubeadmconfig.yaml
  config/metrics/templates/kubeadmcontrolplane.yaml
  config/metrics/templates/machine.yaml
  config/metrics/templates/machinedeployment.yaml
  config/metrics/templates/machinehealthcheck.yaml
  config/metrics/templates/machinepool.yaml
  config/metrics/templates/machineset.yaml
  config/metrics/templates/owner_metric.yaml
  docs/book/src/developer/tilt.md
  hack/observability/kube-state-metrics/chart/kustomization.yaml
  hack/observability/kube-state-metrics/chart/values.yaml
  hack/observability/kube-state-metrics/crd-sidecar-cm.yaml
  hack/observability/kube-state-metrics/crd-sidecar-patch.yaml
  hack/observability/kube-state-metrics/kustomization.yaml
  hack/observability/kube-state-metrics/rbac-crd-aggregation.yaml
  hack/observability/kube-state-metrics/values.yaml
  hack/tools/internal/tilt-prepare/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/devtools

#9387 🌱 Improve Performance dashboard
  hack/observability/grafana/dashboards/cluster-api-performance.json
Labels: cncf-cla: yes, lgtm, size/L, approved, area/devtools

#9412 [release-1.5] 🐛Don't use v1alpha3 in clusterctl upgrade test
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#9340 ✨ ClusterClass: Introduce NamingStrategy and allow generating names using go templates
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/clusterclass_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
  internal/topology/names/names.go
  internal/topology/names/names_test.go
  internal/webhooks/clusterclass.go
  internal/webhooks/clusterclass_test.go
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/clusterclass

#9424 🐛 Pin Plantuml version
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#9425 🐛 topology: fix namingstrategy webhook to not use uppercase characters for testing the template and align unit test to e2e test
  internal/webhooks/clusterclass.go
  internal/webhooks/clusterclass_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass

#9419 :bug: Fix excessive trace logging in the machine health check controller
  internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/machinehealthcheck

#9428 [release-1.5] ✨ ClusterClass: Introduce NamingStrategy and allow generating names using go templates
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/clusterclass_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
  internal/topology/names/names.go
  internal/topology/names/names_test.go
  internal/webhooks/clusterclass.go
  internal/webhooks/clusterclass_test.go
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/clusterclass

#9433 📖 add documentation about namingStrategy in ClusterClasses
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/documentation

#9403 📖 documentation: new Kamaji cp provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/reference/providers.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/documentation

#9246 :seedling: check resource blocking clusterctl move during discovery
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/cluster/objectgraph.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterctl

#9431 [release-1.4] :book: Update jobs.md for newly blocking jobs
  docs/book/src/reference/jobs.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9430 [release-1.5] :book: Update jobs.md for newly blocking jobs
  docs/book/src/reference/jobs.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9429 :book: Update jobs.md for newly blocking jobs
  docs/book/src/reference/jobs.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9264 ⚠️ Implement secure diagnostics (metrics, pprof, log level changes)
  Makefile
  bootstrap/kubeadm/config/manager/manager.yaml
  bootstrap/kubeadm/config/rbac/role.yaml
  bootstrap/kubeadm/main.go
  config/manager/manager.yaml
  config/rbac/role.yaml
  controlplane/kubeadm/config/manager/manager.yaml
  controlplane/kubeadm/config/rbac/role.yaml
  controlplane/kubeadm/main.go
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  docs/book/src/tasks/diagnostics.md
  go.mod
  go.sum
  hack/observability/parca/kustomization.yaml
  hack/observability/parca/rbac-pprof.yaml
  hack/observability/parca/values.yaml
  hack/observability/prometheus/values.yaml
  hack/tools/internal/tilt-prepare/main.go
  main.go
  test/e2e/config/docker.yaml
  test/go.mod
  test/go.sum
  test/infrastructure/docker/config/manager/manager.yaml
  test/infrastructure/docker/config/rbac/role.yaml
  test/infrastructure/docker/main.go
  test/infrastructure/inmemory/config/manager/manager.yaml
  test/infrastructure/inmemory/config/rbac/role.yaml
  test/infrastructure/inmemory/main.go
  util/flags/diagnostics.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/metrics, area/logging

#9417 🌱 Move experimental API v1beta1 webhooks to separate package
  Makefile
  exp/internal/webhooks/doc.go
  exp/internal/webhooks/machinepool.go
  exp/internal/webhooks/machinepool_test.go
  exp/webhooks/alias.go
  exp/webhooks/doc.go
  internal/test/envtest/environment.go
  main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#9439 🌱 Tiltfile: rename deploy_kustomizations to additional_kustomizations
  Tiltfile
  docs/book/src/developer/tilt.md
  hack/tools/internal/tilt-prepare/main.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/devtools

#9389 🌱 Add ownerRefs to BootstrapConfig/InfraMachinePool in classy Clusters
  internal/controllers/topology/cluster/desired_state.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass

#9416 :seedling: extend test/framework to collect workload cluster nodes
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  test/e2e/common.go
  test/framework/alltypes_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/testing

#9445 :seedling: Bump Trivy to v0.45.1
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9441 :seedling: Dump all pods in e2e test clusters
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  test/e2e/common.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9446 🌱 Add loggercheck linter and fix findings
  .golangci.yml
  internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
  test/infrastructure/docker/internal/docker/manager.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9342 🐛 Fix KCP Controller reconcile always return error when workload cluster is unreachable
  controlplane/kubeadm/internal/cluster.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/provider/control-plane-kubeadm

#9444 🌱 Exclude release trigger PRs from release notes
  hack/tools/release/notes.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9448 🌱 Remove redundant GetRESTConfig in KCP Management.GetWorkloadCluster
  controlplane/kubeadm/internal/cluster.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/provider/control-plane-kubeadm

#9438 🌱 Move experimental addons API v1beta1 webhooks to separate package
  Makefile
  exp/addons/internal/webhooks/clusterresourceset_webhook.go
  exp/addons/internal/webhooks/clusterresourceset_webhook_test.go
  exp/addons/internal/webhooks/clusterresourcesetbinding_webhook.go
  exp/addons/internal/webhooks/clusterresourcesetbinding_webhook_test.go
  exp/addons/internal/webhooks/doc.go
  exp/addons/webhooks/alias.go
  exp/addons/webhooks/doc.go
  internal/test/envtest/environment.go
  main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#9460 🌱 Move docker infrastructure experimental API v1beta1 webhooks to sepa…
  test/infrastructure/docker/exp/internal/webhooks/doc.go
  test/infrastructure/docker/exp/internal/webhooks/dockermachinepool_webhook.go
  test/infrastructure/docker/exp/webhooks/alias.go
  test/infrastructure/docker/exp/webhooks/doc.go
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/api

#9462 🌱 test/e2e: structure resources by namespace/kind again
  test/framework/alltypes_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9458 🌱 Move docker infrastructure API v1beta1 webhooks to separate package
  Makefile
  test/infrastructure/docker/internal/webhooks/doc.go
  test/infrastructure/docker/internal/webhooks/dockercluster_webhook.go
  test/infrastructure/docker/internal/webhooks/dockerclustertemplate_webhook.go
  test/infrastructure/docker/internal/webhooks/dockerclustertemplate_webhook_test.go
  test/infrastructure/docker/internal/webhooks/dockermachinetemplate_webhook.go
  test/infrastructure/docker/internal/webhooks/dockermachinetemplate_webhook_test.go
  test/infrastructure/docker/main.go
  test/infrastructure/docker/webhooks/alias.go
  test/infrastructure/docker/webhooks/doc.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#9459 🌱 Move inmemory infrastructure API v1beta1 webhooks to separate package
  Makefile
  test/infrastructure/inmemory/internal/webhooks/doc.go
  test/infrastructure/inmemory/internal/webhooks/inmemorycluster_webhook.go
  test/infrastructure/inmemory/internal/webhooks/inmemoryclustertemplate_webhook.go
  test/infrastructure/inmemory/internal/webhooks/inmemorymachine_webhook.go
  test/infrastructure/inmemory/internal/webhooks/inmemorymachinetemplate_webhook.go
  test/infrastructure/inmemory/main.go
  test/infrastructure/inmemory/webhooks/alias.go
  test/infrastructure/inmemory/webhooks/doc.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#9373 :seedling: Add MachinePool test cases to engine tests
  internal/controllers/topology/cluster/patches/engine_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/testing

#9465 :bug: Reverts pull request from cahillsf/improve-release-speed
  Makefile
  cloudbuild.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9463 :book: Change kubernetes-version in ignition/cluster generation parts of the book
  docs/book/src/clusterctl/commands/generate-cluster.md
  docs/book/src/tasks/experimental-features/ignition.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/documentation

#9415 📖 Bump go minor versions in release branches if they are out of support
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9432 [release-1.4] 🌱 Bump to Go 1.20.8
  Makefile
  Tiltfile
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  hack/ensure-go.sh
  main.go
  test/infrastructure/docker/main.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9393 🌱 Add MachinePools to Topology Quickstart E2E Templates
  docs/book/src/reference/owner_references.md
  test/e2e/data/infrastructure-docker/main/bases/cluster-with-topology.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/framework/ownerreference_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#9469 🌱 Improve labels/annotations in CAPD test ClusterClass
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9464 🌱 Fix some nits in Cluster topology engine tests
  internal/controllers/topology/cluster/patches/engine_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass

#9461 🌱 Enforce import restrictions in all API packages
  bootstrap/kubeadm/api/v1alpha4/groupversion_info.go
  cmd/clusterctl/api/.import-restrictions
  cmd/clusterctl/internal/test/providers/controlplane/generic_types.go
  cmd/clusterctl/internal/test/providers/controlplane/groupversion_info.go
  cmd/clusterctl/internal/test/providers/controlplane/zz_generated.deepcopy.go
  controlplane/kubeadm/api/v1alpha4/groupversion_info.go
  exp/addons/api/.import-restrictions
  exp/addons/api/v1alpha4/clusterresourceset_types.go
  exp/addons/api/v1alpha4/clusterresourcesetbinding_types.go
  exp/addons/api/v1alpha4/groupversion_info.go
  exp/addons/api/v1alpha4/zz_generated.deepcopy.go
  exp/addons/api/v1beta1/.import-restrictions
  exp/api/.import-restrictions
  exp/api/v1alpha4/groupversion_info.go
  exp/api/v1alpha4/machinepool_types.go
  exp/api/v1alpha4/zz_generated.deepcopy.go
  exp/api/v1beta1/.import-restrictions
  exp/ipam/api/.import-restrictions
  exp/ipam/api/v1alpha1/.import-restrictions
  exp/runtime/api/.import-restrictions
  exp/runtime/api/v1alpha1/.import-restrictions
  hack/verify-import-restrictions.sh
  test/infrastructure/docker/api/.import-restrictions
  test/infrastructure/docker/api/v1alpha4/dockercluster_types.go
  test/infrastructure/docker/api/v1alpha4/dockerclustertemplate_types.go
  test/infrastructure/docker/api/v1alpha4/dockermachine_types.go
  test/infrastructure/docker/api/v1alpha4/dockermachinetemplate_types.go
  test/infrastructure/docker/api/v1alpha4/groupversion_info.go
  test/infrastructure/docker/api/v1beta1/.import-restrictions
  test/infrastructure/docker/exp/api/.import-restrictions
  test/infrastructure/docker/exp/api/v1alpha4/dockermachinepool_types.go
  test/infrastructure/docker/exp/api/v1alpha4/groupversion_info.go
  test/infrastructure/docker/exp/api/v1beta1/.import-restrictions
  test/infrastructure/inmemory/api/.import-restrictions
  test/infrastructure/inmemory/api/v1alpha1/.import-restrictions
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#9472 :seedling: Bump apidiff to v0.7.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9474 🌱 Add MachinePool test cases
  internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/testing

#9348 :seedling: Add unit tests for CC MP blueprint, current_state, & desired_state
  internal/controllers/topology/cluster/blueprint_test.go
  internal/controllers/topology/cluster/current_state_test.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/test/builder/infrastructure.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/testing

#9452 🌱 Improve Cluster variable defaulting/validation errors
  internal/topology/variables/cluster_variable_defaulting.go
  internal/topology/variables/cluster_variable_validation.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass

#9380 🌱 Add unit tests for reconcile_state, cluster_controller, & conditions
  controllers/remote/cluster_cache_tracker_fake.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/controllers/topology/cluster/conditions_test.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/suite_test.go
  internal/test/builder/builders.go
  internal/test/builder/infrastructure.go
  internal/test/builder/zz_generated.deepcopy.go
  internal/test/envtest/environment.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/testing

#9477 :bug: Drop MachinePools from Dualstack tests
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/drop-machinepools.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/drop-machinepools.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/kustomization.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#9490 :book: Fix broken link to docker webhook and d2iq
  docs/book/src/developer/providers/webhooks.md
  docs/proposals/20200423-etcd-data-disk.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9482 :seedling: Remove the dependency on cluster-api/utils from addons API
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/api

#9494 🌱 Release v1.4.7
  CHANGELOG/v1.4.7.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9493 :seedling: Add log level for kube components patch to ClusterClass
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/cluster.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/cluster.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#9495 🌱 Release v1.5.2
  CHANGELOG/v1.5.2.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#9500 🌱 Format MachineHealthCheck area in release notes
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9501 [release-1.5] :seedling: Add log level for kube components patch to ClusterClass
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/cluster.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/cluster.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#9499 :seedling: Fix .golangci.yml comments
  .golangci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9504 [release-1.5] :bug: Fix broken e2e test clusterclass
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9506 :seedling: Fix broken e2e test clusterclass
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9502 🌱 Add MachinePools to topology upgrade test
  test/e2e/cluster_upgrade.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-runtimesdk/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades/kustomization.yaml
  test/e2e/self_hosted.go
  test/framework/cluster_topology_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#9511 :book: Fixup `from` typo
  internal/controllers/machinedeployment/machinedeployment_sync.go
  internal/controllers/machineset/machineset_controller_test.go
  internal/controllers/topology/cluster/conditions.go
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation
