Repository kubernetes-sigs/cluster-api, pull requests merged in 2023-08, with the labels that each got.

#9103 🌱 Bump to Go 1.20.7
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9105 [release-1.5] 🌱 Bump to Go 1.20.7
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9093 🌱 Change default log level to 2
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  docs/book/src/developer/logging.md
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
  main.go
  test/extension/main.go
  test/infrastructure/docker/main.go
  test/infrastructure/inmemory/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#9112 🐛 Fix doctoc detection in verify-doctoc.sh
  CONTRIBUTING.md
  Makefile
  docs/proposals/20181121-machine-api.md
  docs/proposals/20190610-machine-states-preboot-bootstrapping.md
  docs/proposals/20190709-cluster-spec-crds.md
  docs/proposals/20190919-machinepool-api.md
  docs/proposals/20191016-clusterctl-redesign.md
  docs/proposals/20191016-e2e-test-framework.md
  docs/proposals/20191017-kubeadm-based-control-plane.md
  docs/proposals/20191030-machine-health-checking.md
  docs/proposals/20200220-cluster-resource-set.md
  docs/proposals/20200330-spot-instances.md
  docs/proposals/20200423-etcd-data-disk.md
  docs/proposals/20200506-conditions.md
  docs/proposals/20200511-clusterctl-extensible-template-processing.md
  docs/proposals/20200602-machine-deletion-phase-hooks.md
  docs/proposals/20200804-windows-support.md
  docs/proposals/20201020-capi-provider-operator.md
  docs/proposals/20210203-externally-managed-cluster-infrastructure.md
  docs/proposals/20210210-insulate-users-from-kubeadm-API-changes.md
  docs/proposals/20210222-kubelet-authentication.md
  docs/proposals/20210310-opt-in-autoscaling-from-zero.md
  docs/proposals/20210526-cluster-class-and-managed-topologies.md
  docs/proposals/20220125-ipam-integration.md
  docs/proposals/20220209-machinepool-machines.md
  docs/proposals/20220221-runtime-SDK.md
  docs/proposals/20220330-topology-mutation-hook.md
  docs/proposals/20220411-cluster-api-state-metrics.md
  docs/proposals/20220414-runtime-hooks.md
  docs/proposals/20220712-cluster-api-addon-orchestration.md
  docs/proposals/20220725-managed-kubernetes.md
  docs/proposals/20220927-label-sync-between-machine-and-nodes.md
  docs/proposals/20221003-In-place-propagation-of-Kubernetes-objects-only-changes.md
  docs/proposals/YYYYMMDD-template.md
  docs/scope-and-objectives.md
  docs/staging-use-cases.md
  hack/generate-doctoc.sh
  hack/verify-doctoc.sh
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#9117 [release-1.5] :bug: Fix link to v1.1-v1.2 provider migration guide
  docs/proposals/20210526-cluster-class-and-managed-topologies.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9115 :seedling: Update actions for 1.5 and make names consistent
  .github/dependabot.yaml
  .github/workflows/pr-dependabot.yaml
  .github/workflows/pr-golangci-lint.yaml
  .github/workflows/pr-md-link-check.yaml
  .github/workflows/pr-verify.yaml
  .github/workflows/release.yaml
  .github/workflows/weekly-image-scan.yaml
  .github/workflows/weekly-md-link-check.yaml
  .github/workflows/weekly-test-release.yaml
  Makefile
  docs/book/src/reference/jobs.md
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/ci

#9122 [release-1.5] 🐛 Bump golang.org/x/net to v0.13.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#9123 [release-1.4] 🐛 Bump golang.org/x/net to v0.13.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#9121 🐛 Bump golang.org/x/net to v0.13.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#9126 :seedling: Bump controller-runtime to v0.15.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9116 🌱 Add separate concurrency flag for cluster cache tracker
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  main.go
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clustercachetracker

#9107 🌱 Set controller-runtime logger for clusterctl
  cmd/clusterctl/cmd/root.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9045 🌱 Remove reliance on controller-runtime scheme builder
  api/v1beta1/cluster_types.go
  api/v1beta1/clusterclass_types.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/machine_types.go
  api/v1beta1/machinedeployment_types.go
  api/v1beta1/machinedeployment_webhook_test.go
  api/v1beta1/machinehealthcheck_types.go
  api/v1beta1/machineset_types.go
  docs/book/src/developer/providers/implementers-guide/create_api.md
  internal/test/builder/builders.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#9084 🌱 hack/observability: add capi_machine_status_certificatesexpirydate metric
  hack/observability/kube-state-metrics/crd-config.yaml
  hack/observability/kube-state-metrics/metrics/machine.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#9141 :book: Remove unnecessary task from release tasks doc
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9120 🌱 Add ClusterClass column to Cluster CRD
  api/v1beta1/cluster_types.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/api

#9139 🌱 CAPD: fix multi error handling in RunContainer
  test/infrastructure/container/docker.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/provider/infrastructure-docker

#9071 🌱 Improve multiple areas PRs with user friendly subs
  hack/tools/release/notes.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9146 📖 Document new scheme-builder patterns in provider migration doc
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9148 🌱 Add .PHONY for doctoc target
  Makefile
Labels: cncf-cla: yes, lgtm, approved, area/devtools

#8260 :book: Add call out for area labels when making a PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#9150 :book: Add a guide describing ownerReference usage in CAPI
  docs/book/src/SUMMARY.md
  docs/book/src/reference/owner_references.md
  test/framework/ownerreference_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#9152 🌱 Use existing value of `SKIP_RESOURCE_CLEANUP` if set in environment
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9156 🌱 Drop duplicate pprof and unused linter excludes
  .golangci.yml
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#9136 🌱 Remove previously deprecated code
  controllers/noderefutil/providerid.go
  controllers/noderefutil/providerid_test.go
  controllers/noderefutil/util.go
  controllers/remote/index.go
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  util/retry.go
  util/util.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#9119 📖 Update CAPI support and guarantees for v1.6
  CONTRIBUTING.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/documentation

#9020 🌱 Move tilt-prepare and log-push to tools/internal
  Makefile
  Tiltfile
  docs/book/src/developer/testing.md
  docs/book/src/developer/tilt.md
  docs/release/release-tasks.md
  hack/tools/internal/log-push/main.go
  hack/tools/internal/log-push/main_test.go
  hack/tools/internal/tilt-prepare/main.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/devtools

#9163 :bug: Generate warning when release notes can not be generated
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9097 🌱 Prepare main branch for v1.6 development
  Makefile
  cmd/clusterctl/hack/create-local-repository.py
  docs/release/release-tasks.md
  hack/tools/internal/tilt-prepare/main.go
  metadata.yaml
  test/e2e/clusterctl_upgrade.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1.5/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.5/bases/cluster-with-topology.yaml
  test/e2e/data/infrastructure-docker/v1.5/bases/crs.yaml
  test/e2e/data/infrastructure-docker/v1.5/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.5/cluster-template-topology/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1.5/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1.5/clusterclass-quick-start.yaml
  test/e2e/data/shared/main/metadata.yaml
  test/e2e/data/shared/v1.5/metadata.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#9144 🌱 Add verify-govulncheck and verify-vulnerabilities targets and integrate to scan action
  .github/workflows/weekly-security-scan.yaml
  Makefile
  docs/release/release-tasks.md
  hack/verify-container-images.sh
Labels: cncf-cla: yes, lgtm, size/M, approved

#9174 :seedling: Bump golangci-lint to v1.54.1
  .github/workflows/pr-golangci-lint.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9164 🐛 Fix AddAnnotations for unstructured.Unstructured
  util/annotations/helpers.go
  util/annotations/helpers_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/util

#9166 🌱 Add back flavor to Waiter interface
  test/framework/clusterctl/clusterctl_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9175 :seedling: Replace hashicorp/go-multierror with kerrors
  hack/tools/conversion-verifier/main.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9179 [release-1.5] 🌱 Add verify-govulncheck and verify-vulnerabilities targets and integrate to scan action
  .github/workflows/weekly-security-scan.yaml
  Makefile
  hack/verify-container-images.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, area/ci

#9180 [release-1.4] 🌱 Add verify-govulncheck and verify-vulnerabilities targets and integrate to scan action
  .github/workflows/weekly-security-scan.yaml
  Makefile
  hack/verify-container-images.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, area/ci

#9147 :seedling: Add colored-line-number output for golangci-lint action
  .github/workflows/pr-golangci-lint.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9183 :seedling: Make dev cluster networking configurable
  hack/kind-install-for-capd.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/devtools

#9170 :bug: Allow to drop useExperimentalRetryJoin field from KubeadmControlPlane.kubeadmConfigSpec
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/provider/control-plane-kubeadm

#9197 🌱 Update cert-manager to v1.12.3
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#9099 🌱 Remove disableInPlacePropagation field in KCP controller
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/controllers/upgrade_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/provider/control-plane-kubeadm

#8586 :seedling: Refactor docker-push* Makefile targets so users can control with ALL_DOCKER_BUILD which images are pushed
  Makefile
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/devtools

#9182 🌱 Makefile: run doctoc only once
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#9192 🌱 go.mod reformat to have only two require blocks
  go.mod
Labels: cncf-cla: yes, lgtm, size/M, approved, area/ci

#9191 :sparkles: Add topology-owned label to MachineHealthChecks.
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/machinehealthcheck

#9202 [release-1.5] 🐛 Allow unsetting useExperimentalRetryJoin field from KubeadmControlPlane
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/provider/control-plane-kubeadm

#9201 [release-1.4] 🐛 Allow unsetting useExperimentalRetryJoin field from KubeadmControlPlane
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/provider/control-plane-kubeadm

#9173 :book: Reword and list which deployments have to be edited for exp features.
  docs/book/src/tasks/experimental-features/experimental-features.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#9206 :seedling: [release-1.4] Update base branch for link checker
  .github/workflows/lint-docs-pr.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9207 :seedling: [release-1.5] Update base branch for link checker
  .github/workflows/lint-docs-pr.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9047 🌱 Move API v1beta1 webhooks to a separate package
  api/v1beta1/machinehealthcheck_types.go
  api/v1beta1/zz_generated.openapi.go
  config/webhook/manifests.yaml
  controlplane/kubeadm/internal/controllers/controller_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/test/builder/builders.go
  internal/test/envtest/environment.go
  internal/webhooks/clusterclass.go
  internal/webhooks/machine.go
  internal/webhooks/machine_test.go
  internal/webhooks/machinedeployment.go
  internal/webhooks/machinedeployment_test.go
  internal/webhooks/machinehealthcheck.go
  internal/webhooks/machinehealthcheck_test.go
  internal/webhooks/machineset.go
  internal/webhooks/machineset_test.go
  main.go
  webhooks/alias.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#9160 ✨ v1.28: Prepare quickstart, capd and tests for the new release including kind bump
  Tiltfile
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing, area/documentation

#9213 📖 docs: update k8s-triage link to one which catches all relevant jobs
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9161 📖 book: Update versions doc adding Kubernetes 1.28 + prowjob documentation
  docs/book/src/developer/providers/version-migration.md
  docs/book/src/reference/jobs.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/documentation

#9225 [release-1.5] ✨ v1.28: Prepare quickstart, capd and tests for the new release includi…
  Tiltfile
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing, area/documentation

#9226 [release-1.5] 📖 book: Update versions doc adding Kubernetes 1.28 + prowjob documentation
  docs/book/src/reference/jobs.md
  docs/book/src/reference/versions.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#9209 📖 .github: improve kubernetes bump issue template
  .github/ISSUE_TEMPLATE/kubernetes_bump.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#9167 🐛Certificate paths in cloud-init scripts should not use a platform-dependent path separator
  util/secret/certificates.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/bootstrap

#9222 ✨ machineset: adjust preflight check to allow kubelet version skew of 3 for clusters running v1.28 and above
  internal/controllers/machineset/machineset_preflight.go
  internal/controllers/machineset/machineset_preflight_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/machineset

#9224 🌱 Fix patch errors not being logged
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/logging

#8690 :sparkles: block move with annotation
  cmd/clusterctl/api/v1alpha3/annotations.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
  docs/book/src/clusterctl/commands/move.md
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  docs/book/src/reference/labels_and_annotations.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterctl

#9232 :book: Documentation improvements: public release session
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9238 [release-1.5] 📖 Add task to update link checker base branch
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9089 🌱 Clarify release team vs k8s/k8s-SIGs org membership
  docs/release/release-team.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#9241 :seedling: Bump kpromo to v4.0.4
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency, area/release

#9113 :seedling: Add test for required properties in clusterclass variables
  internal/topology/variables/clusterclass_variable_validation_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#9165 🐛 tilt: ensure .tiltbuild/bin directory is created early enough, add tilt troubleshooting guide
  Tiltfile
  docs/book/src/developer/tilt.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/devtools

#9245 [release-1.4] 📖 Add task to update link checker base branch
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9111 ✨ Add automation to create release branch and tags
  .github/workflows/release.yaml
  .gitignore
  CHANGELOG/OWNERS
  CHANGELOG/README.md
  Makefile
  OWNERS_ALIASES
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#9244 🌱 github: add workflow to auto-approve golangci-lint if ok-to-test label is set
  .github/workflows/pr-gh-workflow-approve.yaml
  docs/book/src/reference/jobs.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/ci

#9252 🐛 test: pin conformance image to a version which includes a fix for the dualstack tests
  test/e2e/config/docker.yaml
  test/e2e/quick_start_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9259 🌱 github: add edited and reopened as triggers for the GH workflow approval
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9254 🌱 Make ClusterClass generated object names consistent
  cmd/clusterctl/client/cluster/topology_test.go
  internal/controllers/topology/cluster/util.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass

#9263 :seedling: Add dependabot groups. Allow additional patch updates
  .github/dependabot.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, area/ci

#9275 🌱 Update ensure-kubectl.sh to 1.28
  hack/ensure-kubectl.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9266 🌱 Remove reliance on controller-runtime scheme builder for remaining API groups
  bootstrap/kubeadm/api/v1beta1/groupversion_info.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfigtemplate_types.go
  cmd/clusterctl/api/v1alpha3/groupversion_info.go
  cmd/clusterctl/api/v1alpha3/metadata_type.go
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/kubeadm/api/v1beta1/groupversion_info.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_types.go
  test/infrastructure/docker/api/v1beta1/dockercluster_types.go
  test/infrastructure/docker/api/v1beta1/dockerclustertemplate_types.go
  test/infrastructure/docker/api/v1beta1/dockermachine_types.go
  test/infrastructure/docker/api/v1beta1/dockermachinetemplate_types.go
  test/infrastructure/docker/api/v1beta1/groupversion_info.go
  test/infrastructure/docker/exp/api/v1beta1/dockermachinepool_types.go
  test/infrastructure/docker/exp/api/v1beta1/groupversion_info.go
  test/infrastructure/docker/exp/api/v1beta1/zz_generated.deepcopy.go
  test/infrastructure/inmemory/api/v1alpha1/groupversion_info.go
  test/infrastructure/inmemory/api/v1alpha1/inmemorycluster_types.go
  test/infrastructure/inmemory/api/v1alpha1/inmemoryclustertemplate_types.go
  test/infrastructure/inmemory/api/v1alpha1/inmemorymachine_types.go
  test/infrastructure/inmemory/api/v1alpha1/inmemorymachinetemplate_types.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#8999 ⚠️ Bump to controller-runtime v0.16
  bootstrap/kubeadm/main.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controllers/remote/cluster_cache_reconciler_test.go
  controllers/remote/cluster_cache_tracker_test.go
  controlplane/kubeadm/main.go
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  internal/test/envtest/environment.go
  internal/topology/variables/cluster_variable_validation.go
  internal/topology/variables/clusterclass_variable_validation.go
  main.go
  test/go.mod
  test/go.sum
  test/infrastructure/docker/main.go
  test/infrastructure/inmemory/main.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/dependency

#9288 :warning: : Remove go-vcs dependency from releaselink tool
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  docs/book/src/user/quick-start.md
  hack/tools/go.mod
  hack/tools/mdbook/releaselink/releaselink.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/util

#9195 🌱 Bump CAPI visualizer to v1.2.0
  hack/observability/visualizer/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#9270 :book: Documentation improvements: suggestions for team leads
  docs/release/release-tasks.md
  docs/release/release-team.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/documentation

#9291 📖 add step for indexing the CRDs of the latest release
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/XS, approved, area/release

#9296 :seedling: Add CRS re-reconcile to ownerReference test
  test/framework/ownerreference_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#9153 :seedling: Test and document controller ownerReferences
  docs/book/src/reference/owner_references.md
  test/framework/ownerreference_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#9268 🌱 Bump envtest binaries to 1.28
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9302 :bug: Allow duplicate objects in Tiltfile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/devtools

#9251 :seedling: refactor SortForCreate to use sort.Slice
  util/resource/resource.go
  util/resource/resource_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/util

#9307 🌱 Bump corefile-migration library to v1.0.21
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9309 [release-1.5] 🌱 Bump corefile-migration library to v1.0.21
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9310 [release-1.4] 🌱 Bump corefile-migration library to v1.0.21
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9313 :seedling: Refactor e2e ownerRef test utils
  test/framework/ownerreference_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#9315 :bug: Fix tilt-prepare leader-elect setting
  hack/tools/internal/tilt-prepare/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#9308 🐛 Adding metrics container port in tilt-prepare only if it's missing
  hack/tools/internal/tilt-prepare/main.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/devtools

#9311 :seedling: adjust naming in SortForCreate implementation
  util/resource/resource.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/util

#9016 ✨ Add MachinePool workers support in ClusterClass
  api/v1beta1/condition_consts.go
  cmd/clusterctl/client/cluster/topology.go
  config/rbac/role.yaml
  controllers/alias.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/topology/cluster/blueprint.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/conditions.go
  internal/controllers/topology/cluster/current_state.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/patches/engine.go
  internal/controllers/topology/cluster/patches/inline/json_patch_generator.go
  internal/controllers/topology/cluster/patches/template.go
  internal/controllers/topology/cluster/patches/variables/variables.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/scope/blueprint.go
  internal/controllers/topology/cluster/scope/scope.go
  internal/controllers/topology/cluster/scope/state.go
  internal/controllers/topology/cluster/scope/upgradetracker.go
  internal/controllers/topology/cluster/suite_test.go
  internal/controllers/topology/cluster/util.go
  internal/log/log.go
  internal/topology/check/compatibility.go
  internal/topology/variables/cluster_variable_defaulting.go
  internal/topology/variables/cluster_variable_validation.go
  internal/webhooks/cluster.go
  internal/webhooks/clusterclass.go
  internal/webhooks/patch_validation.go
  main.go
  test/extension/handlers/topologymutation/handler.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepooltemplates.yaml
  test/infrastructure/docker/config/crd/kustomization.yaml
  test/infrastructure/docker/exp/api/v1beta1/dockermachinepooltemplate_types.go
  test/infrastructure/docker/exp/api/v1beta1/zz_generated.deepcopy.go
  test/infrastructure/docker/templates/cluster-template-development.yaml
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#9186 :bug: Deduplicating area in pr title in release notes
  hack/tools/release/notes.go
  hack/tools/release/notes_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/release

#9236 🌱 use http get to download files from GitHub in clusterctl
  cmd/clusterctl/client/repository/repository_github.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterctl

#9237 🌱 use goproxy to check version in clusterctl
  cmd/clusterctl/cmd/version_checker.go
  cmd/clusterctl/cmd/version_checker_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterctl

#9298 🐛 MD controller: use regular random suffix for MachineSets, ensure max length 63
  internal/controllers/machinedeployment/machinedeployment_sync.go
  internal/controllers/machinedeployment/machinedeployment_sync_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/machinedeployment

#9318 🌱 Minor fixes for CC+MP implementation
  internal/controllers/topology/cluster/blueprint.go
  internal/controllers/topology/cluster/conditions.go
  internal/controllers/topology/cluster/current_state.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/patches/patch.go
  internal/controllers/topology/cluster/patches/template.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/scope/blueprint.go
  internal/controllers/topology/cluster/scope/scope_test.go
  internal/controllers/topology/cluster/scope/state.go
  internal/controllers/topology/cluster/scope/upgradetracker.go
  internal/controllers/topology/cluster/scope/upgradetracker_test.go
  internal/controllers/topology/cluster/util.go
  internal/topology/check/compatibility.go
  internal/webhooks/cluster.go
  internal/webhooks/clusterclass.go
  internal/webhooks/patch_validation.go
  test/extension/handlers/topologymutation/handler.go
  test/infrastructure/docker/config/crd/kustomization.yaml
  test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachinepooltemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepooltemplates.yaml
  test/infrastructure/docker/exp/api/v1beta1/dockermachinepooltemplate_types.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/clusterclass

#9328 :seedling: Use official plantuml image for diagrams
  Makefile
  docs/Dockerfile
  docs/Makefile
  docs/book/src/images/bootstrap-controller.png
  docs/book/src/images/bootstrap-provider.png
  docs/book/src/images/cluster-admission-cluster-controller.png
  docs/book/src/images/cluster-admission-machine-controller.png
  docs/book/src/images/cluster-admission-machinedeployment-controller.png
  docs/book/src/images/cluster-admission-machinepool-controller.png
  docs/book/src/images/cluster-admission-machineset-controller.png
  docs/book/src/images/cluster-infra-provider.png
  docs/book/src/images/cluster-resource-set-controller.png
  docs/book/src/images/cluster-topology-controller.png
  docs/book/src/images/cluster-topology-reconciller.png
  docs/book/src/images/control-plane-controller.png
  docs/book/src/images/kubeadm-control-plane-machines-resources.png
  docs/book/src/images/machine-infra-provider.png
  docs/book/src/images/machinehealthcheck-controller.png
  docs/book/src/images/management-workload-same-cluster.png
  docs/book/src/images/management-workload-separate-clusters.png
  docs/book/src/images/runtime-sdk-topology-mutation.png
  docs/book/src/images/worker-machines-resources.png
  docs/proposals/images/capi-provider-operator/fig1.png
  docs/proposals/images/capi-provider-operator/fig2.png
  docs/proposals/images/cluster-class/create.png
  docs/proposals/images/cluster-class/update.png
  docs/proposals/images/cluster-spec-crds/figure1.png
  docs/proposals/images/cluster-spec-crds/figure2.png
  docs/proposals/images/clusterctl-extensible-templates/pkgCalls.png
  docs/proposals/images/clusterctl-extensible-templates/templateClient.png
  docs/proposals/images/clusterctl-extensible-templates/yamlProcessor.png
  docs/proposals/images/clusterctl-redesign/config.png
  docs/proposals/images/clusterctl-redesign/init.png
  docs/proposals/images/controlplane/controlplane-init-1.png
  docs/proposals/images/controlplane/controlplane-init-2.png
  docs/proposals/images/controlplane/controlplane-init-3.png
  docs/proposals/images/controlplane/controlplane-init-4.png
  docs/proposals/images/controlplane/controlplane-init-6.png
  docs/proposals/images/controlplane/controlplane-init-7.png
  docs/proposals/images/developer/diagram.png
  docs/proposals/images/kubelet-authentication/client-authenticator-flow.png
  docs/proposals/images/machine-health-check/mhc.png
  docs/proposals/images/machine-states-preboot/Figure3.png
  docs/proposals/images/machine-states-preboot/Figure4.png
  docs/proposals/images/machine-states-preboot/Figure5.png
  docs/proposals/images/machine-states-preboot/Figure6.png
  docs/proposals/images/machine-states-preboot/Figure7.png
  docs/proposals/images/machine-states-preboot/Figure8.png
  docs/proposals/images/machinepool-api/figure1.png
  docs/proposals/images/machinepool-machines/infraref-changed-sequence.png
  docs/proposals/images/topology-mutation-hook/topology-reconciliation.png
Labels: cncf-cla: yes, lgtm, size/M, approved, area/documentation

#9321 🌱 Release v1.5.1
  CHANGELOG/v1.5.1.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#9336 :bug: fix go install path for kpromo v4.0.4
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9184 :seedling: Add licence-scan for pull requests
  CONTRIBUTING.md
  Makefile
  hack/ensure-trivy.sh
  hack/verify-container-images.sh
  hack/verify-licenses.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, area/ci

#9286 🌱 Promote chrischdi to cluster-api reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9339 🌱 golangci-lint: replace deprecated local-prefixes setting for gci
  .golangci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9341 :seedling: Make GO_ARCH explicit in verify_containter script
  hack/verify-container-images.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9337 🌱 Improve release notes formatting
  hack/tools/release/notes.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release
