Repository kubernetes-sigs/cluster-api, pull requests merged in 2023-10, with the labels that each got.

#9512 🌱 Embed ssa.FilterObjectInput into HelperOption to remove duplication
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/options.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
  internal/controllers/topology/cluster/structuredmerge/twowayspatchhelper.go
Labels: cncf-cla: yes, lgtm, size/M, approved, kind/cleanup, ok-to-test, area/clusterclass, area/util

#9510 :seedling: Add test for scale testing machinery
  test/e2e/scale_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#9513 :book: Add a line about the format of key for clusterctl config
  docs/book/src/clusterctl/configuration.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/XS, approved, ok-to-test, area/documentation

#9521 🌱 ipam: add age column to kubectl output
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
  exp/ipam/api/v1alpha1/ipaddress_types.go
  exp/ipam/api/v1alpha1/ipaddressclaim_types.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ipam

#9514 :book: Fix Equinix metal link in docs
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9527 :book: bootstrap: Provide an example.
  docs/book/src/developer/providers/bootstrap.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#9529 ✨CAPD: Initialize configmap object before getting it
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/provider/infrastructure-docker

#9528 ✨Add config maps to CAPD RBAC
  test/infrastructure/docker/config/rbac/role.yaml
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/provider/infrastructure-docker

#9544 :seedling: Bump github.com/docker/distribution
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
  util/container/image.go
  util/container/image_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#9488 :book: Add release tasks to update the GitHub actions to work with the new release
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/XS, approved, area/release

#9551 :seedling: Bump Go to v1.20.10
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9547 🌱 Dump all resource information for self-hosted tests
  test/e2e/common.go
  test/e2e/self_hosted.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#9443 🌱 Update instructions checklist to generate release notes
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#9553 [release-1.4] :seedling: Bump Go to v1.20.10
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9558 :seedling: Bump trivy to v0.46.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9549 🌱 Bump some dependencies in Makefile
  Makefile
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9550 📖 Clarify adding/removing release team members
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/XS, approved, area/release

#9487 :book: Add release task about removing unsupported release version of CAPI
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/XS, approved, area/release

#9573 🌱 update release-notes make target + corresponding doc
  Makefile
  docs/release/release-tasks.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9588 [release-1.4] :bug: Revert ErrClusterLocked check in Machine controller
  internal/controllers/machine/machine_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/machine

#9592 🌱 Bump controller-runtime to v0.16.3
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#9593 📖 Add a note to the CI team tasks to check for stuck/pending jobs in CI
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/XS, approved, area/release

#9471 🌱 Ensure finalizers are resilient on reconciliation
  cmd/clusterctl/client/cluster/ownergraph.go
  test/e2e/quick_start_test.go
  test/framework/finalizers_helpers.go
  test/framework/ownerreference_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/e2e-testing

#9594 [release-1.4] 🌱 Bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#9595 [release-1.5] 🌱 Bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#9605 🌱 Remove extra separator after title in release notes
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9572 :book: Add release templates
  docs/release/release-tasks.md
  docs/release/release-templates.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#9599 [release-1.5] 🌱 Bump go.opentelemetry.io/* dependencies
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#9598 🌱 Bump go.opentelemetry.io/* dependencies
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#9219 🌱 Add util function to get MachinePool by label
  exp/internal/controllers/machinepool_controller_phases.go
  exp/util/suite_test.go
  exp/util/util.go
  exp/util/util_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/machinepool

#9600 🌱 Release v1.4.8
  CHANGELOG/v1.4.8.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9601 🌱 Release v1.5.3
  CHANGELOG/v1.5.3.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9612 🌱 Release v1.6.0-beta.0
  CHANGELOG/v1.6.0-beta.0.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#9614 🌱 Capitalize area prefix in release notes by default
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9565 📖 Add onboarding documentation for the Release Team
  docs/release/release-tasks.md
  docs/release/release-team-onboarding.md
  docs/release/release-team.md
  hack/generate-doctoc.sh
Labels: cncf-cla: yes, lgtm, kind/documentation, size/M, approved, area/release

#9621 🌱 Ensure we generate all webhook manifests.yaml
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/api

#9613 📖 E2e: Document self hosted machine templates
  test/e2e/self_hosted.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9624 [release-1.5] :seedling: Bump controller runtime to v1.15.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#9625 [release-1.4] :seedling: Bump controller runtime to v1.14.7
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#9626 :seedling: Bump golang.org/grpc to v1.59.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#9627 [release-1.5] :seedling: Bump golang.org/grpc to v1.59.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#9571 📖 add proposal for karpenter integration feature group
  docs/community/20231018-karpenter-integration.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/community-meeting

#9590 📖 Define details of "Communicate key dates to the community"
  docs/release/release-tasks.md
Labels: size/S, cncf-cla: yes, lgtm, kind/documentation, approved, area/release

#9648 🌱 Format Community meeting area in release notes
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9650 🌱 Bump PR title checker github action to v0.4.1
  .github/workflows/pr-verify.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#9647 🌱 Release v1.6.0-beta.1
  CHANGELOG/v1.6.0-beta.1.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release
