Repository kubernetes-sigs/cluster-api, pull requests merged in 2023-05, with the labels that each got.

#8579 ✨ Add flags for configuring rate limits
  .gitignore
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  main.go
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8576 🐛 internal/machine-controller fix flakes in phases test
  internal/controllers/machine/machine_controller_phases_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8577 🌱 use providerID string as-is
  api/v1beta1/index/machine.go
  api/v1beta1/index/machine_test.go
  api/v1beta1/index/machinepool.go
  api/v1beta1/index/machinepool_test.go
  api/v1beta1/index/node.go
  api/v1beta1/index/node_test.go
  controllers/noderefutil/providerid.go
  controllers/noderefutil/providerid_test.go
  exp/internal/controllers/machinepool_controller.go
  exp/internal/controllers/machinepool_controller_noderef.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machine/machine_controller_noderef_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8539 [release-1.4] 📖 Update versions doc with k8s v1.27 notes
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8581 🌱 Bump controller-tools to v0.12
  Makefile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/clusterctl

#8593 📖 updates to release task docs and notes tool
  docs/release/release-tasks.md
  hack/tools/release/notes.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8597 📖 Improve cutting release notes steps in release-tasks
  docs/release/release-tasks.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8599 :seedling:Update kubebuilder envtest (1.26.0 -> 1.27.1)
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8544 :book: Remove roadmap.md from the book
  docs/book/src/SUMMARY.md
  docs/book/src/roadmap.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, tide/merge-method-squash, ok-to-test

#8604 🐛 Return error on infra cluster and control plane discovery
  cmd/clusterctl/client/tree/discovery.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#8253 🐛 clusterctl: return early if release for latest tag does not exist yet
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
  cmd/clusterctl/client/repository/repository_versions.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterctl

#8612 :book: Fix documentation
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8613 :book: Adjust release notes section to reduce the chance of wrong copy paste
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8617 🐛 Prevent KCP to create many private keys for each reconcile
  controllers/remote/cluster_cache_tracker.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/workload_cluster.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7966 :sparkles: feat: accept resource mutators in Move operation
  api/v1beta1/cluster_types.go
  api/v1beta1/clusterclass_types.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
  cmd/clusterctl/client/move.go
  cmd/clusterctl/client/move_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/clusterctl

#8611 🐛 ClusterResourceSet: continue applying when apply for a single cluster failed
  exp/addons/internal/controllers/clusterresourceset_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8626 🐛 [release-1.3] Prevent KCP to create many private keys for each reconcile
  controllers/remote/cluster_cache_tracker.go
  controlplane/kubeadm/internal/cluster.go
  controlplane/kubeadm/internal/workload_cluster.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8630 :book: Minor documentation grammar changes for code comments.
  exp/addons/api/v1beta1/clusterresourceset_webhook.go
  exp/api/v1beta1/machinepool_webhook.go
  internal/webhooks/clusterclass.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8632 📖 testing: add jq variant for inspecting json logs
  docs/book/src/developer/testing.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8635 🐛 verifier: use pull_request instead of pull_request_target
  .github/workflows/verify.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8637 🌱 verifier: change back to pull_request_target to make it work again
  .github/workflows/verify.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8638 :seedling: Update cert-manager to v1.11.2
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency, area/clusterctl

#8634 :bug: test/framework fix docker pod log collector
  test/framework/docker_logcollector.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8625 🐛 test/e2e check for machines being ready after provisioning on Runtime SDK test
  test/e2e/cluster_upgrade_runtimesdk.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8645 🌱 Bump docker/distribution to v2.8.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#8650 [release-1.3] :seedling: Bump docker/distribution to v2.8.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#8651 :bug: Fix Documentation for Ignition Bootstrap Feature Gate Environment Variable
  docs/book/src/tasks/experimental-features/ignition.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8642 :bug: Delegate CAPD port selection to the container runtime
  test/infrastructure/docker/internal/docker/kind_manager.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7910 🌱 E2e: Unhold CI packages before installing
  test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl
Labels: cncf-cla: yes, lgtm, lifecycle/stale, size/XS, approved

#8548 :seedling: Disable fail-fast by default for e2e tests
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#8660 [release-1.3] 🌱 Disable fail-fast by default for e2e tests
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8659 [release-1.4] 🌱 Disable fail-fast by default for e2e tests
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8662 🌱 e2e: log leftover processes to eventually detect zombies
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8627 🐛 MachinePool: always patch owned conditions, fix GetTypedPhase, doc fixes
  docs/book/src/tasks/experimental-features/machine-pools.md
  docs/proposals/20190919-machinepool-api.md
  exp/api/v1beta1/machinepool_types.go
  exp/internal/controllers/machinepool_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8676 :seedling: Bump kindnet and haproxy images to latest
  test/e2e/data/cni/kindnet/kindnet.yaml
  test/infrastructure/docker/internal/loadbalancer/const.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#8661 :seedling: Use dualstack kind cluster in quick-start and startup script
  docs/book/src/user/quick-start.md
  hack/kind-install-for-capd.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#8675 🌱 test/framework: add functions to collect infrastructure logs in tests
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
  test/framework/cluster_proxy.go
  test/framework/docker_logcollector.go
  test/infrastructure/container/docker.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8680 :seedling: Update kpromo to v3.6.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#8682 [release-1.4] :seedling: Update kpromo to v3.6.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#8683 [release-1.3] :seedling: Update kpromo to v3.6.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#8422 :bug: update TopologyReconciled condition on cluster deletion
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/conditions.go
  internal/controllers/topology/cluster/conditions_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/clusterclass

#8472 :sparkles: Add support for add-on providers in clusterctl
  cmd/clusterctl/api/v1alpha3/labels.go
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config/providers_client_test.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/client/delete.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/client/upgrade.go
  cmd/clusterctl/cmd/config_repositories_test.go
  cmd/clusterctl/cmd/delete.go
  cmd/clusterctl/cmd/generate_provider.go
  cmd/clusterctl/cmd/init.go
  cmd/clusterctl/cmd/init_list_images.go
  cmd/clusterctl/cmd/upgrade_apply.go
  cmd/clusterctl/hack/create-local-repository.py
  docs/book/src/clusterctl/provider-contract.md
  hack/tools/tilt-prepare/main.go
  test/e2e/clusterctl_upgrade.go
  test/e2e/e2e_suite_test.go
  test/e2e/self_hosted.go
  test/framework/clusterctl/client.go
  test/framework/clusterctl/clusterctl_helpers.go
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/repository.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterctl

#8688 :seedling: Fix typos in phrase "to exist"
  test/e2e/clusterctl_upgrade.go
  test/e2e/kcp_remediations.go
  test/framework/machinehealthcheck_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#8684 :seedling: Pin cgroup driver used in v0.3 and v0.4 templates
  test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.0/bases/md.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#8692 [release-1.3] :seedling: Pin cgroup driver used in v0.3 and v0.4 templates
  test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/mp.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#8686 📖 Retire Managed Kubernetes Feature Group
  docs/community/20221115-managed-kubernetes.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8681 :seedling: Bump kind to v0.19.0
  Tiltfile
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/go.mod
  test/go.sum
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
  test/infrastructure/docker/internal/docker/machine.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#8699 :book: Bump kind version to v1.19.0 in docs
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#8701 :seedling: Fix typo: exits -> exists
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/clusterclass.go
  internal/controllers/topology/cluster/patches/variables/merge.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#8702 :seedling: Update cert-manager to v1.12.0
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  docs/book/src/user/troubleshooting.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#8703 :bug: Remove non-functioning ginkgo.no-color flag
  test/e2e/data/kubetest/conformance-fast.yaml
  test/e2e/data/kubetest/conformance.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#8712 :seedling: Fix outdated link to Kubernetes docs
  docs/book/src/developer/providers/implementers-guide/generate_crds.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#8549 :warning: Stop serving v1alpha3 API types
  Makefile
  api/v1alpha3/cluster_types.go
  api/v1alpha3/machine_types.go
  api/v1alpha3/machinedeployment_types.go
  api/v1alpha3/machinehealthcheck_types.go
  api/v1alpha3/machineset_types.go
  api/v1alpha3/webhook_test.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_types.go
  bootstrap/kubeadm/api/v1alpha3/kubeadmconfigtemplate_types.go
  bootstrap/kubeadm/api/v1alpha3/webhook_test.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/client/cluster/crd_migration.go
  cmd/clusterctl/client/cluster/crd_migration_test.go
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha3/webhook_test.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  docs/book/src/clusterctl/commands/upgrade.md
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
  docs/book/src/reference/jobs.md
  docs/release/release-tasks.md
  exp/addons/api/v1alpha3/clusterresourceset_types.go
  exp/addons/api/v1alpha3/clusterresourcesetbinding_types.go
  exp/addons/api/v1alpha3/webhook_test.go
  exp/api/v1alpha3/machinepool_types.go
  exp/api/v1alpha3/webhook_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/README.md
  test/e2e/data/infrastructure-docker/v0.3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.3/bases/crs.yaml
  test/e2e/data/infrastructure-docker/v0.3/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.3/cluster-template/kustomization.yaml
  test/e2e/data/shared/v0.3/metadata.yaml
  test/framework/clusterctl/client.go
  test/infrastructure/docker/api/v1alpha3/dockercluster_types.go
  test/infrastructure/docker/api/v1alpha3/dockermachine_types.go
  test/infrastructure/docker/api/v1alpha3/dockermachinetemplate_types.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/exp/api/v1alpha3/dockermachinepool_types.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/clusterctl

#8726 :seedling: Pin delve to version supporting go 1.19
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#8725 :seedling: Pin delve to match go minor version
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#8728 :seedling: Improve logging for MachinePool upgrade test
  test/framework/machinepool_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#8729 :book: Removed duplicate text block
  docs/book/src/tasks/experimental-features/cluster-class/change-clusterclass.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#8734 ✨ ci: collect debug information about leftover processes
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8731 :seedling: Align kind registry script with upstream
  hack/kind-install-for-capd.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, area/devtools

#8711 :bug: Allow machine rollout if cert reconcile fails
  controlplane/kubeadm/internal/controllers/controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/provider/control-plane-kubeadm

#8685 🐛 CAPD: change the haproxy entrypoint to prevent getting stopped immediately after start
  test/infrastructure/docker/internal/docker/kind_manager.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8739 :bug: Adjust machinepool helper e2e timeout
  test/framework/machinepool_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8667 🐛 Update MachinePool bootstrap dataSecretName when bootstrap config changes
  exp/internal/controllers/machinepool_controller_phases.go
  exp/internal/controllers/machinepool_controller_phases_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/machinepool

#8740 :book: Add note about v1alpha3 removal to book
  CONTRIBUTING.md
  REVIEWING.md
  docs/book/src/introduction.md
  docs/proposals/20210210-insulate-users-from-kubeadm-API-changes.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#8748 :seedling: Update cert-manager to v1.12.1
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency, area/clusterctl

#8753 📖 Changed the link and removed TODO
  docs/book/src/tasks/experimental-features/ignition.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8758 :bug: Increased assertClusterObjects timeout
  test/e2e/clusterclass_rollout.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8755 :bug: [release-1.3] Adjust machinepool helper e2e timeout
  test/framework/machinepool_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8756 :bug: [release-1.4] Adjust machinepool helper e2e timeout
  test/framework/machinepool_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8761 :bug: Ignore cert annotation in rollout test
  test/e2e/clusterclass_rollout.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8762 📖 Wrapped the values with quotes to make them string
  docs/book/src/developer/tilt.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8749 :seedling: Bump golang version (1.20.3 -> 1.20.4)
  Makefile
  Tiltfile
  hack/ensure-go.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8765 🌱 Move ClusterClass quickstart test from e2e-informing to e2e-main
  test/e2e/quick_start_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8770 :seedling: Bump gcb-docker-gcloud from v20230424-910a2a439d to v20230522-312425ae46
  cloudbuild-nightly.yaml
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8763 📖 Document new and missing jobs
  docs/book/src/reference/jobs.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8769 :seedling: Improve gomega fail handling in clusterClass rollout
  test/e2e/clusterclass_rollout.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8771 :seedling: [release-1.4] Improve gomega fail handling in clusterClass rollout
  test/e2e/clusterclass_rollout.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8595 ✨ MS preflight checks to improve cluster stability
  api/v1beta1/common_types.go
  api/v1beta1/machinedeployment_webhook.go
  api/v1beta1/machineset_webhook.go
  api/v1beta1/machineset_webhook_test.go
  config/manager/manager.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/developer/testing.md
  docs/book/src/developer/tilt.md
  docs/book/src/reference/labels_and_annotations.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  docs/book/src/tasks/experimental-features/machineset-preflight-checks.md
  feature/feature.go
  internal/contract/controlplane.go
  internal/contract/infrastructure_cluster.go
  internal/contract/infrastructure_machine.go
  internal/contract/types.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_preflight.go
  internal/controllers/machineset/machineset_preflight_test.go
  test/e2e/config/docker.yaml
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/machineset
