Repository kubernetes-sigs/cluster-api, pull requests merged in 2023-03, with the labels that each got.

#8206 🌱 fix incorrect assertion
  internal/controllers/machineset/machineset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8180 🌱 Add template metadata to CABPK and KCP types
  bootstrap/kubeadm/api/v1alpha3/conversion.go
  bootstrap/kubeadm/api/v1alpha3/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1alpha4/conversion.go
  bootstrap/kubeadm/api/v1alpha4/zz_generated.conversion.go
  bootstrap/kubeadm/api/v1beta1/kubeadmconfigtemplate_types.go
  bootstrap/kubeadm/api/v1beta1/zz_generated.deepcopy.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  controlplane/kubeadm/api/v1alpha4/conversion.go
  controlplane/kubeadm/api/v1alpha4/zz_generated.conversion.go
  controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_types.go
  controlplane/kubeadm/api/v1beta1/zz_generated.deepcopy.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  docs/book/src/developer/providers/bootstrap.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8145 :seedling: :book: move.md: Warning: Status get lost
  docs/book/src/clusterctl/commands/move.md
  docs/book/src/clusterctl/provider-contract.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#8189 📖 book: update Kubernetes bump documentation according to the new policy
  .github/ISSUE_TEMPLATE/kubernetes_bump.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8026 :seedling: Add DiscoverVariables hook implementation for test extension
  test/e2e/data/infrastructure-docker/main/cluster-template-upgrades-runtimesdk/cluster-runtimesdk.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-runtimesdk.yaml
  test/extension/handlers/topologymutation/handler.go
  test/extension/handlers/topologymutation/handler_test.go
  test/extension/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8088 :sparkles: Make it possible to run envtest-based integration tests from vscode
  Makefile
  dev/vscode-example-configuration/settings.json
  dev/vscode-example-configuration/tasks.json
  dev/vscode-example-configuration/test.env
  docs/book/src/developer/repository-layout.md
  docs/book/src/developer/testing.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8057 ⚠️ in-place propagation support for KCP
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/controllers/suite_test.go
  controlplane/kubeadm/internal/controllers/upgrade_test.go
  controlplane/kubeadm/internal/filters.go
  controlplane/kubeadm/internal/filters_test.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machineset/machineset_controller.go
  internal/util/ssa/managedfields.go
  internal/util/ssa/managedfields_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#8213 🌱 Bump to controller-runtime v0.14.5
  go.mod
  go.sum
  hack/observability/prometheus/values.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved

#8220 :book: Fix broken link to kubectl install
  docs/book/src/developer/providers/implementers-guide/overview.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8223 :bug: Replace fixed build uid with command
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/clusterctl

#8225 [release-1.3] :bug: Replace fixed build uid with command
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8132 🐛 bugfix function aggregateFromMachinesToKCP
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#8228 [release-1.3] 🐛 bugfix function aggregateFromMachinesToKCP
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8227 [release-1.2] 🐛 bugfix function aggregateFromMachinesToKCP
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8207 ✨ SSA: Implement request caching
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/helpers.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machine/machine_controller_test.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinedeployment/machinedeployment_sync.go
  internal/controllers/machinedeployment/mdutil/util.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_controller_test.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
  internal/util/hash/hash.go
  internal/util/ssa/cache.go
  internal/util/ssa/patch.go
  internal/util/ssa/patch_test.go
  internal/util/ssa/suite_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8230 🌱 Bump apidiff to v0.6.0
  Makefile
  docs/book/src/developer/providers/v1.3-to-v1.4.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8232 📖 Clean up some typos and links in CAPI book
  docs/book/src/clusterctl/developers.md
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/developer/architecture/controllers/cluster-topology.md
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/architecture/controllers/machine-pool.md
  docs/book/src/developer/architecture/controllers/machine.md
  docs/book/src/developer/e2e.md
  docs/book/src/developer/logging.md
  docs/book/src/developer/providers/contracts.md
  docs/book/src/developer/providers/v0.3-to-v0.4.md
  docs/book/src/developer/providers/v1.0-to-v1.1.md
  docs/book/src/developer/providers/v1.2-to-v1.3.md
  docs/book/src/developer/repository-layout.md
  docs/book/src/developer/testing.md
  docs/book/src/developer/tilt.md
  docs/book/src/reference/glossary.md
  docs/book/src/security/pod-security-standards.md
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.md
  docs/book/src/tasks/multiple-providers.md
  docs/book/src/user/quick-start.md
  docs/book/src/user/troubleshooting.md
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#8239 📖 Add cloud-provider-azure helm install to quickstart
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#7993 ⚠️ apply `node.cluster.x-k8s.io/uninitialized` during machine creation
  api/v1beta1/common_types.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  docs/book/src/developer/providers/bootstrap.md
  exp/internal/controllers/machinepool_controller_noderef.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machine/machine_controller_noderef_test.go
  internal/controllers/machine/suite_test.go
  internal/util/taints/taints.go
  internal/util/taints/taints_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8244 :seedling: Rename md parameters for consistency
  cmd/clusterctl/client/alpha/machinedeployment.go
  cmd/clusterctl/client/alpha/rollout_rollbacker.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinedeployment/machinedeployment_rolling.go
  internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
  internal/controllers/machinedeployment/machinedeployment_sync.go
  internal/controllers/machinedeployment/mdutil/util.go
  internal/controllers/machinedeployment/mdutil/util_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, kind/cleanup, area/code-organization

#8234 :book: Fix v1alpha4 references in clusterctl comments
  cmd/clusterctl/api/v1alpha3/provider_type.go
  cmd/clusterctl/client/client.go
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/client/init.go
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#8203 :seedling: Add weekly test-release action
  .github/workflows/lint-docs-weekly.yml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  .github/workflows/test-release-weekly.yml
Labels: cncf-cla: yes, lgtm, size/M, approved

#8216 ✨ MachineDeployment rolloutAfter support
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/machinedeployment_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  cmd/clusterctl/client/alpha/kubeadmcontrolplane.go
  cmd/clusterctl/client/alpha/machinedeployment.go
  cmd/clusterctl/client/alpha/rollout_restarter.go
  cmd/clusterctl/client/alpha/rollout_restarter_test.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  docs/book/src/tasks/upgrading-clusters.md
  internal/controllers/machinedeployment/machinedeployment_sync.go
  internal/controllers/machinedeployment/mdutil/util.go
  internal/controllers/machinedeployment/mdutil/util_test.go
  util/collections/machine_filters.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8243 ✨ SSA: improve request caching
  controlplane/kubeadm/internal/controllers/helpers.go
  internal/util/ssa/patch.go
  internal/util/ssa/patch_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8241 🌱 test/framework: don't fix kubeconfig for remote CAPD clusters
  test/framework/cluster_proxy.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8246 :seedling: Make load balancer first-party package in CAPD
  docs/book/src/developer/providers/v1.3-to-v1.4.md
  test/infrastructure/docker/internal/docker/loadbalancer.go
  test/infrastructure/docker/internal/loadbalancer/config.go
  test/infrastructure/docker/internal/loadbalancer/const.go
  test/infrastructure/docker/internal/loadbalancer/doc.go
  test/infrastructure/docker/internal/third_party/forked/README.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8226 🌱 all: setup controller in a consistent way
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  controlplane/kubeadm/internal/controllers/controller.go
  exp/internal/controllers/machinepool_controller.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machineset/machineset_controller.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#7786 ✨ Emit Kubernetes Events when Cluster Phase, ControlPlaneReady, or InfrastructureReady change
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/cluster/cluster_controller_phases.go
  internal/controllers/cluster/cluster_controller_phases_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8259 🌱 fix `TestKubeadmControlPlaneReconciler_initializeControlPlane` flake
  controlplane/kubeadm/internal/controllers/scale_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#7819 🌱 Use GitHub forms for issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/failing_test.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/flaking-test.md
  .github/ISSUE_TEMPLATE/flaking_test.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved

#8187 🌱 Add release notes pr statistics
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8091 🌱 Use Lazy Restmapper
  bootstrap/kubeadm/config/manager/manager.yaml
  bootstrap/kubeadm/main.go
  config/manager/manager.yaml
  controllers/remote/cluster_cache_tracker.go
  controlplane/kubeadm/config/manager/manager.yaml
  controlplane/kubeadm/main.go
  docs/book/src/developer/testing.md
  docs/book/src/developer/tilt.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  feature/feature.go
  internal/test/envtest/environment.go
  main.go
  test/e2e/config/docker.yaml
  test/infrastructure/docker/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8261 🌱 ClusterClass: don't propagate MD upgrade annotations
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#7680 :sparkles: Introduce ClusterName field to ClusterResourceSetBinding
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/webhook/manifests.yaml
  exp/addons/api/v1alpha3/conversion.go
  exp/addons/api/v1alpha3/zz_generated.conversion.go
  exp/addons/api/v1alpha4/conversion.go
  exp/addons/api/v1alpha4/zz_generated.conversion.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_webhook.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_webhook_test.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/addons/internal/controllers/clusterresourceset_controller_test.go
  exp/addons/internal/controllers/clusterresourceset_helpers.go
  exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
  internal/test/envtest/environment.go
  main.go
  test/framework/ownerreference_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#8171 🌱 test/e2e: Add ClusterClass rollout test, extend MD rollout test
  internal/contract/bootstrap_config_template.go
  internal/contract/controlplane_template.go
  internal/contract/infrastructure_cluster_template.go
  internal/contract/infrastructure_machine.go
  internal/contract/infrastructure_machine_template.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  test/e2e/clusterclass_changes.go
  test/e2e/clusterclass_changes_test.go
  test/e2e/clusterclass_rollout.go
  test/e2e/clusterclass_rollout_test.go
  test/e2e/data/infrastructure-docker/main/bases/cluster-with-topology.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
  test/e2e/md_rollout.go
  test/framework/machine_helpers.go
  test/framework/machinedeployment_helpers.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#8278 [release-1.2] 🌱 Bump golang.org/x/net to v0.7.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#8275 🌱 ci: set fail-fast false for all GH actions using matrix
  .github/workflows/golangci-lint.yml
  .github/workflows/scan.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8048 🐛: Make sure the Kubernetes API Server service already created on remote cluster before applying ClusterResourceSets
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/addons/internal/controllers/clusterresourceset_controller_test.go
  exp/addons/internal/controllers/clusterresourceset_helpers.go
  exp/addons/internal/controllers/clusterresourceset_helpers_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#8266 :seedling: replace reflect deepequal in bootstrap kubeadm
  bootstrap/kubeadm/api/v1alpha4/kubeadm_types_test.go
  bootstrap/kubeadm/api/v1beta1/kubeadm_types_test.go
  bootstrap/kubeadm/types/upstreamv1beta1/bootstraptokenstring_test.go
  bootstrap/kubeadm/types/upstreamv1beta2/bootstraptokenstring_test.go
  bootstrap/kubeadm/types/upstreamv1beta3/bootstraptokenstring_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8264 🌱 Merge ownerReference tests with quick start
  test/e2e/quick_start_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#8288 📖 docs: link Kubernetes contributor guide in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8269 :seedling: Add unit test for health check during creation of a new cluster accessor
  controllers/remote/cluster_cache_healthcheck_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#8252 📖 book: extend next steps of quick start
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8297 🐛 bug fix to set node interruptible label
  internal/controllers/machine/machine_controller_node_labels.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8301 🌱 Bump kpromo to v3.5.1
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8305 [release-1.2] 🌱 Bump kpromo to v3.5.1
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8313 [release-1.2] 🌱 CAPD: set privileged PSA policy
  test/infrastructure/docker/config/default/namespace.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8311 🐛 test/e2e: use topology cluster-template for clusterctl upgrade mgmt cluster
  test/e2e/clusterctl_upgrade_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8312 🌱 Bump golangci-lint to v1.51.2
  .github/workflows/golangci-lint.yml
  test/framework/kubetest/setup.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#8315 [release-1.3] 🐛 test/e2e: use topology cluster-template for clusterctl upgrade mgmt cluster
  test/e2e/clusterctl_upgrade_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8307 📖 docs: add link to release 1.4 in capi book
  docs/book/src/introduction.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8240 🐛 Ensure all GitHub releases are fetched when searching provider versions
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#8318 🐛 Add soft ownership from clusters to ClusterResourceSetBinding
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/objectgraph_test.go
  cmd/clusterctl/internal/test/fake_objects.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8330 [release-1.3] 🐛 Ensure all GitHub releases are fetched when searching provider versions
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test

#8256 :bug: Ensure ownerReference apiVersions are always up to date
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  cmd/clusterctl/client/cluster/ownergraph.go
  cmd/clusterctl/internal/test/fake_objects.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/helpers.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/addons/internal/controllers/clusterresourceset_helpers.go
  exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
  exp/internal/controllers/machinepool_controller.go
  exp/util/util.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  test/e2e/clusterctl_upgrade.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/data/infrastructure-docker/v0.4/bases/mhc.yaml
  test/e2e/data/infrastructure-docker/v0.4/cluster-template/kustomization.yaml
  test/e2e/quick_start_test.go
  test/framework/ownerreference_helpers.go
  util/secret/certificates.go
  util/util.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8334 :bug: Fix flaky wait in CRS test
  exp/addons/internal/controllers/clusterresourceset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#8342 🌱 clusterctl: Add labels to OWNERS file
  cmd/clusterctl/OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8332 :bug: Validate variables in defaulting webhook
  internal/controllers/topology/cluster/cluster_controller.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8331 🌱 Bump golangci-lint to 1.52.1 and fix findings
  .github/workflows/golangci-lint.yml
  controlplane/kubeadm/internal/controllers/scale_test.go
  internal/controllers/machine/machine_controller_phases_test.go
  internal/controllers/topology/cluster/conditions.go
  test/framework/machinedeployment_helpers.go
  test/framework/namespace_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8339 🐛 enable updates from CloudInit (mostly ubuntu) based KCPs to Ignition (flatcar) based KCPs
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#8352 :bug: Fix length check in MD helper
  test/framework/machinedeployment_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8363 📖 Add note for registry.k8s.io migration
  docs/book/src/introduction.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8327 📖 Add documentation about KCP remediation
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  docs/book/src/tasks/automated-machine-management/healthchecking.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8360 [release-1.2] 🐛 Ensure all GitHub releases are fetched when searching provider versions
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8358 🐛 set uninitialized taint only on worker nodes
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  docs/book/src/developer/providers/bootstrap.md
  docs/proposals/20220927-label-sync-between-machine-and-nodes.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#8374 ✨Implements Getter interface for IPAddressClaim object
  exp/ipam/api/v1alpha1/ipaddressclaim_types.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8375 📖 book: add missing apiversion deprecation to migration docs
  docs/book/src/developer/providers/v1.3-to-v1.4.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8385 [release-1.3] 📖 Release 1.3 add registry.io notice
  docs/book/src/introduction.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8386 [release-1.2] 📖 Add note for registry.k8s.io migration
  docs/book/src/introduction.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8397 :book: Fix http link in book
  docs/book/src/developer/providers/v1.3-to-v1.4.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8309 📖 docs: update comms team release tasks
  docs/release/release-tasks.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8398 :seedling: Update version matrix for github workflows
  .github/workflows/lint-docs-weekly.yml
  .github/workflows/scan.yml
  .github/workflows/test-release-weekly.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#8356 :bug: Enable updates from CloudInit (mostly ubuntu) based KCPs to Ignition (flatcar) based KCPs
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#8308 📖 docs: update CAPI support and guarantees
  CONTRIBUTING.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8355 📖 book: Update CAPI Quick Start to use clusterctl 1.4
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8405 :seedling: Update controller runtime to 0.14.6
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#8365 :seedling: Allow overriding gingko args in e2e tests
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#8383 :book: Add 1.4 -> 1.5 migrations doc. Move migrations docs to single folder.
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/migrations/v0.3-to-v0.4.md
  docs/book/src/developer/providers/migrations/v0.4-to-v1.0.md
  docs/book/src/developer/providers/migrations/v1.0-to-v1.1.md
  docs/book/src/developer/providers/migrations/v1.1-to-v1.2.md
  docs/book/src/developer/providers/migrations/v1.2-to-v1.3.md
  docs/book/src/developer/providers/migrations/v1.3-to-v1.4.md
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
  docs/book/src/developer/providers/version-migration.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8377 ✨ Move mergeMap to util
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  util/util.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#8414 :bug: Use local kustomize version in create-local-repository.py
  cmd/clusterctl/hack/create-local-repository.py
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/clusterctl

#8439 :book: Fix broken links in migrations guides
  docs/book/src/developer/providers/migrations/v0.4-to-v1.0.md
  docs/book/src/developer/providers/migrations/v1.0-to-v1.1.md
  docs/book/src/developer/providers/migrations/v1.2-to-v1.3.md
  docs/book/src/developer/providers/migrations/v1.3-to-v1.4.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8416 📖 docs: update the release-1.5.md with release team info
  docs/release/releases/release-1.5.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8419 :seedling: :book: Added link to the file format
  test/e2e/config/docker.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8438 :seedling: Add runtime extension components to release
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#8293 🌱 Allow backport for experimental features
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8427 🐛 fix node label propagation
  api/v1beta1/common_types.go
  docs/book/src/reference/labels_and_annotations.md
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machine/machine_controller_noderef_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved
