Repository kubernetes-sigs/cluster-api, pull requests merged in 2023-07, with the labels that each got.

#8950 🌱 hack/observability: add metrics-server chart
  Tiltfile
  docs/book/src/developer/tilt.md
  hack/observability/metrics-server/kustomization.yaml
  hack/observability/metrics-server/values.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved

#8949 🐛 all: only set finalizers if deletionTimestamp is not set
  controlplane/kubeadm/internal/controllers/controller.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/internal/controllers/machinepool_controller.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8955 :book: Add comment about MachinePool MinReadySeconds behaviour
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  exp/api/v1beta1/machinepool_types.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/machinepool

#8961 🌱 hack/observability: use 20 Gi of storage for Prometheus
  hack/observability/prometheus/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8960 📖 Fix description of example values for MHC unhealthy ranges
  docs/book/src/tasks/automated-machine-management/healthchecking.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/machinehealthcheck

#8917 :sparkles: Enable configuring the kubernetes rest client timeout for draining nodes
  controllers/alias.go
  internal/controllers/machine/machine_controller.go
  main.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test

#8958 📖 Add tuning guide
  docs/book/src/SUMMARY.md
  docs/book/src/developer/architecture/controllers/tuning.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#8962 🌱 in-memory provider: add apiserver & etcd metrics
  test/go.mod
  test/go.sum
  test/infrastructure/inmemory/internal/server/api/handler.go
  test/infrastructure/inmemory/internal/server/api/metrics.go
  test/infrastructure/inmemory/internal/server/etcd/handler.go
  test/infrastructure/inmemory/internal/server/etcd/metrics.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8970 [release-1.4] 🌱 Bump google.golang.org/grpc to v1.55.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#8971 [release-1.3] 🌱 Bump google.golang.org/grpc to v1.55.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8953 🌱 test/e2e: improve logging for a detected rollout
  test/e2e/clusterctl_upgrade.go
  test/e2e/self_hosted.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8972 🐛 tilt: fix build_engine setting when using podman
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8974 [release-1.4] :bug: Bump kindest/node image used in e2e tests
  test/framework/bootstrap/kind_provider.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#8975 :seedling: Add SHA to default KIND image used in e2e tests
  test/framework/bootstrap/kind_provider.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#8963 🌱 test/e2e: add field to scale test to deploy Clusters in separate namespace
  test/e2e/scale.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8959 🌱 KCP: Log the reason of a Machine rollout
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/filters.go
  controlplane/kubeadm/internal/filters_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#8746 :sparkles: Add webhook warning for missing ClusterClass
  internal/topology/check/compatibility.go
  internal/topology/check/compatibility_test.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterclass

#8979 ✨ hack/observability bump kube-state-metrics chart to get version v2.9.2
  hack/observability/kube-state-metrics/chart/kustomization.yaml
  hack/observability/kube-state-metrics/chart/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#8930 🌱 Protect well know registry from accidental push during tilt up
  Tiltfile
  docs/book/src/developer/tilt.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#8978 🌱 hack/observability: add apiserver request dashboards
  hack/observability/grafana/dashboards/cluster-api-mgmt-apiserver-requests.json
  hack/observability/grafana/dashboards/cluster-api-wl-apiserver-requests.json
  hack/observability/grafana/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#8836 ✨ Add MachinePool Machine support in clusterctl discovery
  api/v1beta1/machine_types.go
  cmd/clusterctl/client/tree/discovery.go
  cmd/clusterctl/client/tree/discovery_test.go
  cmd/clusterctl/internal/test/fake_objects.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterctl

#8957 ✨ Introduce possibility to create clusterctl plugins
  cmd/clusterctl/cmd/root.go
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/plugins.md
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterctl

#8980 :book: Add Metal3 to list for beta release notification
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, tide/merge-method-squash, area/documentation

#8990 :seedling: Remove auto-labelling for clusterctl
  cmd/clusterctl/OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release, area/clusterctl

#8995 🌱 bump go-github dependency to version v53
  cmd/clusterctl/client/cluster/template.go
  cmd/clusterctl/client/cluster/template_test.go
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
  cmd/clusterctl/cmd/version_checker.go
  cmd/clusterctl/internal/test/fake_github.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#8991 [release-1.4] 🐛 controlplane: prevent nil pointer exception in kcp controller when in…
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#8992 🌱 controlplane: add a test case for syncMachines where the InfraMachine does not exist.
  controlplane/kubeadm/internal/controllers/controller_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8820 :sparkles: Update API with ClusterClass MachinePool support
  api/v1alpha4/conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/cluster_types.go
  api/v1beta1/clusterclass_types.go
  api/v1beta1/common_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved

#8996 :warning: Stop serving v1alpha4 API Versions
  Makefile
  api/v1alpha4/cluster_types.go
  api/v1alpha4/clusterclass_types.go
  api/v1alpha4/machine_types.go
  api/v1alpha4/machinedeployment_types.go
  api/v1alpha4/machinehealthcheck_types.go
  api/v1alpha4/machineset_types.go
  bootstrap/kubeadm/api/v1alpha4/kubeadmconfig_types.go
  bootstrap/kubeadm/api/v1alpha4/kubeadmconfigtemplate_types.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controlplane/kubeadm/api/v1alpha4/kubeadm_control_plane_types.go
  controlplane/kubeadm/api/v1alpha4/kubeadmcontrolplanetemplate_types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/commands/upgrade.md
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  docs/release/release-tasks.md
  exp/addons/api/v1alpha4/clusterresourceset_types.go
  exp/addons/api/v1alpha4/clusterresourcesetbinding_types.go
  exp/api/v1alpha4/machinepool_types.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/README.md
  test/e2e/data/infrastructure-docker/v0.4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/crs.yaml
  test/e2e/data/infrastructure-docker/v0.4/bases/md.yaml
  test/e2e/data/infrastructure-docker/v0.4/cluster-template/kustomization.yaml
  test/e2e/data/shared/v0.4/metadata.yaml
  test/infrastructure/docker/api/v1alpha4/dockercluster_types.go
  test/infrastructure/docker/api/v1alpha4/dockerclustertemplate_types.go
  test/infrastructure/docker/api/v1alpha4/dockermachine_types.go
  test/infrastructure/docker/api/v1alpha4/dockermachinetemplate_types.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/exp/api/v1alpha4/dockermachinepool_types.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#9001 :seedling: Extend docs for patch.NewHelper
  util/patch/patch.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#9002 🌱 Move `internal.labels` to `format` package for use by providers
  api/v1beta1/machineset_webhook.go
  controlplane/kubeadm/internal/cluster_labels.go
  exp/internal/controllers/machinepool_controller_phases.go
  exp/internal/controllers/machinepool_controller_phases_test.go
  internal/controllers/machineset/machineset_controller.go
  util/labels/format/helpers.go
  util/labels/format/helpers_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#9013 :book: Fix role names in release docs
  docs/release/release-team.md
  docs/release/releases/release-1.6.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#9014 :book: Add link to "clusterctl move" docs.
  docs/book/src/clusterctl/commands/move.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#8678 :book: Add a section for configuring Kubelet in Cluster API
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/bootstrap/kubeadm-bootstrap/index.md
  docs/book/src/tasks/bootstrap/kubeadm-bootstrap/kubelet-config.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/L, approved, ok-to-test

#9018 🐛 hack/release-notes: ensure relase notes tool can be used for external projects again
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#9028 🌱 ClusterCacheTracker: ensure Get/List calls are not getting stuck when apiserver is unreachable
  controllers/remote/cluster_cache_tracker.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#9029 🌱 Add more links to release-tasks doc
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9025 🌱 ClusterCacheTracker: fix accessor deletion on health check failure
  controllers/remote/cluster_cache_tracker.go
Labels: size/S, cncf-cla: yes, lgtm, approved

#8785 ✨ Allow adding custom HA proxy config for CAPD load balancer
  test/infrastructure/docker/api/v1alpha3/conversion.go
  test/infrastructure/docker/api/v1alpha4/conversion.go
  test/infrastructure/docker/api/v1alpha4/zz_generated.conversion.go
  test/infrastructure/docker/api/v1beta1/dockercluster_types.go
  test/infrastructure/docker/api/v1beta1/zz_generated.deepcopy.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/docker/internal/docker/loadbalancer.go
  test/infrastructure/docker/internal/loadbalancer/config.go
  test/infrastructure/docker/internal/loadbalancer/config_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#9027 [release-1.4] :seedling: ClusterCacheTracker: ensure Get/List calls are not getting stuck when apiserver is unreachable
  controllers/remote/cluster_cache_tracker.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clustercachetracker

#9033 [release-1.3] 🌱 ClusterCacheTracker: ensure Get/List calls are not getting stuck when apiserver is unreachable
  controllers/remote/cluster_cache_tracker.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clustercachetracker

#9032 :bug: requeue KCP object if ControlPlaneComponentsHealthyCondition is not yet true
  controlplane/kubeadm/internal/controllers/controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/provider/control-plane-kubeadm

#9038 🐛 Bump to docker v24.0.5-0.20230714235725-36e9e796c6fc
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tilt-prepare/main.go
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#9041 :seedling: Add dependabot for test and hack/tools module
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/ci

#9024 🌱 fixed grammatically incorrect plurals in release tools
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#9042 [release-1.5] :bug: Bump to docker v24.0.5-0.20230714235725-36e9e796c6fc
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tilt-prepare/main.go
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#9043 [release-1.4] :bug: Bump to docker v24.0.5-0.20230714235725-36e9e796c6fc
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tilt-prepare/main.go
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#9046 [release-1.3] :bug: Bump to docker v24.0.5-0.20230714235725-36e9e796c6fc
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tilt-prepare/main.go
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#8819 📖 add a note to check with maintainers for blocked comms emails
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9057 🌱 Bump to Go 1.20.6
  Makefile
  Tiltfile
  hack/ensure-go.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9055 🐛 Alphabetically sorting release tool output
  hack/tools/release/notes.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#9059 :seedling: Add exclude for Kustomize API to dependabot config
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9064 :seedling: Bump docker to v24.0.5
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9012 🌱 Add CABPOCNE and CACPOCNE Providers
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/reference/glossary.md
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, ok-to-test

#9074 [release-1.4] :seedling: Change tilt debug base image to golang
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9075 [release-1.3] :seedling: Change tilt debug base image to golang
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#9081 :book: update clusterctl version to v1.5.x in quick start
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved

#9080 📖 Control Plane resources required label from v1.5.0
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#9087 📖 Add v1.6 Release Team members' GitHub/Slack handles
  docs/release/releases/release-1.6.md
Labels: cncf-cla: yes, lgtm, size/M, approved
