Repository kubernetes-sigs/cluster-api, pull requests merged in 2024-08, with the labels that each got.

#10969 🌱 Remove duplicate ca injection via kustomize
  bootstrap/kubeadm/config/crd/kustomization.yaml
  bootstrap/kubeadm/config/crd/patches/cainjection_in_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/patches/cainjection_in_kubeadmconfigtemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clusterclasses.yaml
  config/crd/patches/cainjection_in_clusterresourcesetbindings.yaml
  config/crd/patches/cainjection_in_clusterresourcesets.yaml
  config/crd/patches/cainjection_in_clusters.yaml
  config/crd/patches/cainjection_in_machinedeployments.yaml
  config/crd/patches/cainjection_in_machinehealthchecks.yaml
  config/crd/patches/cainjection_in_machinepools.yaml
  config/crd/patches/cainjection_in_machines.yaml
  config/crd/patches/cainjection_in_machinesets.yaml
  controlplane/kubeadm/config/crd/kustomization.yaml
  controlplane/kubeadm/config/crd/patches/cainjection_in_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/patches/cainjection_in_kubeadmcontrolplanetemplates.yaml
  test/infrastructure/docker/config/crd/kustomization.yaml
  test/infrastructure/docker/config/crd/patches/cainjection_in_dockerclusters.yaml
  test/infrastructure/docker/config/crd/patches/cainjection_in_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachinepooltemplates.yaml
  test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachines.yaml
  test/infrastructure/docker/config/crd/patches/cainjection_in_dockermachinetemplates.yaml
  test/infrastructure/inmemory/config/crd/kustomization.yaml
  test/infrastructure/inmemory/config/crd/patches/cainjection_in_inmemoryclusters.yaml
  test/infrastructure/inmemory/config/crd/patches/cainjection_in_inmemoryclustertemplates.yaml
  test/infrastructure/inmemory/config/crd/patches/cainjection_in_inmemorymachines.yaml
  test/infrastructure/inmemory/config/crd/patches/cainjection_in_inmemorymachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#10972 🐛 Drop caBundle from CRDs to support Kubernetes 1.31
  bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigtemplates.yaml
  config/crd/patches/webhook_in_clusterclasses.yaml
  config/crd/patches/webhook_in_clusterresourcesetbindings.yaml
  config/crd/patches/webhook_in_clusterresourcesets.yaml
  config/crd/patches/webhook_in_clusters.yaml
  config/crd/patches/webhook_in_machinedeployments.yaml
  config/crd/patches/webhook_in_machinehealthchecks.yaml
  config/crd/patches/webhook_in_machinepools.yaml
  config/crd/patches/webhook_in_machines.yaml
  config/crd/patches/webhook_in_machinesets.yaml
  controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanetemplates.yaml
  docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
  test/infrastructure/docker/config/crd/patches/webhook_in_dockerclusters.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepooltemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachines.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinetemplates.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclusters.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclustertemplates.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachines.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, kind/cleanup, area/api

#10979 [release-1.6] 🐛 Drop caBundle from CRDs
  bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigtemplates.yaml
  config/crd/patches/webhook_in_clusterclasses.yaml
  config/crd/patches/webhook_in_clusterresourcesetbindings.yaml
  config/crd/patches/webhook_in_clusterresourcesets.yaml
  config/crd/patches/webhook_in_clusters.yaml
  config/crd/patches/webhook_in_machinedeployments.yaml
  config/crd/patches/webhook_in_machinehealthchecks.yaml
  config/crd/patches/webhook_in_machinepools.yaml
  config/crd/patches/webhook_in_machines.yaml
  config/crd/patches/webhook_in_machinesets.yaml
  controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanetemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockerclusters.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepooltemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachines.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinetemplates.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclusters.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclustertemplates.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachines.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/api

#10978 [release-1.7] 🐛 Drop caBundle from CRDs
  bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/patches/webhook_in_kubeadmconfigtemplates.yaml
  config/crd/patches/webhook_in_clusterclasses.yaml
  config/crd/patches/webhook_in_clusterresourcesetbindings.yaml
  config/crd/patches/webhook_in_clusterresourcesets.yaml
  config/crd/patches/webhook_in_clusters.yaml
  config/crd/patches/webhook_in_machinedeployments.yaml
  config/crd/patches/webhook_in_machinehealthchecks.yaml
  config/crd/patches/webhook_in_machinepools.yaml
  config/crd/patches/webhook_in_machines.yaml
  config/crd/patches/webhook_in_machinesets.yaml
  controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/patches/webhook_in_kubeadmcontrolplanetemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockerclusters.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinepooltemplates.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachines.yaml
  test/infrastructure/docker/config/crd/patches/webhook_in_dockermachinetemplates.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclusters.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemoryclustertemplates.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachines.yaml
  test/infrastructure/inmemory/config/crd/patches/webhook_in_inmemorymachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/api

#10951 :bug: Handle a nil mutator by returning an error, not panicking
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
Labels: cncf-cla: yes, lgtm, kind/bug, size/M, approved, area/clusterctl

#10957 :bug: Ensure move uses mutated metadata when updating a target object
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/cluster/mover_test.go
Labels: cncf-cla: yes, lgtm, kind/bug, size/M, approved, area/clusterctl

#10990 🌱 test/framework: Allow ScaleUp Deployment image to be customized
  test/framework/autoscaler_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#10988 🌱Bump cert-manager to v1.15.2
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#10975 🌱 test: stop using Consistently for rollout checks
  test/e2e/clusterctl_upgrade.go
  test/e2e/self_hosted.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#10998 🐛 Ensure DockerMachinePool providerIDList is deterministic
  test/framework/resourceversion_helpers.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/provider/infrastructure-docker

#10729 🌱 Update Config generation to use inClusterConfig
  cmd/clusterctl/client/cluster/proxy.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/clusterctl

#11004 🌱 test/framework: scale up should use allocatable memory
  test/framework/autoscaler_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#11009 🐛 Fix CRS test flake
  exp/addons/internal/controllers/clusterresourceset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#11010 🌱 Bump docker/docker to v25.0.6
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#10984 🌱 test: add coverage to find issues running on the next kubernetes release as management cluster
  scripts/ci-e2e-lib.sh
  test/e2e/clusterctl_upgrade_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#11013 🌱 Improve reconcile state logs (don't log empty diff)
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass

#11019 🌱 Increase timeout for 2 MHC unit tests
  internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/machinehealthcheck

#11012 🌱 Improve error output of ValidateResourceVersionStable
  test/framework/resourceversion_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#11021 ✨ Bump Kubernetes to v1.31.0-rc.1
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#11016 🚀 Release v1.8.0-rc.1
  CHANGELOG/v1.8.0-rc.1.md
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test, area/release

#10974 [release-1.7] 🐛 MachineSet should allow scale down operations to proceed when templated don't exist
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/machineset

#11028 🌱 Log error when calling a Runtime Extension gets an error that is ignored because of failure policy
  internal/runtime/client/client.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/logging

#11032 :bug: Machine Controller should try to retrieve node on delete
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/machine

#11044 :seedling: Follow-up PR nits from 11032
  internal/controllers/machine/machine_controller_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/machine

#11040 🚀 Release v1.7.5
  CHANGELOG/v1.7.5.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/release

#11041 🚀 Release v1.6.8
  CHANGELOG/v1.6.8.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/release

#11045 🐛 Update controller-runtime dependency to v0.18.5
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#11047 [release-1.7] 🌱 Update Controller runtime to v0.17.6
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#11049 🌱 Improve clusterctl client config logic & error message
  cmd/clusterctl/client/cluster/proxy.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#11051 📖 Update clusterctl version to v1.8.x in quick start
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/documentation

#11030 ✨ Bump Kubernetes in tests to v1.31.0 and claim support for v1.31
  docs/book/src/reference/versions.md
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#11054 🚀 Release v1.8.1
  CHANGELOG/v1.8.1.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#11056 📖 Set 1.6 EOL date
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#11055 📖 docs: fixup release-tasks, drop resolved issue
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#11060 🌱 Fix exclude for revision management in .golangci.yml
  .golangci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#11061 📖 Improve Kubernetes bump issue template
  .github/ISSUE_TEMPLATE/kubernetes_bump.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#10651 📖 release: restructure release docs team roles
  CHANGELOG/README.md
  docs/release/release-tasks.md
  docs/release/release-team-onboarding.md
  docs/release/release-team.md
  docs/release/role-handbooks/ci-signal/README.md
  docs/release/role-handbooks/communications/README.md
  docs/release/role-handbooks/release-lead/README.md
  hack/generate-doctoc.sh
  hack/tools/release/internal/update_providers/provider_issues.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test, area/documentation

#11072 📖 Sync back missing changes from original doc
  docs/release/release-team.md
  docs/release/role-handbooks/ci-signal/README.md
  docs/release/role-handbooks/communications/README.md
  docs/release/role-handbooks/release-lead/README.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/documentation

#11067 🌱 test/e2e: increase concurrency
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#11063 🌱 Bump setup-envtest to v0.19
  .github/ISSUE_TEMPLATE/kubernetes_bump.md
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#11076 📖 docs: fix broken link to tag security whitepaper
  docs/book/src/security/index.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#11066 ✨ Detect panics in e2e tests
  test/framework/deployment_helpers.go
  test/framework/deployment_helpers_test.go
  test/go.mod
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#11081 🌱 Bump kind to v0.24.0
  Tiltfile
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/go.mod
  test/go.sum
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#11073 🌱 Remove redundant self-hosted and clusterctl upgrade tests
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/self_hosted_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#11084 🌱 [release-1.8] Bump kind to v0.24.0
  Tiltfile
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/go.mod
  test/go.sum
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#11089 🐛 always declare try-or-die-command function in kubeadm-bootstrap-script.sh
  bootstrap/kubeadm/internal/cloudinit/kubeadm-bootstrap-script.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/bootstrap

#11087 📖 `cluster.status.conditions.reason` may indeed be empty
  api/v1beta1/condition_types.go
  api/v1beta1/zz_generated.openapi.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclusters.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachines.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#11082 🌱 test: improve autoscale tests for to/from zero and running autoscaler in bootstrap cluster
  test/e2e/autoscaler.go
  test/framework/autoscaler_helpers.go
  test/framework/deployment_helpers.go
  test/framework/machinedeployment_helpers.go
  test/framework/machinepool_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/e2e-testing

#11068 🌱Bump cert-manager to 1.15.3
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#11083 ✨ Collect additional logs with CAPD log collector
  test/framework/docker_logcollector.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/testing

#10907 🌱 Fix error handling when the resource is not found
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  controlplane/kubeadm/internal/controllers/controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, tide/merge-method-squash, area/logging

#11101 🌱 Add nilIsZero to all KSM metric configs where needed
  config/metrics/crd-metrics-config.yaml
  config/metrics/templates/cluster.yaml
  config/metrics/templates/common_metrics.yaml
  config/metrics/templates/machine.yaml
  config/metrics/templates/machinehealthcheck.yaml
  config/metrics/templates/machinepool.yaml
  config/metrics/templates/machineset.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/metrics

#10425 📖 Add extra information in the supported labels and annotations tables
  docs/book/src/reference/labels_and_annotations.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/documentation

#11088 📖 update release docs + fix links in issue template
  .github/ISSUE_TEMPLATE/release_tracking.md
  docs/release/role-handbooks/ci-signal/README.md
  docs/release/role-handbooks/release-lead/README.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#11107 🌱 Revert "Add nilIsZero to all KSM metric configs where needed"
  config/metrics/crd-metrics-config.yaml
  config/metrics/templates/cluster.yaml
  config/metrics/templates/common_metrics.yaml
  config/metrics/templates/machine.yaml
  config/metrics/templates/machinehealthcheck.yaml
  config/metrics/templates/machinepool.yaml
  config/metrics/templates/machineset.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/metrics

#11109 📖 Fix CAPZ redirection links in quick-start page
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#11097 🌱 Add v1.9 release team members to timeline doc
  docs/release/releases/release-1.9.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/release

#11111 🌱 test: Bump autoscaler to v1.31.0
  test/e2e/autoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#11096 🌱 Swap in new 1.9 RT members in OWNERS
  OWNERS_ALIASES
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/release

#11118 📖 Fix typos in clusterctl doc
  docs/book/src/clusterctl/commands/alpha-topology-plan.md
  docs/book/src/clusterctl/commands/upgrade.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#11106 🐛 re-add /finalizers subresource RBAC
  bootstrap/kubeadm/config/rbac/role.yaml
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  config/rbac/role.yaml
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/internal/controllers/machinepool_controller.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  test/infrastructure/docker/config/rbac/role.yaml
  test/infrastructure/docker/exp/controllers/exp.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/inmemory/config/rbac/role.yaml
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/api
