Repository kubernetes-sigs/cluster-api, pull requests merged in 2024-09, with the labels that each got.

#11074 ✨ Refactor node drain
  controllers/alias.go
  go.mod
  internal/controllers/machine/drain/cache.go
  internal/controllers/machine/drain/drain.go
  internal/controllers/machine/drain/drain_test.go
  internal/controllers/machine/drain/filters.go
  internal/controllers/machine/drain/filters_test.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_test.go
  main.go
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/XXL, approved, tide/merge-method-squash, area/machine

#11120 [release-1.8] 🐛 re-add /finalizers subresource RBAC
  bootstrap/kubeadm/config/rbac/role.yaml
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  config/rbac/role.yaml
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/internal/controllers/machinepool_controller.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  test/infrastructure/docker/config/rbac/role.yaml
  test/infrastructure/docker/exp/controllers/exp.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/inmemory/config/rbac/role.yaml
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#11124 🌱 Improve TestReconcileMachinePoolMachines unit test
  exp/internal/controllers/machinepool_controller_phases_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/machinepool

#11121 📖 Add Node drain documentation
  docs/book/src/SUMMARY.md
  docs/book/src/tasks/automated-machine-management/index.md
  docs/book/src/tasks/automated-machine-management/machine_deletions.md
  internal/controllers/machine/drain/drain.go
  internal/controllers/machine/machine_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/machine, area/documentation

#11113 📖 Move Control Plane contracts doc to right chapter
  docs/book/src/SUMMARY.md
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/providers/contracts.md
  docs/book/src/developer/providers/control-plane.md
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test, area/documentation

#10798 🌱 Deprecate obsolete errors pkg
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/migrations/v1.8-to-v1.9.md
  errors/doc.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/util

#11025 🌱 Drop internal log package & improve logs and errors
  exp/runtime/internal/controllers/extensionconfig_controller.go
  exp/topology/desiredstate/desired_state.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/clusterclass/clusterclass_controller_test.go
  internal/controllers/topology/cluster/blueprint.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/current_state.go
  internal/controllers/topology/cluster/patches/engine.go
  internal/controllers/topology/cluster/patches/patch.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/util.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  internal/controllers/topology/machineset/util.go
  internal/hooks/tracking.go
  internal/log/doc.go
  internal/log/log.go
  internal/runtime/client/client.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, tide/merge-method-squash, area/logging

#11119 📖 book: document how to use Lima on macOS for development
  docs/book/src/developer/guide.md
  docs/book/src/developer/tilt.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#11137 🐛 KCP: remove etcd member in pre-terminate hook
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/fakes_test.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/remediation_test.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/controllers/status_test.go
  controlplane/kubeadm/internal/controllers/upgrade_test.go
  test/e2e/clusterclass_rollout.go
  util/collections/machine_collection.go
  util/collections/machine_collection_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, tide/merge-method-squash, area/provider/control-plane-kubeadm

#11136 [release-1.8] 🐛 KCP: remove etcd member in pre-terminate hook
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/fakes_test.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/helpers_test.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/remediation_test.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/controllers/status_test.go
  controlplane/kubeadm/internal/controllers/upgrade_test.go
  test/e2e/clusterclass_rollout.go
  util/collections/machine_collection.go
  util/collections/machine_collection_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, tide/merge-method-squash, area/provider/control-plane-kubeadm

#11143 🚀 Release v1.8.2
  CHANGELOG/v1.8.2.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#11147 🐛 Fix drain log for unreachable Nodes
  internal/controllers/machine/machine_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/machine

#11142 🌱 golangci: add comments to enabled linters
  .golangci.yml
Labels: cncf-cla: yes, lgtm, size/L, approved, area/ci

#11127 🌱 Improve node drain e2e test
  Makefile
  internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-node-drain/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-node-drain/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-node-drain/md.yaml
  test/e2e/node_drain_timeout.go
  test/e2e/node_drain_timeout_test.go
  test/framework/deployment_helpers.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/machine

#11153 📖 Add more documentation about the KCP pre-terminate hook
  api/v1beta1/machine_types.go
  docs/book/src/developer/providers/migrations/v1.8-to-v1.9.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#11156 🌱 Bump to Go 1.22.7
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#11154 [release-1.8] 📖 Add more documentation about the KCP pre-terminate hook
  api/v1beta1/machine_types.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#11146 🌱 KCP: remove code handling Kubernetes <= v1.21
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/fakes_test.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/workload_cluster.go
  controlplane/kubeadm/internal/workload_cluster_etcd.go
  controlplane/kubeadm/internal/workload_cluster_etcd_test.go
  controlplane/kubeadm/internal/workload_cluster_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/provider/control-plane-kubeadm

#11159 [release-1.7] 🌱 Bump to Go 1.22.7
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#11161 🐛 Make KCP pre-terminate hook more robust
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  internal/controllers/machine/machine_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/provider/control-plane-kubeadm

#11164 [release-1.8] 🐛 Make KCP pre-terminate hook more robust
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  internal/controllers/machine/machine_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/provider/control-plane-kubeadm

#11158 🚀 Release v1.7.6
  CHANGELOG/v1.7.6.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/release

#11132 🌱 Bump golangci to v1.60.2
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  cmd/clusterctl/cmd/describe_cluster.go
  internal/controllers/machinedeployment/mdutil/util.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
  test/framework/docker_logcollector.go
  test/infrastructure/docker/internal/docker/loadbalancer.go
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/inmemory/pkg/runtime/cache/client.go
  test/infrastructure/inmemory/pkg/runtime/cache/hooks.go
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, area/ci

#11160 🚀 Release v1.8.3
  CHANGELOG/v1.8.3.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/release

#11062 🌱 replace kubebuilder-release-tools with new workflow
  .github/workflows/pr-verify.yaml
  hack/verify-pr-title.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, area/ci

#11091 :seedling: Add vultr infrastructure provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/reference/providers.md
  docs/book/src/user/quick-start.md
  internal/apis/bootstrap/kubeadm/v1alpha3/zz_generated.deepcopy.go
  internal/apis/core/exp/v1alpha3/zz_generated.deepcopy.go
  internal/apis/core/exp/v1alpha4/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, ok-to-test, area/clusterctl

#11169 🐛 hack: fix the shell used when running pr-verify
  .github/workflows/pr-verify.yaml
Labels: cncf-cla: yes, lgtm, size/XS, area/ci

#10959 :seedling: Log controller name in predicates
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  controllers/remote/cluster_cache_reconciler.go
  controlplane/kubeadm/internal/controllers/controller.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
  exp/internal/controllers/machinepool_controller.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/logging

#11149 ✨ clusterctl: Allow user to suppress API warnings
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/ownergraph.go
  cmd/clusterctl/client/cluster/proxy.go
  cmd/clusterctl/client/cluster/proxy_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterctl

#11163 📖 Update CAPI support and guarantees for v1.9
  CONTRIBUTING.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/documentation

#11177 [release-1.8] 📖 Drop v1.5 column, set v1.6 to EOL in versions.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/documentation

#11140 🌱 Remove previously deprecated --metrics-bind-addr flag
  docs/book/src/reference/ports.md
  util/flags/manager.go
  util/flags/manager_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/util

#10917 🌱 Use url.JoinPath instead of fmt to concat endpoint
  util/kubeconfig/kubeconfig.go
  util/kubeconfig/kubeconfig_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, area/util

#11180 📖 update scale-from-zero proposal
  docs/proposals/20210310-opt-in-autoscaling-from-zero.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#10897 📖 Proposal: Improving status in CAPI resources
  docs/proposals/improve-status-in-CAPI-resources.md
Labels: cncf-cla: yes, lgtm, size/XXL, approved, tide/merge-method-squash, area/api

#11190 📖 Drop k8s.gcr.io deprecation notice
  docs/book/src/introduction.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#11191 📖 Drop old version of migration docs
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/migrations/v0.3-to-v0.4.md
  docs/book/src/developer/providers/migrations/v0.4-to-v1.0.md
  docs/book/src/developer/providers/migrations/v1.0-to-v1.1.md
  docs/book/src/developer/providers/migrations/v1.1-to-v1.2.md
  docs/book/src/developer/providers/migrations/v1.2-to-v1.3.md
  docs/book/src/developer/providers/migrations/v1.3-to-v1.4.md
  docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md
  docs/book/src/developer/providers/migrations/v1.5-to-v1.6.md
  docs/book/src/developer/providers/version-migration.md
  docs/book/src/tasks/upgrading-cluster-api-versions.md
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/documentation

#11187 🌱 Bump coredns version in e2e variables
  test/e2e/config/docker.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#10997 ✨ Implement utils for v1beta2 conditions
  Makefile
  internal/test/builder/crd/test.cluster.x-k8s.io_phase0obj.yaml
  internal/test/builder/crd/test.cluster.x-k8s.io_phase1obj.yaml
  internal/test/builder/crd/test.cluster.x-k8s.io_phase2obj.yaml
  internal/test/builder/crd/test.cluster.x-k8s.io_phase3obj.yaml
  internal/test/builder/doc.go
  internal/test/builder/v1beta2_transition.go
  internal/test/builder/zz_generated.deepcopy.go
  internal/test/envtest/environment.go
  util/conditions/v1beta2/aggregate.go
  util/conditions/v1beta2/aggregate_test.go
  util/conditions/v1beta2/doc.go
  util/conditions/v1beta2/getter.go
  util/conditions/v1beta2/getter_test.go
  util/conditions/v1beta2/matcher.go
  util/conditions/v1beta2/matcher_test.go
  util/conditions/v1beta2/merge_strategies.go
  util/conditions/v1beta2/merge_strategies_test.go
  util/conditions/v1beta2/mirror.go
  util/conditions/v1beta2/mirror_test.go
  util/conditions/v1beta2/options.go
  util/conditions/v1beta2/setter.go
  util/conditions/v1beta2/setter_test.go
  util/conditions/v1beta2/sort.go
  util/conditions/v1beta2/sort_test.go
  util/conditions/v1beta2/summary.go
  util/conditions/v1beta2/summary_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, tide/merge-method-squash, area/util

#11197 🐛 clusterclass: fix nil pointer for empty workers in webhook
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterclass

#11131 :book: infrastructure provider security guidelines
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/cluster-infrastructure.md
  docs/book/src/developer/providers/machine-infrastructure.md
  docs/book/src/security/infrastructure-provider-security-guidance.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/documentation

#11148 🌱 machine: prevent error spamming for NodeOutdatedTaint if objects are not found
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machine/machine_controller_noderef_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/machine

#11178 🌱 condition: fix godoc for MachineNodeHealthyCondition
  api/v1beta1/condition_consts.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/machine

#11145 🌱 test: add PreWaitForControlplaneToBeUpgraded to ClusterUpgradeConformanceSpec
  Makefile
  test/e2e/cluster_upgrade.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-pre-drain/cluster.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-kcp-pre-drain/kustomization.yaml
  test/framework/controlplane_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/e2e-testing

#11194 📖 Group API reference docs
  docs/book/src/SUMMARY.md
  docs/book/src/reference/api/crd-relationships.md
  docs/book/src/reference/api/labels-and-annotations.md
  docs/book/src/reference/api/metadata-propagation.md
  docs/book/src/reference/api/owner-references.md
  docs/book/src/reference/api/reference.md
  docs/book/src/reference/api_reference.md
  docs/book/src/reference/labels_and_annotations.md
  docs/book/src/tasks/experimental-features/cluster-class/operate-cluster.md
  docs/book/src/tasks/experimental-features/machineset-preflight-checks.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/documentation

#11200 [release-1.8] 🌱 Reduce verbosity of logs when calling Runtime Extensions
  internal/runtime/client/client.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/logging

#11201 🌱 test/framework: allow users to modify cache.Options
  test/framework/cluster_proxy.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/testing

#11205 🌱 test/framework: GetCAPIResources should warn on rbac issues
  test/framework/alltypes_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#11150 🌱 Add support for v1beta2 conditions to patch helper
  internal/test/builder/v1beta2_transition.go
  util/conditions/v1beta2/options.go
  util/conditions/v1beta2/patch.go
  util/conditions/v1beta2/patch_test.go
  util/patch/options.go
  util/patch/patch.go
  util/patch/patch_test.go
  util/patch/utils.go
  util/patch/utils_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, area/util

#11208 📖 Refactor core developer guide
  docs/book/src/SUMMARY.md
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/developer/architecture/controllers.md
  docs/book/src/developer/core/controllers/bootstrap.md
  docs/book/src/developer/core/controllers/cluster-resource-set.md
  docs/book/src/developer/core/controllers/cluster-topology.md
  docs/book/src/developer/core/controllers/cluster.md
  docs/book/src/developer/core/controllers/control-plane.md
  docs/book/src/developer/core/controllers/machine-deployment.md
  docs/book/src/developer/core/controllers/machine-health-check.md
  docs/book/src/developer/core/controllers/machine-pool.md
  docs/book/src/developer/core/controllers/machine-set.md
  docs/book/src/developer/core/controllers/machine.md
  docs/book/src/developer/core/controllers/overview.md
  docs/book/src/developer/core/e2e.md
  docs/book/src/developer/core/logging.md
  docs/book/src/developer/core/multi-tenancy.md
  docs/book/src/developer/core/overview.md
  docs/book/src/developer/core/repository-layout.md
  docs/book/src/developer/core/support-multiple-instances.md
  docs/book/src/developer/core/testing.md
  docs/book/src/developer/core/tilt.md
  docs/book/src/developer/core/tuning.md
  docs/book/src/developer/getting-started.md
  docs/book/src/developer/providers/contracts.md
  docs/book/src/developer/providers/control-plane.md
  docs/book/src/developer/providers/getting-started/building-running-and-testing.md
  docs/book/src/reference/api/labels-and-annotations.md
  docs/book/src/reference/glossary.md
  docs/book/src/tasks/experimental-features/experimental-features.md
  docs/book/src/tasks/experimental-features/machine-pools.md
  docs/book/src/tasks/upgrading-clusters.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/documentation

#11207 🌱 Enable race detector for main module unit tests
  Makefile
  bootstrap/kubeadm/types/upstreamv1beta1/conversion_test.go
  bootstrap/kubeadm/types/upstreamv1beta2/conversion_test.go
  bootstrap/kubeadm/types/upstreamv1beta3/conversion_test.go
  bootstrap/kubeadm/types/upstreamv1beta4/conversion_no_fuzz_test.go
  bootstrap/kubeadm/types/upstreamv1beta4/conversion_test.go
  exp/internal/controllers/machinepool_controller_test.go
  exp/ipam/api/v1alpha1/conversion_test.go
  internal/apis/bootstrap/kubeadm/v1alpha3/conversion_test.go
  internal/apis/bootstrap/kubeadm/v1alpha4/conversion_test.go
  internal/apis/controlplane/kubeadm/v1alpha3/conversion_test.go
  internal/apis/controlplane/kubeadm/v1alpha4/conversion_test.go
  internal/apis/core/exp/addons/v1alpha3/conversion_test.go
  internal/apis/core/exp/addons/v1alpha4/conversion_test.go
  internal/apis/core/exp/v1alpha3/conversion_test.go
  internal/apis/core/exp/v1alpha4/conversion_test.go
  internal/apis/core/v1alpha3/conversion_test.go
  internal/apis/core/v1alpha4/conversion_test.go
  internal/test/envtest/environment.go
  test/infrastructure/docker/api/v1alpha3/conversion_test.go
  test/infrastructure/docker/api/v1alpha4/conversion_test.go
  test/infrastructure/docker/exp/api/v1alpha3/conversion_test.go
  test/infrastructure/docker/exp/api/v1alpha4/conversion_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/testing

#11214 📖 Update the developer guide reference
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#11179 ✨ util: Warning handler that discards messages that match a regular expression
  util/apiwarnings/doc.go
  util/apiwarnings/handler.go
  util/apiwarnings/handler_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/util

#11220 :seedling: test/e2e: decrease concurrency
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#11222 [release-1.8] :seedling: test/e2e: decrease concurrency
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#11174 🌱 Foreground deletion for MachineDeployments and MachineSets
  api/v1beta1/machinedeployment_types.go
  api/v1beta1/machineset_types.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller_test.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/machineset/machineset_controller_test.go
  test/e2e/cluster_deletion.go
  test/e2e/cluster_deletion_test.go
  test/framework/finalizers_helpers.go
  util/log/log.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, tide/merge-method-squash, area/machineset, area/machinedeployment

#11212 🌱 test: use cluster without worker definition for kcp only test
  .gitignore
  Makefile
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-kcp-only/cluster-topology-class.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-kcp-only/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-no-workers/disable-control-plane-taint-variable.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-no-workers/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-no-workers/remove-topology-workers.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-kcp-only/clusterclass-name.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-kcp-only/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-kcp-only/remove-worker-patches.yaml
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start-kcp-only/remove-workers.yaml
  test/e2e/quick_start_test.go
  test/e2e/self_hosted_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, area/e2e-testing

#11188 ⚠️ Fix object logging in ResourceHasFilterLabel, ResourceNotPaused & ResourceNotPausedAndHasFilterLabel predicates
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  controllers/external/tracker.go
  controllers/external/tracker_test.go
  controllers/remote/cluster_cache_reconciler.go
  controlplane/kubeadm/internal/controllers/controller.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
  exp/internal/controllers/machinepool_controller.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
  util/predicates/generic_predicates.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/util

#11229 🌱 pr-verify: use env var for passing the PR title
  .github/workflows/pr-verify.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#11173 ✨ clusterctl: Suppress "finalizer name" API warnings in "move" command
  cmd/clusterctl/cmd/move.go
  util/apiwarnings/expressions.go
  util/apiwarnings/handler.go
  util/apiwarnings/handler_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/clusterctl

#11233 🐛 Log errors on specific log levels correctly
  exp/internal/controllers/machinepool_controller_noderef.go
  internal/controllers/machine/drain/drain.go
  internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
  util/util.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/logging

#11236 📖 Fix typos
  config/metrics/templates/README.md
  docs/book/src/developer/providers/migrations/v1.8-to-v1.9.md
  docs/book/src/reference/api/metadata-propagation.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#11166 ✨ machine: Introduce Deletion status field and add timestamps for drain and volumeDetach instead of using the condition
  api/v1beta1/machine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  internal/apis/core/v1alpha3/conversion.go
  internal/apis/core/v1alpha3/zz_generated.conversion.go
  internal/apis/core/v1alpha4/conversion.go
  internal/apis/core/v1alpha4/zz_generated.conversion.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/machine
