Repository kubernetes-sigs/cluster-api, pull requests merged in 2024-01, with the labels that each got.

#9934 🌱 Add missing folder to clean-tilt make target
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#9938 🌱 bump crypto dep version
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9943 [release-1.6] 🌱 Bump golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#9944 [release-1.5] 🌱 Bump golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#9941 :book: Add k0smotron to providers list
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#9946 🌱 Improve patch helper error handling
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  cmd/clusterctl/client/cluster/mover.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/remediation.go
  docs/book/src/developer/providers/migrations/v1.6-to-v1.7.md
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
  exp/internal/controllers/machinepool_controller_noderef.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  internal/hooks/tracking.go
  test/framework/autoscaler_helpers.go
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
  util/patch/patch.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/util

#9942 🌱 Bump cluster-autoscaler to v1.29.0
  test/e2e/autoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9945 🌱 Use min/max funcs from Go SDK
  controlplane/kubeadm/internal/controllers/remediation.go
  hack/tools/internal/log-push/main.go
  internal/controllers/machinedeployment/machinedeployment_rolling.go
  internal/controllers/machinedeployment/mdutil/util.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/util

#9949 🌱 Add 2023 KubeCon talks to the book
  docs/book/src/developer/guide.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#9952 🌱 feat: make docker machine bootstrap timeout configurable
  test/infrastructure/docker/api/v1alpha4/conversion.go
  test/infrastructure/docker/api/v1alpha4/zz_generated.conversion.go
  test/infrastructure/docker/api/v1beta1/dockermachine_types.go
  test/infrastructure/docker/api/v1beta1/zz_generated.deepcopy.go
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/provider/infrastructure-docker

#9948 [release-1.6] 🌱 Bump cluster-autoscaler to v1.29.0
  test/e2e/autoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9960 🐛 Make MachinePools and MachineDeployments optional in ApplyClusterTemplateAndWait
  test/framework/cluster_topology_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9963 🌱 Make etcd and CoreDNS optional in upgrade and self-hosted tests
  test/e2e/cluster_upgrade.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/self_hosted.go
  test/framework/cluster_topology_helpers.go
  test/framework/controlplane_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#9936 🌱 Small improvements to tilt
  Tiltfile
  docs/book/src/developer/tilt.md
  hack/tools/internal/tilt-prepare/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, area/devtools

#9935 🌱 Small improvements to the inmemory api server
  test/infrastructure/inmemory/internal/server/api/const.go
  test/infrastructure/inmemory/internal/server/api/handler.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#9957 📖 Update instructions to generate release notes
  Makefile
  docs/release/release-tasks.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9968 🌱 e2e: drop duplicated scale test
  test/e2e/scale_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/testing

#9977 🌱 [release-1.5] e2e: Rename scale test to drop [Scale] tag
  test/e2e/scale_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#9976 🌱 [release-1.6] e2e: drop duplicated scale test
  test/e2e/scale_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#9961 :book: Add /agenda redirect in book
  docs/book/book.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9865 🌱 Watch for Cluster resources in topology MD controller
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  test/framework/finalizers_helpers.go
  util/util.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/testing

#9972 📖 Fix function link reference and heading level
  CONTRIBUTING.md
  docs/book/src/developer/e2e.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#9981 :seedling: Fix grammar in release script
  hack/tools/release/weekly/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/release

#9985 🐛 Revert "Watch for Cluster resources in topology MD controller"
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  test/framework/finalizers_helpers.go
  util/util.go
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved, area/testing

#9988 🌱 Add DeepCopy method for E2EConfig
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/e2e_config_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#9989 [release-1.6] 🌱 Add DeepCopy method for E2EConfig
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/e2e_config_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#9956 🌱 Stop relying on GVK being set on regular typed objects
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/internal/controllers/machinepool_controller.go
  exp/internal/controllers/machinepool_controller_noderef.go
  internal/contract/references.go
  internal/controllers/clusterclass/clusterclass_controller_test.go
  internal/controllers/clusterclass/suite_test.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machinedeployment/suite_test.go
  internal/controllers/machineset/suite_test.go
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/patches/engine.go
  internal/controllers/topology/cluster/patches/template.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
  internal/test/builder/builders.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller_phases.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#9984 🌱 test/framework add WatchDaemonSetLogsByLabelSelector method
  test/framework/daemonset_helpers.go
  test/framework/deployment_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#9995 🌱 Add test util to resolve Kubernetes versions
  test/framework/kubernetesversions/versions.go
  test/framework/kubernetesversions/versions_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#9987 🌱 Bump controller-tools to v0.14
  Makefile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepooltemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclusters.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclustertemplates.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachines.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#9864 🌱 Mark Machine healthy condition as unknown if we can't list wl nodes
  api/v1beta1/condition_consts.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machine/machine_controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/machine

#9797 :book: add docs/examples for pre-release and nightly img version deployments with clusterctl
  docs/book/src/clusterctl/commands/upgrade.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#9970 🌱 test: add dynamic finalizer assertions for e2e framework
  test/e2e/quick_start_test.go
  test/framework/finalizers_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/testing

#9998 :bug: Use keys/values structured log interface
  exp/runtime/topologymutation/walker.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/runtime-sdk

#10001 🌱 go.mod: bump github.com/cloudflare/circl to v1.3.7
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#10002 🌱 [release-1.6] go.mod: bump github.com/cloudflare/circl to v1.3.7
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#9355 🐛 Bubble up machine drain condition in `MachinesReadyCondition`
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/machine

#9857 🐛 Skip checking `clusterConfiguration.dns` fields when KCP checking MachineNeedRollout
  controlplane/kubeadm/internal/filters.go
  controlplane/kubeadm/internal/filters_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, tide/merge-method-squash, ok-to-test, area/provider/control-plane-kubeadm

#9993 📖 Improve doc for clusterctl update test coverage
  docs/book/src/clusterctl/commands/upgrade.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#10005 📖 Add Cluster API Operator (CAPIO) to the glossary
  docs/book/src/reference/glossary.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10003 [release-1.6] :seedling: test: add dynamic finalizer assertions for e2e framework
  test/e2e/quick_start_test.go
  test/framework/finalizers_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/testing

#10012 🌱 Bump conversion-gen to v0.29.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#10013 🌱 Bump kubebuilder envtest to 1.29.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9918 :bug: Fix wrong branch name display for weekly update script
  hack/tools/release/weekly/main.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/release

#10016 🌱 Release v1.6.1
  CHANGELOG/v1.6.1.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#10015 🌱 Release v1.5.5
  CHANGELOG/v1.5.5.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#10017 🌱 test/e2e: bump WorkloadKubernetesVersion for v1.6 clusterctl upgrade test
  test/e2e/clusterctl_upgrade_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9964 ⚠️ Bump to controller-runtime v0.17.0 & k8s.io v0.29
  bootstrap/kubeadm/main.go
  bootstrap/util/configowner.go
  bootstrap/util/configowner_test.go
  cmd/clusterctl/client/cluster/mover.go
  cmd/clusterctl/client/upgrade_test.go
  controllers/remote/cluster_cache_healthcheck_test.go
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/control_plane_test.go
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  controlplane/kubeadm/internal/controllers/status_test.go
  controlplane/kubeadm/main.go
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/runtime-openapi-gen/main.go
  internal/controllers/machinedeployment/machinedeployment_sync.go
  internal/controllers/machinedeployment/machinedeployment_sync_test.go
  internal/controllers/machinedeployment/mdutil/util.go
  internal/controllers/machinedeployment/mdutil/util_test.go
  internal/test/envtest/environment.go
  main.go
  test/extension/main.go
  test/go.mod
  test/go.sum
  test/infrastructure/docker/main.go
  test/infrastructure/inmemory/main.go
  util/failuredomains/failure_domains.go
  util/failuredomains/failure_domains_test.go
  util/patch/patch.go
  util/patch/utils.go
  util/patch/utils_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/dependency

#10000 🌱 Move ykakarap to emeritus approvers
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/community-meeting

#9937 🌱 hack: implement generator for prowjobs
  .github/ISSUE_TEMPLATE/kubernetes_bump.md
  Makefile
  docs/release/release-tasks.md
  hack/boilerplate/boilerplate.py
  hack/tools/go.mod
  hack/tools/prowjob-gen/README.md
  hack/tools/prowjob-gen/config.go
  hack/tools/prowjob-gen/generator.go
  hack/tools/prowjob-gen/main.go
  hack/tools/prowjob-gen/main_test.go
  hack/tools/prowjob-gen/test/test-configuration.yaml
  hack/tools/prowjob-gen/test/test-main.yaml.golden
  hack/tools/prowjob-gen/test/test.yaml.tpl
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/ci

#10022 🌱 hack/prowjob-gen skip creating empty files
  hack/tools/prowjob-gen/generator.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#10011 🌱 Bump go-apidiff to v0.8.2
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#9971 🌱 Provide faster support for new k8s minor releases
  CONTRIBUTING.md
  docs/book/src/reference/versions.md
  docs/release/release-cycle.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#10018 🌱 Simplify testing nightly builds with clusterctl
  cmd/clusterctl/hack/create-local-repository.py
  docs/book/src/clusterctl/developers.md
  metadata.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/devtools

#9950 🌱 Add completion for fish shell
  cmd/clusterctl/cmd/completion.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/clusterctl

#10030 🌱 test: adjust capd dockerfile so the binary exposes the package in the built binraries path variable
  hack/docker-image-verify.sh
  test/infrastructure/docker/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#10024 [release-1.6] 📖 Sync version and release docs with main
  CONTRIBUTING.md
  docs/book/src/reference/versions.md
  docs/release/release-cycle.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release, area/documentation

#10031 📖 Rename "others..." tab with "Other providers..."
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#9975 🌱 Clarify rules for adding new clusterctl default providers
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/clusterctl/provider-contract.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterctl

#9991 ✨ Add k0smotron provider
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/clusterctl

#10042 🌱 Move CecileRobertMichon to emeritus
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/community-meeting

#9997 🌱 Promote chrischdi to Cluster API maintainer
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/community-meeting

#10046 🌱 test/e2e: Support configuring ExtraPortMappings for the kind cluster
  test/framework/bootstrap/kind_provider.go
  test/framework/bootstrap/kind_util.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/provider/infrastructure-docker

#9986 🌱 Make in memory runtime and server accessible from outside
  test/infrastructure/inmemory/controllers/alias.go
  test/infrastructure/inmemory/internal/cloud/api/v1alpha1/groupversion_info.go
  test/infrastructure/inmemory/internal/cloud/api/v1alpha1/machine_types.go
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller_test.go
  test/infrastructure/inmemory/internal/webhooks/inmemorycluster_webhook.go
  test/infrastructure/inmemory/internal/webhooks/inmemoryclustertemplate_webhook.go
  test/infrastructure/inmemory/internal/webhooks/inmemorymachine_webhook.go
  test/infrastructure/inmemory/internal/webhooks/inmemorymachinetemplate_webhook.go
  test/infrastructure/inmemory/main.go
  test/infrastructure/inmemory/pkg/runtime/alias.go
  test/infrastructure/inmemory/pkg/runtime/cache/cache.go
  test/infrastructure/inmemory/pkg/runtime/cache/cache_test.go
  test/infrastructure/inmemory/pkg/runtime/cache/client.go
  test/infrastructure/inmemory/pkg/runtime/cache/client_test.go
  test/infrastructure/inmemory/pkg/runtime/cache/doc.go
  test/infrastructure/inmemory/pkg/runtime/cache/gc.go
  test/infrastructure/inmemory/pkg/runtime/cache/gc_test.go
  test/infrastructure/inmemory/pkg/runtime/cache/hooks.go
  test/infrastructure/inmemory/pkg/runtime/cache/informer.go
  test/infrastructure/inmemory/pkg/runtime/cache/sync.go
  test/infrastructure/inmemory/pkg/runtime/cache/sync_test.go
  test/infrastructure/inmemory/pkg/runtime/client/client.go
  test/infrastructure/inmemory/pkg/runtime/client/doc.go
  test/infrastructure/inmemory/pkg/runtime/doc.go
  test/infrastructure/inmemory/pkg/runtime/manager/doc.go
  test/infrastructure/inmemory/pkg/runtime/manager/manager.go
  test/infrastructure/inmemory/pkg/runtime/resourcegroup/cached_resourcegroup.go
  test/infrastructure/inmemory/pkg/runtime/resourcegroup/doc.go
  test/infrastructure/inmemory/pkg/runtime/resourcegroup/resourcegroup.go
  test/infrastructure/inmemory/pkg/server/api/const.go
  test/infrastructure/inmemory/pkg/server/api/debug.go
  test/infrastructure/inmemory/pkg/server/api/doc.go
  test/infrastructure/inmemory/pkg/server/api/handler.go
  test/infrastructure/inmemory/pkg/server/api/metrics.go
  test/infrastructure/inmemory/pkg/server/api/portforward/doc.go
  test/infrastructure/inmemory/pkg/server/api/portforward/httpstreams.go
  test/infrastructure/inmemory/pkg/server/api/watch.go
  test/infrastructure/inmemory/pkg/server/certs.go
  test/infrastructure/inmemory/pkg/server/doc.go
  test/infrastructure/inmemory/pkg/server/etcd/doc.go
  test/infrastructure/inmemory/pkg/server/etcd/handler.go
  test/infrastructure/inmemory/pkg/server/etcd/handler_test.go
  test/infrastructure/inmemory/pkg/server/etcd/metrics.go
  test/infrastructure/inmemory/pkg/server/listener.go
  test/infrastructure/inmemory/pkg/server/mux.go
  test/infrastructure/inmemory/pkg/server/mux_test.go
  test/infrastructure/inmemory/pkg/server/proxy/addr.go
  test/infrastructure/inmemory/pkg/server/proxy/conn.go
  test/infrastructure/inmemory/pkg/server/proxy/dial.go
  test/infrastructure/inmemory/pkg/server/proxy/doc.go
  test/infrastructure/inmemory/pkg/server/proxy/proxy.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/provider/infrastructure-in-memory

#9990 🌱 read in dockerfiles from stdin
  Makefile
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#10058 🌱 fix dockerfile for clusterctl build
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#10057 🌱 bump `github.com/docker/docker` from 24.0.7 -> 25.0.0
  hack/tools/go.mod
  hack/tools/go.sum
  test/framework/kubetest/run.go
  test/go.mod
  test/go.sum
  test/infrastructure/container/docker.go
  test/infrastructure/container/interface.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/dependency

#10060 🌱 Add conformance e2e tests
  scripts/ci-e2e-lib.sh
  scripts/ci-e2e.sh
  test/e2e/config/docker.yaml
  test/e2e/k8s_conformance_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#9543 🐛 Fix ClusterCacheTracker memory leak
  controllers/remote/cluster_cache_tracker.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/clustercachetracker

#10040 📖 Refining 'cluster init --help' command documentation
  cmd/clusterctl/cmd/init.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#9077 :seedling: Add scale testing for upgrades
  test/e2e/scale.go
  test/e2e/scale_test.go
  test/framework/cluster_topology_helpers.go
  test/framework/controlplane_helpers.go
  test/framework/machine_helpers.go
  test/infrastructure/inmemory/pkg/server/api/handler.go
  test/infrastructure/inmemory/pkg/server/mux_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#10068 :bug: Fix link to v1alpha4 types
  docs/proposals/20181121-machine-api.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10067 🌱 Add PostCreateNamespace hook to E2E tests
  test/e2e/autoscaler.go
  test/e2e/cluster_upgrade.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/clusterclass_changes.go
  test/e2e/clusterclass_rollout.go
  test/e2e/clusterctl_upgrade.go
  test/e2e/common.go
  test/e2e/k8s_conformance.go
  test/e2e/kcp_adoption.go
  test/e2e/kcp_remediations.go
  test/e2e/machine_pool.go
  test/e2e/md_remediations.go
  test/e2e/md_rollout.go
  test/e2e/md_scale.go
  test/e2e/node_drain_timeout.go
  test/e2e/quick_start.go
  test/e2e/scale.go
  test/e2e/self_hosted.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/e2e-testing

#10066 🌱 Update jobs.md and make it version-independent
  .github/ISSUE_TEMPLATE/kubernetes_bump.md
  docs/book/src/reference/jobs.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/documentation

#9670 🌱Add more helper functions in topologymutation varaible.go to help unmarshal variables
  exp/runtime/topologymutation/errors.go
  exp/runtime/topologymutation/variables.go
  exp/runtime/topologymutation/variables_test.go
  test/extension/handlers/topologymutation/handler.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/runtime-sdk

#10080 🌱 Fix ci-latest test to actually use ci latest
  scripts/ci-e2e-lib.sh
  scripts/ci-e2e.sh
  test/e2e/k8s_conformance_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing
