Repository kubernetes-sigs/cluster-api, pull requests merged in 2024-12, with the labels that each got.

#11472 ⚠️ Deprecate MD.Spec.ProgressDeadlineSeconds
  .golangci.yml
  api/v1beta1/machinedeployment_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/machinedeployment

#11516 ⚠️ Deprecate replica counters planned for removal
  .golangci.yml
  api/v1beta1/machinedeployment_types.go
  api/v1beta1/machineset_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  exp/api/v1beta1/machinepool_types.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/api

#11515 🌱 Drop retry when computing KCP conditions
  controlplane/kubeadm/internal/workload_cluster_conditions.go
  controlplane/kubeadm/internal/workload_cluster_conditions_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/provider/control-plane-kubeadm

#11518 🌱 Drop unused v1beta2 conditions and reasons
  controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
  exp/api/v1beta1/v1beta2_condition_consts.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/conditions

#11525 🌱 Update controller runtime v0.18.6
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#11524 🌱Update controller-runtime to v0.19.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#11521 🌱 Small improvements to v1beta2 conditions godoc
  api/v1beta1/cluster_types.go
  api/v1beta1/machine_types.go
  api/v1beta1/machinedeployment_types.go
  api/v1beta1/machineset_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  controlplane/kubeadm/api/v1beta1/v1beta2_condition_consts.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/filters.go
  internal/controllers/machine/drain/drain.go
  internal/controllers/machinedeployment/mdutil/util.go
  internal/controllers/machineset/machineset_controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/conditions

#11491 📖 Add warning note about hook invocation in SDK
  docs/book/src/tasks/experimental-features/runtime-sdk/index.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#11486 📖 add release 1.8 book link
  docs/book/src/introduction.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#11530 :seedling: Release notes `v1.9.0-rc.1` fix
  CHANGELOG/v1.9.0-rc.1.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#11526 🌱 test: add options for additional resources and verify volume detach to node drain test
  test/e2e/node_drain.go
  test/e2e/node_drain_test.go
  test/framework/convenience.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/e2e-testing

#11533 🌱 [release-1.8] Bump github.com/coredns/corefile-migration to v1.0.24
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#11534 🌱 Bump go to v1.22.10
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#11532 🌱 [release-1.7] Bump github.com/coredns/corefile-migration to v1.0.24
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#11538 🌱 Bump kubernetes release to v1.32.0-rc.1
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#11540 🌱 [release-1.9] Bump kubernetes release to v1.32.0-rc.1
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#11546 🌱 Bump CAPI Visualizer to v1.4.0
  hack/observability/visualizer/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#11415 🐛 remove disableMachineCreate annotation from new machinesets during rolling machine deployment reconciliation
  internal/controllers/machinedeployment/machinedeployment_rolling.go
  internal/controllers/machinedeployment/machinedeployment_rolling_test.go
  internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/machinedeployment

#11544 [release-1.7] 🌱 Bump go 1.22.10
  Makefile
  Tiltfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#11547 :bug: Properly display the namespace name in scale test
  test/e2e/scale.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/e2e-testing

#11555 🚀 Release v1.7.9
  CHANGELOG/v1.7.9.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#11556 🚀 Release v1.8.6
  CHANGELOG/v1.8.6.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#11554 🚀 Release v1.9.0
  CHANGELOG/v1.9.0.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#11557 📖 Set v1.7 EOL date and Update CoreDNS version table
  CONTRIBUTING.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#11563 ✨ Bump Kubernetes in tests to v1.32.0 and claim support for v1.32
  docs/book/src/reference/versions.md
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/testing

#11566 🌱 machine: remove solved todo comment
  internal/controllers/machine/machine_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/machine

#11568 🌱 Bump default kind image to v1.32.0
  docs/book/src/developer/core/tilt.md
  docs/book/src/user/quick-start.md
  test/framework/bootstrap/kind_provider.go
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#11479 📖 Add Cluster API release-1.10 timeline document
  docs/release/releases/release-1.10.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/M, approved, area/release

#11575 📖 book: fix versions.md for v1.32
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#11578 🌱 github: update branches for weekly actions
  .github/workflows/weekly-md-link-check.yaml
  .github/workflows/weekly-security-scan.yaml
  .github/workflows/weekly-test-release.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#11579 🌱 Bump golang.org/x/crypto
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#11581 📖 CONTRIBUTING.md fix dead links
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#11571 🌱Add Runtime Extension dashboard
  hack/observability/grafana/dashboards/runtime-extensions.json
  hack/observability/grafana/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, area/devtools

#11580 [release-1.8] 🌱 Bump golang.org/x/crypto
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#11587 🚀 Release v1.9.1
  CHANGELOG/v1.9.1.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#11588 🌱 GITHUB: downgrade gh-release action
  .github/workflows/release.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#11589 🚀 v1.9.1 trigger release again
  CHANGELOG/v1.9.1.md
Labels: cncf-cla: yes, size/XS, area/release

#11596 :book: Use long name version for Canonical Kubernetes
  docs/book/src/reference/providers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#11594 :seedling: Bump github-action-markdown-link-check to 1.0.15
  .github/workflows/pr-md-link-check.yaml
  .github/workflows/weekly-md-link-check.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#11593 🌱 Bump kpromo to 5ab0dbc74b0228c22a93d240596dff77464aee8f
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#11597 🌱 add TypedAll, ResourceIsUnchanged and TypedResourceIsUnchanged predicates
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  controlplane/kubeadm/internal/controllers/controller.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
  exp/internal/controllers/machinepool_controller.go
  exp/internal/controllers/machinepool_controller_phases.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/cluster/cluster_controller_phases.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
  util/predicates/generic_predicates.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/util

#11598 🌱 Improve KCP scale up when using failure domains
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/scale.go
  util/failuredomains/failure_domains.go
  util/failuredomains/failure_domains_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, tide/merge-method-squash, area/provider/control-plane-kubeadm

#11601 🌱 observability: bump helm charts to newer versions
  hack/observability/grafana/chart/kustomization.yaml
  hack/observability/kube-state-metrics/kustomization.yaml
  hack/observability/loki/kustomization.yaml
  hack/observability/loki/values.yaml
  hack/observability/metrics-server/kustomization.yaml
  hack/observability/parca/kustomization.yaml
  hack/observability/prometheus/kustomization.yaml
  hack/observability/promtail/kustomization.yaml
  hack/observability/tempo/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/devtools

#11606 [release-1.9] 🌱 Reconcile topology only when necessary
  internal/controllers/topology/cluster/cluster_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/cluster

#11605 🌱 Reconcile topology only when necessary
  internal/controllers/topology/cluster/cluster_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/cluster

#11608 🚀 Release v1.9.2
  CHANGELOG/v1.9.2.md
Labels: size/S, lgtm, approved, area/release

#11609 🚀 Release v1.8.7
  CHANGELOG/v1.8.7.md
Labels: cncf-cla: yes, lgtm, approved, area/release

#11611 🐛 Export runtime.Client interface and cache package
  .golangci.yml
  controllers/alias.go
  exp/runtime/client/client.go
  exp/runtime/controllers/alias.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/warmup.go
  exp/runtime/internal/controllers/warmup_test.go
  exp/topology/desiredstate/desired_state.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/clusterclass/clusterclass_controller_test.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_test.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/patches/engine.go
  internal/controllers/topology/cluster/patches/external/external_patch_generator.go
  internal/controllers/topology/cluster/patches/external/external_patch_generator_test.go
  internal/controllers/topology/cluster/patches/external/external_validator.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
  internal/runtime/client/fake/fake_client.go
  main.go
  test/extension/handlers/topologymutation/handler_integration_test.go
  util/cache/cache.go
  util/cache/cache_test.go
  util/cache/doc.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterclass

#11613 [release-1.8] 🐛 Export runtime.Client interface and cache package
  .golangci.yml
  controllers/alias.go
  exp/runtime/client/client.go
  exp/runtime/controllers/alias.go
  exp/runtime/internal/controllers/extensionconfig_controller.go
  exp/runtime/internal/controllers/extensionconfig_controller_test.go
  exp/runtime/internal/controllers/warmup.go
  exp/runtime/internal/controllers/warmup_test.go
  exp/topology/desiredstate/desired_state.go
  internal/controllers/clusterclass/clusterclass_controller.go
  internal/controllers/clusterclass/clusterclass_controller_test.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/patches/engine.go
  internal/controllers/topology/cluster/patches/external/external_patch_generator.go
  internal/controllers/topology/cluster/patches/external/external_patch_generator_test.go
  internal/controllers/topology/cluster/patches/external/external_validator.go
  internal/runtime/client/client.go
  internal/runtime/client/client_test.go
  internal/runtime/client/fake/fake_client.go
  main.go
  test/extension/handlers/topologymutation/handler_integration_test.go
  util/cache/cache.go
  util/cache/cache_test.go
  util/cache/doc.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterclass

#11619 [release-1.8] 🌱 Bump to golang.org/x/net v0.23.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#11614 🚀 Release v1.9.3
  CHANGELOG/v1.9.3.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#11615 🚀 Release v1.8.8
  CHANGELOG/v1.8.8.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#11624 🐛 Machine: sort list of pre-drain hooks for stable condition messages
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_status_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/machine

#11623 📖 Fix a link for Cluster API videos and tutorials
  docs/book/src/developer/providers/getting-started/overview.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/XS, approved, ok-to-test, area/documentation
