Repository kubernetes-sigs/cluster-api, pull requests merged in 2024-05, with the labels that each got.

#10530 🌱 Ensure resourceVersions are stable
  test/e2e/quick_start_test.go
  test/framework/resourceversion_helpers.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#10528 📖 Add v1.7 to v1.8 migration guide
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/documentation

#10549 📖 Minor fixed to developer.md
  docs/book/src/clusterctl/developers.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#10555 📖 Minor fix to configuration.md
  docs/book/src/clusterctl/configuration.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#10554 🌱 Deprecate IP Family builtin variable
  api/v1beta1/cluster_types.go
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
  exp/runtime/hooks/api/v1alpha1/topologymutation_variable_types.go
  exp/runtime/hooks/api/v1alpha1/zz_generated.openapi.go
  internal/controllers/topology/cluster/patches/variables/variables.go
  test/infrastructure/docker/internal/docker/loadbalancer.go
  test/infrastructure/docker/internal/docker/machine.go
Labels: size/S, cncf-cla: yes, lgtm, approved, tide/merge-method-squash, area/clusterclass

#10551 🌱 Allow users to specify webhook server cert and key names
  bootstrap/kubeadm/main.go
  controlplane/kubeadm/main.go
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
  exp/runtime/server/server.go
  main.go
  test/extension/main.go
  test/infrastructure/docker/main.go
  test/infrastructure/inmemory/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#10437 🌱 Add triage-party for the Cluster API backlog
  Makefile
  hack/tools/triage/.gitignore
  hack/tools/triage/config.yaml
  hack/tools/triage/triage-improvements.patch
Labels: cncf-cla: yes, lgtm, size/XL, approved, tide/merge-method-squash, area/devtools

#10560 🐛 test: filter cluster-wide objects asserted in ResourceVersion tests to exclude objects of parallel tests
  cmd/clusterctl/client/cluster/ownergraph.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/cluster_upgrade_runtimesdk_test.go
  test/e2e/quick_start_test.go
  test/framework/finalizers_helpers.go
  test/framework/ownerreference_helpers.go
  test/framework/resourceversion_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/e2e-testing

#10571 🌱 Optimize dependabot config
  .github/dependabot.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/ci

#10561 📖 Document failureReason and Message are considered terminal errors
  docs/book/src/developer/architecture/controllers/cluster.md
  docs/book/src/developer/architecture/controllers/control-plane.md
  docs/book/src/developer/architecture/controllers/machine-pool.md
  docs/book/src/developer/architecture/controllers/machine.md
  docs/book/src/developer/providers/bootstrap.md
  docs/book/src/developer/providers/cluster-infrastructure.md
  docs/book/src/developer/providers/machine-infrastructure.md
  docs/book/src/tasks/automated-machine-management/healthchecking.md
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, area/documentation

#10586 :seedling: Bump go version to 1.22.3
  Makefile
  Tiltfile
  netlify.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#10576 🌱 Flag for old infra machine naming
  config/manager/manager.yaml
  controllers/alias.go
  controlplane/kubeadm/config/manager/manager.yaml
  controlplane/kubeadm/controllers/alias.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/main.go
  internal/controllers/machineset/machineset_controller.go
  main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/provider/control-plane-kubeadm, area/machineset

#10590 🐛 test: Ensure all ownerRef assertions for some Kind are evaluated
  test/framework/ownerreference_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#10580 🌱 Set terminationMessagePolicy to FallbackToLogsOnError for all managers
  bootstrap/kubeadm/config/manager/manager.yaml
  config/manager/manager.yaml
  controlplane/kubeadm/config/manager/manager.yaml
  test/extension/config/default/manager.yaml
  test/infrastructure/docker/config/manager/manager.yaml
  test/infrastructure/inmemory/config/manager/manager.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/logging

#10594 📖 Document terminationMessagePolicy suggestion for providers
  docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10584 🌱 Allow control plane count to be configurable in clusterctl upgrade test.
  test/e2e/clusterctl_upgrade.go
  test/framework/clusterctl/client.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#10604 🚀 Release v1.7.2
  CHANGELOG/v1.7.2.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#10595 🚀 Release v1.6.5
  CHANGELOG/v1.6.5.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#10591 🐛 Skip publishing the `RemediationRestricted` event when there are no unhealthy target
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/machinehealthcheck

#10614 [release-1.7] 🌱 Support MachinePools without MachinePoolMachines in clusterctl upgrade test
  test/e2e/clusterctl_upgrade.go
  test/framework/clusterctl/client.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/testing

#10610 🌱 kind: bump to v0.23.0
  .github/ISSUE_TEMPLATE/kubernetes_bump.md
  .github/dependabot.yaml
  Tiltfile
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/go.mod
  test/go.sum
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, area/e2e-testing

#10615 [release-1.6] 🌱 Support MachinePools without MachinePoolMachines in clusterctl upgrade test
  test/e2e/clusterctl_upgrade.go
  test/framework/clusterctl/client.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/testing

#10632 🐛 Check that replicas pointer is not nil in machinepool controller
  exp/internal/controllers/machinepool_controller_phases.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/machinepool

#10613 🌱 Fix log keys, use upper case for logs
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  bootstrap/kubeadm/main.go
  cmd/clusterctl/client/alpha/machinedeployment.go
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/client.go
  cmd/clusterctl/client/cluster/components.go
  cmd/clusterctl/client/cluster/crd_migration.go
  cmd/clusterctl/client/cluster/installer.go
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/upgrader.go
  cmd/clusterctl/client/config/reader_viper.go
  cmd/clusterctl/client/repository/clusterclass_client.go
  cmd/clusterctl/client/repository/components_client.go
  cmd/clusterctl/client/repository/metadata_client.go
  cmd/clusterctl/client/repository/overrides.go
  cmd/clusterctl/client/repository/template_client.go
  cmd/clusterctl/cmd/version_checker.go
  controllers/remote/cluster_cache_tracker.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/helpers.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/upgrade.go
  controlplane/kubeadm/main.go
  docs/book/src/developer/logging.md
  docs/book/src/developer/providers/implementers-guide/controllers_and_reconciliation.md
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
  docs/proposals/20220221-runtime-SDK.md
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/addons/internal/controllers/clusterresourcesetbinding_controller.go
  exp/internal/controllers/machinepool_controller_noderef.go
  exp/internal/controllers/machinepool_controller_phases.go
  exp/ipam/internal/webhooks/ipaddress.go
  exp/util/util.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machinedeployment/machinedeployment_rollout_ondelete.go
  internal/controllers/machinedeployment/machinedeployment_sync.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
  internal/controllers/topology/cluster/structuredmerge/twowayspatchhelper.go
  internal/log/log.go
  main.go
  test/extension/handlers/topologymutation/handler.go
  test/extension/main.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller_phases.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/docker/internal/docker/machine.go
  test/infrastructure/docker/internal/docker/types/node.go
  test/infrastructure/docker/main.go
  test/infrastructure/inmemory/main.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/logging

#10606 🌱 ClusterCacheTracker: use indexes field instead of passing it around
  controllers/remote/cluster_cache_tracker.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clustercachetracker

#10630 📖 Document KCP limitation
  docs/book/src/tasks/automated-machine-management/healthchecking.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/control-plane

#10640 📖 github: document to cherry-pick the kind bump to the latest release in issue template
  .github/ISSUE_TEMPLATE/kubernetes_bump.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10641 [release-1.7] 🌱 kind: bump to v0.23.0
  .github/dependabot.yaml
  Tiltfile
  docs/book/src/developer/tilt.md
  docs/book/src/user/quick-start.md
  hack/ensure-kind.sh
  test/e2e/config/docker.yaml
  test/framework/bootstrap/kind_provider.go
  test/go.mod
  test/go.sum
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#10618 🌱 test: check for metadata.yaml when resolving releases to not try to use unreleased versions
  cmd/clusterctl/client/repository/repository_github.go
  test/framework/clusterctl/e2e_config.go
  test/framework/clusterctl/e2e_config_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/e2e-testing

#10638 🐛 KCPTemplate & DockerClusterTemplate webhook: default before immutability check
  controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate.go
  controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate_test.go
  test/infrastructure/docker/internal/webhooks/dockerclustertemplate_webhook.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/provider/control-plane-kubeadm, area/provider/infrastructure-docker

#10552 ✨ optimize rbac across controllers
  bootstrap/kubeadm/config/rbac/role.yaml
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  config/rbac/role.yaml
  controlplane/kubeadm/config/rbac/role.yaml
  controlplane/kubeadm/internal/controllers/controller.go
  exp/addons/internal/controllers/clusterresourceset_controller.go
  exp/internal/controllers/machinepool_controller.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machineset/machineset_controller.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/machinedeployment/machinedeployment_controller.go
  internal/controllers/topology/machineset/machineset_controller.go
  test/infrastructure/docker/config/rbac/role.yaml
  test/infrastructure/docker/exp/controllers/exp.go
  test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller.go
  test/infrastructure/docker/internal/controllers/dockercluster_controller.go
  test/infrastructure/docker/internal/controllers/dockermachine_controller.go
  test/infrastructure/inmemory/config/rbac/role.yaml
  test/infrastructure/inmemory/internal/controllers/inmemorycluster_controller.go
  test/infrastructure/inmemory/internal/controllers/inmemorymachine_controller.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/api

#10609 🌱 Drop support for INIT env variables in clusterctl upgrade test
  docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#10619 🌱 Replace reflect.DeepEqual in tests
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_types_test.go
  exp/addons/internal/controllers/clusterresourceset_controller_test.go
  internal/apis/core/exp/addons/v1alpha3/clusterresourcesetbinding_types_test.go
  internal/apis/core/exp/addons/v1alpha4/clusterresourcesetbinding_types_test.go
  internal/controllers/clusterclass/clusterclass_controller_test.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/runtime/client/client_test.go
  internal/topology/variables/schema_test.go
  util/patch/patch_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#10559 🌱 Improve KCP remediation re-entrancy
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/remediation_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/control-plane

#10644 🌱 Improve triage query
  hack/tools/triage/config.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#10652 🌱 test: improve output for ValidateResourceVersionStable by using BeComparable instead of Equal
  test/framework/resourceversion_helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#10628 🌱 Add compare util using go-cmp, modify webhooks & KCP controller
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/controllers/controller.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/status.go
  controlplane/kubeadm/internal/filters.go
  controlplane/kubeadm/internal/filters_test.go
  controlplane/kubeadm/internal/webhooks/kubeadmcontrolplanetemplate.go
  exp/addons/api/v1beta1/clusterresourcesetbinding_types.go
  exp/ipam/internal/webhooks/ipaddress.go
  exp/ipam/internal/webhooks/ipaddressclaim.go
  internal/util/compare/equal.go
  internal/util/compare/equal_test.go
  test/infrastructure/docker/internal/webhooks/dockerclustertemplate_webhook.go
  test/infrastructure/docker/internal/webhooks/dockermachinetemplate_webhook.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/provider/control-plane-kubeadm

#10659 :seedling: drop pr approver workflow top-level permissions
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#10664 [release-1.6] 🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#10569 🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases
  Makefile
  docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#10639 🌱 Use kind as a secondary management cluster for clusterctl E2E tests
  test/e2e/clusterctl_upgrade.go
  test/e2e/clusterctl_upgrade_test.go
  test/framework/bootstrap/kind_util.go
  test/framework/exec/kubectl.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/testing

#10657 🐛 capd: don't add host ports to exposed ports of containers
  test/infrastructure/container/docker.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/provider/infrastructure-docker

#10663 [release-1.7] 🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#10671 🐛 Defaulting webhook should check class is set in ClusterClass-based clusters
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass

#10672 🐛 Fix indexing in ClusterClass webhook MHC validation
  internal/webhooks/clusterclass.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/clusterclass

#10676 [release-1.6] 🌱 Use kind as a secondary management cluster for clusterctl E2E tests
  test/e2e/clusterctl_upgrade.go
  test/e2e/clusterctl_upgrade_test.go
  test/framework/bootstrap/kind_util.go
  test/framework/exec/kubectl.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/testing

#10675 [release-1.7] 🌱 Use kind as a secondary management cluster for clusterctl E2E tests
  test/e2e/clusterctl_upgrade.go
  test/e2e/clusterctl_upgrade_test.go
  test/framework/bootstrap/kind_util.go
  test/framework/exec/kubectl.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/testing

#10642 🌱 Cleanup owner files
  OWNERS_ALIASES
Labels: size/S, cncf-cla: yes, lgtm, approved, area/security

#10658 🌱 Retire the Alternative communication pattern feature group
  docs/community/retired/20221115-managed-kubernetes.md
  docs/community/retired/20230111-alternative-communication-patterns.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/community-meeting

#10680 [release-1.6] 🌱 Cleanup owner files
  OWNERS_ALIASES
Labels: size/S, cncf-cla: yes, lgtm, approved, area/security

#10685 📖 docs: fix dead links
  docs/release/releases/release-1.6.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10682 ✨ Support ControlPlane variable overrides
  api/v1beta1/cluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  internal/apis/core/v1alpha4/conversion.go
  internal/apis/core/v1alpha4/zz_generated.conversion.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/controllers/topology/cluster/patches/engine.go
  internal/controllers/topology/cluster/patches/engine_test.go
  internal/controllers/topology/cluster/patches/variables/variables.go
  internal/controllers/topology/cluster/patches/variables/variables_test.go
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
  internal/topology/variables/cluster_variable_validation.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/clusterclass

#10700 :bug: Use k8s.io/utils/ptr instead of k8s.io/utils/pointer
  internal/apis/core/v1alpha3/cluster_types.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#10695 🐛 re-add patch for events
  bootstrap/kubeadm/config/rbac/role.yaml
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  config/rbac/role.yaml
  controlplane/kubeadm/config/rbac/role.yaml
  controlplane/kubeadm/internal/controllers/controller.go
  exp/internal/controllers/machinepool_controller.go
  internal/controllers/cluster/cluster_controller.go
  internal/controllers/machine/machine_controller.go
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller.go
  internal/controllers/machineset/machineset_controller.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/api

#10703 🌱 Add Cluster.GetClassKey() to retrieve a NamespacedName for classes
  api/v1beta1/cluster_types.go
  api/v1beta1/index/cluster.go
  cmd/clusterctl/client/cluster/objectgraph.go
  cmd/clusterctl/client/cluster/topology.go
  cmd/clusterctl/client/clusterclass.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/cluster_controller_test.go
  internal/controllers/topology/cluster/patches/variables/variables.go
  internal/webhooks/cluster.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterclass

#10688 🌱 Log reason for MachineDeployment rollouts / MachineSet creations
  internal/controllers/machinedeployment/machinedeployment_sync.go
  internal/controllers/machinedeployment/mdutil/util.go
  internal/controllers/machinedeployment/mdutil/util_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/machinedeployment

#10690 🌱 Log diffs for Cluster topology rollouts/patches
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/structuredmerge/dryrun.go
  internal/controllers/topology/cluster/structuredmerge/interfaces.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go
  internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go
  internal/controllers/topology/cluster/structuredmerge/twowayspatchhelper.go
  test/infrastructure/docker/templates/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterclass

#10702 ✨ Fix GetObjectVariableInto util func
  exp/runtime/topologymutation/variables.go
  exp/runtime/topologymutation/variables_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/runtime-sdk, area/clusterclass

#10693 🌱 Improve E2E ValidateFinalizers and ValidateOwnerRef
  test/e2e/quick_start_test.go
  test/framework/finalizers_helpers.go
  test/framework/ownerreference_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/e2e-testing

#10711 🐛 Fix some KCP unit test flakes
  controlplane/kubeadm/internal/controllers/controller_test.go
  controlplane/kubeadm/internal/controllers/scale_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/provider/control-plane-kubeadm
