Repository kubernetes-sigs/cluster-api, pull requests merged in 2024-04, with the labels that each got.

#10329 📖 Cluster api manifesto
  docs/book/src/SUMMARY.md
  docs/book/src/user/manifesto.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/documentation

#10363 🌱 Release v1.7.0-rc.0
  CHANGELOG/v1.7.0-rc.0.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#10359 🌱 [release-1.6] Set linkchecker base branch to release-1.6
  .github/workflows/pr-md-link-check.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/ci

#10357 🌱 Update version matrix for github workflows for release-1.7
  .github/workflows/weekly-md-link-check.yaml
  .github/workflows/weekly-security-scan.yaml
  .github/workflows/weekly-test-release.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/ci

#10347 [release-1.5] 🐛 Improve handling of topology orphaned objects
  internal/controllers/topology/cluster/desired_state.go
  internal/controllers/topology/cluster/desired_state_test.go
  internal/controllers/topology/cluster/reconcile_state.go
  internal/controllers/topology/cluster/reconcile_state_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/clusterclass

#10310 🌱 Add docs on how to get goroutine dump
  docs/book/src/tasks/diagnostics.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10335 🌱 bump docker/docker to 26.0.0+incompatible
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
  test/infrastructure/container/docker.go
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/dependency

#10358 📖 Improve clarity of prowjob configuration regeneration instructions
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#10366 📖 rm duplicated release task
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#10321 :bug: Checking cert's keypair for nil before accessing to avoid panics
  util/secret/certificates.go
  util/secret/certificates_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, tide/merge-method-squash, ok-to-test, area/util

#10349 [release-1.5] 🌱 Added go directive test
  Makefile
  hack/verify-go-directive.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, area/ci

#10348 [release-1.6] 🌱 Added go directive test
  Makefile
  hack/verify-go-directive.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, area/ci

#10346 📖 Document how to connect to InMemoryClusters
  test/infrastructure/inmemory/README.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/documentation

#10328 📖 Drop personas from the book
  docs/book/src/SUMMARY.md
  docs/book/src/user/personas.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/documentation

#10375 🌱 Bump golang to v1.21.9 and golang.org/x/net to mitigate CVE-2023-45288
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#10376 [release-1.6] 🌱 Bump golang to v1.21.9 and golang.org/x/net to mitigate CVE-2023-45288
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#10377 [release-1.5] 🌱 Bump golang to v1.21.9 and golang.org/x/net to mitigate CVE-2023-45288
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, area/dependency

#10369 🌱 release notes: also detect alpha releases as pre releases
  hack/tools/release/notes/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#10371 :book: Document MachinePool feature flag promotion
  docs/book/src/developer/providers/migrations/v1.6-to-v1.7.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10386 🌱 Bump Cluster API Visualizer to v1.3.0
  hack/observability/visualizer/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/devtools

#9774 :bug: Change MachineHealthCheck.spec.unhealthyConditions to optional
  api/v1beta1/clusterclass_types.go
  api/v1beta1/machinehealthcheck_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  docs/book/src/user/concepts.md
  internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
  internal/webhooks/cluster_test.go
  internal/webhooks/clusterclass.go
  internal/webhooks/clusterclass_test.go
  internal/webhooks/machinehealthcheck.go
  internal/webhooks/machinehealthcheck_test.go
  test/e2e/data/infrastructure-docker/main/clusterclass-quick-start.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, ok-to-test, area/machinehealthcheck

#10317 📖 add Cluster API release-1.8 timeline document
  docs/release/releases/release-1.8.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/M, approved, area/release

#10392 📖 Fix broken kube-state-metrics links
  docs/proposals/20220411-cluster-api-state-metrics.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10398 🌱 bump golangci-lint to v1.57.2
  .github/workflows/pr-golangci-lint.yaml
  exp/runtime/hooks/api/v1alpha1/discovery_types.go
  exp/runtime/hooks/api/v1alpha1/lifecyclehooks_types.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#10083 🌱 Add MachinePools to autoscaler e2e test
  exp/internal/webhooks/machinepool.go
  exp/internal/webhooks/machinepool_test.go
  test/e2e/autoscaler.go
  test/e2e/autoscaler_test.go
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-autoscaler/cluster-autoscaler.yaml
  test/framework/autoscaler_helpers.go
  test/framework/machinepool_helpers.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/clusterclass

#10216 🌱 Add MachinePools to handler and topology test
  cmd/clusterctl/client/cluster/assets/topology-test/existing-my-cluster.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/mock-CRDs.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/modified-CP-dockermachinepooltemplate.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/my-cluster-class.yaml
  cmd/clusterctl/client/cluster/assets/topology-test/new-clusterclass-and-cluster.yaml
  cmd/clusterctl/client/cluster/topology_test.go
  test/extension/handlers/topologymutation/handler_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterclass

#10397 🌱 Update order of release note generation tasks
  docs/release/release-tasks.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/release

#10391 🌱 Add more templating func to prowjob-gen
  hack/tools/prowjob-gen/generator.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/ci

#10399 🌱 Fixup patch order in CABPK
  bootstrap/kubeadm/config/crd/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#10408 🐛 SSA: recover gvk after scheme.Convert
  internal/util/ssa/patch.go
  internal/util/ssa/patch_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/util

#10395 🌱 Release v1.7.0-rc.1
  CHANGELOG/v1.7.0-rc.1.md
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/release

#10355 📖 Improve docs for KCP.status.ready & cluster.status.ControlPlaneReady
  api/v1beta1/cluster_types.go
  api/v1beta1/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_types.go
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#10412 🌱 e2e: enable ability to test pre-releases of kubernetes
  scripts/ci-e2e-lib.sh
  scripts/ci-e2e.sh
  test/extension/handlers/topologymutation/handler.go
  test/extension/handlers/topologymutation/handler_test.go
  test/framework/kubetest/run.go
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#10048 🌱 remove redundant watch event handlers via `Owns()`
  internal/controllers/machinedeployment/machinedeployment_controller.go
  internal/controllers/machineset/machineset_controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/machine, area/machineset

#10415 [release-1.7] 🌱 e2e: enable ability to test pre-releases of kubernetes
  scripts/ci-e2e-lib.sh
  scripts/ci-e2e.sh
  test/extension/handlers/topologymutation/handler.go
  test/extension/handlers/topologymutation/handler_test.go
  test/framework/kubetest/run.go
  test/infrastructure/kind/mapper.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#10196 🐛 Delete out of date machines with unhealthy control plane component conditions when rolling out KCP
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/control_plane_test.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/remediation_test.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  docs/proposals/20191017-kubeadm-based-control-plane.md
  util/collections/machine_filters.go
  util/collections/machine_filters_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, ok-to-test, area/provider/control-plane-kubeadm

#10422 [release-1.6] 🐛 Delete out of date machines with unhealthy control plane component conditions when rolling out KCP
  controlplane/kubeadm/internal/control_plane.go
  controlplane/kubeadm/internal/control_plane_test.go
  controlplane/kubeadm/internal/controllers/remediation.go
  controlplane/kubeadm/internal/controllers/remediation_test.go
  controlplane/kubeadm/internal/controllers/scale.go
  controlplane/kubeadm/internal/controllers/scale_test.go
  docs/proposals/20191017-kubeadm-based-control-plane.md
  util/collections/machine_filters.go
  util/collections/machine_filters_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/provider/control-plane-kubeadm

#10424 🐛 e2e: fix kubetest to allow parallel execution on different clusters
  test/e2e/cluster_upgrade.go
  test/e2e/k8s_conformance.go
  test/e2e/quick_start_test.go
  test/framework/kubetest/run.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#10384 ✨ test: Bump Kubernetes version used for testing to v1.30.0-rc.1
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#10370 🌱internal/webhooks: make MDT.replicas and autoscaler mut. exclusive
  internal/test/builder/builders.go
  internal/test/builder/zz_generated.deepcopy.go
  internal/webhooks/cluster.go
  internal/webhooks/cluster_test.go
  internal/webhooks/clusterclass.go
  internal/webhooks/clusterclass_test.go
Labels: cncf-cla: yes, lgtm, kind/feature, size/L, approved, area/clusterclass

#10407 🌱 clusterctl/client/cert_manager: improve shouldUpgrade
  cmd/clusterctl/client/cluster/cert_manager.go
  cmd/clusterctl/client/cluster/cert_manager_test.go
Labels: cncf-cla: yes, lgtm, kind/feature, size/L, approved, area/clusterctl

#10388 🌱 Allow setting worker machine count to nil in ApplyClusterTemplateAndWait & ConfigCluster
  test/e2e/autoscaler.go
  test/framework/clusterctl/client.go
  test/framework/clusterctl/clusterctl_helpers.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#10432 [release-1.5] 🐛 test: fix kubetest to allow parallel execution on different clusters
  test/e2e/cluster_upgrade.go
  test/e2e/k8s_conformance.go
  test/e2e/quick_start_test.go
  test/framework/kubetest/run.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#10402 :sparkles: Support e2e for WSL
  test/framework/cluster_proxy.go
  test/framework/kubetest/run.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/testing

#10438 🌱 Release v1.5.8
  CHANGELOG/v1.5.8.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#10439 🌱 Release v1.6.4
  CHANGELOG/v1.6.4.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#10440 :seedling: Release v1.7.0
  CHANGELOG/v1.7.0.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#10385 :book: add release 1.6 book link
  docs/book/src/introduction.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/release

#10418 📖 Add MachinePools to ClusterClass Documentation
  docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md
  docs/proposals/20210526-cluster-class-and-managed-topologies.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/clusterclass, area/documentation

#10420 :seedling: Export more func in test/e2e/common.go
  test/e2e/autoscaler.go
  test/e2e/cluster_upgrade.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/clusterclass_changes.go
  test/e2e/clusterclass_rollout.go
  test/e2e/clusterctl_upgrade.go
  test/e2e/common.go
  test/e2e/k8s_conformance.go
  test/e2e/kcp_adoption.go
  test/e2e/kcp_remediations.go
  test/e2e/machine_pool.go
  test/e2e/md_remediations.go
  test/e2e/md_rollout.go
  test/e2e/md_scale.go
  test/e2e/node_drain_timeout.go
  test/e2e/quick_start.go
  test/e2e/self_hosted.go
  test/framework/spec_helpers.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, ok-to-test, area/e2e-testing

#10444 📖 update coredns + contributing for v1.7.0
  CONTRIBUTING.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10449 📖 Update guidelines for runtime hook implementation
  docs/book/src/tasks/experimental-features/runtime-sdk/implement-extensions.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#10367 📖 Document the triage process
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, area/documentation

#10455 📖 Update clusterctl version to v1.7.x in quick start
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#10135 🌱 Add MP back to dualstack E2E test
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/drop-machinepools.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv4-primary/kustomization.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/drop-machinepools.yaml
  test/e2e/data/infrastructure-docker/main/cluster-template-topology-dualstack-ipv6-primary/kustomization.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass, area/e2e-testing

#10452 🌱 Bump Go to v1.22.2
  .golangci.yml
  Makefile
  Tiltfile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  netlify.toml
  test/go.mod
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#10453 🐛 CAPD: verify lb config after writing it
  test/infrastructure/docker/internal/docker/loadbalancer.go
  test/infrastructure/docker/internal/docker/types/node.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/provider/infrastructure-docker

#10454 🌱 Bump Kubernetes in tests to v1.30.0 and claim support for v1.30
  docs/book/src/reference/versions.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#10465 [release-1.7] 🌱 Bump Kubernetes in tests to v1.30.0 and claim support for v1.30
  docs/book/src/reference/versions.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, area/testing

#10380 🌱 Bump controller-gen to v0.15
  Makefile
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_metadata.yaml
  cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml
  cmd/clusterctl/config/manifest/clusterctl-api.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinepools.yaml
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddresses.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclustertemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepooltemplates.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclusters.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemoryclustertemplates.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachines.yaml
  test/infrastructure/inmemory/config/crd/bases/infrastructure.cluster.x-k8s.io_inmemorymachinetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/dependency

#10477 🌱 Bump envtest to v1.30.0
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/dependency

#10478 🌱 Bump github.com/docker/docker to v26.0.2
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/provider/infrastructure-docker

#10475 🌱 github: add labels to release-tracking issue template
  .github/ISSUE_TEMPLATE/release_tracking.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#10443 📖 Update docs for ClusterResourceSets
  docs/book/src/tasks/experimental-features/cluster-resource-set.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/clusterresourceset

#10414 📖 decouple the support new kubernetes version process from kind releases
  .github/ISSUE_TEMPLATE/kubernetes_bump.md
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, ok-to-test, area/documentation

#10493 🐛 kubetest: also gather junit reports in case of errors observed from ginkgo
  test/framework/kubetest/run.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/e2e-testing

#10474 🌱 Bump conversion-gen to v0.30.0
  Makefile
  bootstrap/kubeadm/types/upstreamv1beta2/zz_generated.conversion.go
  bootstrap/kubeadm/types/upstreamv1beta2/zz_generated.deepcopy.go
  bootstrap/kubeadm/types/upstreamv1beta3/zz_generated.conversion.go
  bootstrap/kubeadm/types/upstreamv1beta3/zz_generated.deepcopy.go
  exp/ipam/api/v1alpha1/zz_generated.conversion.go
  internal/apis/bootstrap/kubeadm/v1alpha3/zz_generated.conversion.go
  internal/apis/bootstrap/kubeadm/v1alpha4/zz_generated.conversion.go
  internal/apis/controlplane/kubeadm/v1alpha3/conversion.go
  internal/apis/controlplane/kubeadm/v1alpha3/zz_generated.conversion.go
  internal/apis/controlplane/kubeadm/v1alpha4/conversion.go
  internal/apis/controlplane/kubeadm/v1alpha4/zz_generated.conversion.go
  internal/apis/core/exp/addons/v1alpha3/zz_generated.conversion.go
  internal/apis/core/exp/addons/v1alpha4/zz_generated.conversion.go
  internal/apis/core/exp/v1alpha3/conversion.go
  internal/apis/core/exp/v1alpha3/zz_generated.conversion.go
  internal/apis/core/exp/v1alpha4/conversion.go
  internal/apis/core/exp/v1alpha4/zz_generated.conversion.go
  internal/apis/core/v1alpha3/zz_generated.conversion.go
  internal/apis/core/v1alpha4/zz_generated.conversion.go
  internal/runtime/test/v1alpha1/zz_generated.conversion.go
  internal/runtime/test/v1alpha1/zz_generated.deepcopy.go
  test/infrastructure/docker/api/v1alpha3/zz_generated.conversion.go
  test/infrastructure/docker/api/v1alpha4/zz_generated.conversion.go
  test/infrastructure/docker/exp/api/v1alpha3/zz_generated.conversion.go
  test/infrastructure/docker/exp/api/v1alpha4/zz_generated.conversion.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test, area/dependency

#10488 🚀 Release v1.7.1
  CHANGELOG/v1.7.1.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/release

#10501 🌱 Bump github.com/distribution/reference from 0.5.0 to 0.6.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
  util/container/image_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/dependency

#10469 🐛 clusterctl: ensure cert-manager objects get applied before other provider objects
  cmd/clusterctl/client/repository/components.go
  test/framework/clusterctl/ca_injection.go
  test/framework/clusterctl/clusterctl_helpers.go
  test/framework/convenience.go
Labels: cncf-cla: yes, lgtm, size/L, approved, ok-to-test, area/clusterctl

#10502 🐛 Fix conversion-gen outside of GOPATH
  Makefile
Labels: size/S, cncf-cla: yes, lgtm, approved, area/ci

#10506 🌱 envtest: Setup Machine webhook only once
  internal/test/envtest/environment.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/testing

#10489 🌱 Publish nightly manifests to staging bucket
  Makefile
  docs/book/src/clusterctl/commands/upgrade.md
  docs/book/src/clusterctl/developers.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/ci

#10383 🌱 Bump controller-runtime to v0.18.0
  config/crd/bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
  config/crd/bases/cluster.x-k8s.io_machinehealthchecks.yaml
  config/crd/bases/cluster.x-k8s.io_machinesets.yaml
  config/crd/bases/runtime.cluster.x-k8s.io_extensionconfigs.yaml
  controllers/external/tracker.go
  controllers/external/tracker_test.go
  controllers/remote/cluster_cache_tracker.go
  controlplane/kubeadm/internal/webhooks/scale.go
  exp/internal/webhooks/machinepool.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  internal/webhooks/machinedeployment.go
  internal/webhooks/machineset.go
  test/go.mod
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, area/dependency

#10480 📖 Add disclaimer to Kubelet Authentication proposal
  docs/proposals/20210222-kubelet-authentication.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/documentation

#10471 🌱 feat: add support for the linode-linode infrastructure provider to clusterctl
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/reference/glossary.md
  docs/book/src/reference/providers.md
  docs/book/src/user/quick-start.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/clusterctl

#10487 🌱 Add Tinkerbell to the providers list
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/clusterctl/provider-contract.md
  docs/book/src/reference/glossary.md
  docs/book/src/user/quick-start.md
  hack/tools/release/internal/update_providers/provider_issues.go
Labels: size/S, cncf-cla: yes, lgtm, approved, tide/merge-method-squash, area/clusterctl

#10514 🌱Bump cert-manager to 1.14.5
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/guide.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#10521 🌱 Push manifests for main & release-.*
  Makefile
Labels: size/S, cncf-cla: yes, lgtm, approved, area/release

#10510 🌱 Bump autoscaler to v1.30.0
  test/e2e/autoscaler_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/e2e-testing

#10490 📖 Add members of 1.8 release
  docs/release/releases/release-1.8.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/release

#10529 📖 Update CAPI support and guarantees for v1.8
  CONTRIBUTING.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test, area/documentation

#10525 🌱 Improve SSA patch test
  internal/util/ssa/patch_test.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/testing

#10534 📖 Drop docs not maintained
  README.md
  docs/book/src/introduction.md
  docs/scope-and-objectives.md
  docs/staging-use-cases.md
  hack/generate-doctoc.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, area/documentation

#10535 📖 Drop v1.4 column, set v1.5 to EOL in versions.md
  docs/book/src/reference/versions.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/documentation

#10473 🌱 Swap in new 1.8 RT members in OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#10182 🌱 ipam: add spec.clusterName to IPAddressClaim
  config/crd/bases/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  exp/ipam/api/v1alpha1/conversion.go
  exp/ipam/api/v1alpha1/zz_generated.conversion.go
  exp/ipam/api/v1beta1/ipaddressclaim_types.go
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash, ok-to-test, area/ipam

#10540 🐛 Fix log in clusterctl move
  cmd/clusterctl/client/cluster/mover.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, area/clusterctl

#10513 🌱 clusterctl: always run crd migration if possible to reduce conversion webhook usage
  cmd/clusterctl/client/cluster/crd_migration.go
  cmd/clusterctl/client/cluster/crd_migration_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/clusterctl
