Repository kubernetes-sigs/cluster-api, pull requests merged in 2025-04, with the labels that each got.

#12044 🌱 Bump cert-manager to v1.17.1
  cmd/clusterctl/client/config/cert_manager_client.go
  docs/book/src/clusterctl/commands/init.md
  docs/book/src/developer/getting-started.md
  scripts/ci-e2e-lib.sh
  test/e2e/config/docker.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterctl

#12052 🌱 Bump go to v1.23.8
  Makefile
  Tiltfile
  netlify.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/dependency

#12054 🌱 Remove unused List conversion funcs
  api/addons/v1beta2/conversion.go
  api/v1beta2/conversion.go
  bootstrap/kubeadm/api/v1beta2/conversion.go
  controlplane/kubeadm/api/v1beta2/conversion.go
  exp/api/v1beta2/conversion.go
  exp/ipam/api/v1alpha1/conversion.go
  exp/ipam/api/v1beta2/conversion.go
  internal/apis/addons/v1alpha3/conversion.go
  internal/apis/addons/v1alpha4/conversion.go
  internal/apis/bootstrap/kubeadm/v1alpha3/conversion.go
  internal/apis/bootstrap/kubeadm/v1alpha4/conversion.go
  internal/apis/controlplane/kubeadm/v1alpha3/conversion.go
  internal/apis/controlplane/kubeadm/v1alpha4/conversion.go
  internal/apis/core/exp/v1alpha3/conversion.go
  internal/apis/core/exp/v1alpha4/conversion.go
  internal/apis/core/v1alpha3/conversion.go
  internal/apis/core/v1alpha4/conversion.go
  test/infrastructure/docker/api/v1alpha3/conversion.go
  test/infrastructure/docker/api/v1alpha4/conversion.go
  test/infrastructure/docker/api/v1beta1/conversion.go
  test/infrastructure/docker/exp/api/v1alpha3/conversion.go
  test/infrastructure/docker/exp/api/v1alpha4/conversion.go
  test/infrastructure/docker/exp/api/v1beta1/conversion.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api

#12056 :seedling: Fix typo in forward etcd leadership error message
  controlplane/kubeadm/internal/workload_cluster_etcd.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/control-plane

#12058 🌱 Bump corefile-migration library to v1.0.26
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/provider/control-plane-kubeadm

#12063 [release-1.9] 🌱 Bump corefile-migration library to v1.0.26
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, area/provider/control-plane-kubeadm

#12064 [release-1.8] 🌱 Bump corefile-migration library to v1.0.26
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.sum
Labels: cncf-cla: yes, lgtm, approved, area/provider/control-plane-kubeadm

#12067 🌱 Add retry for SSA requests against Kubernetes < v1.29 in clusterctl upgrade tests
  test/e2e/clusterctl_upgrade.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#12071 🚀 Release v1.10.0-rc.0
  CHANGELOG/v1.10.0-rc.0.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#12072 :bug: Fix MaxLength of worker topology Name fields
  api/v1beta1/cluster_types.go
  api/v1beta2/cluster_types.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, tide/merge-method-squash, area/api, area/clusterclass

#12074 📖 add release 1.9 book link
  docs/book/src/introduction.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/documentation

#12073 🌱 Bump Kubernetes version used for testing to v1.33.0-rc.0
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/e2e-testing

#12077 🌱 [release-1.10] github: bump md-link check to 1.0.17
  .github/workflows/pr-md-link-check.yaml
  .github/workflows/weekly-md-link-check.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#12078 🌱 [release-1.9] github: bump md-link check to 1.0.17
  .github/workflows/pr-md-link-check.yaml
  .github/workflows/weekly-md-link-check.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#12079 🌱 [release-1.8] github: bump md-link check to 1.0.17
  .github/workflows/pr-md-link-check.yaml
  .github/workflows/weekly-md-link-check.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#12084 [release-1.10] :bug: Fix MaxLength of worker topology Name fields
  api/v1beta1/cluster_types.go
  config/crd/bases/cluster.x-k8s.io_clusters.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/api, area/clusterclass

#12065 🌱 kcp: allow unsetting etcd.local, etcd.external and dns
  controlplane/kubeadm/internal/webhooks/kubeadm_control_plane.go
  controlplane/kubeadm/internal/webhooks/kubeadm_control_plane_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/provider/control-plane-kubeadm

#12093 📖 Update contract documentation
  docs/book/src/SUMMARY.md
  docs/book/src/developer/providers/contracts/bootstrap-config.md
  docs/book/src/developer/providers/contracts/control-plane.md
  docs/book/src/developer/providers/contracts/infra-cluster.md
  docs/book/src/developer/providers/contracts/infra-machine.md
  docs/book/src/developer/providers/migrations/overview.md
  docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md
  docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md
  docs/proposals/20240916-improve-status-in-CAPI-resources.md
Labels: cncf-cla: yes, lgtm, size/XL, approved, tide/merge-method-squash, area/documentation

#12097 🚀 Release v1.10.0-rc.1
  CHANGELOG/v1.10.0-rc.1.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#12099 🌱 Bump E2E to Kubernetes v1.33.0-rc.1
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/ci

#12101 ⚠️ Add initialization to Machine Status
  api/v1beta1/conversion.go
  api/v1beta1/conversion_test.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/machine_types.go
  api/v1beta2/zz_generated.deepcopy.go
  api/v1beta2/zz_generated.openapi.go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller_test.go
  bootstrap/util/configowner.go
  bootstrap/util/configowner_test.go
  config/crd/bases/cluster.x-k8s.io_machines.yaml
  internal/apis/core/v1alpha3/conversion.go
  internal/apis/core/v1alpha3/conversion_test.go
  internal/apis/core/v1alpha3/zz_generated.conversion.go
  internal/apis/core/v1alpha4/conversion.go
  internal/apis/core/v1alpha4/conversion_test.go
  internal/apis/core/v1alpha4/zz_generated.conversion.go
  internal/controllers/machine/machine_controller_phases.go
  internal/controllers/machine/machine_controller_phases_test.go
  internal/controllers/machine/machine_controller_status.go
  internal/controllers/machine/machine_controller_status_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  internal/controllers/machinehealthcheck/machinehealthcheck_targets_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, area/api, area/machine

#11029 📖 Add In-place updates proposal
  docs/proposals/20240807-in-place-updates.md
Labels: cncf-cla: yes, lgtm, size/XL, approved, area/documentation

#12108 🌱 Add govulncheck to ensure vulnerability
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#12114 🚀 Release v1.10.0
  CHANGELOG/v1.10.0.md
Labels: cncf-cla: yes, lgtm, size/L, approved, area/release

#12115 🚀 Release v1.9.7
  CHANGELOG/v1.9.7.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#12120 📖 Fix version support matrix
  docs/book/src/reference/versions.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation

#12105 [release-1.10] ✨ Bump Kubernetes in tests to v1.33.0 and claim support for v1.33
  docs/book/src/reference/versions.md
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, area/testing

#12104 ✨ Bump Kubernetes in tests to v1.33.0 and claim support for v1.33
  docs/book/src/reference/versions.md
  test/e2e/config/docker.yaml
  test/infrastructure/docker/examples/machine-pool.yaml
  test/infrastructure/docker/examples/simple-cluster-ipv6.yaml
  test/infrastructure/docker/examples/simple-cluster-without-kcp.yaml
  test/infrastructure/docker/examples/simple-cluster.yaml
Labels: size/S, cncf-cla: yes, lgtm, approved, tide/merge-method-squash, area/testing

#12136 [release-1.10] 🐛 Make joinConfiguration.discovery.bootstrapToken.token optional
  bootstrap/kubeadm/api/v1beta1/kubeadm_types.go
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml
  bootstrap/kubeadm/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
  controlplane/kubeadm/config/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanetemplates.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/bootstrap

#12137 🚀 Release v1.10.1
  CHANGELOG/v1.10.1.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#12122 📖 Add Cluster API release-1.11 timeline document
  docs/release/releases/release-1.11.md
Labels: cncf-cla: yes, lgtm, kind/documentation, size/M, approved, area/release

#12117 📖 Update clusterctl version to v1.10.x in quick start
  docs/book/src/user/quick-start.md
Labels: size/S, cncf-cla: yes, lgtm, kind/documentation, approved, area/documentation
