Repository kubernetes-sigs/cluster-api, pull requests merged in 2025-09, with the labels that each got.

#12719 🐛 Stop adding conversion-data annotation to Cluster object
  bootstrap/kubeadm/types/utils.go
  exp/topology/desiredstate/desired_state.go
  internal/controllers/topology/cluster/cluster_controller.go
  internal/controllers/topology/cluster/reconcile_state.go
Labels: size/S, cncf-cla: yes, lgtm, approved, area/clusterclass

#12725 🚀 Release v1.11.1
  CHANGELOG/v1.11.1.md
Labels: cncf-cla: yes, lgtm, size/M, approved, area/release

#12723 🌱 Prepare main branch for v1.12 development
  .gitignore
  Makefile
  cmd/clusterctl/hack/create-local-repository.py
  hack/tools/internal/tilt-prepare/main.go
  metadata.yaml
  test/e2e/clusterctl_upgrade.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/docker.yaml
  test/e2e/data/infrastructure-docker/v1.11/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-docker/v1.11/bases/cluster-with-topology.yaml
  test/e2e/data/infrastructure-docker/v1.11/bases/crs.yaml
  test/e2e/data/infrastructure-docker/v1.11/bases/md.yaml
  test/e2e/data/infrastructure-docker/v1.11/cluster-template-topology/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1.11/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-docker/v1.11/clusterclass-quick-start.yaml
  test/e2e/data/shared/main/metadata.yaml
  test/e2e/data/shared/v1.11/metadata.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved, tide/merge-method-squash, area/release

#12733 🌱 Bump go to v1.24.7
  Makefile
  Tiltfile
  netlify.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved, tide/merge-method-squash, ok-to-test, area/dependency

#12743 🌱 Bump KAL & add nodurations linter
  .golangci-kal.yml
  hack/tools/.custom-gcl.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#12749 [release-1.10] :sparkles: Bump coredns/corefile-migration to v1.0.28
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/provider/control-plane-kubeadm

#12750 [release-1.11] :sparkles: Bump coredns/corefile-migration to v1.0.28
  docs/book/src/reference/versions.md
  go.mod
  go.sum
  hack/tools/go.sum
  test/go.sum
Labels: size/S, cncf-cla: yes, lgtm, approved, area/provider/control-plane-kubeadm

#10875 🌱 Use errors package of Go
  bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go
  cmd/clusterctl/client/cluster/template.go
  cmd/clusterctl/client/cluster/template_test.go
  cmd/clusterctl/client/repository/repository_github.go
  cmd/clusterctl/client/repository/repository_github_test.go
  internal/controllers/cluster/cluster_controller_phases.go
  internal/controllers/clusterresourceset/clusterresourceset_controller.go
  internal/controllers/machine/drain/drain.go
  internal/controllers/machine/machine_controller_noderef.go
  internal/controllers/machinepool/machinepool_controller_noderef.go
  internal/controllers/machinepool/machinepool_controller_phases.go
Labels: cncf-cla: yes, lgtm, lifecycle/stale, size/L, approved, tide/merge-method-squash, area/misc

#12772 🌱 Block FIXME comments
  .golangci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved, area/ci

#12766 🐛 Fix e2e test issues introduced by chained upgrades
  internal/webhooks/cluster.go
  test/e2e/cluster_upgrade_runtimesdk.go
  test/e2e/cluster_upgrade_runtimesdk_test.go
  test/e2e/config/docker.yaml
  test/extension/config/default/kustomization.yaml
  test/extension/handlers/lifecycle/handlers.go
  test/framework/deployment_helpers.go
  test/framework/deployment_helpers_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/e2e-testing

#12642 🌱 update metrics configuration to v1beta2
  config/metrics/crd-clusterrole.yaml
  config/metrics/crd-metrics-config.yaml
  config/metrics/kustomization.yaml
  hack/observability/grafana/dashboards/cluster-api-state.json
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/ci

#12777 📖 List provider implementations of MachinePools
  docs/book/src/tasks/experimental-features/machine-pools.md
Labels: size/S, cncf-cla: yes, lgtm, approved, area/documentation, area/machinepool

#12800 :sparkles: add new control-plane provider HCP
  cmd/clusterctl/client/config/providers_client.go
  cmd/clusterctl/client/config_test.go
  cmd/clusterctl/cmd/config_repositories_test.go
  docs/book/src/reference/providers.md
Labels: size/S, cncf-cla: yes, lgtm, approved, ok-to-test, area/control-plane

#12809 ✨ Add .spec.upgrade.external.generateUpgradePlanExtension field to ClusterClass
  api/core/v1beta1/conversion.go
  api/core/v1beta1/zz_generated.conversion.go
  api/core/v1beta2/clusterclass_types.go
  api/core/v1beta2/zz_generated.deepcopy.go
  api/core/v1beta2/zz_generated.openapi.go
  config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
  internal/api/core/v1alpha4/conversion.go
  internal/api/core/v1alpha4/zz_generated.conversion.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, area/clusterclass
